function tests = testScenarioBatchPrecompute
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
stubFolder = fullfile(fileparts(mfilename('fullpath')), ...
    'fixtures','scenarioBatchStubs');
addpath(stubFolder,'-begin');
clearScenarioBatchFunctions();
testCase.TestData.stubFolder = stubFolder;
end

function setup(testCase)
addpath(testCase.TestData.stubFolder,'-begin');
clearScenarioBatchFunctions();
end

function teardownOnce(testCase)
rmpath(testCase.TestData.stubFolder);
clearScenarioBatchFunctions();
end

function testInterval2ScenarioBatchPrecomputeCallsMatRadWithoutDij(testCase)
context = compactContext();
robustData = intervalRobustData('INTERVAL2');

robustData = ...
    planWorkflow.precompute.IntervalDoseInfluence.precompute( ...
    context,robustData);

verifyFalse(testCase,isfield(robustData,'dij'));
verifyEqual(testCase,robustData.dij_interval.stubMode,'INTERVAL2');
verifyEqual(testCase,robustData.dij_interval.stubNargin,5);
verifyEqual(testCase,robustData.dijIntervalContext.stubNargin,5);
verifyTrue(testCase, ...
    planWorkflow.performance.PrecomputeTiming.isValid( ...
    robustData.dijPrecomputingTiming));
verifyEqual(testCase, ...
    robustData.dijPrecomputingTiming.relativeTime, ...
    robustData.dijPrecomputingTiming.totalTimeSeconds / ...
    context.data.dijPrecomputingTiming.totalTimeSeconds, ...
    'AbsTol',1e-12);
verifyEqual(testCase, ...
    robustData.dijPrecomputingTiming.reference.timeSeconds, ...
    context.data.dijPrecomputingTiming.totalTimeSeconds, ...
    'AbsTol',1e-12);
verifyTrue(testCase, ...
    planWorkflow.performance.PrecomputeSize.isValid( ...
    robustData.dijPrecomputingSize));
verifyEqual(testCase, ...
    robustData.dijPrecomputingSize.totalSizeBytes, ...
    robustData.dij_interval.precomputeSize.totalPrecomputingBytes, ...
    'AbsTol',1e-12);
verifyEqual(testCase, ...
    robustData.dijPrecomputingSize.relativeSize, ...
    robustData.dij_interval.precomputeSize.totalPrecomputingBytes / ...
    context.data.dijPrecomputingSize.totalSizeBytes, ...
    'AbsTol',1e-12);
end

function testIntervalScenarioBatchNominalObjectivesUseContextDij(testCase)
context = compactContext();
robustData = intervalRobustData('INTERVAL2');
robustData.planConfig.hasNominalObjectives = true;
robustData.planConfig.requiresNominalDij = true;

robustData = ...
    planWorkflow.precompute.IntervalDoseInfluence.precompute( ...
    context,robustData);

verifyFalse(testCase,isfield(robustData,'dij'));
verifyEqual(testCase,robustData.dijNominal, ...
    robustData.dijIntervalContext);
verifyEqual(testCase,robustData.stfNominal,robustData.stf);
verifyFalse(testCase,isfield(robustData.plnNominal.propOpt, ...
    'dij_interval'));
end

function testInterval3ScenarioBatchPrecomputeCallsMatRadWithoutDij(testCase)
context = compactContext();
robustData = intervalRobustData('INTERVAL3');

robustData = ...
    planWorkflow.precompute.IntervalDoseInfluence.precompute( ...
    context,robustData);

verifyFalse(testCase,isfield(robustData,'dij'));
verifyEqual(testCase,robustData.dij_interval.stubMode,'INTERVAL3');
verifyEqual(testCase,robustData.dij_interval.stubNargin,5);
verifyEqual(testCase,robustData.dijIntervalContext.stubNargin,5);
verifyEqual(testCase, ...
    robustData.dijPrecomputingTiming.relativeTime, ...
    robustData.dijPrecomputingTiming.totalTimeSeconds / ...
    context.data.dijPrecomputingTiming.totalTimeSeconds, ...
    'AbsTol',1e-12);
end

function testReferenceIntervalScenarioBatchPrecomputeIsSelfReferenced(testCase)
context = compactContext();
robustData = referenceRobustData(intervalRobustData('INTERVAL2'));

robustData = ...
    planWorkflow.precompute.IntervalDoseInfluence.precompute( ...
    context,robustData);

verifyEqual(testCase,robustData.dijPrecomputingTiming.relativeTime,1, ...
    'AbsTol',1e-12);
verifyEqual(testCase, ...
    robustData.dijPrecomputingTiming.reference.timeSeconds, ...
    robustData.dijPrecomputingTiming.totalTimeSeconds,'AbsTol',1e-12);
verifyEqual(testCase,robustData.dijPrecomputingSize.relativeSize,1, ...
    'AbsTol',1e-12);
verifyEqual(testCase, ...
    robustData.dijPrecomputingSize.reference.sizeBytes, ...
    robustData.dijPrecomputingSize.totalSizeBytes,'AbsTol',1e-12);
end

function testProb2ScenarioBatchPrecomputeCallsMatRadWithoutDij(testCase)
context = compactContext();
robustData = probRobustData();

robustData = ...
    planWorkflow.precompute.ProbDoseInfluence.precompute( ...
    context,robustData);

verifyFalse(testCase,isfield(robustData,'dij'));
verifyEqual(testCase,robustData.dij_prob.stubMode,'PROB');
verifyEqual(testCase,robustData.dij_prob.stubNargin,5);
verifyEqual(testCase,robustData.dijProbContext.stubNargin,5);
verifyTrue(testCase, ...
    planWorkflow.performance.PrecomputeTiming.isValid( ...
    robustData.dijPrecomputingTiming));
verifyEqual(testCase, ...
    robustData.dijPrecomputingTiming.relativeTime, ...
    robustData.dijPrecomputingTiming.totalTimeSeconds / ...
    context.data.dijPrecomputingTiming.totalTimeSeconds, ...
    'AbsTol',1e-12);
verifyEqual(testCase, ...
    robustData.dijPrecomputingTiming.reference.timeSeconds, ...
    context.data.dijPrecomputingTiming.totalTimeSeconds, ...
    'AbsTol',1e-12);
verifyTrue(testCase, ...
    planWorkflow.performance.PrecomputeSize.isValid( ...
    robustData.dijPrecomputingSize));
verifyEqual(testCase, ...
    robustData.dijPrecomputingSize.totalSizeBytes, ...
    robustData.dij_prob.precomputeSize.totalPrecomputingBytes, ...
    'AbsTol',1e-12);
verifyEqual(testCase, ...
    robustData.dijPrecomputingSize.relativeSize, ...
    robustData.dij_prob.precomputeSize.totalPrecomputingBytes / ...
    context.data.dijPrecomputingSize.totalSizeBytes, ...
    'AbsTol',1e-12);
end

function testReferenceProb2ScenarioBatchPrecomputeIsSelfReferenced(testCase)
context = compactContext();
robustData = referenceRobustData(probRobustData());

robustData = ...
    planWorkflow.precompute.ProbDoseInfluence.precompute( ...
    context,robustData);

verifyEqual(testCase,robustData.dijPrecomputingTiming.relativeTime,1, ...
    'AbsTol',1e-12);
verifyEqual(testCase, ...
    robustData.dijPrecomputingTiming.reference.timeSeconds, ...
    robustData.dijPrecomputingTiming.totalTimeSeconds,'AbsTol',1e-12);
verifyEqual(testCase,robustData.dijPrecomputingSize.relativeSize,1, ...
    'AbsTol',1e-12);
verifyEqual(testCase, ...
    robustData.dijPrecomputingSize.reference.sizeBytes, ...
    robustData.dijPrecomputingSize.totalSizeBytes,'AbsTol',1e-12);
end

function testProb2ScenarioBatchNominalObjectivesUseContextDij(testCase)
context = compactContext();
robustData = probRobustData();
robustData.planConfig.hasNominalObjectives = true;
robustData.planConfig.requiresNominalDij = true;

robustData = ...
    planWorkflow.precompute.ProbDoseInfluence.precompute( ...
    context,robustData);

verifyFalse(testCase,isfield(robustData,'dij'));
verifyEqual(testCase,robustData.dijNominal,robustData.dijProbContext);
verifyEqual(testCase,robustData.stfNominal,robustData.stf);
verifyFalse(testCase,isfield(robustData.plnNominal.propOpt, ...
    'dij_prob'));
end

function context = compactContext()
context = struct();
context.runConfig = struct('writeCache',false,'useCache',false);
context.data = struct('quantityOpt','', ...
    'dijPrecomputingTiming', ...
    planWorkflow.performance.PrecomputeTiming.single( ...
    10,'reference','Reference','dij',[]), ...
    'dijPrecomputingSize', ...
    planWorkflow.performance.PrecomputeSize.single( ...
    1024,'reference','Reference','dij',[]));
context.log = @(message) [];
end

function robustData = intervalRobustData(mode)
robustData = baseRobustData(mode);
robustData.planConfig.requiresIntervalDij = true;
robustData.planConfig.robustnessOptions = ...
    planWorkflow.config.RobustPlanConfig.defaultRobustnessOptions(mode);
robustData.planConfig.variants = ...
    planWorkflow.config.RobustPlanConfig.defaultVariants(mode);
robustData.strategy = planWorkflow.robustness.AbstractStrategy.create(mode);
end

function robustData = probRobustData()
robustData = baseRobustData('PROB2');
robustData.planConfig.requiresProbDij = true;
robustData.planConfig.robustnessOptions = ...
    planWorkflow.config.RobustPlanConfig.defaultRobustnessOptions('PROB2');
robustData.planConfig.variants = ...
    planWorkflow.config.RobustPlanConfig.defaultVariants('PROB2');
robustData.strategy = planWorkflow.robustness.AbstractStrategy.create('PROB2');
end

function robustData = baseRobustData(mode)
planConfig = planWorkflow.config.RobustPlanConfig.defaultPlan();
planConfig.id = ['scenarioBatch' mode];
planConfig.label = ['Scenario-batch ' mode];
planConfig.objectiveSetName = planConfig.id;
planConfig.robustnessMode = mode;
planConfig.hasNominalObjectives = false;
planConfig.requiresNominalDij = false;
planConfig.requiresScenarioDij = false;
planConfig.requiresIntervalDij = false;
planConfig.requiresProbDij = false;
planConfig.dosePrecompute.useScenarioBatch = true;

robustData = struct();
robustData.planConfig = planConfig;
robustData.ct = struct('refScen',1);
robustData.cst = cell(2,6);
robustData.cst{1,2} = 'PTV';
robustData.cst{2,2} = 'Rectum';
robustData.objectiveInfo = struct( ...
    'ixTarget',1, ...
    'robustOarNames',{{'Rectum'}});
robustData.pln = struct('propOpt',struct());
robustData.stf = struct('totalNumOfBixels',3);
end

function robustData = referenceRobustData(robustData)
robustData.planConfig.id = 'reference';
robustData.planConfig.label = 'Reference';
robustData.planConfig.objectiveSetName = 'reference';
end

function clearScenarioBatchFunctions()
functionNames = { ...
    'matRad_calcDoseInterval', ...
    'matRad_calculateProbabilisticQuantities'};
for functionIx = 1:numel(functionNames)
    clear(functionNames{functionIx});
end
end
