function tests = testConfigValue
tests = functiontests(localfunctions);
end

function testLogicalScalarAcceptsSupportedValues(testCase)
validCases = { ...
    true,true; ...
    false,false; ...
    1,true; ...
    0,false; ...
    'true',true; ...
    'false',false; ...
    'on',true; ...
    'off',false; ...
    "yes",true; ...
    "no",false};

for caseIx = 1:size(validCases,1)
    value = planWorkflow.config.ConfigValue.logicalScalar( ...
        validCases{caseIx,1},sprintf('case%d',caseIx), ...
        'planWorkflow:tests:ConfigValue:InvalidLogical');
    verifyEqual(testCase,value,validCases{caseIx,2});
end
end

function testLogicalScalarRejectsInvalidValues(testCase)
invalidCases = { ...
    [true false], ...
    [], ...
    2, ...
    NaN, ...
    'maybe', ...
    ["true" "false"]};

for caseIx = 1:numel(invalidCases)
    verifyError(testCase,@() ...
        planWorkflow.config.ConfigValue.logicalScalar( ...
        invalidCases{caseIx},sprintf('case%d',caseIx), ...
        'planWorkflow:tests:ConfigValue:InvalidLogical'), ...
        'planWorkflow:tests:ConfigValue:InvalidLogical');
end
end

function testLogicalScalarRequiresExplicitErrorId(testCase)
verifyError(testCase,@() ...
    planWorkflow.config.ConfigValue.logicalScalar(true,'flag'), ...
    'planWorkflow:config:ConfigValue:MissingErrorId');
end
