function tests = testSamplingAnalysisReanalysis
tests = functiontests(localfunctions);
end

function testRecalculateAnalysisMaterializesSamplingAfterReleaseMemory(testCase)
cleanup = installSamplingAnalysisStubs(testCase); %#ok<NASGU>
workflow = planWorkflowTest.SamplingAnalysisWorkflow( ...
    baseSamplingConfig(testCase));

workflow.prepare();
workflow.precompute();
workflow.pullDose();
workflow.optimize();
workflow.sample();
workflow.analyze();

verifyCompactedSamplingData(testCase,workflow.data.sampling, ...
    workflow.cachePath);
dataSnapshot = load(workflow.dataFile,'data');
verifyCompactedSamplingData(testCase,dataSnapshot.data.sampling, ...
    workflow.cachePath);

workflow.releaseMemory();
workflow.recalculateAnalysis();

verifyEqual(testCase,workflow.data.results.analysisCount,2);
verifyEqual(testCase, ...
    workflow.data.results.sampling.reference.meta.sampleDoseSum,36);
verifyEqual(testCase, ...
    workflow.data.results.sampling.robust{1}.meta.sampleDoseSum,72);
verifyCompactedSamplingData(testCase,workflow.data.sampling, ...
    workflow.cachePath);
end

function testRecalculateAnalysisMaterializesSamplingAfterResume(testCase)
cleanup = installSamplingAnalysisStubs(testCase); %#ok<NASGU>
workflow = planWorkflowTest.SamplingAnalysisWorkflow( ...
    baseSamplingConfig(testCase));

workflow.prepare();
workflow.precompute();
workflow.pullDose();
workflow.optimize();
workflow.sample();
workflow.analyze();

resumed = planWorkflow.WorkflowBase.resumeFrom(workflow.stateFile);
verifyClass(testCase,resumed, ...
    'planWorkflowTest.SamplingAnalysisWorkflow');
verifyCompactedSamplingData(testCase,resumed.data.sampling, ...
    resumed.cachePath);

resumed.recalculateAnalysis();

verifyEqual(testCase,resumed.data.results.analysisCount,2);
verifyEqual(testCase, ...
    resumed.data.results.sampling.reference.meta.numSamples,2);
verifyEqual(testCase, ...
    resumed.data.results.sampling.robust{1}.meta.numSamples,2);
verifyCompactedSamplingData(testCase,resumed.data.sampling, ...
    resumed.cachePath);
end

function testSamplingAnalysisFiguresIncludeExpectedDoseDifference(testCase)
cleanup = installSamplingAnalysisStubs(testCase); %#ok<NASGU>
fixture = testCase.applyFixture( ...
    matlab.unittest.fixtures.TemporaryFolderFixture);
analysis = planWorkflow.config.Analysis.defaults();
analysis.figures.save = true;
analysis.figures.visible = 'off';
analysis.figures.closeAfterSave = true;

expectedFig = figure('Visible','off');
meanFig = figure('Visible','off');
stdFig = figure('Visible','off');
nominalFig = figure('Visible','off');
robustnessIndex1Fig = figure('Visible','off');
robustnessIndex2Fig = figure('Visible','off');
expectedAxes = axes('Parent',expectedFig);
title(expectedAxes,'Sampled expected dose difference');
meanAxes = axes('Parent',meanFig);
title(meanAxes,'Sampled expected dose');
stdAxes = axes('Parent',stdFig);
title(stdAxes,'Sampled dose standard deviation');
nominalAxes = axes('Parent',nominalFig);
title(nominalAxes,'Nominal dose');
robustnessAxes1 = axes('Parent',robustnessIndex1Fig);
title(robustnessAxes1,'Sampled robustness index 1');
robustnessAxes2 = axes('Parent',robustnessIndex2Fig);
title(robustnessAxes2,'Sampled robustness index 2');
cleanupFig = onCleanup(@() closeFiguresIfOpen( ...
    [expectedFig meanFig stdFig nominalFig robustnessIndex1Fig robustnessIndex2Fig])); %#ok<NASGU>
figures = struct( ...
    'mean',meanFig, ...
    'std',stdFig, ...
    'nominal',nominalFig, ...
    'robustness',struct( ...
    'index1',robustnessIndex1Fig, ...
    'index2',robustnessIndex2Fig), ...
    'doseDifference',expectedFig);
samplingData = struct('ct',struct(),'cst',{{}});
sample = struct('pln',struct(),'caSamp',{{struct()}});

figureFiles = ...
    planWorkflow.analysis.Figures.saveSamplingAnalysisFigures( ...
    fixture.Folder,'reference',figures,samplingData,sample,analysis);

expectedFile = fullfile(fixture.Folder, ...
    'reference_expected_dose_difference.fig');
meanFile = fullfile(fixture.Folder,'reference_mean_dose.fig');
stdFile = fullfile(fixture.Folder,'reference_std_dose.fig');
nominalFile = fullfile(fixture.Folder,'reference_nominal_dose.fig');
robustnessFile1 = fullfile(fixture.Folder,'reference_robustness1.fig');
robustnessFile2 = fullfile(fixture.Folder,'reference_robustness2.fig');
dvhMultiscenarioFile = fullfile(fixture.Folder, ...
    'reference_dvh_multiscenario.fig');
dvhTrustbandFile = fullfile(fixture.Folder,'reference_dvh_trustband.fig');
verifyTrue(testCase,isfield(figureFiles,'expectedDoseDifference'));
verifyEqual(testCase,figureFiles.expectedDoseDifference,expectedFile);
verifyEqual(testCase,figureFiles.meanDose,meanFile);
verifyEqual(testCase,figureFiles.stdDose,stdFile);
verifyEqual(testCase,figureFiles.nominalDose,nominalFile);
verifyEqual(testCase,figureFiles.robustness1,robustnessFile1);
verifyEqual(testCase,figureFiles.robustness2,robustnessFile2);
verifyEqual(testCase,figureFiles.dvhMultiscenario,dvhMultiscenarioFile);
verifyEqual(testCase,figureFiles.dvhTrustband,dvhTrustbandFile);
verifyTrue(testCase,exist(expectedFile,'file') == 2);
verifyTrue(testCase,exist(meanFile,'file') == 2);
verifyTrue(testCase,exist(stdFile,'file') == 2);
verifyTrue(testCase,exist(nominalFile,'file') == 2);
verifyTrue(testCase,exist(robustnessFile1,'file') == 2);
verifyTrue(testCase,exist(robustnessFile2,'file') == 2);
verifyTrue(testCase,exist(dvhMultiscenarioFile,'file') == 2);
verifyTrue(testCase,exist(dvhTrustbandFile,'file') == 2);
verifyEqual(testCase,readFigureTitle(expectedFile), ...
    {'Sampled expected dose difference'; ...
    'Reference plan'});
verifyEqual(testCase,readFigureTitle(meanFile), ...
    {'Sampled expected dose'; ...
    'Reference plan'});
verifyEqual(testCase,readFigureTitle(stdFile), ...
    {'Sampled dose standard deviation'; ...
    'Reference plan'});
verifyEqual(testCase,readFigureTitle(nominalFile), ...
    {'Nominal dose'; ...
    'Reference plan'});
verifyEqual(testCase,readFigureTitle(robustnessFile1), ...
    {'Sampled robustness index 1'; ...
    'Reference plan'});
verifyEqual(testCase,readFigureTitle(robustnessFile2), ...
    {'Sampled robustness index 2'; ...
    'Reference plan'});
verifyEqual(testCase,readFigureTitle(dvhMultiscenarioFile), ...
    {'Sampled multi-scenario DVH'; ...
    'Reference plan'});
verifyEqual(testCase,readFigureTitle(dvhTrustbandFile), ...
    {'Sampled DVH trust band'; ...
    'Reference plan'});
verifyStaticFigureHasNoSliceControl(testCase,meanFile);
end

function testSliceControlPersistsInteractiveSpatialFigures(testCase)
cleanup = installSamplingAnalysisStubs(testCase); %#ok<NASGU>
fixture = testCase.applyFixture( ...
    matlab.unittest.fixtures.TemporaryFolderFixture);
analysis = planWorkflow.config.Analysis.defaults();
analysis.figures.save = true;
analysis.figures.visible = 'off';
analysis.figures.closeAfterSave = true;
analysis.figures.sliceControl = true;

figures = struct( ...
    'mean',newHiddenFigureWithTitle('Sampled expected dose'), ...
    'std',newHiddenFigureWithTitle('Sampled dose standard deviation'), ...
    'nominal',newHiddenFigureWithTitle('Nominal dose'), ...
    'robustness',struct( ...
    'index1',newHiddenFigureWithTitle('Sampled robustness index 1'), ...
    'index2',newHiddenFigureWithTitle('Sampled robustness index 2')), ...
    'doseDifference',newHiddenFigureWithTitle( ...
    'Sampled expected dose difference'));
cleanupFig = onCleanup(@() closeFiguresIfOpen( ...
    [figures.mean figures.std figures.nominal ...
    figures.robustness.index1 figures.robustness.index2 ...
    figures.doseDifference])); %#ok<NASGU>

samplingData = struct();
samplingData.ct = struct('cubeDim',[2 2 3]);
samplingData.cst = {};
sample = struct();
sample.pln = struct('numOfFractions',1);
sample.caSamp = {};
sample.resultGUINomScen = struct( ...
    'physicalDose',reshape(1:12,[2 2 3]));
doseStat = sliceControlDoseStat();
meta = struct( ...
    'slice',2, ...
    'plane',3, ...
    'displayScale',1, ...
    'doseDifferenceWindow',[], ...
    'analysisContext',struct('quantity','physicalDose'));

figureFiles = ...
    planWorkflow.analysis.Figures.saveSamplingAnalysisFigures( ...
    fixture.Folder,'reference',figures,samplingData,sample, ...
    analysis,doseStat,meta);

verifyInteractiveSliceFigure(testCase,figureFiles.meanDose,'dose',3);
verifyInteractiveSliceFigure(testCase,figureFiles.stdDose,'dose',3);
verifyInteractiveSliceFigure(testCase,figureFiles.nominalDose,'dose',3);
verifyInteractiveSliceFigure(testCase,figureFiles.robustness1, ...
    'robustness',3);
verifyInteractiveSliceFigure(testCase,figureFiles.robustness2, ...
    'robustness',3);
verifyInteractiveSliceFigure(testCase, ...
    figureFiles.expectedDoseDifference,'expectedDoseDifference',3);
end

function verifyCompactedSamplingData(testCase,samplingData,cachePath)
verifyTrue(testCase,isfield(samplingData,'samplingPayloadRef'));
verifyTrue(testCase,isfield(samplingData.reference,'samplingPayloadRef'));
verifyTrue(testCase,isfield(samplingData.robust{1}, ...
    'samplingPayloadRef'));
verifyFalse(testCase,isfield(samplingData,'ct'));
verifyFalse(testCase,isfield(samplingData,'cst'));
verifyFalse(testCase,isfield(samplingData,'multScen'));
verifyFalse(testCase,isfield(samplingData.reference,'caSamp'));
verifyFalse(testCase,isfield(samplingData.reference,'mSampDose'));
verifyFalse(testCase,isfield(samplingData.reference,'resultGUINomScen'));
verifyFalse(testCase,isfield(samplingData.robust{1},'caSamp'));
verifyPayloadRefFile(testCase,cachePath,samplingData.samplingPayloadRef);
verifyPayloadRefFile(testCase,cachePath, ...
    samplingData.reference.samplingPayloadRef);
verifyPayloadRefFile(testCase,cachePath, ...
    samplingData.robust{1}.samplingPayloadRef);
end

function verifyPayloadRefFile(testCase,cachePath,ref)
verifyTrue(testCase, ...
    planWorkflow.persistence.SamplingPayloadArtifact.isRef(ref));
verifyTrue(testCase, ...
    exist(fullfile(cachePath,ref.cacheRelativeFile),'file') == 2);
end

function config = baseSamplingConfig(testCase)
fixture = testCase.applyFixture( ...
    matlab.unittest.fixtures.TemporaryFolderFixture);
config = struct();
config.outputRootPath = fullfile(fixture.Folder,'output');
config.cacheRootPath = fullfile(fixture.Folder,'cache');
config.runId = 'sampling-reanalysis-test';
config.analysis = planWorkflow.config.Analysis.defaults();
config.analysis.figures.save = false;
config.analysis.figures.visible = 'off';
config.quantityOpt = 'physicalDose';
end

function cleanup = installSamplingAnalysisStubs(testCase)
fixture = testCase.applyFixture( ...
    matlab.unittest.fixtures.TemporaryFolderFixture);
writeMatRadSamplingAnalysisStub(fixture.Folder);
writeMatRadEvaluationModeStub(fixture.Folder);
writeMatRadShowDVHFromSamplingStub(fixture.Folder);
writeMatRadPlotStubs(fixture.Folder);
addpath(fixture.Folder,'-begin');
clear('matRad_samplingAnalysis','matRad_convertToEvaluationMode', ...
    'matRad_showDVHFromSampling','matRad_plotSamplingDoseCubeAnalysis', ...
    'matRad_plotSamplingRobustnessAnalysis', ...
    'matRad_plotExpectedDoseDifferenceAnalysis');
cleanup = onCleanup(@() cleanupSamplingAnalysisStubs(fixture.Folder));
end

function writeMatRadSamplingAnalysisStub(folder)
fid = fopen(fullfile(folder,'matRad_samplingAnalysis.m'),'w');
fprintf(fid,[ ...
    'function [cstStat,doseStat,meta,figures] = matRad_samplingAnalysis(~,~,~,caSamp, ...\n' ...
    '    mSampDose,resultGUINomScen,varargin)\n' ...
    'dvh = struct(''doseGrid'',[0; 1; 2],''volumePoints'',[100; 50; 0]);\n' ...
    'cstStat = struct(''name'',''CTV'',''dvhStat'',struct(''mean'',dvh,''std'',dvh));\n' ...
    'doseStat = struct();\n' ...
    'doseStat.meanCubeW = reshape([1 2 3 4],[2 2 1]);\n' ...
    'doseStat.stdCubeW = zeros(2,2,1);\n' ...
    'doseStat.meanCube = doseStat.meanCubeW;\n' ...
    'doseStat.stdCube = doseStat.stdCubeW;\n' ...
    'doseStat.sampleMask = true(2,2,1);\n' ...
    'doseStat.sampleCoverageFraction = 1;\n' ...
    'doseStat.gammaAnalysis = struct(''gammaPassRate'',100,''gammaCube'',ones(2));\n' ...
    'doseStat.robustnessAnalysis = struct(''index1'',struct(''robustnessIndex'',1));\n' ...
    'meta = struct();\n' ...
    'meta.numSamples = numel(caSamp);\n' ...
    'meta.sampleDoseSum = double(sum(mSampDose(:)));\n' ...
    'meta.nominalFieldCount = numel(fieldnames(resultGUINomScen));\n' ...
    'figures = struct();\n' ...
    'figures.mean = [];\n' ...
    'figures.std = [];\n' ...
    'figures.nominal = [];\n' ...
    'figures.robustness = struct(''index1'',[],''index2'',[]);\n' ...
    'figures.doseDifference = [];\n' ...
    'end\n']);
fclose(fid);
end

function writeMatRadEvaluationModeStub(folder)
fid = fopen(fullfile(folder,'matRad_convertToEvaluationMode.m'),'w');
fprintf(fid,[ ...
    'function [value,mode] = matRad_convertToEvaluationMode(value,~,mode)\n' ...
    'if nargin < 3 || isempty(mode)\n' ...
    '    mode = ''perFraction'';\n' ...
    'end\n' ...
    'mode = char(mode);\n' ...
    'end\n']);
fclose(fid);
end

function writeMatRadShowDVHFromSamplingStub(folder)
fid = fopen(fullfile(folder,'matRad_showDVHFromSampling.m'),'w');
fprintf(fid,[ ...
    'function matRad_showDVHFromSampling(varargin)\n' ...
    'plot([0 1],[1 0]);\n' ...
    'end\n']);
fclose(fid);
end

function writeMatRadPlotStubs(folder)
fid = fopen(fullfile(folder,'matRad_plotSamplingDoseCubeAnalysis.m'),'w');
fprintf(fid,[ ...
    'function fig = matRad_plotSamplingDoseCubeAnalysis(doseAnalysis,doseCube,~,~,slice,varargin)\n' ...
    '[fig,ax] = localAxes(varargin{:});\n' ...
    'imagesc(ax,localSlice(doseCube,slice));\n' ...
    'title(ax,doseAnalysis.title);\n' ...
    'set(ax,''UserData'',struct(''kind'',''dose'',''slice'',slice));\n' ...
    'end\n' ...
    'function [fig,ax] = localAxes(varargin)\n' ...
    'ax = [];\n' ...
    'for i = 1:2:numel(varargin)\n' ...
    '    if strcmpi(varargin{i},''axesHandle''), ax = varargin{i + 1}; end\n' ...
    'end\n' ...
    'if isempty(ax), fig = figure(''Visible'',''off''); ax = axes(''Parent'',fig); else, fig = ancestor(ax,''figure''); end\n' ...
    'end\n' ...
    'function sliceData = localSlice(cube,slice)\n' ...
    'if ndims(cube) < 3, sliceData = cube; else, sliceData = squeeze(cube(:,:,slice)); end\n' ...
    'end\n']);
fclose(fid);

fid = fopen(fullfile(folder,'matRad_plotSamplingRobustnessAnalysis.m'),'w');
fprintf(fid,[ ...
    'function fig = matRad_plotSamplingRobustnessAnalysis(analysis,~,~,slice,varargin)\n' ...
    '[fig,ax,method] = localAxes(varargin{:});\n' ...
    'imagesc(ax,squeeze(analysis.(method).robustnessCube(:,:,slice)));\n' ...
    'title(ax,[''Sampled robustness '' method]);\n' ...
    'set(ax,''UserData'',struct(''kind'',''robustness'',''method'',method,''slice'',slice));\n' ...
    'end\n' ...
    'function [fig,ax,method] = localAxes(varargin)\n' ...
    'ax = []; method = ''index1'';\n' ...
    'for i = 1:2:numel(varargin)\n' ...
    '    if strcmpi(varargin{i},''axesHandle''), ax = varargin{i + 1}; end\n' ...
    '    if strcmpi(varargin{i},''method''), method = varargin{i + 1}; end\n' ...
    'end\n' ...
    'if isempty(ax), fig = figure(''Visible'',''off''); ax = axes(''Parent'',fig); else, fig = ancestor(ax,''figure''); end\n' ...
    'end\n']);
fclose(fid);

fid = fopen(fullfile(folder,'matRad_plotExpectedDoseDifferenceAnalysis.m'),'w');
fprintf(fid,[ ...
    'function fig = matRad_plotExpectedDoseDifferenceAnalysis(analysis,~,~,slice,varargin)\n' ...
    '[fig,ax] = localAxes(varargin{:});\n' ...
    'imagesc(ax,squeeze(analysis.signedExpectedDoseDifferenceCube(:,:,slice)));\n' ...
    'title(ax,''Sampled expected dose difference'');\n' ...
    'set(ax,''UserData'',struct(''kind'',''expectedDoseDifference'',''slice'',slice));\n' ...
    'end\n' ...
    'function [fig,ax] = localAxes(varargin)\n' ...
    'ax = [];\n' ...
    'for i = 1:2:numel(varargin)\n' ...
    '    if strcmpi(varargin{i},''axesHandle''), ax = varargin{i + 1}; end\n' ...
    'end\n' ...
    'if isempty(ax), fig = figure(''Visible'',''off''); ax = axes(''Parent'',fig); else, fig = ancestor(ax,''figure''); end\n' ...
    'end\n']);
fclose(fid);
end

function cleanupSamplingAnalysisStubs(folder)
pathEntries = strsplit(path,pathsep);
if any(strcmp(pathEntries,folder))
    rmpath(folder);
end
clear('matRad_samplingAnalysis','matRad_convertToEvaluationMode', ...
    'matRad_showDVHFromSampling','matRad_plotSamplingDoseCubeAnalysis', ...
    'matRad_plotSamplingRobustnessAnalysis', ...
    'matRad_plotExpectedDoseDifferenceAnalysis');
end

function closeFiguresIfOpen(figures)
for i = 1:numel(figures)
    if ishghandle(figures(i))
        close(figures(i));
    end
end
end

function titleText = readFigureTitle(filePath)
fig = openfig(filePath,'invisible');
cleanup = onCleanup(@() close(fig));
axesHandles = findall(fig,'Type','Axes');
axesHandles = axesHandles(~strcmp(get(axesHandles,'Tag'),'Colorbar'));
titleText = get(get(findTitledAxes(axesHandles),'Title'),'String');
clear cleanup;
end

function fig = newHiddenFigureWithTitle(titleText)
fig = figure('Visible','off');
axesHandle = axes('Parent',fig);
title(axesHandle,titleText);
end

function doseStat = sliceControlDoseStat()
cube = reshape(1:12,[2 2 3]);
doseStat = struct();
doseStat.meanCubeW = cube;
doseStat.stdCubeW = cube .* 0.1;
doseStat.meanAnalysis = struct('title','Sampled expected dose');
doseStat.stdAnalysis = struct('title','Sampled dose standard deviation');
doseStat.nominalAnalysis = struct('title','Nominal dose');
doseStat.robustnessAnalysis = struct( ...
    'index1',struct('robustnessCube',cube), ...
    'index2',struct('robustnessCube',cube));
doseStat.expectedDoseDifferenceAnalysis = struct( ...
    'signedExpectedDoseDifferenceCube',cube);
end

function verifyStaticFigureHasNoSliceControl(testCase,filePath)
fig = openfig(filePath,'invisible');
cleanup = onCleanup(@() close(fig)); %#ok<NASGU>
verifyFalse(testCase,isappdata(fig,'planWorkflowSlicePayload'));
verifyEmpty(testCase,findobj(fig,'Tag','planWorkflowSliceSlider'));
end

function verifyInteractiveSliceFigure(testCase,filePath,kind,sliceMax)
fig = openfig(filePath,'invisible');
cleanup = onCleanup(@() close(fig)); %#ok<NASGU>
verifyTrue(testCase,isappdata(fig,'planWorkflowSlicePayload'));
payload = getappdata(fig,'planWorkflowSlicePayload');
verifyEqual(testCase,payload.kind,kind);
slider = findobj(fig,'Tag','planWorkflowSliceSlider');
verifyNotEmpty(testCase,slider);
verifyEqual(testCase,get(slider,'Min'),1);
verifyEqual(testCase,get(slider,'Max'),sliceMax);
set(slider,'Value',sliceMax);
planWorkflow.analysis.Figures.updateSliceFigure(slider,[]);
payload = getappdata(fig,'planWorkflowSlicePayload');
verifyEqual(testCase,payload.slice,sliceMax);
axesHandle = findTitledAxes(mainAxesInFigure(fig));
userData = get(axesHandle,'UserData');
verifyEqual(testCase,userData.slice,sliceMax);
end

function axesHandles = mainAxesInFigure(fig)
axesHandles = findall(fig,'Type','Axes');
tags = get(axesHandles,'Tag');
if ischar(tags)
    tags = {tags};
end
axesHandles = axesHandles(~strcmp(tags,'Colorbar'));
end

function axesHandle = findTitledAxes(axesHandles)
axesHandle = axesHandles(1);
for i = 1:numel(axesHandles)
    candidateTitle = get(get(axesHandles(i),'Title'),'String');
    if ~isempty(candidateTitle)
        axesHandle = axesHandles(i);
        return;
    end
end
end
