function tests = testResultLogger
tests = functiontests(localfunctions);
end

function testExpectedQiFormattingUsesTotalEvaluationMode(testCase)
planResults = expectedPlanResults(20);
context = planWorkflow.analysis.PlanEvaluationContext.fromPlanResults(planResults);

verifyEqual(testCase,planWorkflow.analysis.ResultLogger.formatMetricValue( ...
    planResults.expectedQi,'mean',context,planResults,1),'40');
verifyEqual(testCase,planWorkflow.analysis.ResultLogger.formatMetricValue( ...
    planResults.expectedQi,'D_95',context,planResults,1),'36');
end

function testExpectedQiFormattingUsesPerFractionEvaluationMode(testCase)
planResults = expectedPlanResults(1);
context = planWorkflow.analysis.PlanEvaluationContext.fromPlanResults(planResults);

verifyEqual(testCase,planWorkflow.analysis.ResultLogger.formatMetricValue( ...
    planResults.expectedQi,'mean',context,planResults,1),'2');
verifyEqual(testCase,planWorkflow.analysis.ResultLogger.formatMetricValue( ...
    planResults.expectedQi,'D_95',context,planResults,1),'1.8');
end

function testExpectedQiVolumeAtDoseOutsideGridUsesDvhBounds(testCase)
doseGrid = [0 1 2 3];
volumePoints = [100 100 50 0];

verifyEqual(testCase,planWorkflow.analysis.ExpectedQi.dvhVolumeAtDose( ...
    doseGrid,volumePoints,-0.1),1);
verifyEqual(testCase,planWorkflow.analysis.ExpectedQi.dvhVolumeAtDose( ...
    doseGrid,volumePoints,4),0);
verifyEqual(testCase,planWorkflow.analysis.ExpectedQi.dvhVolumeAtDose( ...
    [2 0 3 1], [50 100 0 100],1.5),0.75, ...
    'AbsTol',1e-12);
end

function testQiSummaryDoesNotContainClinicalVEndpoints(testCase)
[fields,headers] = planWorkflow.analysis.ResultLogger.qiSummaryColumns();

verifyFalse(testCase,any(strcmp(fields,'V_17_1Gy')));
verifyFalse(testCase,any(strcmp(fields,'V_34_3Gy')));
verifyFalse(testCase,any(strcmp(headers,'V17.1')));
verifyFalse(testCase,any(strcmp(headers,'V34.3')));
end

function testDirectQiLogUsesPlanEvaluationContext(testCase)
planResults = expectedPlanResults(20);
planResults = rmfield(planResults,'expectedQi');
planResults.qi = struct('name','PTV','mean',2,'D_95',1.8);
messages = {};

planWorkflow.analysis.ResultLogger.logQiResults(@capture, ...
    'reference plan',planResults);

text = strjoin(messages,newline);
verifyTrue(testCase,contains(text,'evaluationMode: total'));
verifyTrue(testCase,contains(text,'analysisQuantity: physicalDose'));
verifyTrue(testCase,contains(text,'40'));
verifyTrue(testCase,contains(text,'36'));

    function capture(message)
        messages{end + 1} = message; %#ok<AGROW>
    end
end

function testClinicalEndpointsUseTotalThresholds(testCase)
planResults = struct();
planResults.evaluationModeBase = 'perFraction';
planResults.evaluationMode = 'total';
planResults.evaluationScale = 30;
planResults.numOfFractions = 30;
planResults.analysisQuantity = 'physicalDose';
planResults.cstStat = [structureStat('BLADDER'),structureStat('RECTUM')];

endpoints = planWorkflow.analysis.EndpointStructureContract.endpoints( ...
    struct('description','prostate'));
rows = planWorkflow.analysis.ClinicalEndpointEvaluator.rows( ...
    planResults.cstStat,endpoints, ...
    planWorkflow.analysis.PlanEvaluationContext.fromPlanResults(planResults));

verifyEqual(testCase,{rows.metric},{'V60','V40','V50'});
verifyEqual(testCase,[rows.mean],[50 83.3333333333333 66.6666666666667], ...
    'AbsTol',1e-10);
verifyEqual(testCase,[rows.uncertaintyHalfWidth], ...
    [10 3.33333333333333 6.66666666666666], ...
    'AbsTol',1e-10);
verifyEqual(testCase,[rows.min],[40 80 60], ...
    'AbsTol',1e-10);
verifyEqual(testCase,[rows.max],[60 86.6666666666667 73.3333333333333], ...
    'AbsTol',1e-10);
end

function testClinicalTotalDoseEndpointsIgnoreDisplayMode(testCase)
planResults = struct();
planResults.evaluationModeBase = 'perFraction';
planResults.evaluationMode = 'perFraction';
planResults.evaluationScale = 1;
planResults.numOfFractions = 30;
planResults.analysisQuantity = 'physicalDose';
planResults.cstStat = [structureStat('BLADDER'),structureStat('RECTUM')];

endpoints = planWorkflow.analysis.EndpointStructureContract.endpoints( ...
    struct('description','prostate'));
rows = planWorkflow.analysis.ClinicalEndpointEvaluator.rows( ...
    planResults.cstStat,endpoints, ...
    planWorkflow.analysis.PlanEvaluationContext.fromPlanResults(planResults));

verifyEqual(testCase,[rows.mean],[50 83.3333333333333 66.6666666666667], ...
    'AbsTol',1e-10);
end

function testClinicalPorUsesEndpointGoal(testCase)
planResults = expectedPlanResults(1);
planResults.cstStat = structureStat('OAR');
planResults.cstStat.dvhStat.mean.doseGrid = [0 2 4 6];
referenceResults = planResults;
referenceResults.cstStat = structureStat('OAR');
endpoint = struct( ...
    'structureNames',{{'OAR'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'outputDoseMode','perFractionDose', ...
    'unit','Gy');
endpoints = planWorkflow.analysis.ClinicalEndpointCatalog.normalize( ...
    endpoint,'testEndpoint');

rows = planWorkflow.analysis.ClinicalEndpointEvaluator.evaluatePlan( ...
    planResults,endpoints,referenceResults);

verifyGreaterThan(testCase,rows.deltaFromReference,0);
verifyGreaterThan(testCase,rows.por,0);
verifyEqual(testCase,rows.goal,'lowerIsBetter');

endpoint.goal = 'higherIsBetter';
endpoints = planWorkflow.analysis.ClinicalEndpointCatalog.normalize( ...
    endpoint,'testEndpoint');
rows = planWorkflow.analysis.ClinicalEndpointEvaluator.evaluatePlan( ...
    planResults,endpoints,referenceResults);

verifyGreaterThan(testCase,rows.deltaFromReference,0);
verifyLessThan(testCase,rows.por,0);
verifyEqual(testCase,rows.goal,'higherIsBetter');
end

function testClinicalVEndpointAboveDvhGridReportsZero(testCase)
planResults = struct();
planResults.evaluationModeBase = 'perFraction';
planResults.evaluationMode = 'perFraction';
planResults.evaluationScale = 1;
planResults.numOfFractions = 30;
planResults.analysisQuantity = 'physicalDose';
planResults.cstStat = structureStat('BLADDER');
endpoint = struct( ...
    'structureNames',{{'BLADDER'}}, ...
    'metric','V120', ...
    'kind','V', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'threshold',120, ...
    'thresholdUnit','Gy', ...
    'thresholdMode','totalDose', ...
    'unit','%');

endpoints = planWorkflow.analysis.ClinicalEndpointCatalog.normalize( ...
    endpoint,'testEndpoint');
rows = planWorkflow.analysis.ClinicalEndpointEvaluator.rows( ...
    planResults.cstStat,endpoints, ...
    planWorkflow.analysis.PlanEvaluationContext.fromPlanResults(planResults));

verifyEqual(testCase,rows.mean,0);
end

function testClinicalDoseOutputsIgnoreDisplayMode(testCase)
planResults = struct();
planResults.evaluationModeBase = 'perFraction';
planResults.evaluationMode = 'perFraction';
planResults.evaluationScale = 1;
planResults.numOfFractions = 30;
planResults.analysisQuantity = 'physicalDose';
planResults.cstStat = structureStat('HEART');
endpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy');

endpoints = planWorkflow.analysis.ClinicalEndpointCatalog.normalize( ...
    endpoint,'testEndpoint');
rows = planWorkflow.analysis.ClinicalEndpointEvaluator.rows( ...
    planResults.cstStat,endpoints, ...
    planWorkflow.analysis.PlanEvaluationContext.fromPlanResults(planResults));

verifyEqual(testCase,rows.mean,60,'AbsTol',1e-12);
end

function testClinicalEndpointRejectsDoseQuantityMismatch(testCase)
planResults = struct();
planResults.evaluationModeBase = 'perFraction';
planResults.evaluationMode = 'perFraction';
planResults.evaluationScale = 1;
planResults.numOfFractions = 30;
planResults.analysisQuantity = 'RBExDose';
planResults.cstStat = structureStat('HEART');
endpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy');
endpoints = planWorkflow.analysis.ClinicalEndpointCatalog.normalize( ...
    endpoint,'testEndpoint');

verifyError(testCase,@() ...
    planWorkflow.analysis.ClinicalEndpointEvaluator.rows( ...
    planResults.cstStat,endpoints, ...
    planWorkflow.analysis.PlanEvaluationContext.fromPlanResults(planResults)), ...
    ['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
     'EndpointDoseQuantityMismatch']);
end

function testClinicalEndpointRequiresDoseQuantity(testCase)
endpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy');

verifyError(testCase,@() ...
    planWorkflow.analysis.ClinicalEndpointCatalog.normalize(endpoint, ...
    'testEndpoint'), ...
    ['planWorkflow:analysis:ClinicalEndpointCatalog:' ...
     'MissingEndpointField']);
end

function testClinicalEndpointRequiresGoal(testCase)
endpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'doseQuantity','physicalDose', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy');

verifyError(testCase,@() ...
    planWorkflow.analysis.ClinicalEndpointCatalog.normalize(endpoint, ...
    'testEndpoint'), ...
    ['planWorkflow:analysis:ClinicalEndpointCatalog:' ...
     'MissingEndpointField']);
end

function testClinicalEndpointRequiresEndpointQuantity(testCase)
planResults = struct();
planResults.evaluationModeBase = 'perFraction';
planResults.evaluationMode = 'perFraction';
planResults.evaluationScale = 1;
planResults.numOfFractions = 30;
planResults.cstStat = structureStat('HEART');
endpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy');
endpoints = planWorkflow.analysis.ClinicalEndpointCatalog.normalize( ...
    endpoint,'testEndpoint');

verifyError(testCase,@() ...
    planWorkflow.analysis.ClinicalEndpointEvaluator.rows( ...
    planResults.cstStat,endpoints, ...
    planWorkflow.analysis.PlanEvaluationContext.fromPlanResults(planResults)), ...
    ['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
     'MissingEndpointQuantity']);
end

function testRbexdEndpointRequiresRbexdUnit(testCase)
endpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','RBExDose', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy');

verifyError(testCase,@() ...
    planWorkflow.analysis.ClinicalEndpointCatalog.normalize(endpoint, ...
    'testEndpoint'), ...
    ['planWorkflow:analysis:ClinicalEndpointCatalog:' ...
     'InvalidEndpointOutputUnit']);
end

function testClinicalTotalDoseEndpointRequiresFractionCount(testCase)
planResults = struct();
planResults.evaluationModeBase = 'perFraction';
planResults.evaluationMode = 'total';
planResults.evaluationScale = 30;
planResults.analysisQuantity = 'physicalDose';
planResults.cstStat = structureStat('HEART');
endpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy');
endpoints = planWorkflow.analysis.ClinicalEndpointCatalog.normalize( ...
    endpoint,'testEndpoint');

verifyError(testCase,@() ...
    planWorkflow.analysis.ClinicalEndpointEvaluator.rows( ...
    planResults.cstStat,endpoints, ...
    planWorkflow.analysis.PlanEvaluationContext.fromPlanResults(planResults)), ...
    ['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
     'MissingFractionCountForTotalEndpoint']);
end

function testExpectedQiMinMaxAndStdUseTrustband(testCase)
cstStat = structureStat('OAR',[0 20 10 5]);
cst = cell(1,6);
cst{1,3} = 'OAR';
cst{1,6} = {};
pln = struct('numOfFractions',1);

qi = planWorkflow.analysis.ExpectedQi.fromCstStat(cstStat,cst,pln);

verifyEqual(testCase,qi.mean,2);
verifyEqual(testCase,qi.spatialStdDose, ...
    planWorkflow.analysis.ExpectedQi.stdDoseFromDvh( ...
    [0 1 2 3],[100 100 50 0]),'AbsTol',1e-12);
verifyEqual(testCase,qi.uncertaintyHalfWidth,0.2125,'AbsTol',1e-12);
verifyEqual(testCase,qi.trustbandHalfWidth,0.2125,'AbsTol',1e-12);
verifyEqual(testCase,qi.min,1);
verifyEqual(testCase,qi.max,3);
end

function testClinicalEndpointsLoadFromDescriptionJson(testCase)
endpoints = planWorkflow.analysis.EndpointStructureContract.endpoints( ...
    struct('description','h&n'));

verifyNotEmpty(testCase,endpoints);
verifyTrue(testCase,any(strcmp({endpoints.metric},'Dmax')));
verifyTrue(testCase,any(strcmp({endpoints.kind},'mean')));
end

function testClinicalEndpointsFilterByAnalysisQuantity(testCase)
endpoints = planWorkflow.analysis.EndpointStructureContract.endpoints( ...
    struct('description','prostate'),'RBExDose');

verifyEmpty(testCase,endpoints);
end

function testEndpointFileAndInlineEndpointsAreAdditive(testCase)
fileEndpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy');
inlineEndpoint = struct( ...
    'structureNames',{{'BLADDER'}}, ...
    'metric','V60', ...
    'kind','V', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'threshold',60, ...
    'thresholdUnit','Gy', ...
    'thresholdMode','totalDose', ...
    'unit','%');
endpointFile = writeEndpointFile(fileEndpoint);
cleanup = onCleanup(@() delete(endpointFile)); %#ok<NASGU>
runConfig.analysis.endpointsFile = endpointFile;
runConfig.analysis.endpoints = inlineEndpoint;

endpoints = planWorkflow.analysis.EndpointStructureContract.endpoints( ...
    runConfig,'physicalDose');

verifyEqual(testCase,{endpoints.metric},{'Dmean','V60'});
end

function testEndpointFileFiltersIncompatibleDoseQuantity(testCase)
physicalEndpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy');
rbexdEndpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','DmeanRBE', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','RBExDose', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy(RBE)');
endpointFile = writeEndpointFile([physicalEndpoint rbexdEndpoint]);
cleanup = onCleanup(@() delete(endpointFile)); %#ok<NASGU>
runConfig.analysis.endpointsFile = endpointFile;

endpoints = planWorkflow.analysis.EndpointStructureContract.endpoints( ...
    runConfig,'RBExDose');

verifyEqual(testCase,{endpoints.metric},{'DmeanRBE'});
end

function testEndpointFileDiscoveryUsesLightweightMetadata(testCase)
endpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose');
endpointFile = writeEndpointFile(endpoint);
cleanup = onCleanup(@() delete(endpointFile)); %#ok<NASGU>

doseQuantities = ...
    planWorkflow.analysis.ClinicalEndpointCatalog.fileDoseQuantities( ...
    endpointFile);

verifyEqual(testCase,doseQuantities,{'physicalDose'});
verifyError(testCase,@() ...
    planWorkflow.analysis.ClinicalEndpointCatalog.loadFile(endpointFile), ...
    ['planWorkflow:analysis:ClinicalEndpointCatalog:' ...
     'MissingEndpointField']);
end

function testClinicalEndpointMismatchSkipsInsteadOfFailing(testCase)
planResults = struct();
planResults.evaluationModeBase = 'perFraction';
planResults.evaluationMode = 'perFraction';
planResults.evaluationScale = 1;
planResults.numOfFractions = 30;
planResults.analysisQuantity = 'RBExDose';
planResults.cstStat = structureStat('BLADDER');
runConfig.description = 'prostate';
messages = {};

planWorkflow.analysis.ResultLogger.logClinicalEndpointResults( ...
    @capture,'reference plan',planResults,runConfig,[]);

text = strjoin(messages,newline);
verifyTrue(testCase,contains(text, ...
    'no endpoints configured for endpointQuantity "RBExDose"'));

    function capture(message)
        messages{end + 1} = message; %#ok<AGROW>
    end
end

function testClinicalEndpointsUseEndpointQuantityCstStat(testCase)
planResults = struct();
planResults.evaluationModeBase = 'perFraction';
planResults.evaluationMode = 'perFraction';
planResults.evaluationScale = 1;
planResults.numOfFractions = 30;
planResults.analysisQuantity = 'effect';
planResults.endpointQuantity = 'physicalDose';
planResults.cstStat = structureStat('HEART');
planResults.cstStat.dvhStat.mean.doseGrid = [0 20 40 60];
planResults.cstStat.dvhStat.mean.volumePoints = [100 100 100 100];
planResults.endpointCstStat = structureStat('HEART');
planResults.endpointCstStat.dvhStat.mean.doseGrid = [0 1 2 3];
planResults.endpointCstStat.dvhStat.mean.volumePoints = [100 100 50 0];
endpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy');
endpoints = planWorkflow.analysis.ClinicalEndpointCatalog.normalize( ...
    endpoint,'testEndpoint');

rows = planWorkflow.analysis.ClinicalEndpointEvaluator.evaluatePlan( ...
    planResults,endpoints,[]);

verifyEqual(testCase,rows.mean,60,'AbsTol',1e-12);
end

function testEndpointFileOptionsUseCanonicalDoseQuantity(testCase)
analysis = planWorkflow.config.Analysis.defaults();
protonConfig.radiationMode = 'protons';
protonConfig.bioModel = 'constRBE';
photonConfig.radiationMode = 'photons';
photonConfig.bioModel = 'none';
photonConfig.quantityOpt = 'effect';
analysis.endpointsFile = 'prostate.json';

protonOptions = planWorkflow.gui.WorkflowParameterOptions.analysisOptionSets( ...
    analysis,struct(),protonConfig);
analysis.endpointsFile = '';
photonOptions = planWorkflow.gui.WorkflowParameterOptions.analysisOptionSets( ...
    analysis,struct(),photonConfig);

verifyEqual(testCase, ...
    planWorkflow.plan.DoseQuantityResolver.fromRunConfig(photonConfig), ...
    'effect');
verifyEqual(testCase, ...
    planWorkflow.plan.DoseQuantityResolver.visualFromRunConfig( ...
    photonConfig),'physicalDose');
verifyEqual(testCase,protonOptions.endpointsFile.values{2},'none');
verifyFalse(testCase,any(strcmp( ...
    protonOptions.endpointsFile.validValues,'prostate.json')));
verifyTrue(testCase,any(strcmp( ...
    protonOptions.endpointsFile.values,'prostate.json')));
verifyTrue(testCase,contains(protonOptions.endpointsFile.labels{1}, ...
    'not valid'));
verifyTrue(testCase,any(strcmp( ...
    photonOptions.endpointsFile.values,'prostate.json')));
end

function testEffectQuantityHasNoClinicalEndpointCatalog(testCase)
verifyEqual(testCase, ...
    planWorkflow.analysis.ClinicalEndpointCatalog.fileNamesForDoseQuantity( ...
    'effect'),{'none'});

endpoint = struct( ...
    'structureNames',{{'PTV'}}, ...
    'metric','DmeanEffect', ...
    'kind','mean', ...
    'goal','reportOnly', ...
    'doseQuantity','effect', ...
    'unit','effect', ...
    'outputDoseMode','totalDose');

verifyError(testCase,@() ...
    planWorkflow.analysis.ClinicalEndpointCatalog.normalize( ...
    endpoint,'effect endpoint'), ...
    'planWorkflow:analysis:ClinicalEndpointCatalog:InvalidEndpointDoseQuantity');
end

function testClinicalEndpointThresholdSemanticsAreRequired(testCase)
endpoint = struct( ...
    'structureNames',{{'BLADDER'}}, ...
    'metric','V60', ...
    'kind','V', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'threshold',60, ...
    'unit','%');

verifyError(testCase,@() ...
    planWorkflow.analysis.ClinicalEndpointCatalog.normalize(endpoint, ...
    'testEndpoint'), ...
    ['planWorkflow:analysis:ClinicalEndpointCatalog:' ...
     'MissingEndpointThresholdSemantics']);
end

function testClinicalEndpointThresholdSemanticsAreExplicit(testCase)
endpoint = struct( ...
    'structureNames',{{'RECTUM'}}, ...
    'metric','D5', ...
    'kind','D', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'threshold',5, ...
    'thresholdUnit','%', ...
    'thresholdMode','volumePercent', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy');

endpoints = planWorkflow.analysis.ClinicalEndpointCatalog.normalize( ...
    endpoint,'testEndpoint');

verifyEqual(testCase,endpoints.thresholdUnit,'%');
verifyEqual(testCase,endpoints.thresholdMode,'volumePercent');
verifyEqual(testCase,endpoints.outputDoseMode,'totalDose');
end

function testClinicalDoseEndpointOutputModeIsRequired(testCase)
endpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'unit','Gy');

verifyError(testCase,@() ...
    planWorkflow.analysis.ClinicalEndpointCatalog.normalize(endpoint, ...
    'testEndpoint'), ...
    ['planWorkflow:analysis:ClinicalEndpointCatalog:' ...
     'InvalidEndpointOutputDoseMode']);
end

function testClinicalEndpointRejectsDisplayModeThreshold(testCase)
endpoint = struct( ...
    'structureNames',{{'BLADDER'}}, ...
    'metric','V60', ...
    'kind','V', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'threshold',60, ...
    'thresholdUnit','Gy', ...
    'thresholdMode','evaluationDose', ...
    'unit','%');

verifyError(testCase,@() ...
    planWorkflow.analysis.ClinicalEndpointCatalog.normalize(endpoint, ...
    'testEndpoint'), ...
    ['planWorkflow:analysis:ClinicalEndpointCatalog:' ...
     'InvalidEndpointThresholdSemantics']);
end

function testMissingClinicalEndpointsAreLogged(testCase)
planResults = struct();
planResults.evaluationModeBase = 'perFraction';
planResults.evaluationMode = 'perFraction';
planResults.evaluationScale = 1;
planResults.numOfFractions = 30;
planResults.analysisQuantity = 'physicalDose';
planResults.cstStat = structureStat('BLADDER');
runConfig.analysis.endpoints = struct( ...
    'structureNames',{{'RECTUM'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy');
messages = {};

planWorkflow.analysis.ResultLogger.logClinicalEndpointResults( ...
    @capture,'reference plan',planResults,runConfig,[]);

text = strjoin(messages,newline);
verifyTrue(testCase,contains(text, ...
    'missing required endpoint Dmean (mean) for reference plan'));
verifyTrue(testCase,contains(text,'RECTUM'));

    function capture(message)
        messages{end + 1} = message; %#ok<AGROW>
    end
end

function testClinicalEndpointsAreLoggedWithoutSampling(testCase)
endpoint = struct( ...
    'structureNames',{{'HEART'}}, ...
    'metric','Dmean', ...
    'kind','mean', ...
    'goal','lowerIsBetter', ...
    'doseQuantity','physicalDose', ...
    'outputDoseMode','totalDose', ...
    'unit','Gy');
results = struct();
results.runConfig.analysis.endpoints = endpoint;
results.reference = rmfield(expectedPlanResults(1),'expectedQi');
results.reference.label = 'Reference';
results.reference.qi = struct('name','HEART','mean',2);
results.reference.cstStat = structureStat('HEART');
messages = {};

planWorkflow.analysis.ResultLogger.log(@capture,results);

text = strjoin(messages,newline);
verifyTrue(testCase,contains(text, ...
    'Analysis clinical endpoints Reference from DVH'));
verifyTrue(testCase,contains(text,'Dmean'));

    function capture(message)
        messages{end + 1} = message; %#ok<AGROW>
    end
end

function testExpectedQiLogIncludesEvaluationContext(testCase)
planResults = expectedPlanResults(20);
messages = {};

planWorkflow.analysis.ResultLogger.logExpectedQiResults(@capture, ...
    'reference plan',planResults);

text = strjoin(messages,newline);
verifyTrue(testCase,contains(text,'evaluationMode: total'));
verifyTrue(testCase,contains(text,'evaluationModeBase: perFraction'));

    function capture(message)
        messages{end + 1} = message; %#ok<AGROW>
    end
end

function testSamplingSummaryUsesCurrentRobustnessSchema(testCase)
planResults = struct();
planResults.doseStat = struct();
planResults.doseStat.gammaAnalysis.gammaPassRate = 54.42;
planResults.doseStat.robustnessAnalysis.index1.robustnessIndex = 0.1234;
planResults.doseStat.robustnessAnalysis.index2.robustnessIndex = 0.5678;
planResults.doseStat.meanCubeW = [1 2 3];
planResults.doseStat.stdCubeW = [0.1 0.2 0.3];

row = planWorkflow.analysis.ResultLogger.formatSamplingPlanRow( ...
    'reference',planResults,[24 repmat(9,1,6)]);

verifyTrue(testCase,contains(row,'54.42'));
verifyTrue(testCase,contains(row,'0.123'));
verifyTrue(testCase,contains(row,'0.568'));
end

function testSamplingSummaryUsesPlanLabels(testCase)
samplingResults = struct();
samplingResults.scenarioMode = 'wcScen';
samplingResults.reference = samplingPlanResults('Reference (Nominal)',0.416);
samplingResults.robust = { ...
    samplingPlanResults('PTV',0.419), ...
    samplingPlanResults('INTERVAL2 (theta1=5)',0.8)};
messages = {};

planWorkflow.analysis.ResultLogger.logSamplingResults(@capture, ...
    samplingResults);

text = strjoin(messages,newline);
verifyTrue(testCase,contains(text,'Reference (Nominal)'));
verifyTrue(testCase,contains(text,'PTV'));
verifyTrue(testCase,contains(text,'INTERVAL2 (theta1=5)'));
verifyFalse(testCase,contains(text,'robust plan 1'));
verifyFalse(testCase,contains(text,'robust plan 2'));

    function capture(message)
        messages{end + 1} = message; %#ok<AGROW>
    end
end

function planResults = expectedPlanResults(evaluationScale)
planResults = struct();
planResults.evaluationModeBase = 'perFraction';
if evaluationScale == 1
    planResults.evaluationMode = 'perFraction';
else
    planResults.evaluationMode = 'total';
end
planResults.evaluationScale = evaluationScale;
planResults.numOfFractions = max(1,evaluationScale);
planResults.analysisQuantity = 'physicalDose';
planResults.expectedQi = struct( ...
    'name','PTV', ...
    'COV1',0.95, ...
    'COV_95',0.96, ...
    'COV_98',0.97, ...
    'COV_99',0.98, ...
    'mean',2, ...
    'spatialStdDose',0.1, ...
    'uncertaintyHalfWidth',0.05, ...
    'min',1, ...
    'max',2.5, ...
    'D_95',1.8, ...
    'D_98',1.7, ...
    'D_2',2.4, ...
    'D_50',2.0);
planResults.cstStat = structureStat('PTV');
end

function planResults = samplingPlanResults(label,ri1)
planResults = struct();
planResults.label = label;
planResults.doseStat.robustnessAnalysis.index1.robustnessIndex = ri1;
planResults.doseStat.robustnessAnalysis.index2.robustnessIndex = ri1;
planResults.doseStat.meanCubeW = 1;
planResults.doseStat.stdCubeW = 0.1;
end

function cstStat = structureStat(name,stdVolume)
if nargin < 2
    stdVolume = [0 0 10 0];
end
dvh = struct();
dvh.doseGrid = [0 1 2 3];
dvh.volumePoints = [100 100 50 0];
stdDvh = struct();
stdDvh.doseGrid = dvh.doseGrid;
stdDvh.volumePoints = stdVolume;

cstStat = struct();
cstStat.name = name;
cstStat.dvhStat = struct('mean',dvh,'std',stdDvh,'min',dvh,'max',dvh);
end

function filePath = writeEndpointFile(endpoints)
filePath = [tempname '.json'];
document = struct('endpoints',endpoints);
fid = fopen(filePath,'w');
fprintf(fid,'%s',jsonencode(document));
fclose(fid);
end
