classdef DosePullingPanel
    % DosePullingPanel Owns dose-pulling GUI parameter contracts.

    methods (Static)
        function tableHandle = create(parent,position,callbacks)
            if nargin < 3
                callbacks = struct();
            end
            tableHandle = planWorkflow.gui.ParameterPanelRenderer.create( ...
                parent,position, ...
                planWorkflow.gui.panels.DosePullingPanel.specs(), ...
                planWorkflow.gui.panels.DosePullingPanel.optionSets(), ...
                struct(),callbacks);
        end

        function specs = specs()
            specs = planWorkflow.gui.ParameterPanelSpecAdapter.fromSchema( ...
                planWorkflow.config.WorkflowParameterSchema.dosePullingSpecs());
        end

        function load(tableHandle,runConfig)
            planWorkflow.gui.ParameterPanelRenderer.load( ...
                tableHandle,runConfig, ...
                planWorkflow.gui.panels.DosePullingPanel.optionSets(), ...
                struct());
            planWorkflow.gui.panels.DosePullingPanel.refresh(tableHandle);
        end

        function runConfig = sync(tableHandle,runConfig)
            runConfig = planWorkflow.gui.ParameterPanelRenderer.toConfig( ...
                runConfig,tableHandle);
        end

        function refresh(tableHandle)
            channel1Enabled = ...
                planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                tableHandle,'dose_pulling1');
            channel2Enabled = ...
                planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                tableHandle,'dose_pulling2');
            strategy = ...
                planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                tableHandle,'dose_pulling_strategy');
            selectionPolicy = ...
                planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                tableHandle,'dose_pulling_selection_policy');
            fields = planWorkflow.gui.panels.DosePullingPanel.visibleFields( ...
                channel1Enabled,channel2Enabled,strategy,selectionPolicy);
            planWorkflow.gui.ParameterPanelRenderer.setVisibleFields( ...
                tableHandle,fields);
        end

        function fields = visibleFields(channel1Enabled,channel2Enabled, ...
                strategy,selectionPolicy)
            if nargin < 3
                strategy = [];
            end
            if nargin < 4
                selectionPolicy = [];
            end
            fields = ...
                planWorkflow.config.WorkflowParameterSchema.dosePullingVisibleFields( ...
                channel1Enabled,channel2Enabled,strategy,selectionPolicy);
        end

        function optionSets = optionSets()
            optionSets = struct();
            optionSets.dose_pulling_strategy = ...
                {'heuristicMultiObjective','Threshold'};
            optionSets.dose_pulling_search_schedule = {'exponential'};
            optionSets.dose_pulling_selection_policy = ...
                {'normalizedKnee','lexicographic','weightedSum'};
        end
    end
end
