classdef PrecomputeEditorPanel
    % PrecomputeEditorPanel Builds precompute editor tabs and controls.

    methods (Static)
        function callbacks = callbacks(handlers,defaultCallback)
            callbacks = struct( ...
                'reference_label',handlers.referencePlanLabelChanged, ...
                'robustness',handlers.selectionChanged, ...
                'reference_robustness',handlers.selectionChanged, ...
                'reference_KMode',handlers.selectionChanged, ...
                'reference_scen_mode',handlers.selectionChanged, ...
                'reference_ctActive',handlers.selectionChanged, ...
                'reference_setupActive',handlers.selectionChanged, ...
                'reference_rangeActive',handlers.selectionChanged, ...
                'reference_gantryActive',handlers.selectionChanged, ...
                'reference_couchActive',handlers.selectionChanged, ...
                'label',handlers.planLabelChanged, ...
                'KMode',handlers.selectionChanged, ...
                'scen_mode',handlers.selectionChanged, ...
                'ctActive',handlers.selectionChanged, ...
                'setupActive',handlers.selectionChanged, ...
                'rangeActive',handlers.selectionChanged, ...
                'gantryActive',handlers.selectionChanged, ...
                'couchActive',handlers.selectionChanged);
            if nargin >= 2 && ~isempty(defaultCallback)
                callbacks.defaultCallback = defaultCallback;
            end
        end

        function handles = create(parent,runConfig,callbacks)
            handles = struct();
            handles.callbacks = callbacks;
            layout = planWorkflow.gui.panels.PrecomputePanel.actionLayout();
            handles.addRobustPlanButton = uicontrol( ...
                'Parent',parent,'Style','pushbutton', ...
                'String','Add robust plan','Units','normalized', ...
                'Position',layout.addRobustPlanButton, ...
                'Callback',callbacks.addRobustPlan);
            handles.deleteRobustPlanButton = uicontrol( ...
                'Parent',parent,'Style','pushbutton', ...
                'String','Delete robust plan','Units','normalized', ...
                'Position',layout.deleteRobustPlanButton, ...
                'Callback',callbacks.deleteRobustPlan);
            handles.tabGroup = uitabgroup('Parent',parent, ...
                'Units','normalized','Position',layout.tabGroup);
            handles.transversalTab = uitab(handles.tabGroup, ...
                'Title','General');
            handles.referenceTab = uitab(handles.tabGroup,'Title', ...
                planWorkflow.gui.panels.PrecomputePanel.referencePlanTabTitle( ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig).label));
            handles.transversalConfigTable = ...
                planWorkflow.gui.ParameterPanelRenderer.create( ...
                handles.transversalTab,[0.03 0.05 0.94 0.90], ...
                planWorkflow.gui.panels.PrecomputePanel.transversalSpecs(), ...
                planWorkflow.gui.panels.PrecomputePanel.optionSets( ...
                runConfig),struct(),struct());
            handles.referenceConfigTable = ...
                planWorkflow.gui.ParameterPanelRenderer.create( ...
                handles.referenceTab,[0.03 0.05 0.94 0.90], ...
                planWorkflow.gui.panels.PrecomputePanel.referenceSpecs(), ...
                planWorkflow.gui.panels.PrecomputePanel.optionSets( ...
                runConfig),struct(),callbacks.reference);
            handles.robustTabs = gobjects(0);
            handles.robustConfigTables = handles.referenceConfigTable;
            handles.robustConfigTables(:) = [];
            handles.configTables = [ ...
                handles.transversalConfigTable; ...
                handles.referenceConfigTable];
        end

        function [handles,runConfig,template] = load(handles,runConfig, ...
                template,transversalConfig)
            [runConfig,template] = ...
                planWorkflow.gui.panels.PrecomputeEditorPanel.align( ...
                runConfig,template);
            if planWorkflow.gui.panels.PrecomputeEditorPanel.robustTabsNeedRebuild( ...
                    handles,runConfig)
                handles = ...
                    planWorkflow.gui.panels.PrecomputeEditorPanel.rebuildRobustTabs( ...
                    handles,runConfig);
            else
                handles = ...
                    planWorkflow.gui.panels.PrecomputeEditorPanel.refreshConfigTables( ...
                    handles);
            end

            planWorkflow.gui.ParameterPanelRenderer.load( ...
                handles.transversalConfigTable,transversalConfig, ...
                planWorkflow.gui.panels.PrecomputePanel.optionSets( ...
                runConfig),struct());
            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            planWorkflow.gui.ParameterPanelRenderer.load( ...
                handles.referenceConfigTable, ...
                planWorkflow.config.RobustPlanPanelAdapter.referencePanelConfig( ...
                runConfig), ...
                planWorkflow.gui.panels.PrecomputePanel.optionSets( ...
                runConfig,reference),struct());
            planWorkflow.gui.panels.PrecomputeEditorPanel.storeLoadedField( ...
                handles.referenceConfigTable,'reference_robustness', ...
                reference.robustnessMode);
            handles = ...
                planWorkflow.gui.panels.PrecomputeEditorPanel.refreshTitles( ...
                handles,runConfig);

            robustPlans = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            for planIx = 1:numel(handles.robustConfigTables)
                planWorkflow.gui.ParameterPanelRenderer.load( ...
                    handles.robustConfigTables(planIx), ...
                    planWorkflow.config.RobustPlanPanelAdapter.planPanelConfig( ...
                    robustPlans(planIx)), ...
                    planWorkflow.gui.panels.PrecomputePanel.optionSets( ...
                    runConfig,robustPlans(planIx)),struct());
                planWorkflow.gui.panels.PrecomputeEditorPanel.storeLoadedField( ...
                    handles.robustConfigTables(planIx),'robustness', ...
                    robustPlans(planIx).robustnessMode);
            end
            handles = ...
                planWorkflow.gui.panels.PrecomputeEditorPanel.refreshVisibility( ...
                handles);
        end

        function [handles,runConfig,template,transversalConfig] = sync( ...
                handles,runConfig,template,transversalConfig)
            transversalConfig = ...
                planWorkflow.gui.ParameterPanelRenderer.toConfig( ...
                transversalConfig,handles.transversalConfigTable);
            runConfig.doseResolution = transversalConfig.doseResolution;
            runConfig.useCache = transversalConfig.useCache;
            runConfig.writeCache = transversalConfig.writeCache;

            referencePanel = ...
                planWorkflow.gui.ParameterPanelRenderer.toConfig( ...
                planWorkflow.config.RobustPlanPanelAdapter.defaultReferencePanelConfig(), ...
                handles.referenceConfigTable);
            if planWorkflow.gui.panels.PrecomputeEditorPanel.fieldChanged( ...
                    handles.referenceConfigTable,'reference_robustness', ...
                    referencePanel.reference_robustness)
                template = ...
                    planWorkflow.templates.ObjectiveRobustnessMutator.harmonizeTemplateNonNoneRobustness( ...
                    template,'reference', ...
                    referencePanel.reference_robustness);
            end
            runConfig = ...
                planWorkflow.config.RobustPlanPanelAdapter.applyReferencePanelConfig( ...
                runConfig,referencePanel);

            robustObjectiveSets = ...
                planWorkflow.templates.PlanTemplate.robustObjectiveSets( ...
                template);
            robustPlans = repmat( ...
                planWorkflow.config.RobustPlanConfig.defaultPlan(), ...
                1,numel(handles.robustConfigTables));
            for planIx = 1:numel(handles.robustConfigTables)
                if planIx <= numel(robustObjectiveSets)
                    planConfig = ...
                        planWorkflow.config.RobustPlanPanelAdapter.defaultPlanPanelConfig( ...
                        robustObjectiveSets(planIx));
                else
                    planConfig = ...
                        planWorkflow.config.RobustPlanPanelAdapter.planPanelConfig( ...
                        planWorkflow.config.RobustPlanConfig.defaultPlan());
                end
                planConfig = ...
                    planWorkflow.gui.ParameterPanelRenderer.toConfig( ...
                    planConfig,handles.robustConfigTables(planIx));
                if planWorkflow.gui.panels.PrecomputeEditorPanel.fieldChanged( ...
                        handles.robustConfigTables(planIx),'robustness', ...
                        planConfig.robustness)
                    template = ...
                        planWorkflow.templates.ObjectiveRobustnessMutator.harmonizeTemplateNonNoneRobustness( ...
                        template,planConfig.objectiveSetName, ...
                        planConfig.robustness);
                end
                robustPlans(planIx) = ...
                    planWorkflow.config.RobustPlanPanelAdapter.planFromPanelConfig( ...
                    planConfig);
            end

            runConfig.precompute.robustPlans = ...
                planWorkflow.config.RobustPlanConfig.normalizePlans( ...
                robustPlans);
            [runConfig,template] = ...
                planWorkflow.gui.panels.PrecomputeEditorPanel.align( ...
                runConfig,template);
            handles = ...
                planWorkflow.gui.panels.PrecomputeEditorPanel.refreshTitles( ...
                handles,runConfig);
            planWorkflow.gui.ParameterPanelRenderer.load( ...
                handles.referenceConfigTable, ...
                planWorkflow.config.RobustPlanPanelAdapter.referencePanelConfig( ...
                runConfig), ...
                planWorkflow.gui.panels.PrecomputePanel.optionSets( ...
                runConfig, ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig)),struct());
            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            planWorkflow.gui.panels.PrecomputeEditorPanel.storeLoadedField( ...
                handles.referenceConfigTable,'reference_robustness', ...
                reference.robustnessMode);
            robustPlans = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            for planIx = 1:min(numel(handles.robustConfigTables), ...
                    numel(robustPlans))
                planWorkflow.gui.ParameterPanelRenderer.load( ...
                    handles.robustConfigTables(planIx), ...
                    planWorkflow.config.RobustPlanPanelAdapter.planPanelConfig( ...
                    robustPlans(planIx)), ...
                    planWorkflow.gui.panels.PrecomputePanel.optionSets( ...
                    runConfig,robustPlans(planIx)),struct());
                planWorkflow.gui.panels.PrecomputeEditorPanel.storeLoadedField( ...
                    handles.robustConfigTables(planIx),'robustness', ...
                    robustPlans(planIx).robustnessMode);
            end
            handles = ...
                planWorkflow.gui.panels.PrecomputeEditorPanel.refreshVisibility( ...
                handles);
        end

        function handles = refreshVisibility(handles)
            referenceRobustness = ...
                planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                handles.referenceConfigTable,'reference_robustness');
            referenceScenMode = ...
                planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                handles.referenceConfigTable,'reference_scen_mode');
            referenceKMode = ...
                planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                handles.referenceConfigTable,'reference_KMode');
            referenceDimensionConfig = ...
                planWorkflow.gui.panels.ScenarioPanel.dimensionActiveConfigFromPanel( ...
                handles.referenceConfigTable,'reference');
            planWorkflow.gui.ParameterPanelRenderer.setVisibleFields( ...
                handles.transversalConfigTable, ...
                planWorkflow.gui.panels.PrecomputePanel.transversalVisibleFields());
            planWorkflow.gui.ParameterPanelRenderer.setVisibleFields( ...
                handles.referenceConfigTable, ...
                planWorkflow.gui.panels.PrecomputePanel.referenceVisibleFields( ...
                referenceRobustness,referenceScenMode, ...
                referenceDimensionConfig,referenceKMode));
            for planIx = 1:numel(handles.robustConfigTables)
                tableHandle = handles.robustConfigTables(planIx);
                robustness = ...
                    planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                    tableHandle,'robustness');
                scenMode = ...
                    planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                    tableHandle,'scen_mode');
                KMode = planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                    tableHandle,'KMode');
                dimensionConfig = ...
                    planWorkflow.gui.panels.ScenarioPanel.dimensionActiveConfigFromPanel( ...
                    tableHandle,'');
                planWorkflow.gui.ParameterPanelRenderer.setVisibleFields( ...
                    tableHandle, ...
                    planWorkflow.gui.panels.PrecomputePanel.robustVisibleFields( ...
                    robustness,scenMode,dimensionConfig,KMode));
            end
        end

        function handles = rebuildRobustTabs(handles,runConfig)
            selectedTab = [];
            if isfield(handles,'tabGroup') && ishandle(handles.tabGroup)
                try
                    selectedTab = get(handles.tabGroup,'SelectedTab');
                catch
                end
            end
            selectedRobustIx = ...
                planWorkflow.gui.panels.PrecomputeEditorPanel.robustTabIndex( ...
                handles,selectedTab);

            for tabIx = 1:numel(handles.robustTabs)
                if ishandle(handles.robustTabs(tabIx))
                    delete(handles.robustTabs(tabIx));
                end
            end
            handles.robustTabs = gobjects(0);
            handles.robustConfigTables = handles.referenceConfigTable;
            handles.robustConfigTables(:) = [];

            robustPlans = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            for planIx = 1:numel(robustPlans)
                handles.robustTabs(planIx,1) = uitab( ...
                    handles.tabGroup,'Title',char(robustPlans(planIx).label));
                handles.robustConfigTables(planIx,1) = ...
                    planWorkflow.gui.ParameterPanelRenderer.create( ...
                    handles.robustTabs(planIx),[0.03 0.05 0.94 0.90], ...
                    planWorkflow.gui.panels.PrecomputePanel.robustSpecs(), ...
                    planWorkflow.gui.panels.PrecomputePanel.optionSets( ...
                    runConfig,robustPlans(planIx)),struct(), ...
                    handles.callbacks.reference);
            end
            handles = ...
                planWorkflow.gui.panels.PrecomputeEditorPanel.refreshConfigTables( ...
                handles);
            planWorkflow.gui.panels.PrecomputeEditorPanel.storeRobustTabKeys( ...
                handles,robustPlans);
            if ~isempty(selectedRobustIx) && ...
                    selectedRobustIx <= numel(handles.robustTabs)
                set(handles.tabGroup,'SelectedTab', ...
                    handles.robustTabs(selectedRobustIx));
            end
        end

        function handles = refreshTitles(handles,runConfig)
            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            if ishandle(handles.referenceTab)
                set(handles.referenceTab,'Title', ...
                    planWorkflow.gui.panels.PrecomputePanel.referencePlanTabTitle( ...
                    reference.label));
            end
            robustPlans = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            for planIx = 1:min(numel(handles.robustTabs),numel(robustPlans))
                if ishandle(handles.robustTabs(planIx))
                    set(handles.robustTabs(planIx),'Title', ...
                        char(robustPlans(planIx).label));
                end
            end
        end

        function handles = refreshConfigTables(handles)
            handles.configTables = [ ...
                handles.transversalConfigTable; ...
                handles.referenceConfigTable];
            for planIx = 1:numel(handles.robustConfigTables)
                handles.configTables(end + 1,1) = ...
                    handles.robustConfigTables(planIx); %#ok<AGROW>
            end
        end

        function tableHandle = activeParameterPanel(handles)
            tableHandle = [];
            if ~ishandle(handles.tabGroup)
                return;
            end
            selectedTab = get(handles.tabGroup,'SelectedTab');
            if isequal(selectedTab,handles.transversalTab)
                tableHandle = handles.transversalConfigTable;
            elseif isequal(selectedTab,handles.referenceTab)
                tableHandle = handles.referenceConfigTable;
            else
                robustTabIx = ...
                    planWorkflow.gui.panels.PrecomputeEditorPanel.robustTabIndex( ...
                    handles,selectedTab);
                if ~isempty(robustTabIx)
                    tableHandle = handles.robustConfigTables(robustTabIx);
                end
            end
        end

        function controls = controls(handles)
            controls = planWorkflow.gui.ParameterPanelRenderer.controls( ...
                handles.configTables);
            controls = [controls; handles.addRobustPlanButton; ...
                handles.deleteRobustPlanButton];
        end

        function [runConfig,template] = align(runConfig,template)
            [runConfig,template] = ...
                planWorkflow.gui.PlanEditorContract.alignPrecomputeWithTemplate( ...
                runConfig,template);
        end

        function tf = robustTabsNeedRebuild(handles,runConfig)
            tf = true;
            if ~isfield(handles,'tabGroup') || ~ishandle(handles.tabGroup) || ...
                    ~isfield(handles,'robustTabs') || ...
                    ~isfield(handles,'robustConfigTables')
                return;
            end

            robustPlans = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            if numel(handles.robustTabs) ~= numel(robustPlans) || ...
                    numel(handles.robustConfigTables) ~= numel(robustPlans)
                return;
            end

            for planIx = 1:numel(handles.robustTabs)
                if ~ishandle(handles.robustTabs(planIx)) || ...
                        ~isstruct(handles.robustConfigTables(planIx)) || ...
                        ~isfield(handles.robustConfigTables(planIx), ...
                        'panel') || ...
                        ~isgraphics(handles.robustConfigTables(planIx).panel)
                    return;
                end
            end

            currentKeys = ...
                planWorkflow.gui.panels.PrecomputeEditorPanel.robustTabKeys( ...
                handles);
            desiredKeys = ...
                planWorkflow.gui.panels.PrecomputeEditorPanel.robustPlanKeys( ...
                robustPlans);
            tf = ~isequal(currentKeys,desiredKeys);
        end

        function tabIx = robustTabIndex(handles,tabHandle)
            tabIx = [];
            if isempty(tabHandle) || ~isfield(handles,'robustTabs')
                return;
            end
            for candidateIx = 1:numel(handles.robustTabs)
                if ishandle(handles.robustTabs(candidateIx)) && ...
                        isequal(tabHandle,handles.robustTabs(candidateIx))
                    tabIx = candidateIx;
                    return;
                end
            end
        end

        function storeLoadedField(tableHandle,fieldName,value)
            if ~isstruct(tableHandle) || ~isfield(tableHandle,'panel') || ...
                    ~isgraphics(tableHandle.panel)
                return;
            end
            setappdata(tableHandle.panel, ...
                planWorkflow.gui.panels.PrecomputeEditorPanel.loadedFieldKey( ...
                fieldName),char(value));
        end

        function tf = fieldChanged(tableHandle,fieldName,currentValue)
            tf = false;
            if ~isstruct(tableHandle) || ~isfield(tableHandle,'panel') || ...
                    ~isgraphics(tableHandle.panel)
                return;
            end
            key = ...
                planWorkflow.gui.panels.PrecomputeEditorPanel.loadedFieldKey( ...
                fieldName);
            if ~isappdata(tableHandle.panel,key)
                return;
            end
            loadedValue = getappdata(tableHandle.panel,key);
            tf = ~strcmp(char(loadedValue),char(currentValue));
        end

        function key = loadedFieldKey(fieldName)
            key = ['planWorkflowLoaded_' ...
                matlab.lang.makeValidName(char(fieldName))];
        end

        function storeRobustTabKeys(handles,robustPlans)
            if ~isfield(handles,'tabGroup') || ~ishandle(handles.tabGroup)
                return;
            end
            setappdata(handles.tabGroup,'planWorkflowRobustTabKeys', ...
                planWorkflow.gui.panels.PrecomputeEditorPanel.robustPlanKeys( ...
                robustPlans));
        end

        function keys = robustTabKeys(handles)
            keys = {};
            if ~isfield(handles,'tabGroup') || ~ishandle(handles.tabGroup)
                return;
            end
            if isappdata(handles.tabGroup,'planWorkflowRobustTabKeys')
                keys = getappdata(handles.tabGroup, ...
                    'planWorkflowRobustTabKeys');
            end
        end

        function keys = robustPlanKeys(robustPlans)
            keys = cell(1,numel(robustPlans));
            for planIx = 1:numel(robustPlans)
                keys{planIx} = sprintf('%s|%s', ...
                    planWorkflow.gui.panels.PrecomputeEditorPanel.planFieldText( ...
                    robustPlans(planIx),'id'), ...
                    planWorkflow.gui.panels.PrecomputeEditorPanel.planFieldText( ...
                    robustPlans(planIx),'objectiveSetName'));
            end
        end

        function value = planFieldText(planConfig,fieldName)
            value = '';
            if isstruct(planConfig) && isfield(planConfig,fieldName) && ...
                    ~isempty(planConfig.(fieldName))
                value = char(planConfig.(fieldName));
            end
        end
    end
end
