classdef PrepareEditorPanel
    % PrepareEditorPanel Builds prepare/template/beam/objective editor tabs.

    methods (Static)
        function callbacks = callbacks(handlers,defaultCallback)
            callbacks = struct( ...
                'description',handlers.descriptionChanged, ...
                'plan_template',handlers.templateChanged, ...
                'AcquisitionType',handlers.acquisitionTypeChanged);
            if nargin >= 2 && ~isempty(defaultCallback)
                callbacks.defaultCallback = defaultCallback;
            end
        end

        function handles = create(parent,template,state,callbacks)
            handles = struct();
            handles.prepareTabGroup = uitabgroup('Parent',parent, ...
                'Units','normalized','Position',[0.02 0.04 0.96 0.92]);
            handles.planParametersTab = uitab(handles.prepareTabGroup, ...
                'Title','1. Plan parameters');
            handles.templateSettingsTab = uitab(handles.prepareTabGroup, ...
                'Title','2. Template');
            handles.beamSettingsTab = uitab(handles.prepareTabGroup, ...
                'Title','3. Beam');
            handles.structuresSettingsTab = uitab(handles.prepareTabGroup, ...
                'Title','4. Structures');
            handles.objectivesSettingsTab = uitab(handles.prepareTabGroup, ...
                'Title','5. Objectives');

            [handles.preparePatientImagesConfigTable, ...
                handles.prepareTemplateConfigTable,handles.templatePopup, ...
                handles.prepareParameterTables,handles.caseIdPopup] = ...
                planWorkflow.gui.panels.PrepareEditorPanel.createPlanPanels( ...
                handles,state,callbacks);
            [handles.beamConfigTable,handles.beamPopup, ...
                handles.gantryEdit,handles.couchEdit] = ...
                planWorkflow.gui.panels.PrepareEditorPanel.createBeamPanel( ...
                handles,state,callbacks);
            [handles.addStructureButton,handles.removeStructureButton, ...
                handles.structuresTable] = ...
                planWorkflow.gui.panels.PrepareEditorPanel.createStructurePanel( ...
                handles,callbacks);
            [handles.prescriptionEdit,handles.fractionsEdit, ...
                handles.addObjectiveButton,handles.deleteObjectiveButton, ...
                handles.addRobustPlanButton, ...
                handles.deleteRobustPlanButton,handles.objectiveTabGroup] = ...
                planWorkflow.gui.panels.PrepareEditorPanel.createObjectivePanel( ...
                handles,template,callbacks);
        end

        function [patientTable,templateTable,templatePopup, ...
                parameterTables,caseIdPopup] = createPlanPanels( ...
                handles,state,callbacks)
            patientTable = ...
                planWorkflow.gui.ParameterPanelRenderer.create( ...
                handles.planParametersTab,[0.03 0.05 0.94 0.90], ...
                planWorkflow.gui.ParameterPanelSpecAdapter.fromSchema( ...
                planWorkflow.config.WorkflowParameterSchema.preparePlanParameterSpecs()), ...
                state.planParameterOptions,state.planParameterSelection, ...
                callbacks.planParameter);
            [templateTable,templatePopup] = ...
                planWorkflow.gui.ParameterPanelRenderer.create( ...
                handles.templateSettingsTab,[0.03 0.05 0.94 0.90], ...
                planWorkflow.gui.ParameterPanelSpecAdapter.fromSchema( ...
                planWorkflow.config.WorkflowParameterSchema.prepareTemplateSpecs()), ...
                state.planParameterOptions,state.planParameterSelection, ...
                callbacks.planParameter);
            parameterTables = [patientTable; templateTable];
            caseIdPopup = ...
                planWorkflow.gui.panels.PrepareEditorPanel.control( ...
                patientTable,'caseID');
        end

        function [beamTable,beamPopup,gantryEdit,couchEdit] = ...
                createBeamPanel(handles,state,callbacks)
            beamTable = planWorkflow.gui.ParameterPanelRenderer.create( ...
                handles.beamSettingsTab,[0.03 0.05 0.94 0.90], ...
                planWorkflow.gui.ParameterPanelSpecAdapter.fromSchema( ...
                planWorkflow.config.WorkflowParameterSchema.prepareBeamSpecs()), ...
                planWorkflow.gui.WorkflowParameterOptions.prepareBeamOptionSets( ...
                state.beamIds,state.radiationModes, ...
                state.machineOptions,state.bioModelOptions, ...
                state.quantityOptions), ...
                struct('plan_beams',state.selectedBeamIx, ...
                'radiationMode',state.selectedRadiationModeIx, ...
                'machine',state.selectedMachineIx, ...
                'bioModel',state.selectedBioModelIx, ...
                'quantityOpt',state.selectedQuantityIx, ...
                'includeOtherRadiationModes', ...
                state.includeOtherRadiationModes), ...
                callbacks.beam);
            beamPopup = ...
                planWorkflow.gui.panels.PrepareEditorPanel.control( ...
                beamTable,'plan_beams');
            gantryEdit = ...
                planWorkflow.gui.panels.PrepareEditorPanel.control( ...
                beamTable,'gantryAngles');
            couchEdit = ...
                planWorkflow.gui.panels.PrepareEditorPanel.control( ...
                beamTable,'couchAngles');
        end

        function [addButton,removeButton,structuresTable] = ...
                createStructurePanel(handles,callbacks)
            addButton = uicontrol( ...
                'Parent',handles.structuresSettingsTab,'Style','pushbutton', ...
                'String','Add structure','Units','normalized', ...
                'Position',[0.72 0.87 0.12 0.08], ...
                'Callback',callbacks.addStructure);
            removeButton = uicontrol( ...
                'Parent',handles.structuresSettingsTab,'Style','pushbutton', ...
                'String','Remove structure','Units','normalized', ...
                'Position',[0.85 0.87 0.12 0.08], ...
                'Callback',callbacks.removeStructure);
            structuresTable = uitable( ...
                'Parent',handles.structuresSettingsTab, ...
                'Units','normalized','Position',[0.03 0.16 0.94 0.65], ...
                'ColumnName',{'Kind','Name','Role','Color','Priority', ...
                'Operation','Margins mm'}, ...
                'ColumnEditable',[false true true false true true true], ...
                'ColumnFormat',{{'Structure','Ring'},'char', ...
                planWorkflow.gui.panels.PreparePanel.supportedStructureRoles(), ...
                'char','char','char','char'}, ...
                'ColumnWidth',{90 210 100 120 70 170 130}, ...
                'CellSelectionCallback',callbacks.structureSelected, ...
                'CellEditCallback',callbacks.structureEdited);
            planWorkflow.gui.panels.PrepareEditorPanel.addHelpText( ...
                handles.structuresSettingsTab, ...
                planWorkflow.gui.HelpText.structure('Operation'), ...
                [0.03 0.095 0.94 0.04]);
            planWorkflow.gui.panels.PrepareEditorPanel.addHelpText( ...
                handles.structuresSettingsTab, ...
                planWorkflow.gui.HelpText.structure('Margins mm'), ...
                [0.03 0.05 0.94 0.04]);
        end

        function [prescriptionEdit,fractionsEdit,addButton,deleteButton, ...
                addRobustButton,deleteRobustButton,objectiveTabGroup] = ...
                createObjectivePanel(handles,template,callbacks)
            layout = planWorkflow.gui.panels.PreparePanel.objectiveHeaderLayout();
            uicontrol('Parent',handles.objectivesSettingsTab,'Style','text', ...
                'String','Prescription dose', ...
                'HorizontalAlignment','left','Units','normalized', ...
                'Position',layout.prescriptionLabel);
            prescriptionEdit = uicontrol( ...
                'Parent',handles.objectivesSettingsTab,'Style','edit', ...
                'String',num2str(template.prescriptionDose), ...
                'Units','normalized','Position',layout.prescriptionEdit, ...
                'Callback',callbacks.prescriptionChanged);
            uicontrol('Parent',handles.objectivesSettingsTab,'Style','text', ...
                'String','Fractions', ...
                'HorizontalAlignment','left','Units','normalized', ...
                'Position',layout.fractionsLabel);
            fractionsEdit = uicontrol( ...
                'Parent',handles.objectivesSettingsTab,'Style','edit', ...
                'Units','normalized','Position',layout.fractionsEdit, ...
                'Callback',callbacks.fractionsChanged);
            addButton = planWorkflow.gui.panels.PrepareEditorPanel.button( ...
                handles.objectivesSettingsTab,'Add objective', ...
                layout.addObjectiveButton,callbacks.addObjective);
            deleteButton = planWorkflow.gui.panels.PrepareEditorPanel.button( ...
                handles.objectivesSettingsTab,'Delete objective', ...
                layout.deleteObjectiveButton,callbacks.deleteObjective);
            addRobustButton = planWorkflow.gui.panels.PrepareEditorPanel.button( ...
                handles.objectivesSettingsTab,'Add robust plan', ...
                layout.addRobustPlanButton,callbacks.addRobustPlan);
            deleteRobustButton = ...
                planWorkflow.gui.panels.PrepareEditorPanel.button( ...
                handles.objectivesSettingsTab,'Delete robust plan', ...
                layout.deleteRobustPlanButton,callbacks.deleteRobustPlan);

            parametersHelpText = ...
                planWorkflow.gui.panels.PreparePanel.objectiveHelpTextForDisplay( ...
                'Parameters JSON');
            dosePullingHelpText = ...
                planWorkflow.gui.panels.PreparePanel.objectiveHelpTextForDisplay( ...
                'DosePulling JSON');
            parametersHelpHeight = ...
                planWorkflow.gui.TextLayout.wideHelpTextHeightForDisplay( ...
                parametersHelpText);
            dosePullingHelpHeight = ...
                planWorkflow.gui.TextLayout.wideHelpTextHeightForDisplay( ...
                dosePullingHelpText);
            dosePullingHelpY = 0.035;
            parametersHelpY = dosePullingHelpY + dosePullingHelpHeight + ...
                0.010;
            objectivesTableBottom = parametersHelpY + ...
                parametersHelpHeight + 0.025;
            objectiveTabGroup = uitabgroup( ...
                'Parent',handles.objectivesSettingsTab, ...
                'Units','normalized','Position', ...
                [0.03 objectivesTableBottom 0.94 ...
                layout.objectiveTabsTop - objectivesTableBottom]);
            planWorkflow.gui.panels.PrepareEditorPanel.addHelpText( ...
                handles.objectivesSettingsTab,parametersHelpText, ...
                [0.03 parametersHelpY 0.94 parametersHelpHeight]);
            planWorkflow.gui.panels.PrepareEditorPanel.addHelpText( ...
                handles.objectivesSettingsTab,dosePullingHelpText, ...
                [0.03 dosePullingHelpY 0.94 dosePullingHelpHeight]);
        end

        function loadPlanParameters(handles,runConfig,optionSets, ...
                selectedOptions)
            for tableIx = 1:numel(handles.prepareParameterTables)
                planWorkflow.gui.ParameterPanelRenderer.load( ...
                    handles.prepareParameterTables(tableIx),runConfig, ...
                    optionSets,selectedOptions);
            end
        end

        function runConfig = syncPlanParameters(handles,runConfig)
            for tableIx = 1:numel(handles.prepareParameterTables)
                runConfig = planWorkflow.gui.ParameterPanelRenderer.toConfig( ...
                    runConfig,handles.prepareParameterTables(tableIx));
            end
        end

        function tableHandle = activeParameterPanel(handles)
            tableHandle = [];
            if ~ishandle(handles.prepareTabGroup)
                return;
            end
            selectedTab = get(handles.prepareTabGroup,'SelectedTab');
            if isequal(selectedTab,handles.planParametersTab)
                tableHandle = handles.preparePatientImagesConfigTable;
            elseif isequal(selectedTab,handles.templateSettingsTab)
                tableHandle = handles.prepareTemplateConfigTable;
            elseif isequal(selectedTab,handles.beamSettingsTab)
                tableHandle = handles.beamConfigTable;
            end
        end

        function controls = parameterControls(handles)
            controls = planWorkflow.gui.ParameterPanelRenderer.controls( ...
                handles.prepareParameterTables);
        end

        function buttonHandle = button(parent,label,position,callback)
            buttonHandle = uicontrol( ...
                'Parent',parent,'Style','pushbutton', ...
                'String',label,'Units','normalized', ...
                'Position',position,'Callback',callback);
        end

        function addHelpText(parent,text,position)
            uicontrol('Parent',parent,'Style','text', ...
                'String',text,'HorizontalAlignment','left', ...
                'Units','normalized','Position',position, ...
                'FontSize',planWorkflow.gui.TextLayout.helpTextFontSize(), ...
                'ForegroundColor',[0.35 0.35 0.35]);
        end

        function controlHandle = control(tableHandle,fieldName)
            fields = {tableHandle.specs.field};
            fieldIx = find(strcmp(fields,fieldName),1);
            if isempty(fieldIx)
                error(['planWorkflow:gui:PrepareEditorPanel:' ...
                    'UnknownField'], ...
                    'Unknown prepare panel field "%s".',char(fieldName));
            end
            controlHandle = tableHandle.controls(fieldIx);
        end
    end
end
