classdef SamplingPanel
    % SamplingPanel Owns sampling GUI parameter contracts.

    methods (Static)
        function tableHandle = create(parent,position,runConfig,callbacks)
            if nargin < 4
                callbacks = struct();
            end
            tableHandle = planWorkflow.gui.ParameterPanelRenderer.create( ...
                parent,position, ...
                planWorkflow.gui.panels.SamplingPanel.specs(), ...
                planWorkflow.gui.panels.SamplingPanel.optionSets( ...
                runConfig),struct(),callbacks);
        end

        function specs = specs()
            specs = planWorkflow.gui.ParameterPanelSpecAdapter.fromSchema( ...
                planWorkflow.config.WorkflowParameterSchema.samplingSpecs());
        end

        function load(tableHandle,runConfig)
            planWorkflow.gui.ParameterPanelRenderer.load( ...
                tableHandle,runConfig, ...
                planWorkflow.gui.panels.SamplingPanel.optionSets( ...
                runConfig),struct());
            planWorkflow.gui.panels.SamplingPanel.refresh(tableHandle, ...
                runConfig);
        end

        function runConfig = sync(tableHandle,runConfig)
            runConfig = planWorkflow.gui.ParameterPanelRenderer.toConfig( ...
                runConfig,tableHandle);
            if logical(runConfig.sampling_linkToOptimization)
                runConfig = ...
                    planWorkflow.gui.panels.SamplingPanel.syncToOptimization( ...
                    runConfig);
            end
        end

        function runConfig = refresh(tableHandle,runConfig)
            linkToOptimization = ...
                planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                tableHandle,'sampling_linkToOptimization');
            if logical(linkToOptimization)
                runConfig = ...
                    planWorkflow.gui.panels.SamplingPanel.syncToOptimization( ...
                    runConfig);
            else
                runConfig = ...
                    planWorkflow.gui.panels.SamplingPanel.refreshCaseIds( ...
                    tableHandle,runConfig);
            end

            scenMode = ...
                planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                tableHandle,'sampling_scen_mode');
            dimensionConfig = ...
                planWorkflow.gui.panels.ScenarioPanel.dimensionActiveConfigFromPanel( ...
                tableHandle,'sampling');
            fields = planWorkflow.gui.panels.SamplingPanel.visibleFields( ...
                linkToOptimization,scenMode,dimensionConfig);
            planWorkflow.gui.ParameterPanelRenderer.setVisibleFields( ...
                tableHandle,fields);
        end

        function runConfig = syncToOptimization(runConfig)
            runConfig.sampling_caseID = runConfig.caseID;
            runConfig.sampling_AcquisitionType = runConfig.AcquisitionType;
            runConfig.sampling_dicomMetadata = runConfig.dicomMetadata;
        end

        function runConfig = refreshCaseIds(tableHandle,runConfig)
            samplingCasePopup = ...
                planWorkflow.gui.panels.SamplingPanel.control( ...
                tableHandle,'sampling_caseID');
            currentCaseId = runConfig.sampling_caseID;
            if ishandle(samplingCasePopup)
                popupCases = get(samplingCasePopup,'String');
                if ischar(popupCases)
                    popupCases = cellstr(popupCases);
                end
                popupValue = get(samplingCasePopup,'Value');
                if ~isempty(popupCases) && popupValue <= numel(popupCases)
                    currentCaseId = popupCases{popupValue};
                end
            end

            acquisitionType = ...
                planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                tableHandle,'sampling_AcquisitionType');
            runConfig.sampling_AcquisitionType = char(acquisitionType);
            caseIds = ...
                planWorkflow.gui.WorkflowParameterOptions.availableCaseIds( ...
                runConfig.patientDataPath,runConfig.description, ...
                runConfig.sampling_AcquisitionType);
            [caseIds,selectedCaseIx] = ...
                planWorkflow.gui.WorkflowParameterOptions.caseIdOptionSet( ...
                caseIds,currentCaseId);
            runConfig.sampling_caseID = caseIds{selectedCaseIx};
            set(samplingCasePopup,'String',caseIds,'Value',selectedCaseIx);
        end

        function control = control(tableHandle,fieldName)
            fields = {tableHandle.specs.field};
            fieldIx = find(strcmp(fields,fieldName),1);
            if isempty(fieldIx)
                error('planWorkflow:gui:SamplingPanel:UnknownField', ...
                    'Sampling panel does not define field "%s".', ...
                    char(fieldName));
            end
            control = tableHandle.controls(fieldIx);
        end

        function optionSets = optionSets(runConfig)
            optionSets = ...
                planWorkflow.gui.WorkflowParameterOptions.samplingOptionSets( ...
                runConfig);
        end

        function fields = visibleFields( ...
                linkToOptimization,scenMode,dimensionConfig)
            if nargin < 3
                dimensionConfig = struct();
            end
            fields = ...
                planWorkflow.config.WorkflowParameterSchema.samplingVisibleFields( ...
                linkToOptimization,scenMode, ...
                dimensionConfig);
        end
    end
end
