classdef ScenarioPanel
    % ScenarioPanel Owns scenario GUI visibility and field contracts.

    methods (Static)
        function fields = visibleFields(scenMode,wcSigmaField, ...
                sampleSizeField,dimensionConfig)
            fields = ...
                planWorkflow.config.WorkflowParameterSchema.scenarioVisibleFields( ...
                scenMode,wcSigmaField, ...
                sampleSizeField,dimensionConfig);
        end

        function fields = prefixedVisibleFields(scenMode,prefix, ...
                wcSigmaField,sampleSizeField,dimensionConfig)
            fields = ...
                planWorkflow.config.WorkflowParameterSchema.prefixedScenarioVisibleFields( ...
                scenMode,prefix, ...
                wcSigmaField,sampleSizeField,dimensionConfig);
        end

        function dimensionConfig = dimensionActiveConfigFromPanel( ...
                tableHandle,prefix)
            if nargin < 2
                prefix = '';
            end
            dimensionConfig = struct();
            fields = [{'ctActive','ctReferenceScenId'}, ...
                planWorkflow.scenario.dimensionActiveFields()];
            specFields = {tableHandle.specs.field};
            for fieldIx = 1:numel(fields)
                fieldName = fields{fieldIx};
                if isempty(prefix)
                    panelFieldName = fieldName;
                else
                    panelFieldName = [char(prefix) '_' char(fieldName)];
                end
                if any(strcmp(specFields,panelFieldName))
                    dimensionConfig.(fieldName) = ...
                        planWorkflow.gui.ParameterPanelRenderer.fieldValue( ...
                        tableHandle,panelFieldName);
                end
            end
            dimensionConfig = ...
                planWorkflow.gui.panels.ScenarioPanel.completeDimensionActiveConfig( ...
                dimensionConfig);
        end

        function fields = selectionFields(scenMode,dimensionConfig)
            %#ok<INUSD> dimensionConfig kept for the panel API symmetry.
            fields = planWorkflow.config.ScenarioSpec.selectionFields( ...
                scenMode,'');
        end

        function fields = parameterFields(dimensionConfig)
            fields = planWorkflow.config.ScenarioSpec.parameterFields( ...
                '',dimensionConfig);
        end

        function fields = ctParameterFields(dimensionConfig)
            fields = planWorkflow.config.ScenarioSpec.ctParameterFields( ...
                '',dimensionConfig);
        end

        function tf = anyDimensionActive(dimensionConfig)
            dimensionConfig = ...
                planWorkflow.config.ScenarioSpec.completeDimensionConfig( ...
                dimensionConfig);
            tf = dimensionConfig.setupActive || ...
                dimensionConfig.rangeActive || ...
                dimensionConfig.gantryActive || ...
                dimensionConfig.couchActive;
        end

        function tf = anyRangeDimensionActive(dimensionConfig)
            dimensionConfig = ...
                planWorkflow.config.ScenarioSpec.completeDimensionConfig( ...
                dimensionConfig);
            tf = dimensionConfig.rangeActive;
        end

        function dimensionConfig = completeDimensionActiveConfig( ...
                dimensionConfig)
            dimensionConfig = ...
                planWorkflow.config.ScenarioSpec.completeDimensionConfig( ...
                dimensionConfig);
        end
    end
end
