classdef AnalysisService
    % AnalysisService Owns plan and sampling analysis orchestration.

    methods (Static)
        function analysis = completeConfig(runConfig,data)
            analysis = planWorkflow.config.Analysis.normalize(runConfig.analysis);
            if isfield(data,'pln') && isfield(data,'objectiveInfo') && ...
                    isstruct(data.objectiveInfo) && ...
                    isfield(data.objectiveInfo,'prescriptionDose') && ...
                    ~isempty(data.objectiveInfo.prescriptionDose)
                analysis = planWorkflow.config.Analysis.applyPrescriptionDefaults( ...
                    analysis,data.objectiveInfo.prescriptionDose,data.pln);
            end
        end

        function [resultGUI,dvh,qi] = runPlanAnalysis( ...
                analysis,ct,cst,stf,pln,resultGUI,showFigures, ...
                optimizationQuantity)
            if nargin < 8
                optimizationQuantity = '';
            end
            [resultGUI,dvh,qi] = planWorkflow.analysis.PlanAnalysis.run( ...
                analysis,ct,cst,stf,pln,resultGUI,showFigures, ...
                optimizationQuantity);
        end

        function [resultGUIAnalysis,dvh,qi] = runFromOptimizationResult( ...
                context,ct,cst,stf,pln,resultGUIOptimization,showFigures)
            resultGUIAnalysis = ...
                planWorkflow.analysis.AnalysisService.createAnalysisResultGUI( ...
                context,ct,cst,stf,pln,resultGUIOptimization);
            [resultGUIAnalysis,dvh,qi] = ...
                planWorkflow.analysis.AnalysisService.runPlanAnalysis( ...
                context.runConfig.analysis,ct,cst,stf,pln, ...
                resultGUIAnalysis,showFigures, ...
                planWorkflow.analysis.AnalysisService.optimizationQuantity( ...
                context));
        end

        function planResults = attachAnalysisMetadata(planResults, ...
                resultGUIAnalysis,dvh)
            metadataFields = {'analysisQuantity','evaluationModeBase', ...
                'endpointQuantity','evaluationMode','evaluationScale', ...
                'numOfFractions'};
            for fieldIx = 1:numel(metadataFields)
                fieldName = metadataFields{fieldIx};
                if isfield(resultGUIAnalysis,fieldName)
                    planResults.(fieldName) = resultGUIAnalysis.(fieldName);
                end
            end
            if nargin >= 3 && ~isempty(dvh)
                planResults.cstStat = ...
                    planWorkflow.analysis.AnalysisService.cstStatFromDvh(dvh);
            end
            if isfield(resultGUIAnalysis,'endpointDvh') && ...
                    ~isempty(resultGUIAnalysis.endpointDvh)
                planResults.endpointCstStat = ...
                    planWorkflow.analysis.AnalysisService.cstStatFromDvh( ...
                    resultGUIAnalysis.endpointDvh);
            end
        end

        function cstStat = cstStatFromDvh(dvh)
            cstStat = repmat(struct('name','','dvhStat',struct()), ...
                1,numel(dvh));
            for i = 1:numel(dvh)
                structureName = sprintf('structure_%d',i);
                if isfield(dvh(i),'name') && ~isempty(dvh(i).name)
                    structureName = char(dvh(i).name);
                end
                cstStat(i).name = structureName;
                cstStat(i).dvhStat = struct( ...
                    'mean',dvh(i), ...
                    'min',dvh(i), ...
                    'max',dvh(i));
            end
        end

        function resultGUIAnalysis = createAnalysisResultGUI( ...
                context,ct,cst,stf,pln,resultGUIOptimization)
            if ~isstruct(resultGUIOptimization) || ...
                    ~isfield(resultGUIOptimization,'w') || ...
                    isempty(resultGUIOptimization.w)
                error('planWorkflow:analysis:MissingOptimizationWeights', ...
                    ['Plan analysis requires optimized fluence weights ' ...
                     'in resultGUI.w.']);
            end

            if isfield(context,'forwardDoseForAnalysis') && ...
                    ~isempty(context.forwardDoseForAnalysis)
                resultGUIAnalysis = context.forwardDoseForAnalysis( ...
                    ct,cst,stf,pln,resultGUIOptimization.w);
            else
                resultGUIAnalysis = matRad_calcDoseForward( ...
                    ct,cst,stf,pln,resultGUIOptimization.w);
            end
            resultGUIAnalysis = ...
                planWorkflow.analysis.AnalysisService.copyOptimizationMetadata( ...
                resultGUIAnalysis,resultGUIOptimization);
        end

        function resultGUIAnalysis = copyOptimizationMetadata( ...
                resultGUIAnalysis,resultGUIOptimization)
            resultGUIAnalysis.w = resultGUIOptimization.w;
            metadataFields = {'wUnsequenced','usedOptimizer','info'};
            for fieldIx = 1:numel(metadataFields)
                fieldName = metadataFields{fieldIx};
                if isfield(resultGUIOptimization,fieldName)
                    resultGUIAnalysis.(fieldName) = ...
                        resultGUIOptimization.(fieldName);
                end
            end
        end

        function logResults(context,results)
            planWorkflow.analysis.ResultLogger.log( ...
                @(message) context.log(message),results);
        end

        function samplingResults = analyzeSamplingData(context,samplingData)
            context.log('Analyzing sampled dose scenarios.');

            samplingResults = struct();
            samplingResults.scenarioMode = samplingData.scenarioMode;
            if isfield(samplingData,'samplingConfig')
                samplingResults.samplingConfig = samplingData.samplingConfig;
            end
            if isfield(samplingData,'planSet')
                samplingResults.planSet = samplingData.planSet;
            end
            if isfield(samplingData,'scenarioBasis')
                samplingResults.scenarioBasis = samplingData.scenarioBasis;
            end
            if isfield(samplingData,'structureNormalizationReport')
                samplingResults.structureNormalizationReport = ...
                    samplingData.structureNormalizationReport;
            end
            samplingResults.reference = ...
                planWorkflow.analysis.AnalysisService.analyzeSamplingPlan( ...
                context,samplingData,samplingData.reference,'reference');

            if isfield(samplingData,'robust')
                samplingResults.robust = cell(1,numel(samplingData.robust));
                for planIx = 1:numel(samplingData.robust)
                    sample = samplingData.robust{planIx};
                    label = ...
                        planWorkflow.analysis.AnalysisService.sampleLabel( ...
                        sample,planIx);
                    sample.label = label;
                    samplingResults.robust{planIx} = ...
                        planWorkflow.analysis.AnalysisService.analyzeSamplingPlan( ...
                        context,samplingData,sample,label);
                end
            end
        end

        function planSamplingResults = analyzeSamplingPlan( ...
                context,samplingData,sample,label)
            analysis = context.runConfig.analysis;
            slice = planWorkflow.analysis.AnalysisService.samplingSlice( ...
                samplingData.ct,sample.pln);
            ctScenProb = ...
                planWorkflow.analysis.AnalysisService.ctScenProbMatrix( ...
                samplingData.ctScenProb);

            [cstStat,doseStat,meta,gammaFig,robustnessFig1, ...
                robustnessFig2] = matRad_samplingAnalysis( ...
                samplingData.ct,sample.cst,sample.pln,sample.caSamp, ...
                sample.mSampDose,sample.resultGUINomScen, ...
                'ctScenProb',ctScenProb, ...
                'gammaCriterion',analysis.gammaCriteria, ...
                'robustnessCriteria',analysis.robustnessCriteria, ...
                'robustnessTargetMode',analysis.robustnessTargetMode, ...
                'robustnessTargets',analysis.robustnessTargets, ...
                'slice',slice);

            planSamplingResults = struct();
            if isfield(sample,'label') && ~isempty(sample.label)
                planSamplingResults.label = char(sample.label);
            else
                planSamplingResults.label = char(label);
            end
            planSamplingResults.cstStat = cstStat;
            planSamplingResults.doseStat = doseStat;
            planSamplingResults.meta = meta;
            planSamplingResults.evaluationModeBase = 'perFraction';
            planSamplingResults.analysisQuantity = ...
                planWorkflow.plan.DoseQuantityResolver.visualFromPlan( ...
                sample.pln, ...
                planWorkflow.analysis.AnalysisService.optimizationQuantity( ...
                context));
            planSamplingResults.endpointQuantity = ...
                planSamplingResults.analysisQuantity;
            if isfield(sample.pln,'numOfFractions') && ...
                    ~isempty(sample.pln.numOfFractions)
                planSamplingResults.numOfFractions = ...
                    sample.pln.numOfFractions;
            end
            [planSamplingResults.evaluationScale, ...
                planSamplingResults.evaluationMode] = ...
                matRad_convertToEvaluationMode( ...
                1,sample.pln,analysis.evaluationMode);
            planSamplingResults.expectedQi = ...
                planWorkflow.analysis.ExpectedQi.fromCstStat( ...
                cstStat,sample.cst,sample.pln);
            planSamplingResults.expectedQiSource = ...
                'cstStat(i).dvhStat.mean from matRad_samplingAnalysis';
            planSamplingResults.expectedDvhSource = ...
                'cstStat(i).dvhStat.mean from matRad_samplingAnalysis';
            analysisFolder = fullfile(context.rootPath,'sampling_analysis');
            planSamplingResults.figureFiles = ...
                planWorkflow.analysis.Figures.saveSamplingAnalysisFigures( ...
                analysisFolder,label,gammaFig,robustnessFig1, ...
                robustnessFig2,samplingData,sample,doseStat,analysis,slice);
        end

        function quantity = optimizationQuantity(context)
            quantity = '';
            if isstruct(context) && isfield(context,'data') && ...
                    isstruct(context.data) && isfield(context.data,'quantityOpt')
                quantity = context.data.quantityOpt;
            end
        end

        function matrix = ctScenProbMatrix(ctScenProb)
            if isempty(ctScenProb)
                matrix = [];
                return;
            end
            if isnumeric(ctScenProb) && ismatrix(ctScenProb) && ...
                    size(ctScenProb,2) == 2
                matrix = ctScenProb;
            else
                matrix = [(1:numel(ctScenProb))' ctScenProb(:)];
            end
        end

        function slice = samplingSlice(ct,pln)
            isocenter = pln.propStf.isoCenter(1,:);
            if isfield(ct,'z') && ~isempty(ct.z)
                [~,slice] = min(abs(ct.z - isocenter(3)));
            else
                slice = round(isocenter(3) / ct.resolution.z);
            end
            slice = max(1,min(ct.cubeDim(3),slice));
        end

        function label = sampleLabel(sample,resultIx)
            fallbackLabel = sprintf('robust_%d',resultIx);
            if isstruct(sample) && isfield(sample,'label') && ...
                    ~isempty(sample.label)
                fallbackLabel = char(sample.label);
            end
            label = fallbackLabel;
        end
    end
end
