classdef ClinicalEndpointEvaluator
    % ClinicalEndpointEvaluator Evaluates clinical endpoints from DVH stats.

    methods (Static)
        function [rows,missingEndpoints] = evaluatePlan( ...
                planResults,endpoints,referencePlanResults)
            if nargin < 3
                referencePlanResults = [];
            end

            rows = struct([]);
            missingEndpoints = ...
                planWorkflow.analysis.ClinicalEndpointEvaluator.emptyMissingEndpoint();
            if ~isstruct(planResults) || ~isfield(planResults,'cstStat') || ...
                    isempty(planResults.cstStat) || isempty(endpoints)
                return;
            end

            context = ...
                planWorkflow.analysis.PlanEvaluationContext.fromPlanResults( ...
                planResults);
            cstStat = ...
                planWorkflow.analysis.ClinicalEndpointEvaluator.endpointCstStat( ...
                planResults,context);
            [rows,missingEndpoints] = ...
                planWorkflow.analysis.ClinicalEndpointEvaluator.rows( ...
                cstStat,endpoints,context);
            referenceRows = ...
                planWorkflow.analysis.ClinicalEndpointEvaluator.referenceRows( ...
                referencePlanResults,endpoints);
            rows = ...
                planWorkflow.analysis.ClinicalEndpointEvaluator.addPor( ...
                rows,referenceRows);
        end

        function [rows,missingEndpoints] = rows(cstStat,endpoints,context)
            if nargin < 3 || isempty(context)
                context = ...
                    planWorkflow.analysis.PlanEvaluationContext.fromPlanResults( ...
                    struct());
            end

            rows = struct([]);
            missingEndpoints = ...
                planWorkflow.analysis.ClinicalEndpointEvaluator.emptyMissingEndpoint();
            for endpointIx = 1:numel(endpoints)
                cstIx = ...
                    planWorkflow.analysis.ClinicalEndpointEvaluator.findCstStat( ...
                    cstStat,endpoints(endpointIx).structureNames);
                if isempty(cstIx)
                    missingEndpoints(end + 1) = ...
                        planWorkflow.analysis.ClinicalEndpointEvaluator.missingEndpoint( ...
                        endpoints(endpointIx)); %#ok<AGROW>
                    continue;
                end

                row = ...
                    planWorkflow.analysis.ClinicalEndpointEvaluator.evaluateEndpoint( ...
                    cstStat(cstIx),endpoints(endpointIx),context);
                if isempty(row)
                    continue;
                end

                if isempty(rows)
                    rows = row;
                else
                    rows(end + 1) = row; %#ok<AGROW>
                end
            end
        end

        function rows = referenceRows(planResults,endpoints)
            rows = struct([]);
            if ~isstruct(planResults) || ~isfield(planResults,'cstStat') || ...
                    isempty(planResults.cstStat)
                return;
            end

            context = ...
                planWorkflow.analysis.PlanEvaluationContext.fromPlanResults( ...
                planResults);
            cstStat = ...
                planWorkflow.analysis.ClinicalEndpointEvaluator.endpointCstStat( ...
                planResults,context);
            rows = planWorkflow.analysis.ClinicalEndpointEvaluator.rows( ...
                cstStat,endpoints,context);
        end

        function cstStat = endpointCstStat(planResults,context)
            cstStat = struct([]);
            if isstruct(planResults) && isfield(planResults,'endpointCstStat') && ...
                    ~isempty(planResults.endpointCstStat)
                cstStat = planResults.endpointCstStat;
                return;
            end
            if isstruct(planResults) && isfield(planResults,'cstStat') && ...
                    ~isempty(planResults.cstStat) && ...
                    strcmp(char(context.endpointQuantity), ...
                    char(context.analysisQuantity))
                cstStat = planResults.cstStat;
            end
        end

        function rows = addPor(rows,referenceRows)
            for rowIx = 1:numel(rows)
                rows(rowIx).deltaFromReference = NaN;
                rows(rowIx).por = NaN;
                referenceIx = ...
                    planWorkflow.analysis.ClinicalEndpointEvaluator.findRow( ...
                    referenceRows,rows(rowIx));
                if ~isempty(referenceIx)
                    rows(rowIx).deltaFromReference = rows(rowIx).mean - ...
                        referenceRows(referenceIx).mean;
                    rows(rowIx).por = ...
                        planWorkflow.analysis.ClinicalEndpointEvaluator.goalAdjustedPor( ...
                        rows(rowIx).deltaFromReference,rows(rowIx).goal);
                end
            end
        end

        function por = goalAdjustedPor(delta,goal)
            switch char(goal)
                case 'higherIsBetter'
                    por = delta;
                case 'lowerIsBetter'
                    por = -delta;
                case 'reportOnly'
                    por = NaN;
                otherwise
                    error(['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
                        'InvalidEndpointGoal'], ...
                        'Unsupported endpoint goal "%s".',char(goal));
            end
        end

        function ix = findRow(rows,targetRow)
            ix = [];
            if isempty(rows)
                return;
            end

            for rowIx = 1:numel(rows)
                if strcmpi(rows(rowIx).structure,targetRow.structure) && ...
                        strcmpi(rows(rowIx).metric,targetRow.metric) && ...
                        strcmpi(rows(rowIx).unit,targetRow.unit) && ...
                        strcmpi(rows(rowIx).doseQuantity, ...
                        targetRow.doseQuantity)
                    ix = rowIx;
                    return;
                end
            end
        end

        function ix = findCstStat(cstStat,structureNames)
            ix = [];
            for i = 1:numel(cstStat)
                structureName = ...
                    planWorkflow.analysis.ExpectedQi.structTextField( ...
                    cstStat(i),{'name','VOIname'},'');
                for nameIx = 1:numel(structureNames)
                    if strcmpi(structureName,structureNames{nameIx})
                        ix = i;
                        return;
                    end
                end
            end
        end

        function row = evaluateEndpoint(cstStat,endpoint,context)
            if nargin < 3 || isempty(context)
                context = ...
                    planWorkflow.analysis.PlanEvaluationContext.fromPlanResults( ...
                    struct());
            end

            row = struct([]);
            if ~isfield(cstStat,'dvhStat') || ...
                    ~isfield(cstStat.dvhStat,'mean')
                return;
            end

            planWorkflow.analysis.ClinicalEndpointEvaluator.assertDoseQuantity( ...
                endpoint,context);

            meanValue = ...
                planWorkflow.analysis.ClinicalEndpointEvaluator.evaluateDvh( ...
                cstStat.dvhStat.mean,endpoint,context);
            [lowerDvh,upperDvh,hasTrustband] = ...
                planWorkflow.analysis.ExpectedQi.trustbandLimitDvhs( ...
                cstStat.dvhStat);
            minValue = NaN;
            maxValue = NaN;
            stdValue = NaN;
            if hasTrustband
                minValue = ...
                    planWorkflow.analysis.ClinicalEndpointEvaluator.evaluateDvh( ...
                    lowerDvh,endpoint,context);
                maxValue = ...
                    planWorkflow.analysis.ClinicalEndpointEvaluator.evaluateDvh( ...
                    upperDvh,endpoint,context);
                [minValue,maxValue] = ...
                    planWorkflow.analysis.ExpectedQi.orderedBounds( ...
                    minValue,maxValue);
                stdValue = ...
                    planWorkflow.analysis.ExpectedQi.trustbandHalfWidth( ...
                    minValue,maxValue);
            end

            row = struct();
            row.structure = ...
                planWorkflow.analysis.ExpectedQi.structTextField( ...
                cstStat,{'name','VOIname'},endpoint.structureNames{1});
            row.metric = endpoint.metric;
            row.goal = endpoint.goal;
            row.doseQuantity = endpoint.doseQuantity;
            row.mean = meanValue;
            row.uncertaintyHalfWidth = stdValue;
            row.min = minValue;
            row.max = maxValue;
            row.deltaFromReference = NaN;
            row.por = NaN;
            row.unit = endpoint.unit;
        end

        function value = evaluateDvh(dvh,endpoint,context)
            if nargin < 3 || isempty(context)
                context = ...
                    planWorkflow.analysis.PlanEvaluationContext.fromPlanResults( ...
                    struct());
            end

            value = NaN;
            if ~isfield(dvh,'doseGrid') || ~isfield(dvh,'volumePoints')
                return;
            end

            doseGrid = dvh.doseGrid(:);
            volumePoints = dvh.volumePoints(:);
            switch endpoint.kind
                case 'V'
                    threshold = ...
                        planWorkflow.analysis.ClinicalEndpointEvaluator.doseThreshold( ...
                        endpoint,context);
                    value = 100 * ...
                        planWorkflow.analysis.ExpectedQi.dvhVolumeAtDose( ...
                        doseGrid,volumePoints,threshold);
                case 'D'
                    threshold = ...
                        planWorkflow.analysis.ClinicalEndpointEvaluator.volumeThreshold( ...
                        endpoint);
                    value = ...
                        planWorkflow.analysis.ExpectedQi.dvhDoseAtVolume( ...
                        doseGrid,volumePoints,threshold);
                    value = value * ...
                        planWorkflow.analysis.ClinicalEndpointEvaluator.doseOutputScale( ...
                        endpoint,context);
                case 'mean'
                    value = ...
                        planWorkflow.analysis.ExpectedQi.meanDoseFromDvh( ...
                        doseGrid,volumePoints);
                    value = value * ...
                        planWorkflow.analysis.ClinicalEndpointEvaluator.doseOutputScale( ...
                        endpoint,context);
                case 'max'
                    value = ...
                        planWorkflow.analysis.ExpectedQi.maxDoseFromDvh( ...
                        doseGrid,volumePoints);
                    value = value * ...
                        planWorkflow.analysis.ClinicalEndpointEvaluator.doseOutputScale( ...
                        endpoint,context);
            end
        end

        function scale = doseOutputScale(endpoint,context)
            if ~isfield(endpoint,'outputDoseMode') || ...
                    isempty(endpoint.outputDoseMode)
                error(['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
                    'MissingEndpointOutputDoseMode'], ...
                    ['Endpoint "%s" must define outputDoseMode for ' ...
                     'dose-valued metrics.'],char(endpoint.metric));
            end

            switch char(endpoint.outputDoseMode)
                case 'perFractionDose'
                    scale = ...
                        planWorkflow.analysis.ClinicalEndpointEvaluator.perFractionDoseScale( ...
                        context,endpoint);
                case 'totalDose'
                    scale = ...
                        planWorkflow.analysis.ClinicalEndpointEvaluator.totalDoseScale( ...
                        context,endpoint);
                otherwise
                    error(['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
                        'InvalidEndpointOutputDoseMode'], ...
                        ['Endpoint "%s" outputDoseMode must be totalDose ' ...
                         'or perFractionDose.'],char(endpoint.metric));
            end
        end

        function threshold = doseThreshold(endpoint,context)
            expectedUnit = ...
                planWorkflow.analysis.ClinicalEndpointCatalog.doseUnit( ...
                endpoint.doseQuantity,'clinical endpoint');
            if ~strcmp(endpoint.thresholdUnit,expectedUnit)
                error(['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
                    'InvalidDoseThresholdSemantics'], ...
                    ['Endpoint "%s" must define a %s dose threshold for ' ...
                     'V metrics.'],char(endpoint.metric),expectedUnit);
            end

            switch char(endpoint.thresholdMode)
                case 'perFractionDose'
                    threshold = endpoint.threshold;
                case 'totalDose'
                    threshold = endpoint.threshold / ...
                        planWorkflow.analysis.ClinicalEndpointEvaluator.totalDoseScale( ...
                        context,endpoint);
                otherwise
                    error(['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
                        'InvalidDoseThresholdSemantics'], ...
                        ['Endpoint "%s" thresholdMode must be totalDose ' ...
                         'or perFractionDose.'],char(endpoint.metric));
            end
        end

        function scale = totalDoseScale(context,endpoint)
            if strcmp(context.evaluationModeBase,'total')
                scale = 1;
                return;
            end
            if planWorkflow.analysis.PlanEvaluationContext.isPositiveScalar( ...
                    context.numOfFractions)
                scale = context.numOfFractions;
                return;
            end
            error(['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
                'MissingFractionCountForTotalEndpoint'], ...
                ['Endpoint "%s" uses totalDose but the plan results do ' ...
                 'not define numOfFractions.'],char(endpoint.metric));
        end

        function scale = perFractionDoseScale(context,endpoint)
            if strcmp(context.evaluationModeBase,'perFraction')
                scale = 1;
                return;
            end
            if strcmp(context.evaluationModeBase,'total') && ...
                    planWorkflow.analysis.PlanEvaluationContext.isPositiveScalar( ...
                    context.numOfFractions)
                scale = 1 / context.numOfFractions;
                return;
            end
            error(['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
                'MissingFractionCountForPerFractionEndpoint'], ...
                ['Endpoint "%s" uses perFractionDose but the plan ' ...
                 'results do not define a compatible dose basis.'], ...
                char(endpoint.metric));
        end

        function threshold = volumeThreshold(endpoint)
            if ~strcmp(endpoint.thresholdUnit,'%') || ...
                    ~strcmp(endpoint.thresholdMode,'volumePercent')
                error(['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
                    'InvalidVolumeThresholdSemantics'], ...
                    ['Endpoint "%s" must define a %% volumePercent ' ...
                     'threshold for D metrics.'],char(endpoint.metric));
            end
            threshold = endpoint.threshold;
        end

        function assertDoseQuantity(endpoint,context)
            if ~isfield(endpoint,'doseQuantity') || ...
                    isempty(endpoint.doseQuantity)
                error(['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
                    'MissingEndpointDoseQuantity'], ...
                    'Endpoint "%s" must define doseQuantity.', ...
                    char(endpoint.metric));
            end
            if ~isfield(context,'endpointQuantity') || ...
                    isempty(context.endpointQuantity)
                error(['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
                    'MissingEndpointQuantity'], ...
                    ['Endpoint "%s" requires plan results to define ' ...
                     'endpointQuantity.'],char(endpoint.metric));
            end
            if ~strcmp(char(endpoint.doseQuantity), ...
                    char(context.endpointQuantity))
                error(['planWorkflow:analysis:ClinicalEndpointEvaluator:' ...
                    'EndpointDoseQuantityMismatch'], ...
                    ['Endpoint "%s" expects doseQuantity "%s", but plan ' ...
                     'endpoint results were evaluated as "%s".'], ...
                    char(endpoint.metric),char(endpoint.doseQuantity), ...
                    char(context.endpointQuantity));
            end
        end

        function missing = emptyMissingEndpoint()
            missing = repmat(struct('metric','','kind','', ...
                'structureNames',{{}},'required',true),0,1);
        end

        function missing = missingEndpoint(endpoint)
            missing = struct();
            missing.metric = char(endpoint.metric);
            missing.kind = char(endpoint.kind);
            missing.structureNames = endpoint.structureNames;
            missing.required = ...
                planWorkflow.analysis.EndpointStructureContract.isRequired( ...
                endpoint);
        end
    end
end
