classdef NominalForwardInputs
    % NominalForwardInputs Builds nominal forward-dose inputs for analysis.

    methods (Static)
        function [stf,pln] = robustVariant(robustData,variantResult)
            pln = planWorkflow.results.VariantPlanResolver.resolve( ...
                robustData,variantResult);
            stf = planWorkflow.analysis.NominalForwardInputs.analysisStf( ...
                robustData);
            planWorkflow.precompute.OptimizationInput.assertWeightSteeringMatch( ...
                planWorkflow.precompute.OptimizationInput.require( ...
                robustData,'robust analysis'),variantResult.resultGUI, ...
                planWorkflow.analysis.NominalForwardInputs.planId( ...
                robustData), ...
                planWorkflow.analysis.NominalForwardInputs.variantId( ...
                variantResult),'robust analysis');
            pln = planWorkflow.analysis.NominalForwardInputs.nominalPlan( ...
                robustData,pln);
        end

        function pln = nominalPlan(robustData,pln)
            pln = ...
                planWorkflow.analysis.NominalForwardInputs.removeOptimizationPayload( ...
                pln);

            [scenarioModel,hasScenarioModel] = ...
                planWorkflow.analysis.NominalForwardInputs.nominalScenarioModel( ...
                robustData,pln);
            if hasScenarioModel
                pln.multScen = scenarioModel;
                return;
            end

            optimizationInput = ...
                planWorkflow.precompute.OptimizationInput.require( ...
                robustData,'robust nominal forward plan');
            if ~isempty(optimizationInput.ct)
                nominalScenario = ...
                    planWorkflow.analysis.NominalForwardInputs.nominalScenarioConfig( ...
                    robustData,pln);
                pln.multScen = planWorkflow.scenario.createModel( ...
                    optimizationInput.ct,nominalScenario.scen_mode, ...
                    nominalScenario,'optimization');
            end
        end
    end

    methods (Static, Access = private)
        function stf = analysisStf(robustData)
            optimizationInput = ...
                planWorkflow.precompute.OptimizationInput.require( ...
                robustData,'robust analysis');
            stf = optimizationInput.stf;
        end

        function id = planId(robustData)
            id = '<unknown>';
            if isstruct(robustData) && isfield(robustData,'planConfig') && ...
                    isstruct(robustData.planConfig) && ...
                    isfield(robustData.planConfig,'id') && ...
                    ~isempty(robustData.planConfig.id)
                id = char(robustData.planConfig.id);
            end
        end

        function id = variantId(variantResult)
            id = '<unknown>';
            if isstruct(variantResult) && isfield(variantResult,'variantId') && ...
                    ~isempty(variantResult.variantId)
                id = char(variantResult.variantId);
            end
        end

        function [scenarioModel,hasScenarioModel] = ...
                nominalScenarioModel(robustData,pln)
            scenarioModel = [];
            hasScenarioModel = false;
            candidateModels = ...
                planWorkflow.analysis.NominalForwardInputs.candidateModels( ...
                robustData,pln);

            for modelIx = 1:numel(candidateModels)
                [scenarioModel,hasScenarioModel] = ...
                    planWorkflow.analysis.NominalForwardInputs.extractNominalScenario( ...
                    candidateModels{modelIx},robustData);
                if hasScenarioModel
                    return;
                end
            end
        end

        function candidateModels = candidateModels(robustData,pln)
            candidateModels = {};
            if isfield(pln,'multScen') && ~isempty(pln.multScen)
                candidateModels{end + 1} = pln.multScen; %#ok<AGROW>
            end
            if isfield(robustData,'plnNominal') && ...
                    isfield(robustData.plnNominal,'multScen') && ...
                    ~isempty(robustData.plnNominal.multScen)
                candidateModels{end + 1} = ...
                    robustData.plnNominal.multScen; %#ok<AGROW>
            end
            if isfield(robustData,'pln') && ...
                    isfield(robustData.pln,'multScen') && ...
                    ~isempty(robustData.pln.multScen)
                candidateModels{end + 1} = ...
                    robustData.pln.multScen; %#ok<AGROW>
            end
        end

        function [scenarioModel,hasScenarioModel] = ...
                extractNominalScenario(sourceModel,robustData)
            scenarioModel = [];
            hasScenarioModel = false;
            if isempty(sourceModel) || ...
                    ~ismethod(sourceModel,'getNominalScenarioIds') || ...
                    ~ismethod(sourceModel,'extractSingleScenario')
                return;
            end

            nominalIds = sourceModel.getNominalScenarioIds();
            if isempty(nominalIds)
                return;
            end

            scenarioId = ...
                planWorkflow.analysis.NominalForwardInputs.selectNominalScenarioId( ...
                sourceModel,nominalIds,robustData);
            scenarioModel = sourceModel.extractSingleScenario(scenarioId);
            hasScenarioModel = true;
        end

        function scenarioId = selectNominalScenarioId( ...
                sourceModel,nominalIds,robustData)
            scenarioId = nominalIds(1);
            referenceCtScenarioId = ...
                planWorkflow.analysis.NominalForwardInputs.referenceCtScenarioId( ...
                robustData);
            if isempty(referenceCtScenarioId) || ...
                    ~ismethod(sourceModel,'getCtScenario')
                return;
            end

            ctScenarioIds = arrayfun(@(id) ...
                sourceModel.getCtScenario(id),nominalIds);
            matchingIx = find(ctScenarioIds == referenceCtScenarioId,1,'first');
            if ~isempty(matchingIx)
                scenarioId = nominalIds(matchingIx);
            end
        end

        function scenario = nominalScenarioConfig(robustData,pln)
            scenario = ...
                planWorkflow.config.RobustPlanConfig.defaultScenario( ...
                'nomScen');
            scenario.ctActive = false;
            scenario.setupActive = false;
            scenario.rangeActive = false;
            scenario.gantryActive = false;
            scenario.couchActive = false;

            referenceCtScenarioId = ...
                planWorkflow.analysis.NominalForwardInputs.referenceCtScenarioId( ...
                robustData);
            if ~isempty(referenceCtScenarioId)
                scenario.ctReferenceScenId = referenceCtScenarioId;
            end

            scenario = ...
                planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                scenario);
            scenario = planWorkflow.config.ScenarioSpec.withBeamCount( ...
                scenario,pln);
        end

        function referenceCtScenarioId = referenceCtScenarioId(robustData)
            referenceCtScenarioId = [];
            if isfield(robustData,'ctReferenceView') && ...
                    isstruct(robustData.ctReferenceView) && ...
                    isfield(robustData.ctReferenceView,'active') && ...
                    logical(robustData.ctReferenceView.active) && ...
                    isfield(robustData.ctReferenceView, ...
                    'localCtReferenceScenId') && ...
                    ~isempty(robustData.ctReferenceView.localCtReferenceScenId)
                referenceCtScenarioId = ...
                    robustData.ctReferenceView.localCtReferenceScenId;
                return;
            end
            if isfield(robustData,'optimizationInput') && ...
                    isstruct(robustData.optimizationInput) && ...
                    isfield(robustData.optimizationInput,'ct') && ...
                    isstruct(robustData.optimizationInput.ct) && ...
                    isfield(robustData.optimizationInput.ct,'refScen') && ...
                    ~isempty(robustData.optimizationInput.ct.refScen)
                referenceCtScenarioId = ...
                    robustData.optimizationInput.ct.refScen;
                return;
            end
            if isfield(robustData,'dij_prob2') && ...
                    isfield(robustData.dij_prob2,'refScen') && ...
                    ~isempty(robustData.dij_prob2.refScen)
                referenceCtScenarioId = robustData.dij_prob2.refScen;
                return;
            end

            if isfield(robustData,'planConfig') && ...
                    isfield(robustData.planConfig,'scenario') && ...
                    isfield(robustData.planConfig.scenario, ...
                    'ctReferenceScenId') && ...
                    ~isempty(robustData.planConfig.scenario.ctReferenceScenId)
                referenceCtScenarioId = ...
                    robustData.planConfig.scenario.ctReferenceScenId;
            end
        end

        function pln = removeOptimizationPayload(pln)
            if ~isfield(pln,'propOpt') || ~isstruct(pln.propOpt)
                return;
            end

            optimizationOnlyFields = {'scen4D','dij_interval','dij_prob2'};
            for fieldIx = 1:numel(optimizationOnlyFields)
                fieldName = optimizationOnlyFields{fieldIx};
                if isfield(pln.propOpt,fieldName)
                    pln.propOpt = rmfield(pln.propOpt,fieldName);
                end
            end
        end
    end
end
