classdef DosePullingConfig
    % DosePullingConfig Shared dose-pulling channel contract.

    methods (Static)
        function defaults = defaults()
            defaults = struct( ...
                'dose_pulling1',false, ...
                'dose_pulling1_target',{{'CTV'}}, ...
                'dose_pulling1_criteria',{{'COV1'}}, ...
                'dose_pulling1_limit',0.98, ...
                'dose_pulling1_start',0, ...
                'dose_pulling2',false, ...
                'dose_pulling2_target',{{'CTV'}}, ...
                'dose_pulling2_criteria','meanQiTarget', ...
                'dose_pulling2_limit',0.80, ...
                'dose_pulling2_start',0, ...
                'dose_pulling_max_iter',100, ...
                'dose_pulling_strategy','heuristicMultiObjective', ...
                'dose_pulling_search_schedule','exponential', ...
                'dose_pulling_local_window',8, ...
                'dose_pulling_patience',3, ...
                'dose_pulling_target_tol',1e-3, ...
                'dose_pulling_selection_policy','normalizedKnee', ...
                'dose_pulling_target_weight',1.0, ...
                'dose_pulling_oar_weight',1.0, ...
                'dose_pulling_step_weight',1e-6, ...
                'dose_pulling_max_vmax_percent',100, ...
                'dose_pulling_use_warm_start',true);
        end

        function runConfig = applyDefaults(runConfig)
            defaults = planWorkflow.config.DosePullingConfig.defaults();
            defaultFields = fieldnames(defaults);
            for i = 1:numel(defaultFields)
                fieldName = defaultFields{i};
                if ~isfield(runConfig,fieldName)
                    runConfig.(fieldName) = defaults.(fieldName);
                end
            end
        end

        function runConfig = validateActiveStartConfigs(template,runConfig)
            if ~isfield(template,'dosePulling') || ...
                    isempty(template.dosePulling)
                return;
            end

            channelNames = fieldnames(template.dosePulling);
            for i = 1:numel(channelNames)
                planWorkflow.config.DosePullingConfig.activeStartValue( ...
                    runConfig,template.dosePulling.(channelNames{i}), ...
                    channelNames{i});
            end
        end

        function tf = isChannelEnabled(runConfig,channelName)
            tf = false;
            enabledField = ...
                planWorkflow.config.DosePullingConfig.enabledFieldName( ...
                channelName);
            if ~isstruct(runConfig) || ~isfield(runConfig,enabledField)
                return;
            end

            value = runConfig.(enabledField);
            if isempty(value)
                return;
            end
            tf = planWorkflow.config.DosePullingConfig.logicalFlag( ...
                value,enabledField);
        end

        function value = activeStartValue(runConfig,channel,channelName)
            value = [];
            if ~planWorkflow.config.DosePullingConfig.isChannelEnabled( ...
                    runConfig,channelName)
                return;
            end

            startConfig = char(channel.startConfig);
            if ~isfield(runConfig,startConfig)
                error('planWorkflow:config:DosePullingConfig:MissingStartConfig', ...
                    ['runConfig does not define active dose pulling ' ...
                     'startConfig "%s" for channel "%s".'], ...
                    startConfig,channelName);
            end

            value = runConfig.(startConfig);
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value)
                error('planWorkflow:config:DosePullingConfig:InvalidStartConfig', ...
                    'runConfig.%s must be a finite numeric scalar.', ...
                    startConfig);
            end
        end

        function runConfig = normalizeSearchConfig(runConfig)
            runConfig.dose_pulling_strategy = ...
                planWorkflow.config.DosePullingConfig.canonicalText( ...
                runConfig,'dose_pulling_strategy', ...
                {'Threshold','heuristicMultiObjective'}, ...
                'heuristicMultiObjective');
            runConfig.dose_pulling_search_schedule = ...
                planWorkflow.config.DosePullingConfig.canonicalText( ...
                runConfig,'dose_pulling_search_schedule', ...
                {'exponential'},'exponential');
            runConfig.dose_pulling_selection_policy = ...
                planWorkflow.config.DosePullingConfig.canonicalText( ...
                runConfig,'dose_pulling_selection_policy', ...
                {'normalizedKnee','lexicographic','weightedSum'}, ...
                'normalizedKnee');

            runConfig.dose_pulling_max_iter = ...
                planWorkflow.config.DosePullingConfig.nonnegativeInteger( ...
                runConfig,'dose_pulling_max_iter',100);
            runConfig.dose_pulling_local_window = ...
                planWorkflow.config.DosePullingConfig.nonnegativeInteger( ...
                runConfig,'dose_pulling_local_window',8);
            runConfig.dose_pulling_patience = ...
                planWorkflow.config.DosePullingConfig.positiveInteger( ...
                runConfig,'dose_pulling_patience',3);
            runConfig.dose_pulling_target_tol = ...
                planWorkflow.config.DosePullingConfig.nonnegativeScalar( ...
                runConfig,'dose_pulling_target_tol',1e-3);
            runConfig.dose_pulling_target_weight = ...
                planWorkflow.config.DosePullingConfig.nonnegativeScalar( ...
                runConfig,'dose_pulling_target_weight',1.0);
            runConfig.dose_pulling_oar_weight = ...
                planWorkflow.config.DosePullingConfig.nonnegativeScalar( ...
                runConfig,'dose_pulling_oar_weight',1.0);
            runConfig.dose_pulling_step_weight = ...
                planWorkflow.config.DosePullingConfig.nonnegativeScalar( ...
                runConfig,'dose_pulling_step_weight',1e-6);
            runConfig.dose_pulling_max_vmax_percent = ...
                planWorkflow.config.DosePullingConfig.nonnegativeScalar( ...
                runConfig,'dose_pulling_max_vmax_percent',100);
            if ~isfield(runConfig,'dose_pulling_use_warm_start') || ...
                    isempty(runConfig.dose_pulling_use_warm_start)
                runConfig.dose_pulling_use_warm_start = true;
            else
                runConfig.dose_pulling_use_warm_start = ...
                    planWorkflow.config.DosePullingConfig.logicalFlag( ...
                    runConfig.dose_pulling_use_warm_start, ...
                    'dose_pulling_use_warm_start');
            end
        end

        function strategy = strategy(runConfig)
            if ~isfield(runConfig,'dose_pulling_strategy') || ...
                    isempty(runConfig.dose_pulling_strategy)
                strategy = 'Threshold';
                return;
            end
            normalized = ...
                planWorkflow.config.DosePullingConfig.normalizeSearchConfig( ...
                runConfig);
            strategy = normalized.dose_pulling_strategy;
        end

        function fieldName = enabledFieldName(channelName)
            fieldName = regexprep(char(channelName),'_(\d+)$','$1');
        end

        function tf = logicalFlag(value,fieldName)
            if islogical(value) && isscalar(value)
                tf = value;
                return;
            end
            if isnumeric(value) && isscalar(value) && isfinite(value) && ...
                    any(value == [0 1])
                tf = logical(value);
                return;
            end
            if ischar(value) || (isstring(value) && isscalar(value))
                text = lower(strtrim(char(value)));
                if any(strcmp(text,{'true','on','1','yes'}))
                    tf = true;
                    return;
                end
                if any(strcmp(text,{'false','off','0','no'}))
                    tf = false;
                    return;
                end
            end

            error('planWorkflow:config:DosePullingConfig:InvalidChannelFlag', ...
                ['runConfig.%s must be a logical scalar or one of ' ...
                 'true/false, on/off, 1/0, yes/no.'],fieldName);
        end
    end

    methods (Static, Access = private)
        function value = canonicalText(runConfig,fieldName,allowed,defaultValue)
            if ~isfield(runConfig,fieldName) || isempty(runConfig.(fieldName))
                value = defaultValue;
                return;
            end

            raw = char(runConfig.(fieldName));
            ix = find(strcmpi(raw,allowed),1);
            if isempty(ix)
                error('planWorkflow:config:DosePullingConfig:InvalidValue', ...
                    'runConfig.%s must be one of: %s.', ...
                    fieldName,strjoin(allowed,', '));
            end
            value = allowed{ix};
        end

        function value = nonnegativeScalar(runConfig,fieldName,defaultValue)
            value = ...
                planWorkflow.config.DosePullingConfig.scalarValue( ...
                runConfig,fieldName,defaultValue);
            if value < 0
                error('planWorkflow:config:DosePullingConfig:InvalidValue', ...
                    'runConfig.%s must be nonnegative.',fieldName);
            end
        end

        function value = positiveInteger(runConfig,fieldName,defaultValue)
            value = ...
                planWorkflow.config.DosePullingConfig.nonnegativeInteger( ...
                runConfig,fieldName,defaultValue);
            if value < 1
                error('planWorkflow:config:DosePullingConfig:InvalidValue', ...
                    'runConfig.%s must be a positive integer.',fieldName);
            end
        end

        function value = nonnegativeInteger(runConfig,fieldName,defaultValue)
            value = ...
                planWorkflow.config.DosePullingConfig.scalarValue( ...
                runConfig,fieldName,defaultValue);
            if value < 0 || abs(value - round(value)) > eps(value)
                error('planWorkflow:config:DosePullingConfig:InvalidValue', ...
                    'runConfig.%s must be a nonnegative integer.', ...
                    fieldName);
            end
            value = round(value);
        end

        function value = scalarValue(runConfig,fieldName,defaultValue)
            if ~isfield(runConfig,fieldName) || isempty(runConfig.(fieldName))
                value = defaultValue;
                return;
            end

            value = runConfig.(fieldName);
            if ~(isnumeric(value) && isscalar(value) && isfinite(value))
                error('planWorkflow:config:DosePullingConfig:InvalidValue', ...
                    'runConfig.%s must be a finite numeric scalar.', ...
                    fieldName);
            end
        end
    end
end
