classdef Resources
    % Resources Normalizes computational resource configuration.

    methods (Static)
        function config = defaults()
            config = struct();
            config.memory = struct( ...
                'enabled',true, ...
                'samplePeriodSeconds',0.5, ...
                'includeChildProcesses',true, ...
                'keepSamples',false);
            config.sampling = struct( ...
                'autoLimitWorkers',true, ...
                'workerMemorySafetyFactor',1.2, ...
                'memoryReserveFraction',0.10, ...
                'minWorkerMemoryBytes',2 * 1024^3, ...
                'workerUpperBound',[]);
            config.doseCalculation = struct( ...
                'autoLimitWorkers',true, ...
                'workerMemorySafetyFactor',1.2, ...
                'memoryReserveFraction',0.10, ...
                'minWorkerMemoryBytes',4 * 1024^3, ...
                'workerUpperBound',[], ...
                'releasePoolAfterStage',false);
        end

        function config = normalize(config)
            defaults = planWorkflow.config.Resources.defaults();
            if nargin < 1 || isempty(config)
                config = defaults;
                return;
            end
            if ~isstruct(config) || ~isscalar(config)
                error('planWorkflow:config:Resources:InvalidConfig', ...
                    'runConfig.resources must be a scalar struct.');
            end

            config = planWorkflow.config.Resources.mergeDefaults( ...
                config,defaults);
            config.memory = ...
                planWorkflow.config.Resources.normalizeMemory( ...
                config.memory);
            config.sampling = ...
                planWorkflow.config.Resources.normalizeSampling( ...
                config.sampling);
            config.doseCalculation = ...
                planWorkflow.config.Resources.normalizeDoseCalculation( ...
                config.doseCalculation);
        end

        function options = samplingNameValuePairs(runConfig)
            resources = planWorkflow.config.Resources.fromRunConfig( ...
                runConfig);
            sampling = resources.sampling;
            options = { ...
                'autoLimitWorkers',sampling.autoLimitWorkers, ...
                'workerMemorySafetyFactor', ...
                sampling.workerMemorySafetyFactor, ...
                'memoryReserveFraction',sampling.memoryReserveFraction, ...
                'minWorkerMemoryBytes',sampling.minWorkerMemoryBytes, ...
                'workerUpperBound',sampling.workerUpperBound};
        end

        function options = doseParallelOptions(runConfig)
            resources = planWorkflow.config.Resources.fromRunConfig( ...
                runConfig);
            doseCalculation = resources.doseCalculation;
            options = struct();
            if ~doseCalculation.autoLimitWorkers
                return;
            end
            options.workerMemorySafetyFactor = ...
                doseCalculation.workerMemorySafetyFactor;
            options.memoryReserveFraction = ...
                doseCalculation.memoryReserveFraction;
            options.minWorkerMemoryBytes = ...
                doseCalculation.minWorkerMemoryBytes;
            options.workerUpperBound = doseCalculation.workerUpperBound;
        end

        function resources = fromRunConfig(runConfig)
            if isstruct(runConfig) && isfield(runConfig,'resources')
                resources = planWorkflow.config.Resources.normalize( ...
                    runConfig.resources);
            else
                resources = planWorkflow.config.Resources.defaults();
            end
        end
    end

    methods (Static, Access = private)
        function config = normalizeMemory(config)
            if ~isstruct(config) || ~isscalar(config)
                error('planWorkflow:config:Resources:InvalidMemoryConfig', ...
                    'runConfig.resources.memory must be a scalar struct.');
            end
            config.enabled = planWorkflow.config.ConfigValue.logicalScalar( ...
                config.enabled,'runConfig.resources.memory.enabled', ...
                'planWorkflow:config:Resources:InvalidMemoryEnabled');
            config.includeChildProcesses = ...
                planWorkflow.config.ConfigValue.logicalScalar( ...
                config.includeChildProcesses, ...
                'runConfig.resources.memory.includeChildProcesses', ...
                ['planWorkflow:config:Resources:' ...
                'InvalidIncludeChildProcesses']);
            config.keepSamples = planWorkflow.config.ConfigValue.logicalScalar( ...
                config.keepSamples, ...
                'runConfig.resources.memory.keepSamples', ...
                'planWorkflow:config:Resources:InvalidKeepSamples');
            config.samplePeriodSeconds = ...
                planWorkflow.config.Resources.nonnegativeScalar( ...
                config.samplePeriodSeconds, ...
                'runConfig.resources.memory.samplePeriodSeconds');
        end

        function config = normalizeSampling(config)
            config = planWorkflow.config.Resources.normalizeWorkerConfig( ...
                config,'runConfig.resources.sampling', ...
                'planWorkflow:config:Resources:InvalidSamplingConfig');
        end

        function config = normalizeDoseCalculation(config)
            config = planWorkflow.config.Resources.normalizeWorkerConfig( ...
                config,'runConfig.resources.doseCalculation', ...
                'planWorkflow:config:Resources:InvalidDoseCalculationConfig');
            config.releasePoolAfterStage = ...
                planWorkflow.config.ConfigValue.logicalScalar( ...
                config.releasePoolAfterStage, ...
                ['runConfig.resources.doseCalculation.' ...
                'releasePoolAfterStage'], ...
                ['planWorkflow:config:Resources:' ...
                'InvalidReleasePoolAfterStage']);
        end

        function config = normalizeWorkerConfig(config,context,errorId)
            if ~isstruct(config) || ~isscalar(config)
                error(errorId,'%s must be a scalar struct.',context);
            end
            config.autoLimitWorkers = ...
                planWorkflow.config.ConfigValue.logicalScalar( ...
                config.autoLimitWorkers, ...
                [context '.autoLimitWorkers'], ...
                'planWorkflow:config:Resources:InvalidAutoLimitWorkers');
            config.workerMemorySafetyFactor = ...
                planWorkflow.config.Resources.scalarAtLeast( ...
                config.workerMemorySafetyFactor,1, ...
                [context '.workerMemorySafetyFactor']);
            config.memoryReserveFraction = ...
                planWorkflow.config.Resources.reserveFraction( ...
                config.memoryReserveFraction, ...
                [context '.memoryReserveFraction']);
            config.minWorkerMemoryBytes = ...
                planWorkflow.config.Resources.nonnegativeScalar( ...
                config.minWorkerMemoryBytes, ...
                [context '.minWorkerMemoryBytes']);
            config.workerUpperBound = ...
                planWorkflow.config.Resources.workerUpperBound( ...
                config.workerUpperBound, ...
                [context '.workerUpperBound']);
        end

        function value = nonnegativeScalar(value,context)
            valid = isnumeric(value) && isscalar(value) && ...
                isfinite(value) && value >= 0;
            if ~valid
                error('planWorkflow:config:Resources:InvalidNumericValue', ...
                    '%s must be a finite non-negative scalar.',context);
            end
        end

        function value = scalarAtLeast(value,minimum,context)
            valid = isnumeric(value) && isscalar(value) && ...
                isfinite(value) && value >= minimum;
            if ~valid
                error('planWorkflow:config:Resources:InvalidNumericValue', ...
                    '%s must be a finite scalar >= %g.',context,minimum);
            end
        end

        function value = reserveFraction(value,context)
            valid = isnumeric(value) && isscalar(value) && ...
                isfinite(value) && value >= 0 && value < 1;
            if ~valid
                error('planWorkflow:config:Resources:InvalidReserveFraction', ...
                    '%s must be a finite scalar in [0,1).',context);
            end
        end

        function value = workerUpperBound(value,context)
            if isempty(value)
                return;
            end
            valid = isnumeric(value) && isscalar(value) && ...
                isfinite(value) && value >= 1 && round(value) == value;
            if ~valid
                error('planWorkflow:config:Resources:InvalidWorkerUpperBound', ...
                    '%s must be empty or a positive integer scalar.', ...
                    context);
            end
        end

        function config = mergeDefaults(config,defaults)
            fields = fieldnames(defaults);
            for i = 1:numel(fields)
                fieldName = fields{i};
                if ~isfield(config,fieldName)
                    config.(fieldName) = defaults.(fieldName);
                elseif isstruct(config.(fieldName)) && ...
                        isstruct(defaults.(fieldName)) && ...
                        isscalar(config.(fieldName)) && ...
                        isscalar(defaults.(fieldName))
                    config.(fieldName) = ...
                        planWorkflow.config.Resources.mergeDefaults( ...
                        config.(fieldName),defaults.(fieldName));
                end
            end
        end
    end
end
