classdef RobustPlanConfig
    % RobustPlanConfig Normalizes the canonical robust-plan workflow contract.

    methods (Static)
        function precompute = defaults()
            precompute = struct();
            precompute.reference = planWorkflow.config.RobustPlanConfig.defaultReference();
            precompute.robustPlans = repmat( ...
                planWorkflow.config.RobustPlanConfig.defaultPlan(),1,0);
        end

        function reference = defaultReference()
            referenceScenario = ...
                planWorkflow.config.RobustPlanConfig.defaultScenario( ...
                'nomScen');
            referenceScenario.ctActive = false;
            referenceScenario.setupActive = false;
            referenceScenario.rangeActive = false;
            referenceScenario.gantryActive = false;
            referenceScenario.couchActive = false;
            reference = struct( ...
                'label','', ...
                'robustnessMode','none', ...
                'optimization4D', ...
                planWorkflow.config.RobustPlanConfig.defaultOptimization4D(), ...
                'scenario',referenceScenario, ...
                'robustnessOptions',struct(), ...
                'dosePrecompute', ...
                planWorkflow.config.RobustPlanConfig.defaultDosePrecompute(), ...
                'variants', ...
                planWorkflow.config.RobustPlanConfig.defaultVariants( ...
                'none'));
        end

        function plan = defaultPlan()
            contract = ...
                planWorkflow.config.RobustPlanConfig.defaultRobustnessContract();
            plan = struct( ...
                'id','', ...
                'label','', ...
                'objectiveSetName','', ...
                'robustnessMode',contract.robustnessMode, ...
                'hasNominalObjectives',contract.hasNominalObjectives, ...
                'requiresNominalDij',contract.requiresNominalDij, ...
                'requiresScenarioDij',contract.requiresScenarioDij, ...
                'requiresIntervalDij',contract.requiresIntervalDij, ...
                'requiresProb2Dij',contract.requiresProb2Dij, ...
                'optimization4D', ...
                planWorkflow.config.RobustPlanConfig.defaultOptimization4D(), ...
                'scenario', ...
                planWorkflow.config.RobustPlanConfig.defaultScenario( ...
                'wcScen'), ...
                'robustnessOptions',struct(), ...
                'dosePrecompute', ...
                planWorkflow.config.RobustPlanConfig.defaultDosePrecompute(), ...
                'variants',[], ...
                'variantsWithPenalties',[]);
        end

        function dosePrecompute = defaultDosePrecompute()
            dosePrecompute = struct( ...
                'useStreaming',false, ...
                'SecondPassStrategy','disk', ...
                'KeepCache',false, ...
                'CacheRoot','');
        end

        function contract = defaultRobustnessContract()
            contract = struct( ...
                'objectiveSetId','', ...
                'hasNominalObjectives',true, ...
                'robustnessMode','none', ...
                'nonNoneModes',{{}}, ...
                'requiresNominalDij',true, ...
                'requiresScenarioDij',false, ...
                'requiresIntervalDij',false, ...
                'requiresProb2Dij',false);
        end

        function scenario = defaultScenario(mode)
            if nargin < 1 || isempty(mode)
                mode = 'wcScen';
            end
            scenario = planWorkflow.config.ScenarioSpec.defaults(mode);
        end

        function options = defaultRobustnessOptions(robustnessMode)
            if nargin < 1 || isempty(robustnessMode)
                error(['planWorkflow:config:RobustPlanConfig:' ...
                    'MissingRobustnessMode'], ...
                    'defaultRobustnessOptions requires an explicit mode.');
            end
            options = ...
                planWorkflow.config.RobustStrategySpec.defaultStrategyOptions( ...
                robustnessMode);
        end

        function options = defaultOptimization4D()
            options = struct( ...
                'enabled',false, ...
                'scen4D','all');
        end

        function variants = defaultVariants(strategy)
            if nargin < 1 || isempty(strategy)
                strategy = 'none';
            end
            variants = planWorkflow.config.RobustPlanConfig.defaultVariant( ...
                strategy,1);
        end

        function variant = defaultVariant(strategy,variantIx)
            if nargin < 2 || isempty(variantIx)
                variantIx = 1;
            end
            variant = ...
                planWorkflow.config.RobustStrategySpec.defaultVariant( ...
                strategy,variantIx);
        end

        function fields = variantParameterFields(strategy)
            fields = ...
                planWorkflow.config.RobustStrategySpec.variantParameterFields( ...
                strategy);
        end

        function fields = allVariantParameterFields()
            fields = ...
                planWorkflow.config.RobustStrategySpec.allVariantParameterFields();
        end

        function precompute = normalizePrecompute(precompute,contracts)
            if nargin < 2
                contracts = [];
            end
            if nargin < 1 || isempty(precompute)
                precompute = struct();
            end
            if ~isstruct(precompute) || ~isscalar(precompute)
                error('planWorkflow:config:RobustPlanConfig:InvalidPrecompute', ...
                    'config.precompute must be a scalar struct.');
            end

            defaults = planWorkflow.config.RobustPlanConfig.defaults();
            precompute = planWorkflow.config.RobustPlanConfig.mergeDefaults( ...
                precompute,defaults);
            precompute.reference = ...
                planWorkflow.config.RobustPlanConfig.normalizeReference( ...
                precompute.reference);
            precompute.robustPlans = ...
                planWorkflow.config.RobustPlanConfig.normalizePlans( ...
                precompute.robustPlans,contracts);
        end

        function reference = normalizeReference(reference)
            if nargin < 1 || isempty(reference)
                reference = struct();
            end
            if ~isstruct(reference) || ~isscalar(reference)
                error('planWorkflow:config:RobustPlanConfig:InvalidReference', ...
                    'config.precompute.reference must be a scalar struct.');
            end

            allowed = {'label','robustnessMode','optimization4D','scenario', ...
                'robustnessOptions','dosePrecompute','variants'};
            planWorkflow.config.RobustPlanConfig.assertAllowedFields( ...
                reference,allowed,'config.precompute.reference');
            defaults = planWorkflow.config.RobustPlanConfig.defaultReference();
            reference = planWorkflow.config.RobustPlanConfig.mergeDefaults( ...
                reference,defaults);
            reference.label = ...
                planWorkflow.config.RobustPlanConfig.optionalText( ...
                reference.label,'config.precompute.reference.label');
            reference.robustnessMode = ...
                planWorkflow.config.RobustPlanConfig.robustnessModeText( ...
                reference.robustnessMode, ...
                'config.precompute.reference.robustnessMode');
            reference.scenario = ...
                planWorkflow.config.RobustPlanConfig.normalizeScenario( ...
                reference.scenario,defaults.scenario, ...
                'config.precompute.reference.scenario');
            reference.optimization4D = ...
                planWorkflow.config.RobustPlanConfig.optimization4DFromScenario( ...
                reference.scenario);
            reference.robustnessOptions = ...
                planWorkflow.config.RobustPlanConfig.normalizeRobustnessOptionsForMode( ...
                reference.robustnessMode,reference.robustnessOptions, ...
                'config.precompute.reference');
            reference.dosePrecompute = ...
                planWorkflow.config.RobustPlanConfig.normalizeDosePrecompute( ...
                reference.dosePrecompute, ...
                'config.precompute.reference.dosePrecompute');
            reference.variants = ...
                planWorkflow.config.RobustPlanConfig.normalizeVariants( ...
                reference.variants,reference.robustnessMode, ...
                'config.precompute.reference.variants');
        end

        function plans = normalizePlans(plans,contracts)
            if nargin < 2
                contracts = [];
            end
            if nargin < 1 || isempty(plans)
                plans = repmat( ...
                    planWorkflow.config.RobustPlanConfig.defaultPlan(),1,0);
                return;
            end
            if ~isstruct(plans)
                error('planWorkflow:config:RobustPlanConfig:InvalidRobustPlans', ...
                    'config.precompute.robustPlans must be a struct array.');
            end

            if planWorkflow.config.RobustPlanConfig.isNamedPlanStruct(plans)
                plans = planWorkflow.config.RobustPlanConfig.namedPlansToArray( ...
                    plans,contracts);
                contracts = [];
            end

            plans = plans(:)';
            normalized = repmat( ...
                planWorkflow.config.RobustPlanConfig.defaultPlan(), ...
                1,numel(plans));
            ids = cell(1,numel(plans));
            for planIx = 1:numel(plans)
                normalized(planIx) = ...
                    planWorkflow.config.RobustPlanConfig.normalizePlan( ...
                    plans(planIx),planIx, ...
                    planWorkflow.config.RobustPlanConfig.contractAt( ...
                    contracts,planIx));
                ids{planIx} = char(normalized(planIx).id);
            end
            if numel(unique(ids)) ~= numel(ids)
                error('planWorkflow:config:RobustPlanConfig:DuplicateRobustPlanId', ...
                    'config.precompute.robustPlans ids must be unique.');
            end
            plans = normalized;
        end

        function plan = normalizePlan(plan,planIx,contract)
            if nargin < 2 || isempty(planIx)
                planIx = 1;
            end
            if nargin < 3 || isempty(contract)
                contract = ...
                    planWorkflow.config.RobustPlanConfig.contractFromPlan( ...
                    plan);
            end
            if ~isstruct(plan) || ~isscalar(plan)
                error('planWorkflow:config:RobustPlanConfig:InvalidRobustPlan', ...
                    'Each robust plan must be a scalar struct.');
            end
            explicitRobustnessMode = ...
                planWorkflow.config.RobustPlanConfig.explicitRobustnessMode( ...
                plan,'config.precompute.robustPlans.robustnessMode');
            allowed = {'id','label','objectiveSetName','robustnessMode', ...
                'hasNominalObjectives','requiresNominalDij', ...
                'requiresScenarioDij','requiresIntervalDij', ...
                'requiresProb2Dij', ...
                'optimization4D','scenario','robustnessOptions', ...
                'dosePrecompute','variants','variantsWithPenalties'};
            planWorkflow.config.RobustPlanConfig.assertAllowedFields( ...
                plan,allowed,'config.precompute.robustPlans');

            defaults = planWorkflow.config.RobustPlanConfig.defaultPlan();
            defaults.id = sprintf('robust_%d',planIx);
            defaults.label = sprintf('Robust %d',planIx);
            defaults.objectiveSetName = defaults.id;
            plan = planWorkflow.config.RobustPlanConfig.mergeDefaults( ...
                plan,defaults);

            plan.id = planWorkflow.config.RobustPlanConfig.identifierText( ...
                plan.id,'config.precompute.robustPlans.id');
            plan.label = planWorkflow.config.RobustPlanConfig.requiredText( ...
                plan.label,'config.precompute.robustPlans.label');
            plan.objectiveSetName = ...
                planWorkflow.config.RobustPlanConfig.identifierText( ...
                plan.objectiveSetName, ...
                'config.precompute.robustPlans.objectiveSetName');
            plan = ...
                planWorkflow.config.RobustPlanConfig.retargetForRobustnessContract( ...
                plan,contract,explicitRobustnessMode);
            plan = ...
                planWorkflow.config.RobustPlanConfig.applyRobustnessContract( ...
                plan,contract);
            planWorkflow.config.RobustPlanConfig.assertSingleCompactPrecomputeMode( ...
                plan,'config.precompute.robustPlans');
            plan.scenario = ...
                planWorkflow.config.RobustPlanConfig.normalizeScenario( ...
                plan.scenario,defaults.scenario, ...
                'config.precompute.robustPlans.scenario');
            plan.optimization4D = ...
                planWorkflow.config.RobustPlanConfig.optimization4DFromScenario( ...
                plan.scenario);
            plan.robustnessOptions = ...
                planWorkflow.config.RobustPlanConfig.normalizeRobustnessOptionsForMode( ...
                plan.robustnessMode,plan.robustnessOptions, ...
                'config.precompute.robustPlans');
            plan.dosePrecompute = ...
                planWorkflow.config.RobustPlanConfig.normalizeDosePrecompute( ...
                plan.dosePrecompute, ...
                'config.precompute.robustPlans.dosePrecompute');
            plan.variants = ...
                planWorkflow.config.RobustPlanConfig.normalizeVariants( ...
                plan.variants,plan.robustnessMode, ...
                'config.precompute.robustPlans.variants');
            plan.variantsWithPenalties = ...
                planWorkflow.config.RobustPlanConfig.normalizeVariantsWithPenalties( ...
                plan.variantsWithPenalties,plan.variants, ...
                plan.robustnessMode, ...
                'config.precompute.robustPlans.variantsWithPenalties');
        end

        function scenario = normalizeScenario(scenario,defaults,context)
            if nargin < 2 || isempty(defaults)
                defaults = ...
                    planWorkflow.config.RobustPlanConfig.defaultScenario();
            end
            if nargin < 3
                context = 'scenario';
            end
            scenario = planWorkflow.config.ScenarioSpec.normalize( ...
                scenario,defaults,context);
        end

        function scenario = matRadScenario(scenario)
            scenario = planWorkflow.config.ScenarioSpec.matRadScenario( ...
                scenario);
        end

        function options = normalizeRobustnessOptions(robustnessMode,options)
            if nargin < 1 || isempty(robustnessMode)
                error(['planWorkflow:config:RobustPlanConfig:' ...
                    'MissingRobustnessMode'], ...
                    'normalizeRobustnessOptions requires an explicit mode.');
            end
            if nargin < 2 || isempty(options)
                options = struct();
            end
            if ~isstruct(options) || ~isscalar(options)
                error('planWorkflow:config:RobustPlanConfig:InvalidRobustnessOptions', ...
                    'robustnessOptions must be a scalar struct.');
            end
            options = ...
                planWorkflow.config.RobustStrategySpec.normalizeStrategyOptions( ...
                robustnessMode,options,'robustnessOptions');
        end

        function options = optimization4DFromScenario(scenario)
            options = ...
                planWorkflow.config.RobustPlanConfig.defaultOptimization4D();
            if isstruct(scenario) && isfield(scenario,'ctActive') && ...
                    logical(scenario.ctActive)
                options.enabled = true;
                options.scen4D = 'all';
            end
        end

        function options = normalizeRobustnessOptionsForMode( ...
                robustnessMode,options,context)
            if nargin < 2 || isempty(options)
                options = struct();
            end
            if nargin < 3 || isempty(context)
                context = 'robustPlan';
            end
            if ~isstruct(options) || ~isscalar(options)
                error('planWorkflow:config:RobustPlanConfig:InvalidRobustnessOptions', ...
                    '%s.robustnessOptions must be a scalar struct.',context);
            end
            options = ...
                planWorkflow.config.RobustStrategySpec.normalizeStrategyOptions( ...
                robustnessMode,options,[context '.robustnessOptions']);
        end

        function dosePrecompute = normalizeDosePrecompute( ...
                dosePrecompute,context)
            if nargin < 1 || isempty(dosePrecompute)
                dosePrecompute = struct();
            end
            if nargin < 2 || isempty(context)
                context = 'dosePrecompute';
            end
            if ~isstruct(dosePrecompute) || ~isscalar(dosePrecompute)
                error(['planWorkflow:config:RobustPlanConfig:' ...
                    'InvalidDosePrecompute'], ...
                    '%s must be a scalar struct.',context);
            end
            allowed = {'useStreaming','SecondPassStrategy','KeepCache', ...
                'CacheRoot'};
            planWorkflow.config.RobustPlanConfig.assertAllowedFields( ...
                dosePrecompute,allowed,context);

            dosePrecompute = ...
                planWorkflow.config.RobustPlanConfig.mergeDefaults( ...
                dosePrecompute, ...
                planWorkflow.config.RobustPlanConfig.defaultDosePrecompute());
            dosePrecompute.useStreaming = logicalScalar( ...
                dosePrecompute.useStreaming,[context '.useStreaming']);
            dosePrecompute.KeepCache = logicalScalar( ...
                dosePrecompute.KeepCache,[context '.KeepCache']);
            dosePrecompute.SecondPassStrategy = lower( ...
                planWorkflow.config.RobustPlanConfig.requiredText( ...
                dosePrecompute.SecondPassStrategy, ...
                [context '.SecondPassStrategy']));
            if ~any(strcmp(dosePrecompute.SecondPassStrategy, ...
                    {'disk','recompute'}))
                error(['planWorkflow:config:RobustPlanConfig:' ...
                    'InvalidDosePrecomputeStrategy'], ...
                    '%s.SecondPassStrategy must be disk or recompute.', ...
                    context);
            end
            dosePrecompute.CacheRoot = ...
                planWorkflow.config.RobustPlanConfig.pathText( ...
                dosePrecompute.CacheRoot,[context '.CacheRoot']);
        end

        function variants = normalizeVariants(variants,robustnessMode,context)
            if nargin < 3
                context = 'variants';
            end
            if isempty(variants)
                variants = ...
                    planWorkflow.config.RobustPlanConfig.defaultVariants( ...
                    robustnessMode);
            end
            if ~isstruct(variants) || isempty(variants)
                error('planWorkflow:config:RobustPlanConfig:InvalidVariants', ...
                    '%s must contain at least one variant.',context);
            end
            variants = variants(:)';
            normalized = repmat( ...
                planWorkflow.config.RobustPlanConfig.defaultVariant( ...
                robustnessMode,1),1,numel(variants));
            ids = cell(1,numel(variants));
            for variantIx = 1:numel(variants)
                normalized(variantIx) = ...
                    planWorkflow.config.RobustPlanConfig.normalizeVariant( ...
                    variants(variantIx),robustnessMode,variantIx, ...
                    context);
                ids{variantIx} = char(normalized(variantIx).id);
            end
            if numel(unique(ids)) ~= numel(ids)
                error('planWorkflow:config:RobustPlanConfig:DuplicateVariantId', ...
                    '%s ids must be unique.',context);
            end
            variants = normalized;
        end

        function variant = normalizeVariant(variant,robustnessMode,variantIx,context)
            if ~isstruct(variant) || ~isscalar(variant)
                error('planWorkflow:config:RobustPlanConfig:InvalidVariant', ...
                    '%s entries must be scalar structs.',context);
            end
            variantContext = sprintf('%s(%d)',context,variantIx);
            defaultVariant = ...
                planWorkflow.config.RobustPlanConfig.defaultVariant( ...
                robustnessMode,variantIx);
            allowed = fieldnames(defaultVariant)';
            planWorkflow.config.RobustPlanConfig.assertAllowedFields( ...
                variant,allowed,variantContext);
            required = ...
                planWorkflow.config.RobustPlanConfig.requiredVariantFields( ...
                robustnessMode);
            for fieldIx = 1:numel(required)
                fieldName = required{fieldIx};
                if ~isfield(variant,fieldName) || isempty(variant.(fieldName))
                    error('planWorkflow:config:RobustPlanConfig:MissingVariantParameter', ...
                        '%s.%s is required for %s variants.', ...
                        variantContext,fieldName,char(robustnessMode));
                end
            end
            variant = planWorkflow.config.RobustPlanConfig.mergeDefaults( ...
                variant,defaultVariant);
            variant.id = planWorkflow.config.RobustPlanConfig.identifierText( ...
                variant.id,[variantContext '.id']);
            variant.label = planWorkflow.config.RobustPlanConfig.requiredText( ...
                variant.label,[variantContext '.label']);

            for fieldIx = 1:numel(required)
                fieldName = required{fieldIx};
                variant.(fieldName) = finiteNumericScalar( ...
                    variant.(fieldName),[variantContext '.' fieldName]);
            end
        end

        function variants = normalizeVariantsWithPenalties( ...
                variants,baseVariants,robustnessMode,context)
            if nargin < 4
                context = 'variantsWithPenalties';
            end
            if isempty(variants)
                variants = repmat( ...
                    planWorkflow.config.RobustPlanConfig.defaultVariant( ...
                    robustnessMode,1),1,0);
                return;
            end
            if ~isstruct(variants) || isempty(variants)
                error('planWorkflow:config:RobustPlanConfig:InvalidVariants', ...
                    '%s must be a struct array.',context);
            end
            variants = variants(:)';
            ids = cell(1,numel(variants));
            required = ...
                planWorkflow.config.RobustPlanConfig.requiredVariantFields( ...
                robustnessMode);
            for variantIx = 1:numel(variants)
                variantContext = sprintf('%s(%d)',context,variantIx);
                variant = variants(variantIx);
                if ~isstruct(variant) || ~isscalar(variant)
                    error('planWorkflow:config:RobustPlanConfig:InvalidVariant', ...
                        '%s entries must be scalar structs.',context);
                end
                variant.id = ...
                    planWorkflow.config.RobustPlanConfig.identifierText( ...
                    variant.id,[variantContext '.id']);
                variant.label = ...
                    planWorkflow.config.RobustPlanConfig.requiredText( ...
                    variant.label,[variantContext '.label']);
                for fieldIx = 1:numel(required)
                    fieldName = required{fieldIx};
                    if isfield(variant,fieldName)
                        variant.(fieldName) = finiteNumericScalar( ...
                            variant.(fieldName), ...
                            [variantContext '.' fieldName]);
                    end
                end
                variants(variantIx) = variant;
                ids{variantIx} = char(variant.id);
            end
            if numel(unique(ids)) ~= numel(ids)
                error('planWorkflow:config:RobustPlanConfig:DuplicateVariantId', ...
                    '%s ids must be unique.',context);
            end
        end

        function runConfig = variantRunConfig(runConfig,plan,variantIx)
            variant = ...
                planWorkflow.config.RobustPlanConfig.variantWithPenalty( ...
                plan,variantIx);
            runConfig.robustnessMode = char(plan.robustnessMode);
            runConfig.variant = variant;
            if ~isempty(fieldnames(plan.robustnessOptions))
                runConfig.robustnessOptions = plan.robustnessOptions;
            elseif isfield(runConfig,'robustnessOptions')
                runConfig = rmfield(runConfig,'robustnessOptions');
            end
        end

        function variants = variantsWithPenalties(plan)
            variants = repmat( ...
                planWorkflow.config.RobustPlanConfig.defaultVariant( ...
                'none',1),1,0);
            if ~isstruct(plan)
                return;
            end
            if isfield(plan,'variantsWithPenalties') && ...
                    ~isempty(plan.variantsWithPenalties)
                variants = plan.variantsWithPenalties(:)';
                return;
            end
            if isfield(plan,'variants') && ~isempty(plan.variants)
                variants = ...
                    planWorkflow.config.RobustPlanConfig.baseVariantsWithPenalties( ...
                    plan.variants(:)');
            end
        end

        function variant = variantWithPenalty(plan,variantIx)
            variants = ...
                planWorkflow.config.RobustPlanConfig.variantsWithPenalties( ...
                plan);
            if isempty(variants)
                error('planWorkflow:config:RobustPlanConfig:MissingVariant', ...
                    'Plan has no configured variants.');
            end
            variant = variants(variantIx);
        end

        function count = variantWithPenaltyCount(plan)
            count = numel( ...
                planWorkflow.config.RobustPlanConfig.variantsWithPenalties( ...
                plan));
            count = max(1,count);
        end

        function plans = plansFromRunConfig(runConfig)
            plans = repmat( ...
                planWorkflow.config.RobustPlanConfig.defaultPlan(),1,0);
            if isstruct(runConfig) && isfield(runConfig,'precompute') && ...
                    isstruct(runConfig.precompute) && ...
                    isfield(runConfig.precompute,'robustPlans')
                plans = ...
                    planWorkflow.config.RobustPlanConfig.normalizePlans( ...
                    runConfig.precompute.robustPlans);
            end
        end

        function reference = referenceFromRunConfig(runConfig)
            if isstruct(runConfig) && isfield(runConfig,'precompute') && ...
                    isstruct(runConfig.precompute) && ...
                    isfield(runConfig.precompute,'reference')
                reference = ...
                    planWorkflow.config.RobustPlanConfig.normalizeReference( ...
                    runConfig.precompute.reference);
            else
                reference = planWorkflow.config.RobustPlanConfig.defaultReference();
            end
        end

        function names = robustnessModeNames(plans)
            names = cell(1,numel(plans));
            for i = 1:numel(plans)
                names{i} = char(plans(i).robustnessMode);
            end
        end

        function label = pathLabel(plans)
            if isempty(plans)
                label = 'none';
                return;
            end
            parts = cell(1,numel(plans));
            for i = 1:numel(plans)
                parts{i} = [char(plans(i).id) '_' ...
                    char(plans(i).robustnessMode)];
            end
            label = strjoin(parts,'+');
        end

        function assertAllowedFields(config,allowed,context)
            fields = fieldnames(config);
            for i = 1:numel(fields)
                if ~any(strcmp(fields{i},allowed))
                    error('planWorkflow:config:RobustPlanConfig:UnsupportedField', ...
                        'Unsupported %s field "%s".',context,fields{i});
                end
            end
        end
    end

    methods (Static, Access = private)
        function variants = baseVariantsWithPenalties(baseVariants)
            if isempty(baseVariants)
                variants = baseVariants;
                return;
            end
            assignments = repmat(struct('groupField','','groupIx',0, ...
                'objectiveIx',0,'structureName','','value',0),1,0);
            variants = baseVariants(:)';
            for variantIx = 1:numel(variants)
                variants(variantIx).baseVariantId = ...
                    char(variants(variantIx).id);
                variants(variantIx).baseVariantLabel = ...
                    char(variants(variantIx).label);
                variants(variantIx).baseVariantIndex = variantIx;
                variants(variantIx).penaltyCombinationIndex = 1;
                variants(variantIx).penaltyCombinationCount = 1;
                variants(variantIx).penaltyAssignments = assignments;
                variants(variantIx).penaltyLabel = '';
            end
        end

        function tf = isNamedPlanStruct(plans)
            tf = false;
            if ~isscalar(plans)
                return;
            end
            planFields = fieldnames(plans);
            allowed = {'id','label','objectiveSetName','robustnessMode', ...
                'hasNominalObjectives','requiresNominalDij', ...
                'requiresScenarioDij','requiresIntervalDij', ...
                'requiresProb2Dij', ...
                'optimization4D','scenario','robustnessOptions', ...
                'dosePrecompute','variants','variantsWithPenalties'};
            if isempty(planFields) || all(ismember(planFields,allowed))
                return;
            end
            for i = 1:numel(planFields)
                fieldValue = plans.(planFields{i});
                if ~isvarname(planFields{i}) || ~isstruct(fieldValue) || ...
                        ~isscalar(fieldValue)
                    return;
                end
            end
            tf = true;
        end

        function plans = namedPlansToArray(namedPlans,contracts)
            if nargin < 2
                contracts = [];
            end
            ids = fieldnames(namedPlans);
            plans = repmat( ...
                planWorkflow.config.RobustPlanConfig.defaultPlan(), ...
                1,numel(ids));
            for planIx = 1:numel(ids)
                planId = ids{planIx};
                plan = namedPlans.(planId);
                if isfield(plan,'id') && ~strcmp(char(plan.id),planId)
                    error('planWorkflow:config:RobustPlanConfig:RobustPlanIdMismatch', ...
                        ['config.precompute.robustPlans.%s.id must match ' ...
                         'the robust plan field name.'],planId);
                end
                plan.id = planId;
                if ~isfield(plan,'objectiveSetName') || ...
                        isempty(plan.objectiveSetName)
                    plan.objectiveSetName = planId;
                end
                plans(planIx) = ...
                    planWorkflow.config.RobustPlanConfig.normalizePlan( ...
                    plan,planIx, ...
                    planWorkflow.config.RobustPlanConfig.contractAt( ...
                    contracts,planIx));
            end
        end

        function contract = contractAt(contracts,planIx)
            contract = [];
            if isempty(contracts)
                return;
            end
            if numel(contracts) < planIx
                return;
            end
            contract = contracts(planIx);
        end

        function contract = contractFromPlan(plan)
            contract = ...
                planWorkflow.config.RobustPlanConfig.defaultRobustnessContract();
            if ~isstruct(plan)
                return;
            end
            fields = {'hasNominalObjectives','robustnessMode', ...
                'requiresNominalDij','requiresScenarioDij', ...
                'requiresIntervalDij','requiresProb2Dij'};
            for i = 1:numel(fields)
                fieldName = fields{i};
                if isfield(plan,fieldName) && ~isempty(plan.(fieldName))
                    contract.(fieldName) = plan.(fieldName);
                end
            end
        end

        function mode = explicitRobustnessMode(plan,context)
            mode = '';
            if ~isstruct(plan) || ~isfield(plan,'robustnessMode') || ...
                    isempty(plan.robustnessMode)
                return;
            end
            mode = planWorkflow.config.RobustPlanConfig.robustnessModeText( ...
                plan.robustnessMode,context);
        end

        function plan = retargetForRobustnessContract( ...
                plan,contract,explicitRobustnessMode)
            if nargin < 3 || isempty(explicitRobustnessMode)
                return;
            end
            if strcmp(explicitRobustnessMode,'none')
                return;
            end
            contractMode = ...
                planWorkflow.config.RobustPlanConfig.robustnessModeText( ...
                contract.robustnessMode, ...
                'config.precompute.robustPlans.robustnessMode');
            if strcmp(explicitRobustnessMode,contractMode)
                return;
            end
            plan.robustnessMode = contractMode;
            plan.robustnessOptions = ...
                planWorkflow.config.RobustPlanConfig.defaultRobustnessOptions( ...
                contractMode);
            plan.variants = ...
                planWorkflow.config.RobustPlanConfig.defaultVariants( ...
                contractMode);
            plan.variantsWithPenalties = [];
        end

        function plan = applyRobustnessContract(plan,contract)
            if nargin < 2 || isempty(contract)
                contract = ...
                    planWorkflow.config.RobustPlanConfig.defaultRobustnessContract();
            end
            plan.robustnessMode = ...
                planWorkflow.config.RobustPlanConfig.robustnessModeText( ...
                contract.robustnessMode, ...
                'config.precompute.robustPlans.robustnessMode');
            plan.hasNominalObjectives = logicalScalar( ...
                contract.hasNominalObjectives, ...
                'config.precompute.robustPlans.hasNominalObjectives');
            plan.requiresNominalDij = logicalScalar( ...
                contract.requiresNominalDij, ...
                'config.precompute.robustPlans.requiresNominalDij');
            plan.requiresScenarioDij = logicalScalar( ...
                contract.requiresScenarioDij, ...
                'config.precompute.robustPlans.requiresScenarioDij');
            plan.requiresIntervalDij = logicalScalar( ...
                contract.requiresIntervalDij, ...
                'config.precompute.robustPlans.requiresIntervalDij');
            plan.requiresProb2Dij = logicalScalar( ...
                contract.requiresProb2Dij, ...
                'config.precompute.robustPlans.requiresProb2Dij');
        end

        function assertSingleCompactPrecomputeMode(plan,context)
            if ~isstruct(plan)
                return;
            end
            requiresInterval = isfield(plan,'requiresIntervalDij') && ...
                logical(plan.requiresIntervalDij);
            requiresProb2 = isfield(plan,'requiresProb2Dij') && ...
                logical(plan.requiresProb2Dij);
            if requiresInterval && requiresProb2
                error(['planWorkflow:config:RobustPlanConfig:' ...
                    'MixedCompactPrecomputeModes'], ...
                    ['%s cannot require both INTERVAL and PROB2 compact ' ...
                     'dose precompute. Split them into independent ' ...
                     'plans.'],context);
            end
        end

        function merged = mergeDefaults(value,defaults)
            merged = value;
            fields = fieldnames(defaults);
            for i = 1:numel(fields)
                fieldName = fields{i};
                if ~isfield(merged,fieldName) || isempty(merged.(fieldName))
                    merged.(fieldName) = defaults.(fieldName);
                elseif isstruct(merged.(fieldName)) && ...
                        isstruct(defaults.(fieldName)) && ...
                        isscalar(merged.(fieldName)) && ...
                        isscalar(defaults.(fieldName))
                    merged.(fieldName) = ...
                        planWorkflow.config.RobustPlanConfig.mergeDefaults( ...
                        merged.(fieldName),defaults.(fieldName));
                end
            end
        end

        function value = optionalText(value,context)
            if ~(ischar(value) || (isstring(value) && isscalar(value)))
                error('planWorkflow:config:RobustPlanConfig:InvalidText', ...
                    '%s must be text.',context);
            end
            value = regexprep(strtrim(char(string(value))),'\s+',' ');
        end

        function value = pathText(value,context)
            if ~(ischar(value) || (isstring(value) && isscalar(value)))
                error('planWorkflow:config:RobustPlanConfig:InvalidText', ...
                    '%s must be text.',context);
            end
            value = strtrim(char(string(value)));
        end

        function value = requiredText(value,context)
            value = planWorkflow.config.RobustPlanConfig.optionalText( ...
                value,context);
            if isempty(value)
                error('planWorkflow:config:RobustPlanConfig:InvalidText', ...
                    '%s must be non-empty text.',context);
            end
        end

        function value = identifierText(value,context)
            value = planWorkflow.config.RobustPlanConfig.requiredText( ...
                value,context);
            if ~isvarname(value)
                error('planWorkflow:config:RobustPlanConfig:InvalidIdentifier', ...
                    '%s must be a valid MATLAB identifier.',context);
            end
        end

        function value = robustnessModeText(value,context)
            value = planWorkflow.config.RobustPlanConfig.requiredText( ...
                value,context);
            supported = ...
                planWorkflow.matRadCapabilitiesReader.supportedWorkflowRobustnessModes();
            if ~any(strcmp(value,supported))
                error('planWorkflow:config:RobustPlanConfig:UnknownStrategy', ...
                    'Unknown objective robustness mode "%s" in %s.', ...
                        value,context);
            end
        end

        function fields = requiredVariantFields(robustnessMode)
            fields = ...
                planWorkflow.config.RobustStrategySpec.variantParameterFields( ...
                robustnessMode);
        end

    end
end

function value = logicalScalar(value,context)
if ischar(value) || (isstring(value) && isscalar(value))
    switch lower(char(value))
        case {'true','1','yes','on'}
            value = true;
        case {'false','0','no','off'}
            value = false;
        otherwise
            error('planWorkflow:config:RobustPlanConfig:InvalidLogical', ...
                '%s must be scalar logical.',context);
    end
else
    value = logical(value);
end
if ~isscalar(value)
    error('planWorkflow:config:RobustPlanConfig:InvalidLogical', ...
        '%s must be scalar logical.',context);
end
end

function value = positiveIntegerScalar(value,context)
if ~(isnumeric(value) && isscalar(value) && isfinite(value) && ...
        value >= 1 && round(value) == value)
    error('planWorkflow:config:RobustPlanConfig:InvalidPositiveInteger', ...
        '%s must be a positive integer scalar.',context);
end
end

function value = positiveIntegerVector(value,context)
if ~(isnumeric(value) && isvector(value) && ~isempty(value) && ...
        all(isfinite(value(:))) && all(value(:) >= 1) && ...
        all(round(value(:)) == value(:)))
    error('planWorkflow:config:RobustPlanConfig:InvalidPositiveIntegerVector', ...
        '%s must be a numeric vector of positive integer scenario indices.', ...
        context);
end
value = value(:)';
end

function value = optionalNonnegativeIntegerScalar(value,context)
if isempty(value)
    value = [];
    return;
end
if ~(isnumeric(value) && isscalar(value) && isfinite(value) && ...
        value >= 0 && round(value) == value)
    error('planWorkflow:config:RobustPlanConfig:InvalidOptionalInteger', ...
        '%s must be empty or a non-negative integer scalar.',context);
end
end

function value = finiteNumericScalar(value,context)
if ~(isnumeric(value) && isscalar(value) && isfinite(value))
    error('planWorkflow:config:RobustPlanConfig:InvalidNumericScalar', ...
        '%s must be a finite numeric scalar.',context);
end
end

function value = nonnegativeNumericScalar(value,context)
value = finiteNumericScalar(value,context);
if value < 0
    error('planWorkflow:config:RobustPlanConfig:InvalidNumericScalar', ...
        '%s must be a non-negative numeric scalar.',context);
end
end
