classdef WorkflowContractValidator
    % WorkflowContractValidator Validates edited workflow contracts.

    methods (Static)
        function [template,runConfig] = validateAction(template,runConfig)
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.ensureReferencePlanLabel( ...
                runConfig);
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.alignRobustPlansWithTemplate( ...
                runConfig,template);
            runConfig.precompute = ...
                planWorkflow.config.RobustPlanConfig.normalizePrecompute( ...
                runConfig.precompute);
            runConfig = ...
                planWorkflow.plan.DoseQuantityResolver.applyDefaultToRunConfig( ...
                runConfig,false);
            if isfield(runConfig,'analysis') && isstruct(runConfig.analysis)
                runConfig.analysis = ...
                    planWorkflow.config.Analysis.normalize( ...
                    runConfig.analysis);
                endpointQuantity = ...
                    planWorkflow.plan.DoseQuantityResolver.visualFromRunConfig( ...
                    runConfig);
                planWorkflow.analysis.EndpointStructureContract.endpoints( ...
                    runConfig,endpointQuantity);
            end
            template = ...
                planWorkflow.config.WorkflowContractValidator.syncRobustObjectiveSetLabels( ...
                template,runConfig);
            planWorkflow.templates.PlanTemplate.validateEffectiveTemplate( ...
                template,runConfig);
            endpointQuantity = ...
                planWorkflow.plan.DoseQuantityResolver.visualFromRunConfig( ...
                runConfig);
            planWorkflow.analysis.EndpointStructureContract.validateTemplate( ...
                template,runConfig,endpointQuantity);
        end

        function runConfig = alignRobustPlansWithTemplate(runConfig,template)
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.ensureReferencePlanLabel( ...
                runConfig);
            robustObjectiveSets = ...
                planWorkflow.templates.PlanTemplate.robustObjectiveSets( ...
                template);
            existingPlans = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            if isempty(robustObjectiveSets)
                planWorkflow.config.WorkflowContractValidator.assertNoUnmatchedPlans( ...
                    existingPlans,false(1,numel(existingPlans)));
                runConfig.precompute.robustPlans = ...
                    planWorkflow.config.RobustPlanConfig.normalizePlans([]);
                return;
            end

            matchedPlans = false(1,numel(existingPlans));
            alignedPlans = repmat( ...
                planWorkflow.config.RobustPlanConfig.defaultPlan(), ...
                1,numel(robustObjectiveSets));
            for planIx = 1:numel(robustObjectiveSets)
                objectiveSet = robustObjectiveSets(planIx);
                [plan,matchedPlanIx] = ...
                    planWorkflow.config.WorkflowContractValidator.matchingRobustPlan( ...
                    existingPlans,objectiveSet);
                if matchedPlanIx ~= 0
                    matchedPlans(matchedPlanIx) = true;
                end
                if isempty(fieldnames(plan))
                    plan = ...
                        planWorkflow.config.RobustPlanPanelAdapter.defaultPlanFromRunConfig( ...
                        runConfig,objectiveSet);
                end
                plan.id = char(objectiveSet.id);
                if ~isfield(plan,'label') || isempty(plan.label)
                    plan.label = char(objectiveSet.label);
                else
                    plan.label = ...
                        planWorkflow.config.WorkflowContractValidator.normalizeRobustPlanLabel( ...
                        plan.label);
                end
                plan.objectiveSetName = char(objectiveSet.id);
                plan = ...
                    planWorkflow.config.RobustPlanPanelAdapter.completePlan( ...
                    plan,runConfig);
                alignedPlans(planIx) = plan;
            end
            planWorkflow.config.WorkflowContractValidator.assertNoUnmatchedPlans( ...
                existingPlans,matchedPlans);
            if ~isfield(runConfig,'precompute') || ...
                    ~isstruct(runConfig.precompute)
                runConfig.precompute = ...
                    planWorkflow.config.RobustPlanConfig.defaults();
            end
            runConfig.precompute.robustPlans = ...
                planWorkflow.config.RobustPlanConfig.normalizePlans( ...
                alignedPlans);
        end

        function runConfig = ensureReferencePlanLabel(runConfig)
            if ~isfield(runConfig,'precompute') || ...
                    ~isstruct(runConfig.precompute)
                runConfig.precompute = ...
                    planWorkflow.config.RobustPlanConfig.defaults();
            end
            if ~isfield(runConfig.precompute,'reference') || ...
                    ~isstruct(runConfig.precompute.reference)
                runConfig.precompute.reference = ...
                    planWorkflow.config.RobustPlanConfig.defaultReference();
            end
            runConfig.precompute.reference.label = ...
                planWorkflow.config.WorkflowContractValidator.normalizeReferencePlanLabel( ...
                runConfig.precompute.reference.label);
        end

        function template = syncRobustObjectiveSetLabels(template,runConfig)
            robustPlans = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            if isempty(robustPlans)
                return;
            end

            robustObjectiveSets = ...
                planWorkflow.templates.PlanTemplate.robustObjectiveSets( ...
                template);
            for planIx = 1:numel(robustPlans)
                objectiveSetName = ...
                    char(robustPlans(planIx).objectiveSetName);
                objectiveSetIx = ...
                    planWorkflow.config.WorkflowContractValidator.findRobustObjectiveSet( ...
                    robustObjectiveSets,objectiveSetName);
                if objectiveSetIx ~= 0
                    robustObjectiveSets(objectiveSetIx).label = ...
                        planWorkflow.config.WorkflowContractValidator.normalizeRobustPlanLabel( ...
                        robustPlans(planIx).label);
                end
            end
            template.objectiveSets.robustPlans = robustObjectiveSets;
        end

        function label = normalizeReferencePlanLabel(label)
            label = regexprep(strtrim(char(string(label))),'\s+',' ');
        end

        function label = normalizeRobustPlanLabel(label)
            label = regexprep(strtrim(char(string(label))),'\s+',' ');
            if isempty(label)
                error('planWorkflow:config:WorkflowContractValidator:InvalidPlanLabel', ...
                    'Plan label must be non-empty.');
            end
        end
    end

    methods (Static, Access = private)
        function [plan,planIx] = matchingRobustPlan(plans,objectiveSet)
            plan = struct();
            planIx = 0;
            objectiveSetId = char(objectiveSet.id);
            for candidateIx = 1:numel(plans)
                if isfield(plans(candidateIx),'objectiveSetName') && ...
                        strcmp(char(plans(candidateIx).objectiveSetName), ...
                        objectiveSetId)
                    plan = plans(candidateIx);
                    planIx = candidateIx;
                    return;
                end
                if isfield(plans(candidateIx),'id') && ...
                        strcmp(char(plans(candidateIx).id),objectiveSetId)
                    plan = plans(candidateIx);
                    planIx = candidateIx;
                    return;
                end
            end
        end

        function assertNoUnmatchedPlans(plans,matchedPlans)
            if isempty(plans)
                return;
            end
            unmatchedIx = find(~matchedPlans,1);
            if isempty(unmatchedIx)
                return;
            end
            plan = plans(unmatchedIx);
            planId = '<missing>';
            objectiveSetName = '<missing>';
            if isfield(plan,'id') && ~isempty(plan.id)
                planId = char(plan.id);
            end
            if isfield(plan,'objectiveSetName') && ...
                    ~isempty(plan.objectiveSetName)
                objectiveSetName = char(plan.objectiveSetName);
            end
            error(['planWorkflow:config:WorkflowContractValidator:' ...
                'UnmatchedRobustPlan'], ...
                ['Robust plan "%s" references objectiveSetName "%s", ' ...
                 'but the active template has no matching robust objective ' ...
                 'set. Update config.precompute.robustPlans.<planId> or ' ...
                 'the template objective set id explicitly.'], ...
                planId,objectiveSetName);
        end

        function objectiveSetIx = findRobustObjectiveSet( ...
                robustObjectiveSets,objectiveSetName)
            objectiveSetIx = 0;
            objectiveSetName = char(objectiveSetName);
            for candidateIx = 1:numel(robustObjectiveSets)
                if strcmp(char(robustObjectiveSets(candidateIx).id), ...
                        objectiveSetName)
                    objectiveSetIx = candidateIx;
                    return;
                end
            end
        end
    end
end
