classdef WorkflowContractValidator
    % WorkflowContractValidator Validates edited workflow contracts.

    methods (Static)
        function [template,runConfig] = validateAction(template,runConfig)
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.ensureReferencePlanLabel( ...
                runConfig);
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.alignReferenceWithTemplate( ...
                runConfig,template);
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.alignRobustPlansWithTemplate( ...
                runConfig,template);
            runConfig.precompute = ...
                planWorkflow.config.RobustPlanConfig.normalizePrecompute( ...
                runConfig.precompute);
            runConfig = ...
                planWorkflow.plan.DoseQuantityResolver.applyDefaultToRunConfig( ...
                runConfig,false);
            if isfield(runConfig,'analysis') && isstruct(runConfig.analysis)
                runConfig.analysis = ...
                    planWorkflow.config.Analysis.normalize( ...
                    runConfig.analysis);
                endpointQuantity = ...
                    planWorkflow.plan.DoseQuantityResolver.visualFromRunConfig( ...
                    runConfig);
                planWorkflow.analysis.EndpointStructureContract.endpoints( ...
                    runConfig,endpointQuantity);
            end
            template = ...
                planWorkflow.config.WorkflowContractValidator.syncRobustObjectiveSetLabels( ...
                template,runConfig);
            planWorkflow.templates.PlanTemplate.validateEffectiveTemplate( ...
                template,runConfig);
            endpointQuantity = ...
                planWorkflow.plan.DoseQuantityResolver.visualFromRunConfig( ...
                runConfig);
            planWorkflow.analysis.EndpointStructureContract.validateTemplate( ...
                template,runConfig,endpointQuantity);
        end

        function runConfig = alignRobustPlansWithTemplate(runConfig,template)
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.ensureReferencePlanLabel( ...
                runConfig);
            robustObjectiveSets = ...
                planWorkflow.templates.PlanTemplate.robustObjectiveSets( ...
                template);
            existingPlans = ...
                planWorkflow.config.WorkflowContractValidator.rawRobustPlansFromRunConfig( ...
                runConfig);
            if isempty(robustObjectiveSets)
                planWorkflow.config.WorkflowContractValidator.assertNoUnmatchedPlans( ...
                    existingPlans,false(1,numel(existingPlans)));
                runConfig.precompute.robustPlans = ...
                    planWorkflow.config.RobustPlanConfig.normalizePlans([]);
                return;
            end

            matchedPlans = false(1,numel(existingPlans));
            alignedPlans = repmat( ...
                planWorkflow.config.RobustPlanConfig.defaultPlan(), ...
                1,numel(robustObjectiveSets));
            robustnessContracts = repmat( ...
                planWorkflow.config.RobustPlanConfig.defaultRobustnessContract(), ...
                1,numel(robustObjectiveSets));
            for planIx = 1:numel(robustObjectiveSets)
                objectiveSet = robustObjectiveSets(planIx);
                robustnessContracts(planIx) = ...
                    planWorkflow.templates.ObjectiveRobustnessContract.forObjectiveSet( ...
                    objectiveSet);
                [plan,matchedPlanIx] = ...
                    planWorkflow.config.WorkflowContractValidator.matchingRobustPlan( ...
                    existingPlans,objectiveSet);
                if matchedPlanIx ~= 0
                    matchedPlans(matchedPlanIx) = true;
                end
                if isempty(fieldnames(plan))
                    plan = ...
                        planWorkflow.config.RobustPlanPanelAdapter.defaultPlanFromRunConfig( ...
                        runConfig,objectiveSet);
                end
                plan.id = char(objectiveSet.id);
                if ~isfield(plan,'label') || isempty(plan.label)
                    plan.label = char(objectiveSet.label);
                else
                    plan.label = ...
                        planWorkflow.config.WorkflowContractValidator.normalizeRobustPlanLabel( ...
                        plan.label);
                end
                plan.objectiveSetName = char(objectiveSet.id);
                plan = ...
                    planWorkflow.config.RobustPlanPanelAdapter.completePlan( ...
                    plan,runConfig,robustnessContracts(planIx));
                plan.variantsWithPenalties = ...
                    planWorkflow.templates.ObjectivePenaltyVariants.variantsWithPenalties( ...
                    objectiveSet,plan.variants,plan.robustnessMode);
                alignedPlans(planIx) = plan;
            end
            planWorkflow.config.WorkflowContractValidator.assertNoUnmatchedPlans( ...
                existingPlans,matchedPlans);
            if ~isfield(runConfig,'precompute') || ...
                    ~isstruct(runConfig.precompute)
                runConfig.precompute = ...
                    planWorkflow.config.RobustPlanConfig.defaults();
            end
            runConfig.precompute.robustPlans = ...
                planWorkflow.config.RobustPlanConfig.normalizePlans( ...
                alignedPlans,robustnessContracts);
        end

        function runConfig = alignReferenceWithTemplate(runConfig,template)
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.ensureReferencePlanLabel( ...
                runConfig);
            contract = ...
                planWorkflow.templates.ObjectiveRobustnessContract.forTemplateObjectiveSet( ...
                template,'reference');
            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            contractMode = char(contract.robustnessMode);
            currentMode = char(reference.robustnessMode);
            if ~strcmp(currentMode,contractMode)
                reference.robustnessOptions = ...
                    planWorkflow.config.RobustPlanConfig.defaultRobustnessOptions( ...
                    contractMode);
                reference.variants = ...
                    planWorkflow.config.RobustPlanConfig.defaultVariants( ...
                    contractMode);
            end
            reference.robustnessMode = contractMode;
            runConfig.precompute.reference = ...
                planWorkflow.config.RobustPlanConfig.normalizeReference( ...
                reference);
        end

        function runConfig = ensureReferencePlanLabel(runConfig)
            if ~isfield(runConfig,'precompute') || ...
                    ~isstruct(runConfig.precompute)
                runConfig.precompute = ...
                    planWorkflow.config.RobustPlanConfig.defaults();
            end
            if ~isfield(runConfig.precompute,'reference') || ...
                    ~isstruct(runConfig.precompute.reference)
                runConfig.precompute.reference = ...
                    planWorkflow.config.RobustPlanConfig.defaultReference();
            end
            runConfig.precompute.reference.label = ...
                planWorkflow.config.WorkflowContractValidator.normalizeReferencePlanLabel( ...
                runConfig.precompute.reference.label);
        end

        function template = syncRobustObjectiveSetLabels(template,runConfig)
            robustPlans = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            if isempty(robustPlans)
                return;
            end

            robustObjectiveSets = ...
                planWorkflow.templates.PlanTemplate.robustObjectiveSets( ...
                template);
            for planIx = 1:numel(robustPlans)
                objectiveSetName = ...
                    char(robustPlans(planIx).objectiveSetName);
                objectiveSetIx = ...
                    planWorkflow.config.WorkflowContractValidator.findRobustObjectiveSet( ...
                    robustObjectiveSets,objectiveSetName);
                if objectiveSetIx ~= 0
                    robustObjectiveSets(objectiveSetIx).label = ...
                        planWorkflow.config.WorkflowContractValidator.normalizeRobustPlanLabel( ...
                        robustPlans(planIx).label);
                end
            end
            template.objectiveSets.robustPlans = robustObjectiveSets;
        end

        function label = normalizeReferencePlanLabel(label)
            label = regexprep(strtrim(char(string(label))),'\s+',' ');
        end

        function label = normalizeRobustPlanLabel(label)
            label = regexprep(strtrim(char(string(label))),'\s+',' ');
            if isempty(label)
                error('planWorkflow:config:WorkflowContractValidator:InvalidPlanLabel', ...
                    'Plan label must be non-empty.');
            end
        end
    end

    methods (Static, Access = private)
        function plans = rawRobustPlansFromRunConfig(runConfig)
            plans = repmat( ...
                planWorkflow.config.RobustPlanConfig.defaultPlan(),1,0);
            if ~isstruct(runConfig) || ~isfield(runConfig,'precompute') || ...
                    ~isstruct(runConfig.precompute) || ...
                    ~isfield(runConfig.precompute,'robustPlans') || ...
                    isempty(runConfig.precompute.robustPlans)
                return;
            end

            rawPlans = runConfig.precompute.robustPlans;
            if planWorkflow.config.WorkflowContractValidator.isNamedPlanStruct( ...
                    rawPlans)
                ids = fieldnames(rawPlans);
                rawPlanCells = cell(1,numel(ids));
                planFields = {};
                for planIx = 1:numel(ids)
                    plan = rawPlans.(ids{planIx});
                    if isfield(plan,'id') && ~isempty(plan.id) && ...
                            ~strcmp(char(plan.id),ids{planIx})
                        error(['planWorkflow:config:RobustPlanConfig:' ...
                            'RobustPlanIdMismatch'], ...
                            ['config.precompute.robustPlans.%s.id must ' ...
                             'match the robust plan field name.'], ...
                            ids{planIx});
                    end
                    plan.id = ids{planIx};
                    if ~isfield(plan,'objectiveSetName') || ...
                            isempty(plan.objectiveSetName)
                        plan.objectiveSetName = ids{planIx};
                    end
                    rawPlanCells{planIx} = plan;
                    planFields = unique([planFields; fieldnames(plan)], ...
                        'stable'); %#ok<AGROW>
                end
                planTemplate = cell2struct( ...
                    cell(numel(planFields),1),planFields,1);
                plans = repmat(planTemplate,1,numel(ids));
                for planIx = 1:numel(ids)
                    plan = rawPlanCells{planIx};
                    fields = fieldnames(plan);
                    for fieldIx = 1:numel(fields)
                        plans(planIx).(fields{fieldIx}) = ...
                            plan.(fields{fieldIx});
                    end
                end
                return;
            end

            if ~isstruct(rawPlans)
                error('planWorkflow:config:RobustPlanConfig:InvalidRobustPlans', ...
                    'config.precompute.robustPlans must be a struct array.');
            end
            plans = rawPlans(:)';
        end

        function tf = isNamedPlanStruct(plans)
            tf = false;
            if ~isstruct(plans) || ~isscalar(plans)
                return;
            end
            planFields = fieldnames(plans);
            allowed = {'id','label','objectiveSetName','robustnessMode', ...
                'hasNominalObjectives','requiresNominalDij', ...
                'requiresScenarioDij','requiresIntervalDij', ...
                'requiresProb2Dij', ...
                'optimization4D','scenario','robustnessOptions', ...
                'dosePrecompute','variants','variantsWithPenalties'};
            if isempty(planFields) || all(ismember(planFields,allowed))
                return;
            end
            for i = 1:numel(planFields)
                fieldValue = plans.(planFields{i});
                if ~isvarname(planFields{i}) || ~isstruct(fieldValue) || ...
                        ~isscalar(fieldValue)
                    return;
                end
            end
            tf = true;
        end

        function [plan,planIx] = matchingRobustPlan(plans,objectiveSet)
            plan = struct();
            planIx = 0;
            objectiveSetId = char(objectiveSet.id);
            for candidateIx = 1:numel(plans)
                if isfield(plans(candidateIx),'objectiveSetName') && ...
                        strcmp(char(plans(candidateIx).objectiveSetName), ...
                        objectiveSetId)
                    plan = plans(candidateIx);
                    planIx = candidateIx;
                    return;
                end
                if isfield(plans(candidateIx),'id') && ...
                        strcmp(char(plans(candidateIx).id),objectiveSetId)
                    plan = plans(candidateIx);
                    planIx = candidateIx;
                    return;
                end
            end
        end

        function assertNoUnmatchedPlans(plans,matchedPlans)
            if isempty(plans)
                return;
            end
            unmatchedIx = find(~matchedPlans,1);
            if isempty(unmatchedIx)
                return;
            end
            plan = plans(unmatchedIx);
            planId = '<missing>';
            objectiveSetName = '<missing>';
            if isfield(plan,'id') && ~isempty(plan.id)
                planId = char(plan.id);
            end
            if isfield(plan,'objectiveSetName') && ...
                    ~isempty(plan.objectiveSetName)
                objectiveSetName = char(plan.objectiveSetName);
            end
            error(['planWorkflow:config:WorkflowContractValidator:' ...
                'UnmatchedRobustPlan'], ...
                ['Robust plan "%s" references objectiveSetName "%s", ' ...
                 'but the active template has no matching robust objective ' ...
                 'set. Update config.precompute.robustPlans.<planId> or ' ...
                 'the template objective set id explicitly.'], ...
                planId,objectiveSetName);
        end

        function objectiveSetIx = findRobustObjectiveSet( ...
                robustObjectiveSets,objectiveSetName)
            objectiveSetIx = 0;
            objectiveSetName = char(objectiveSetName);
            for candidateIx = 1:numel(robustObjectiveSets)
                if strcmp(char(robustObjectiveSets(candidateIx).id), ...
                        objectiveSetName)
                    objectiveSetIx = candidateIx;
                    return;
                end
            end
        end
    end
end
