classdef WorkflowParameterSchema
    % WorkflowParameterSchema Canonical editable workflow parameters.

    methods (Static)
        function specs = prepareSpecs()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.preparePatientImagesSpecs(), ...
                planWorkflow.config.WorkflowParameterSchema.prepareTemplateSpecs(), ...
                planWorkflow.config.WorkflowParameterSchema.prepareConfigSpecs()];
        end

        function specs = preparePlanParameterSpecs()
            specs = ...
                planWorkflow.config.WorkflowParameterSchema.preparePatientImagesSpecs();
        end

        function specs = preparePatientImagesSpecs()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.section( ...
                'Patient','patientSection') ...
                planWorkflow.config.WorkflowParameterSchema.preparePatientSpecs(), ...
                planWorkflow.config.WorkflowParameterSchema.section( ...
                'Images','imagesSection') ...
                planWorkflow.config.WorkflowParameterSchema.prepareImagesSpecs()];
        end

        function specs = preparePatientSpecs()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'description','description','char','','selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'caseID','caseID','char','','selection')];
        end

        function specs = prepareImagesSpecs()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'AcquisitionType','AcquisitionType','char','','selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'hlutFileName','hlutFileName','char', ...
                'hlutFileName','selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'dicomMetadata','dicomMetadata','structJson') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'resolution','resolution','resolution')];
        end

        function specs = prepareTemplateSpecs()
            specs = ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Template','plan_template','template', ...
                'plan_template','selection');
        end

        function specs = prepareConfigSpecs()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'patientDataPath','patientDataPath','char') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'runId','runId','char') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'rootPath','rootPath','char') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'outputRootPath','outputRootPath','char') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'cacheRootPath','cacheRootPath','char') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'n_cores','n_cores','numericScalar')];
        end

        function specs = prepareBeamSpecs()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'radiationMode','radiationMode','char','','selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Include other radiation types', ...
                'includeOtherRadiationModes','logical') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Machine','machine','char','','selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Radiobiological model','bioModel','char','','selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Optimization quantity','quantityOpt','char', ...
                'quantityOpt','selection') ...
                planWorkflow.config.WorkflowParameterSchema.displayParameter( ...
                'bioOpt','bioOpt','char','bioOpt') ...
                planWorkflow.config.WorkflowParameterSchema.displayParameter( ...
                'quantityVis','quantityVis','char','quantityVis') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Beam set','plan_beams','char','','selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Gantry angles','gantryAngles','numericVector') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Couch angles','couchAngles','numericVector')];
        end

        function fields = prepareFields()
            fields = planWorkflow.config.WorkflowParameterSchema.configFields( ...
                [planWorkflow.config.WorkflowParameterSchema.prepareSpecs(), ...
                 planWorkflow.config.WorkflowParameterSchema.prepareBeamSpecs()]);
            fields(strcmp(fields,'includeOtherRadiationModes')) = [];
            fields(strcmp(fields,'gantryAngles')) = [];
            fields(strcmp(fields,'couchAngles')) = [];
        end

        function specs = precomputeSpecs()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.precomputeTransversalSpecs(), ...
                planWorkflow.config.WorkflowParameterSchema.precomputeReferenceSpecs(), ...
                planWorkflow.config.WorkflowParameterSchema.precomputeRobustSpecs()];
        end

        function specs = precomputeTransversalSpecs()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.section( ...
                'Dose Calculation','doseCalculationSection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Bixel width','bixelWidth','numericScalar','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'doseResolution','doseResolution','resolution', ...
                'doseResolution') ...
                planWorkflow.config.WorkflowParameterSchema.section( ...
                'Cache','cacheSection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'useCache','useCache','logical','useCache') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'writeCache','writeCache','logical','writeCache')];
        end

        function specs = precomputeReferenceSpecs()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Plan label','reference_label','char', ...
                'referencePlanLabel') ...
                planWorkflow.config.WorkflowParameterSchema.robustnessStrategySpecs( ...
                'reference') ...
                planWorkflow.config.WorkflowParameterSchema.robustnessParameterSpecs( ...
                'reference') ...
                planWorkflow.config.WorkflowParameterSchema.scenarioSpecs( ...
                'reference')];
        end

        function specs = precomputeRobustSpecs()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Plan label','label','char','planLabel') ...
                planWorkflow.config.WorkflowParameterSchema.section( ...
                'Objective robustness','robustnessSection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'robustness','robustness','char','robustness', ...
                'selection') ...
                planWorkflow.config.WorkflowParameterSchema.robustnessParameterSpecs( ...
                '') ...
                planWorkflow.config.WorkflowParameterSchema.scenarioSpecs('')];
        end

        function specs = robustnessStrategySpecs(prefix)
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.section( ...
                'Robustness strategy','robustnessSection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'robustness', ...
                planWorkflow.config.WorkflowParameterSchema.prefixedField( ...
                prefix,'robustness'),'char','robustness','selection')];
        end

        function specs = robustnessParameterSpecs(prefix)
            specs = planWorkflow.config.WorkflowParameterSchema.section( ...
                'Robustness Parameters','robustnessParameterSection');
            parameterSpecs = ...
                planWorkflow.config.RobustStrategySpec.allParameterSpecs();
            for specIx = 1:numel(parameterSpecs)
                fieldName = parameterSpecs(specIx).name;
                specs(end + 1) = ...
                    planWorkflow.config.WorkflowParameterSchema.parameter( ...
                    parameterSpecs(specIx).label, ...
                    planWorkflow.config.WorkflowParameterSchema.prefixedField( ...
                    prefix,fieldName),parameterSpecs(specIx).type, ...
                    fieldName, ...
                    planWorkflow.config.WorkflowParameterSchema.controlKindFromSpec( ...
                    parameterSpecs(specIx))); %#ok<AGROW>
            end
        end

        function specs = scenarioSpecs(prefix)
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.section( ...
                'Scenario mode','scenarioModeSection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'scen_mode', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'scen_mode'),'char','scen_mode','selection') ...
                planWorkflow.config.WorkflowParameterSchema.section( ...
                'Scenario components','scenarioSelectionSection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'CT scenarios', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'ctActive'),'logical','ctActive') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Setup uncertainty', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'setupActive'),'logical','setupActive') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Range uncertainty', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'rangeActive'),'logical','rangeActive') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Gantry angle uncertainty', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'gantryActive'),'logical','gantryActive') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Couch angle uncertainty', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'couchActive'),'logical','couchActive') ...
                planWorkflow.config.WorkflowParameterSchema.section( ...
                'Scenario parameters','scenarioParameterSection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Reference CT scenario', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'ctReferenceScenId'), ...
                'numericScalar','ctReferenceScenId') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'CT scenario probabilities', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'ctScenProb'), ...
                'numericVectorAllowEmpty','ctScenProb') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'shiftSD', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'shiftSD'),'numericVector','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'rangeAbsSD', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'rangeAbsSD'),'numericScalar','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'rangeRelSD', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'rangeRelSD'),'numericScalar','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'gantryAngleSD', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'gantryAngleSD'),'numericScalar', ...
                'gantryAngleSD') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'couchAngleSD', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'couchAngleSD'),'numericScalar', ...
                'couchAngleSD') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'wcSigma', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'wcSigma'),'numericScalar','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'numOfRangeGridPoints', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'numOfRangeGridPoints'),'numericScalar','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'size', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'random_size'),'numericScalar','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'randomSeed', ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'randomSeed'),'numericScalarAllowEmpty', ...
                'randomSeed')];
        end

        function specs = dosePullingSpecs()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Channel 1','dose_pulling1','logical','dose_pulling1') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Targets','dose_pulling1_target','cellstr', ...
                'dose_pulling1_target') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Criteria','dose_pulling1_criteria','cellstr', ...
                'dose_pulling1_criteria') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Limit','dose_pulling1_limit','numericVector', ...
                'dose_pulling1_limit') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Start','dose_pulling1_start','numericScalar', ...
                'dose_pulling1_start') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Channel 2','dose_pulling2','logical','dose_pulling2') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Targets','dose_pulling2_target','cellstr', ...
                'dose_pulling2_target') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Criteria','dose_pulling2_criteria','char', ...
                'dose_pulling2_criteria') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Limit','dose_pulling2_limit','numericScalar', ...
                'dose_pulling2_limit') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Start','dose_pulling2_start','numericScalar', ...
                'dose_pulling2_start') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Max iterations','dose_pulling_max_iter','numericScalar', ...
                'dose_pulling_max_iter') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Strategy','dose_pulling_strategy','char', ...
                'dose_pulling_strategy','selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Search schedule','dose_pulling_search_schedule', ...
                'char','dose_pulling_search_schedule','selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Local window','dose_pulling_local_window', ...
                'numericScalar','dose_pulling_local_window') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Patience','dose_pulling_patience','numericScalar', ...
                'dose_pulling_patience') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Target tolerance','dose_pulling_target_tol', ...
                'numericScalar','dose_pulling_target_tol') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Selection policy','dose_pulling_selection_policy', ...
                'char','dose_pulling_selection_policy','selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Target weight','dose_pulling_target_weight', ...
                'numericScalar','dose_pulling_target_weight') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'OAR weight','dose_pulling_oar_weight', ...
                'numericScalar','dose_pulling_oar_weight') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Step weight','dose_pulling_step_weight', ...
                'numericScalar','dose_pulling_step_weight') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Max Vmax %','dose_pulling_max_vmax_percent', ...
                'numericScalar','dose_pulling_max_vmax_percent') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Warm start','dose_pulling_use_warm_start', ...
                'logical','dose_pulling_use_warm_start')];
        end

        function specs = optimizeSpecs()
            specs = planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'optimizer','optimizer','char','','selection');
        end

        function specs = samplingSpecs()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'Link case to optimization', ...
                'sampling_linkToOptimization','logical', ...
                'sampling_linkToOptimization') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'caseID','sampling_caseID','char','','selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'AcquisitionType','sampling_AcquisitionType','char','', ...
                'selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'dicomMetadata','sampling_dicomMetadata','structJson','') ...
                planWorkflow.config.WorkflowParameterSchema.scenarioSpecs( ...
                'sampling')];
        end

        function specs = analysisSpecs()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'evaluationMode','evaluationMode','char','','selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'doseWindow','doseWindow','numericVectorAllowEmpty','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'doseWindowDvh','doseWindowDvh', ...
                'numericVectorAllowEmpty','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'doseWindowUncertainty','doseWindowUncertainty', ...
                'numericVectorAllowEmpty','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'doseWindowRelativeUncertainty1', ...
                'doseWindowRelativeUncertainty1', ...
                'numericVectorAllowEmpty','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'doseWindowRelativeUncertainty2', ...
                'doseWindowRelativeUncertainty2', ...
                'numericVectorAllowEmpty','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'doseWindowUvh','doseWindowUvh', ...
                'numericVectorAllowEmpty','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'gammaWindow','gammaWindow','numericVector','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'gammaCriteria','gammaCriteria','numericVector','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'robustnessCriteria','robustnessCriteria', ...
                'numericVector','') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'robustnessTargetMode','robustnessTargetMode','char', ...
                'robustnessTargetMode','selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'robustnessTargets','robustnessTargets','multiSelect', ...
                'robustnessTargets') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'endpointsFile','endpointsFile','char','endpointsFile', ...
                'selection') ...
                planWorkflow.config.WorkflowParameterSchema.parameter( ...
                'endpoints','endpoints','structArrayJson','')];
        end

        function fields = precomputeExportFields(runConfig)
            fields = planWorkflow.config.StageConfigSchema.presetFields( ...
                'precompute');
            robustPlans = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            if isempty(robustPlans)
                fields(strcmp(fields,'robustPlans')) = [];
            end
        end

        function fields = precomputeTransversalVisibleFields()
            fields = planWorkflow.config.WorkflowParameterSchema.fields( ...
                planWorkflow.config.WorkflowParameterSchema.precomputeTransversalSpecs());
        end

        function fields = precomputeTransversalParameterFields()
            fields = ...
                planWorkflow.config.WorkflowParameterSchema.parameterFieldsOnly( ...
                planWorkflow.config.WorkflowParameterSchema.precomputeTransversalVisibleFields());
        end

        function fields = precomputeReferenceVisibleFields( ...
                robustness,scenMode,dimensionConfig,KMode,radiusMode)
            if nargin < 1 || isempty(robustness)
                robustness = 'none';
            end
            if nargin < 2 || isempty(scenMode)
                scenMode = 'nomScen';
            end
            if nargin < 3 || isempty(dimensionConfig)
                dimensionConfig = struct();
            end
            if nargin < 4 || isempty(KMode)
                KMode = 'dynamic';
            end
            if nargin < 5 || isempty(radiusMode)
                radiusMode = 'std';
            end

            fields = {'reference_label','robustnessSection', ...
                'reference_robustness'};
            robustnessFields = ...
                planWorkflow.config.WorkflowParameterSchema.robustnessVisibleFields( ...
                robustness,'reference',KMode,radiusMode);
            if ~isempty(robustnessFields)
                fields = [fields,{'robustnessParameterSection'}, ...
                    robustnessFields];
            end
            fields = [fields, ...
                planWorkflow.config.WorkflowParameterSchema.prefixedScenarioVisibleFields( ...
                scenMode,'reference','reference_wcSigma', ...
                'reference_random_size',dimensionConfig)];
            fields = unique(fields,'stable');
        end

        function fields = precomputeReferenceParameterFields( ...
                robustness,scenMode,dimensionConfig,KMode,radiusMode)
            if nargin < 1
                robustness = [];
            end
            if nargin < 2
                scenMode = [];
            end
            if nargin < 3
                dimensionConfig = struct();
            end
            if nargin < 4
                KMode = [];
            end
            if nargin < 5
                radiusMode = [];
            end
            fields = ...
                planWorkflow.config.WorkflowParameterSchema.parameterFieldsOnly( ...
                planWorkflow.config.WorkflowParameterSchema.precomputeReferenceVisibleFields( ...
                robustness,scenMode,dimensionConfig,KMode,radiusMode));
        end

        function fields = precomputeRobustVisibleFields( ...
                robustness,scenMode,dimensionConfig,KMode,radiusMode)
            if nargin < 3 || isempty(dimensionConfig)
                dimensionConfig = struct();
            end
            if nargin < 4 || isempty(KMode)
                KMode = 'dynamic';
            end
            if nargin < 5 || isempty(radiusMode)
                radiusMode = 'std';
            end

            fields = {'label','robustnessSection','robustness'};
            robustnessFields = ...
                planWorkflow.config.WorkflowParameterSchema.robustnessVisibleFields( ...
                robustness,'',KMode,radiusMode);
            if ~isempty(robustnessFields)
                fields = [fields,{'robustnessParameterSection'}, ...
                    robustnessFields];
            end
            fields = [fields, ...
                planWorkflow.config.WorkflowParameterSchema.prefixedScenarioVisibleFields( ...
                scenMode,'','wcSigma','random_size',dimensionConfig)];
            fields = unique(fields,'stable');
        end

        function fields = precomputeRobustParameterFields( ...
                robustness,scenMode,dimensionConfig,KMode,radiusMode)
            if nargin < 1
                robustness = [];
            end
            if nargin < 2
                scenMode = [];
            end
            if nargin < 3
                dimensionConfig = struct();
            end
            if nargin < 4
                KMode = [];
            end
            if nargin < 5
                radiusMode = [];
            end
            fields = ...
                planWorkflow.config.WorkflowParameterSchema.parameterFieldsOnly( ...
                planWorkflow.config.WorkflowParameterSchema.precomputeRobustVisibleFields( ...
                robustness,scenMode,dimensionConfig,KMode,radiusMode));
        end

        function fields = dosePullingVisibleFields( ...
                channel1Enabled,channel2Enabled,strategy,selectionPolicy)
            if nargin < 3 || isempty(strategy)
                strategy = 'heuristicMultiObjective';
            end
            if nargin < 4 || isempty(selectionPolicy)
                selectionPolicy = 'normalizedKnee';
            end

            fields = {'dose_pulling1'};
            if logical(channel1Enabled)
                fields = [fields,{'dose_pulling1_target', ...
                    'dose_pulling1_criteria','dose_pulling1_limit', ...
                    'dose_pulling1_start'}];
            end

            fields = [fields,{'dose_pulling2'}];
            if logical(channel2Enabled)
                fields = [fields,{'dose_pulling2_target', ...
                    'dose_pulling2_criteria','dose_pulling2_limit', ...
                    'dose_pulling2_start'}];
            end
            fields = [fields,{'dose_pulling_max_iter', ...
                'dose_pulling_strategy'}];
            if strcmpi(char(strategy),'heuristicMultiObjective')
                fields = [fields,{'dose_pulling_search_schedule', ...
                    'dose_pulling_local_window','dose_pulling_patience', ...
                    'dose_pulling_target_tol', ...
                    'dose_pulling_selection_policy'}];
                if strcmpi(char(selectionPolicy),'weightedSum')
                    fields = [fields,{'dose_pulling_target_weight', ...
                        'dose_pulling_oar_weight', ...
                        'dose_pulling_step_weight'}];
                end
                fields = [fields,{'dose_pulling_max_vmax_percent', ...
                    'dose_pulling_use_warm_start'}];
            end
        end

        function fields = samplingVisibleFields( ...
                linkToOptimization,scenMode,dimensionConfig)
            if nargin < 3 || isempty(dimensionConfig)
                dimensionConfig = struct();
            end
            fields = {'sampling_linkToOptimization'};
            if ~logical(linkToOptimization)
                fields = [fields,{'sampling_caseID', ...
                    'sampling_AcquisitionType', ...
                    'sampling_dicomMetadata'}];
            end
            fields = [fields, ...
                planWorkflow.config.WorkflowParameterSchema.prefixedScenarioVisibleFields( ...
                scenMode,'sampling','sampling_wcSigma','sampling_size', ...
                dimensionConfig)];
            fields = unique(fields,'stable');
        end

        function fields = samplingParameterFields( ...
                linkToOptimization,scenMode,dimensionConfig)
            if nargin < 3
                dimensionConfig = struct();
            end
            fields = ...
                planWorkflow.config.WorkflowParameterSchema.parameterFieldsOnly( ...
                planWorkflow.config.WorkflowParameterSchema.samplingVisibleFields( ...
                linkToOptimization,scenMode,dimensionConfig));
        end

        function fields = analysisVisibleFields(targetMode)
            fields = planWorkflow.config.WorkflowParameterSchema.fields( ...
                planWorkflow.config.WorkflowParameterSchema.analysisSpecs());
            if strcmp(char(targetMode),'all')
                fields(strcmp(fields,'robustnessTargets')) = [];
            end
        end

        function value = parseValue(text,type,fieldName)
            switch char(type)
                case 'char'
                    value = char(string(text));
                case 'logical'
                    value = ...
                        planWorkflow.config.WorkflowParameterSchema.parseLogical( ...
                        text,fieldName);
                case 'numericScalar'
                    value = ...
                        planWorkflow.config.WorkflowParameterSchema.parseNumericScalar( ...
                        text,fieldName);
                case 'numericScalarAllowEmpty'
                    value = ...
                        planWorkflow.config.WorkflowParameterSchema.parseNumericScalarAllowEmpty( ...
                        text,fieldName);
                case 'numericVector'
                    value = ...
                        planWorkflow.config.WorkflowParameterSchema.parseNumericVector( ...
                        text,fieldName);
                case 'numericVectorAllowEmpty'
                    value = ...
                        planWorkflow.config.WorkflowParameterSchema.parseNumericVectorAllowEmpty( ...
                        text,fieldName);
                case 'resolution'
                    value = ...
                        planWorkflow.config.WorkflowParameterSchema.parseResolution( ...
                        text);
                case 'cellstr'
                    value = ...
                        planWorkflow.config.WorkflowParameterSchema.parseCellText( ...
                        text,fieldName);
                case {'cellstrAllowEmpty','multiSelect'}
                    value = ...
                        planWorkflow.config.WorkflowParameterSchema.parseCellTextAllowEmpty( ...
                        text);
                case 'structJson'
                    value = ...
                        planWorkflow.config.WorkflowParameterSchema.parseStructJson( ...
                        text,fieldName);
                case 'structArrayJson'
                    value = ...
                        planWorkflow.config.WorkflowParameterSchema.parseStructArrayJson( ...
                        text,fieldName);
                otherwise
                    error(['planWorkflow:config:WorkflowParameterSchema:' ...
                        'UnknownConfigType'], ...
                        'Unsupported config value type "%s".',char(type));
            end
        end

        function fields = robustnessVisibleFields( ...
                robustness,prefix,KMode,radiusMode)
            if nargin < 2
                prefix = '';
            end
            if nargin < 3 || isempty(KMode)
                KMode = 'dynamic';
            end
            if nargin < 4 || isempty(radiusMode)
                radiusMode = 'std';
            end
            fields = ...
                planWorkflow.config.RobustStrategySpec.visibleParameterFields( ...
                robustness,struct('KMode',KMode,'radiusMode',radiusMode));
            for i = 1:numel(fields)
                fields{i} = ...
                    planWorkflow.config.WorkflowParameterSchema.prefixedField( ...
                    prefix,fields{i});
            end
        end

        function fields = scenarioVisibleFields(scenMode,wcSigmaField, ...
                sampleSizeField,dimensionConfig)
            if nargin < 4
                dimensionConfig = struct();
            end
            fields = planWorkflow.config.ScenarioSpec.visiblePanelFields( ...
                scenMode,'',dimensionConfig);
            fields(strcmp(fields,'wcSigma')) = {wcSigmaField};
            fields(strcmp(fields,'random_size')) = {sampleSizeField};
        end

        function fields = prefixedScenarioVisibleFields(scenMode,prefix, ...
                wcSigmaField,sampleSizeField,dimensionConfig)
            if nargin < 5
                dimensionConfig = struct();
            end
            dimensionConfig = ...
                planWorkflow.config.WorkflowParameterSchema.dimensionConfig( ...
                prefix,dimensionConfig);
            fields = planWorkflow.config.ScenarioSpec.visiblePanelFields( ...
                scenMode,prefix,dimensionConfig);
            fields(strcmp(fields, ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'wcSigma'))) = {wcSigmaField};
            fields(strcmp(fields, ...
                planWorkflow.config.ScenarioSpec.panelFieldName( ...
                prefix,'random_size'))) = {sampleSizeField};
        end

        function fields = parameterFieldsOnly(fields)
            sectionFields = ...
                planWorkflow.config.WorkflowParameterSchema.sectionFields();
            fields = fields(~ismember(fields,sectionFields));
        end

        function fields = parameterSectionFields()
            fields = planWorkflow.config.WorkflowParameterSchema.sectionFields();
        end

        function fields = fields(specs)
            fields = {specs.field};
        end

        function fields = configFields(specs)
            fields = {};
            for specIx = 1:numel(specs)
                if strcmp(specs(specIx).type,'section')
                    continue;
                end
                if isfield(specs(specIx),'isConfigField') && ...
                        ~specs(specIx).isConfigField
                    continue;
                end
                fields{end + 1} = specs(specIx).field; %#ok<AGROW>
            end
        end
    end

    methods (Static, Access = private)
        function values = parseVector(text)
            text = char(string(text));
            text = regexprep(text,'[\[\],;]',' ');
            values = sscanf(text,'%f')';
        end

        function values = parseResolution(text)
            values = ...
                planWorkflow.config.WorkflowParameterSchema.parseVector(text);
            if numel(values) ~= 3 || any(values <= 0)
                error(['planWorkflow:config:WorkflowParameterSchema:' ...
                    'InvalidDoseResolution'], ...
                    'Resolution must contain three positive values.');
            end
        end

        function values = parseNumericVector(text,fieldName)
            values = ...
                planWorkflow.config.WorkflowParameterSchema.parseVector(text);
            if isempty(values) || any(~isfinite(values))
                error(['planWorkflow:config:WorkflowParameterSchema:' ...
                    'InvalidNumericConfig'], ...
                    'runConfig.%s must contain finite numeric values.', ...
                    fieldName);
            end
        end

        function values = parseNumericVectorAllowEmpty(text,fieldName)
            text = strtrim(char(string(text)));
            if isempty(text) || strcmp(text,'[]')
                values = [];
                return;
            end
            values = ...
                planWorkflow.config.WorkflowParameterSchema.parseNumericVector( ...
                text,fieldName);
        end

        function value = parseNumericScalar(text,fieldName)
            values = ...
                planWorkflow.config.WorkflowParameterSchema.parseNumericVector( ...
                text,fieldName);
            if numel(values) ~= 1
                error(['planWorkflow:config:WorkflowParameterSchema:' ...
                    'InvalidNumericConfig'], ...
                    'runConfig.%s must be a finite numeric scalar.', ...
                    fieldName);
            end
            value = values;
        end

        function value = parseNumericScalarAllowEmpty(text,fieldName)
            text = strtrim(char(string(text)));
            if isempty(text) || strcmp(text,'[]')
                value = [];
                return;
            end
            value = ...
                planWorkflow.config.WorkflowParameterSchema.parseNumericScalar( ...
                text,fieldName);
        end

        function value = parseLogical(text,fieldName)
            text = lower(strtrim(char(string(text))));
            switch text
                case {'true','1','yes','on'}
                    value = true;
                case {'false','0','no','off'}
                    value = false;
                otherwise
                    error(['planWorkflow:config:WorkflowParameterSchema:' ...
                        'InvalidLogicalConfig'], ...
                        ['runConfig.%s must be true/false, 1/0, ' ...
                         'yes/no, or on/off.'],fieldName);
            end
        end

        function values = parseCellText(text,fieldName)
            text = regexprep(char(string(text)),'[\{\}\[\]''"]','');
            tokens = regexp(text,'[,;]','split');
            tokens = strtrim(tokens);
            values = tokens(~cellfun('isempty',tokens));
            if isempty(values)
                error(['planWorkflow:config:WorkflowParameterSchema:' ...
                    'InvalidCellstrConfig'], ...
                    'runConfig.%s must contain at least one value.', ...
                    fieldName);
            end
        end

        function values = parseCellTextAllowEmpty(text)
            text = strtrim(char(string(text)));
            if isempty(text) || strcmp(text,'[]')
                values = [];
            else
                values = ...
                    planWorkflow.config.WorkflowParameterSchema.parseCellText( ...
                    text,'analysis.robustnessTargets');
            end
        end

        function value = parseStructJson(text,fieldName)
            text = strtrim(char(string(text)));
            if isempty(text) || strcmp(text,'{}')
                value = struct();
                return;
            end
            try
                value = jsondecode(text);
            catch ME
                error(['planWorkflow:config:WorkflowParameterSchema:' ...
                    'InvalidStructJson'], ...
                    'runConfig.%s must be valid JSON: %s', ...
                    fieldName,ME.message);
            end
            if isempty(value)
                value = struct();
            end
            if ~isstruct(value) || ~isscalar(value)
                error(['planWorkflow:config:WorkflowParameterSchema:' ...
                    'InvalidStructJson'], ...
                    'runConfig.%s must decode to a scalar struct.', ...
                    fieldName);
            end
        end

        function value = parseStructArrayJson(text,fieldName)
            text = strtrim(char(string(text)));
            if isempty(text) || strcmp(text,'[]')
                value = struct([]);
                return;
            end
            try
                value = jsondecode(text);
            catch ME
                error(['planWorkflow:config:WorkflowParameterSchema:' ...
                    'InvalidStructJson'], ...
                    'runConfig.%s must be valid JSON: %s', ...
                    fieldName,ME.message);
            end
            if isempty(value)
                value = struct([]);
            end
            if ~isstruct(value)
                error(['planWorkflow:config:WorkflowParameterSchema:' ...
                    'InvalidStructJson'], ...
                    'runConfig.%s must decode to a struct or struct array.', ...
                    fieldName);
            end
        end

        function spec = parameter(name,field,type,helpKey,controlKind, ...
                optionsKey,isConfigField)
            if nargin < 4
                helpKey = '';
            end
            if nargin < 5 || isempty(controlKind)
                controlKind = ...
                    planWorkflow.config.WorkflowParameterSchema.defaultControlKind( ...
                    type);
            end
            if nargin < 6 || isempty(optionsKey)
                optionsKey = field;
            end
            if nargin < 7 || isempty(isConfigField)
                isConfigField = true;
            end
            spec = struct('name',name,'field',field,'type',type, ...
                'helpKey',helpKey,'controlKind',controlKind, ...
                'optionsKey',optionsKey, ...
                'isConfigField',logical(isConfigField));
        end

        function spec = displayParameter(name,field,type,helpKey)
            if nargin < 4
                helpKey = '';
            end
            spec = planWorkflow.config.WorkflowParameterSchema.parameter( ...
                name,field,type,helpKey,'readOnly','',false);
        end

        function spec = section(name,field)
            spec = planWorkflow.config.WorkflowParameterSchema.parameter( ...
                name,field,'section','','section');
        end

        function controlKind = controlKindFromSpec(spec)
            controlKind = ...
                planWorkflow.config.WorkflowParameterSchema.defaultControlKind( ...
                spec.type);
            if isfield(spec,'optionValues') && ~isempty(spec.optionValues)
                controlKind = 'selection';
            end
        end

        function controlKind = defaultControlKind(type)
            switch char(type)
                case 'section'
                    controlKind = 'section';
                case 'logical'
                    controlKind = 'checkbox';
                case 'multiSelect'
                    controlKind = 'multiSelect';
                otherwise
                    controlKind = 'edit';
            end
        end

        function field = prefixedField(prefix,fieldName)
            if isempty(prefix)
                field = fieldName;
            else
                field = [char(prefix) '_' char(fieldName)];
            end
        end

        function fields = sectionFields()
            specs = [ ...
                planWorkflow.config.WorkflowParameterSchema.prepareSpecs(), ...
                planWorkflow.config.WorkflowParameterSchema.precomputeSpecs(), ...
                planWorkflow.config.WorkflowParameterSchema.dosePullingSpecs(), ...
                planWorkflow.config.WorkflowParameterSchema.optimizeSpecs(), ...
                planWorkflow.config.WorkflowParameterSchema.samplingSpecs(), ...
                planWorkflow.config.WorkflowParameterSchema.analysisSpecs()];
            isSection = strcmp({specs.type},'section');
            fields = unique({specs(isSection).field},'stable');
        end

        function output = dimensionConfig(prefix,input)
            output = struct();
            if nargin < 2 || ~isstruct(input)
                return;
            end
            fields = [{'ctActive','ctReferenceScenId'}, ...
                planWorkflow.scenario.dimensionActiveFields()];
            for i = 1:numel(fields)
                fieldName = fields{i};
                if isfield(input,fieldName)
                    output.(fieldName) = input.(fieldName);
                    continue;
                end
                prefixed = ...
                    planWorkflow.config.ScenarioSpec.panelFieldName( ...
                    prefix,fieldName);
                if isfield(input,prefixed)
                    output.(fieldName) = input.(prefixed);
                end
            end
        end
    end
end
