classdef DosePullingMetrics
    % DosePullingMetrics Computes robust dose-pulling quality metrics.

    methods (Static)
        function metrics = robust(runConfig,cst,pln,resultGUI, ...
                ctScenProb,iteration,robustData)
            if nargin < 6 || isempty(iteration)
                iteration = 0;
            end
            if planWorkflow.precompute.DosePullingMetrics.requiresIntervalDij( ...
                    robustData)
                metrics = ...
                    planWorkflow.precompute.DosePullingMetrics.intervalMetrics( ...
                    runConfig,cst,pln,resultGUI,robustData,iteration);
                return;
            end

            targetNames = ...
                planWorkflow.precompute.DosePullingUtils.asCellstr( ...
                runConfig.dose_pulling2_target);
            criteria = ...
                planWorkflow.precompute.DosePullingUtils.expandCellToCount( ...
                runConfig.dose_pulling1_criteria,numel(targetNames), ...
                'dose_pulling1_criteria');
            scenProb = matRad_getScenProb(pln,ctScenProb);
            scenarioValues = zeros(pln.multScen.totNumScen,numel(criteria));

            for scenIt = 1:pln.multScen.totNumScen
                doseField = [pln.bioParam.quantityVis '_' num2str(scenIt)];
                qi = matRad_calcQualityIndicators(cst,pln, ...
                    resultGUI.(doseField),[],[]);
                targetIx = ...
                    planWorkflow.precompute.DosePullingUtils.findQiTargets( ...
                    qi,targetNames);
                for targetIt = 1:numel(criteria)
                    scenarioValues(scenIt,targetIt) = ...
                        qi(targetIx(targetIt)).(criteria{targetIt});
                end
            end

            metrics = ...
                planWorkflow.precompute.DosePullingMetrics.metricsStruct( ...
                runConfig,iteration,targetNames,criteria, ...
                sum(scenarioValues .* scenProb(:),1), ...
                min(scenarioValues,[],1));
        end

        function values = selectRobustCriteria(runConfig,metrics)
            switch runConfig.dose_pulling2_criteria
                case 'meanQiTarget'
                    values = metrics.meanQiTarget;
                case 'minQiTarget'
                    values = metrics.minQiTarget;
                otherwise
                    error('planWorkflow:precompute:DosePulling:UnknownCriteria', ...
                        'Unknown dose_pulling2_criteria "%s".', ...
                        runConfig.dose_pulling2_criteria);
            end
        end
    end

    methods (Static, Access = private)
        function metrics = intervalMetrics(runConfig,cst,pln,resultGUI, ...
                robustData,iteration)
            targetNames = ...
                planWorkflow.precompute.DosePullingUtils.asCellstr( ...
                runConfig.dose_pulling2_target);
            criteria = ...
                planWorkflow.precompute.DosePullingUtils.expandCellToCount( ...
                runConfig.dose_pulling1_criteria,numel(targetNames), ...
                'dose_pulling1_criteria');

            centerCube = ...
                planWorkflow.precompute.DosePullingMetrics.intervalDoseCube( ...
                runConfig,robustData,resultGUI.w,false);
            conservativeCube = ...
                planWorkflow.precompute.DosePullingMetrics.intervalDoseCube( ...
                runConfig,robustData,resultGUI.w,true);
            qiCenter = matRad_calcQualityIndicators(cst,pln,centerCube,[],[]);
            qiConservative = matRad_calcQualityIndicators(cst,pln, ...
                conservativeCube,[],[]);
            centerTargetIx = ...
                planWorkflow.precompute.DosePullingUtils.findQiTargets( ...
                qiCenter,targetNames);
            conservativeTargetIx = ...
                planWorkflow.precompute.DosePullingUtils.findQiTargets( ...
                qiConservative,targetNames);

            centerValues = zeros(1,numel(criteria));
            conservativeValues = zeros(1,numel(criteria));
            for targetIt = 1:numel(criteria)
                centerValues(targetIt) = ...
                    qiCenter(centerTargetIx(targetIt)).(criteria{targetIt});
                conservativeValues(targetIt) = ...
                    qiConservative(conservativeTargetIx(targetIt)).( ...
                    criteria{targetIt});
            end

            metrics = ...
                planWorkflow.precompute.DosePullingMetrics.metricsStruct( ...
                runConfig,iteration,targetNames,criteria,centerValues, ...
                conservativeValues);
        end

        function metrics = metricsStruct(runConfig,iteration,targetNames, ...
                criteria,meanValues,minValues)
            metrics = struct();
            metrics.step = 2;
            metrics.iteration = iteration;
            metrics.targetNames = targetNames;
            metrics.criteria = criteria;
            metrics.meanQiTarget = meanValues;
            metrics.minQiTarget = minValues;
            metrics.selectedCriterion = runConfig.dose_pulling2_criteria;
            metrics.selectedValues = ...
                planWorkflow.precompute.DosePullingMetrics.selectRobustCriteria( ...
                runConfig,metrics);
            metrics.limits = ...
                planWorkflow.precompute.DosePullingUtils.expandNumericToCount( ...
                runConfig.dose_pulling2_limit,numel(metrics.selectedValues), ...
                'dose_pulling2_limit');
            metrics.isSatisfied = all(metrics.selectedValues >= metrics.limits);
        end

        function doseCube = intervalDoseCube(runConfig,robustData,w, ...
                useConservativeTargetBound)
            doseVector = robustData.dij_interval.center*w;
            if useConservativeTargetBound
                targetRows = ...
                    planWorkflow.precompute.DosePullingMetrics.intervalTargetRows( ...
                    runConfig,robustData.cst,robustData.dij_interval);
                targetRows = targetRows(targetRows >= 1 & ...
                    targetRows <= numel(doseVector));
                if ~isempty(targetRows)
                    radiusMargin = ...
                        planWorkflow.precompute.DosePullingMetrics.intervalTargetMargin( ...
                        robustData.dij_interval,w,targetRows,doseVector);
                    doseVector(targetRows) = max( ...
                        doseVector(targetRows) - radiusMargin,0);
                end
            end
            doseCube = reshape(full(doseVector), ...
                robustData.dij_intervalContext.doseGrid.dimensions);
        end

        function rows = intervalTargetRows(runConfig,cst,dijInterval)
            targetNames = ...
                planWorkflow.precompute.DosePullingUtils.asCellstr( ...
                runConfig.dose_pulling2_target);
            rows = [];
            contourIx = 1;
            if isfield(dijInterval,'refScen') && ~isempty(dijInterval.refScen)
                contourIx = dijInterval.refScen;
            end
            for targetIt = 1:numel(targetNames)
                for cstIx = 1:size(cst,1)
                    if ~strcmp(cst{cstIx,2},targetNames{targetIt}) || ...
                            size(cst,2) < 4 || isempty(cst{cstIx,4})
                        continue;
                    end
                    contours = cst{cstIx,4};
                    if iscell(contours) && numel(contours) >= contourIx && ...
                            ~isempty(contours{contourIx})
                        rows = [rows; contours{contourIx}(:)]; %#ok<AGROW>
                    elseif iscell(contours) && ~isempty(contours{1})
                        rows = [rows; contours{1}(:)]; %#ok<AGROW>
                    elseif isnumeric(contours)
                        rows = [rows; contours(:)]; %#ok<AGROW>
                    end
                    break;
                end
            end
            rows = unique(rows(:),'stable');
        end

        function margin = intervalTargetMargin(dijInterval,w,targetRows, ...
                doseVector)
            radiusSquared = full(w' * dijInterval.radius * w - ...
                doseVector(targetRows)' * doseVector(targetRows));
            if radiusSquared < 0 && abs(radiusSquared) < 1e-10
                radiusSquared = 0;
            end
            margin = sqrt(max(radiusSquared,0) / max(1,numel(targetRows)));
        end

        function tf = requiresIntervalDij(robustData)
            tf = false;
            if isfield(robustData,'strategy') && ...
                    isa(robustData.strategy, ...
                    'planWorkflow.robustness.AbstractStrategy')
                tf = robustData.strategy.requiresIntervalDij();
                return;
            end
            if isfield(robustData,'planConfig') && ...
                    isfield(robustData.planConfig,'robustnessMode')
                tf = any(strcmp(char(robustData.planConfig.robustnessMode), ...
                    {'INTERVAL2','INTERVAL3'}));
            end
        end
    end
end
