classdef DosePulling
    % DosePulling Runs objective dose-pulling without Engine-shaped deps.

    methods (Static)
        function context = defaultContext(runConfig,logFn)
            context = planWorkflow.precompute.DosePulling.context( ...
                runConfig, ...
                @(dij,cst,pln,initialWeights) ...
                planWorkflow.precompute.DosePullingOptimizer.run( ...
                runConfig,dij,cst,pln,initialWeights), ...
                @(ct,cst,stf,pln,resultGUI,showFigures) ...
                planWorkflow.precompute.DosePullingAnalyzer.run( ...
                runConfig,ct,cst,stf,pln,resultGUI,showFigures), ...
                @(cst,pln,resultGUI,ctScenProb,iteration,robustData) ...
                planWorkflow.precompute.DosePullingMetrics.robust( ...
                runConfig,cst,pln,resultGUI,ctScenProb,iteration, ...
                robustData), ...
                @(metrics) ...
                planWorkflow.precompute.DosePullingPolicy.robustNeedsUpdate( ...
                runConfig,metrics), ...
                logFn);
        end

        function context = context(runConfig,optimizer,analyzer,metrics, ...
                policy,logger)
            context = struct();
            context.runConfig = runConfig;
            context.optimizer = ...
                planWorkflow.precompute.DosePulling.requireFunction( ...
                optimizer,'optimizer');
            context.analyzer = ...
                planWorkflow.precompute.DosePulling.requireFunction( ...
                analyzer,'analyzer');
            context.metrics = ...
                planWorkflow.precompute.DosePulling.requireFunction( ...
                metrics,'metrics');
            context.policy = ...
                planWorkflow.precompute.DosePulling.requireFunction( ...
                policy,'policy');
            context.log = planWorkflow.precompute.DosePulling.requireFunction( ...
                logger,'logger');
        end

        function [cst,report] = runReference(context,ct,cst,dij,stf,pln)
            strategy = planWorkflow.config.DosePullingConfig.strategy( ...
                context.runConfig);
            if strcmp(strategy,'heuristicMultiObjective')
                context.runConfig = ...
                    planWorkflow.config.DosePullingConfig.normalizeSearchConfig( ...
                    context.runConfig);
                [cst,report] = ...
                    planWorkflow.precompute.DosePulling.runReferenceHeuristic( ...
                    context,ct,cst,dij,stf,pln);
                return;
            end

            runConfig = context.runConfig;
            maxIterations = runConfig.dose_pulling_max_iter;
            targetNames = ...
                planWorkflow.precompute.DosePullingUtils.asCellstr( ...
                runConfig.dose_pulling1_target);
            criteria = ...
                planWorkflow.precompute.DosePullingUtils.expandCellToCount( ...
                runConfig.dose_pulling1_criteria,numel(targetNames), ...
                'dose_pulling1_criteria');
            limits = ...
                planWorkflow.precompute.DosePullingUtils.expandNumericToCount( ...
                runConfig.dose_pulling1_limit,numel(targetNames), ...
                'dose_pulling1_limit');

            resultGUI = context.optimizer(dij,cst,pln,[]);
            [resultGUI,dvh,qi] = context.analyzer(ct,cst,stf,pln, ...
                resultGUI,false);
            targetIx = ...
                planWorkflow.precompute.DosePullingUtils.findQiTargets( ...
                qi,targetNames);
            history = planWorkflow.precompute.DosePulling.referenceHistory( ...
                qi,targetIx,criteria,0,targetNames,limits);
            planWorkflow.precompute.DosePulling.logReferenceProgress( ...
                context,history(end),'initial');

            iteration = runConfig.dose_pulling1_start + 1;
            while iteration <= maxIterations && ...
                    planWorkflow.precompute.DosePulling.referenceNeedsUpdate( ...
                    qi,targetIx,criteria,limits)
                [cst,optimizationFlag] = planWorkflow.structures.pullDose( ...
                    cst,1);
                if ~optimizationFlag
                    context.log(sprintf(['Dose pulling step 1 stopped at ' ...
                        'iteration %d because planWorkflow.structures.' ...
                        'pullDose did not update any objective.'], ...
                        iteration));
                    break;
                end

                resultGUI = context.optimizer(dij,cst,pln,resultGUI.w);
                [resultGUI,dvh,qi] = context.analyzer( ...
                    ct,cst,stf,pln,resultGUI,false);
                history(end + 1) = ...
                    planWorkflow.precompute.DosePulling.referenceHistory( ...
                    qi,targetIx,criteria,iteration,targetNames,limits); %#ok<AGROW>
                planWorkflow.precompute.DosePulling.logReferenceProgress( ...
                    context,history(end),'after pull');
                iteration = iteration + 1;
            end

            converged = ...
                ~planWorkflow.precompute.DosePulling.referenceNeedsUpdate( ...
                qi,targetIx,criteria,limits);
            planWorkflow.precompute.DosePulling.logSummary( ...
                context,1,converged,numel(history) - 1);

            report = struct();
            report.initialWeights = resultGUI.w;
            report.dvh = dvh;
            report.qi = qi;
            report.history = history;
            report.converged = converged;
            report.iterations = numel(history) - 1;
        end

        function [robustData,report] = runRobust(context,robustData)
            strategy = planWorkflow.config.DosePullingConfig.strategy( ...
                context.runConfig);
            if strcmp(strategy,'heuristicMultiObjective')
                context.runConfig = ...
                    planWorkflow.config.DosePullingConfig.normalizeSearchConfig( ...
                    context.runConfig);
                [robustData,report] = ...
                    planWorkflow.precompute.DosePulling.runRobustHeuristic( ...
                    context,robustData);
                return;
            end

            runConfig = context.runConfig;
            maxIterations = runConfig.dose_pulling_max_iter;
            numVariants = ...
                planWorkflow.config.RobustPlanConfig.variantWithPenaltyCount( ...
                robustData.planConfig);
            robustData.initialWeights = cell(1,numVariants);

            report = struct();
            report.plans = cell(1,numVariants);

            cstByVariant = ...
                planWorkflow.precompute.DosePulling.cstByVariant( ...
                robustData,numVariants);
            previousWeights = cell(1,numVariants);
            histories = cell(1,numVariants);
            [resultGUIByVariant,metricsByVariant,histories] = ...
                planWorkflow.precompute.DosePulling.evaluateRobustVariants( ...
                context,robustData,cstByVariant,previousWeights,0,histories, ...
                numVariants,'initial');

            iteration = runConfig.dose_pulling2_start + 1;
            while iteration <= maxIterations && ...
                    planWorkflow.precompute.DosePulling.anyRobustVariantNeedsUpdate( ...
                    context,metricsByVariant)
                [cstByVariant,optimizationFlag] = ...
                    planWorkflow.precompute.DosePulling.applyPullsByVariant( ...
                    cstByVariant,2,1);
                if ~optimizationFlag
                    context.log(sprintf(['Dose pulling step 2 stopped at ' ...
                        'iteration %d because planWorkflow.structures.' ...
                        'pullDose did not update any objective.'], ...
                        iteration));
                    break;
                end

                previousWeights = ...
                    planWorkflow.precompute.DosePulling.resultWeights( ...
                    resultGUIByVariant);
                [resultGUIByVariant,metricsByVariant,histories] = ...
                    planWorkflow.precompute.DosePulling.evaluateRobustVariants( ...
                    context,robustData,cstByVariant,previousWeights,iteration, ...
                    histories,numVariants,'after pull');
                iteration = iteration + 1;
            end

            robustData = ...
                planWorkflow.precompute.RobustDataFactory.setCstByVariant( ...
                robustData,cstByVariant);
            robustData.initialWeights = ...
                planWorkflow.precompute.DosePulling.resultWeights( ...
                resultGUIByVariant);
            for variantIx = 1:numVariants
                history = histories{variantIx};
                metrics = metricsByVariant{variantIx};
                converged = ~context.policy(metrics);
                planWorkflow.precompute.DosePulling.logSummary( ...
                    context,2,converged,numel(history) - 1,variantIx, ...
                    numVariants);

                report.plans{variantIx} = struct( ...
                    'history',history, ...
                    'converged',converged, ...
                    'iterations',numel(history) - 1);
            end
        end
    end

    methods (Static, Access = private)
        function [cst,report] = runReferenceHeuristic( ...
                context,ct,cst,dij,stf,pln)
            runConfig = context.runConfig;
            targetNames = ...
                planWorkflow.precompute.DosePullingUtils.asCellstr( ...
                runConfig.dose_pulling1_target);
            criteria = ...
                planWorkflow.precompute.DosePullingUtils.expandCellToCount( ...
                runConfig.dose_pulling1_criteria,numel(targetNames), ...
                'dose_pulling1_criteria');
            limits = ...
                planWorkflow.precompute.DosePullingUtils.expandNumericToCount( ...
                runConfig.dose_pulling1_limit,numel(targetNames), ...
                'dose_pulling1_limit');

            initialState = ...
                planWorkflow.precompute.DosePulling.emptySearchState();
            initialState.cst = cst;
            evaluator = @(state,step) ...
                planWorkflow.precompute.DosePulling.evaluateReferenceStep( ...
                context,ct,dij,stf,pln,targetNames,criteria,limits, ...
                state,step);
            search = planWorkflow.precompute.DosePullingStepSearch.run( ...
                runConfig,initialState,evaluator);

            bestState = search.bestState;
            cst = bestState.cst;
            converged = search.best.isSatisfied;
            planWorkflow.precompute.DosePulling.logSummary( ...
                context,1,converged,search.best.step);

            report = struct();
            report.initialWeights = bestState.weights;
            report.dvh = bestState.dvh;
            report.qi = bestState.qi;
            report.history = search.results;
            report.selected = search.best;
            report.search = rmfield(search,{'states','bestState'});
            report.converged = converged;
            report.iterations = search.best.step;
        end

        function [robustData,report] = runRobustHeuristic( ...
                context,robustData)
            runConfig = context.runConfig;
            numVariants = ...
                planWorkflow.config.RobustPlanConfig.variantWithPenaltyCount( ...
                robustData.planConfig);
            robustData.initialWeights = cell(1,numVariants);

            initialState = ...
                planWorkflow.precompute.DosePulling.emptySearchState();
            initialState.robustData = robustData;
            initialState.weights = cell(1,numVariants);
            evaluator = @(state,step) ...
                planWorkflow.precompute.DosePulling.evaluateRobustStep( ...
                context,state,step,numVariants);
            search = planWorkflow.precompute.DosePullingStepSearch.run( ...
                runConfig,initialState,evaluator);

            bestState = search.bestState;
            robustData = bestState.robustData;
            robustData.initialWeights = bestState.weights;

            report = struct();
            report.plans = cell(1,numVariants);
            for variantIx = 1:numVariants
                history = ...
                    planWorkflow.precompute.DosePulling.robustHistoryForVariant( ...
                    search.results,variantIx);
                selected = search.best.metricsByVariant{variantIx};
                converged = ~context.policy(selected);
                planWorkflow.precompute.DosePulling.logSummary( ...
                    context,2,converged,search.best.step,variantIx, ...
                    numVariants);

                report.plans{variantIx} = struct( ...
                    'history',history, ...
                    'selected',selected, ...
                    'converged',converged, ...
                    'iterations',search.best.step);
            end
            report.search = rmfield(search,{'states','bestState'});
            report.selected = search.best;
        end

        function [state,result] = evaluateReferenceStep( ...
                context,ct,dij,stf,pln,targetNames,criteria,limits, ...
                state,step)
            if step < state.step
                error(['planWorkflow:precompute:DosePulling:' ...
                    'NonMonotoneStepEvaluation'], ...
                    'Cannot evaluate dose-pulling step %d after step %d.', ...
                    step,state.step);
            end

            [state.cst,~] = planWorkflow.precompute.DosePulling.applyPulls( ...
                state.cst,1,step - state.step);
            initialWeights = ...
                planWorkflow.precompute.DosePulling.warmStartWeights( ...
                context.runConfig,state.weights);
            resultGUI = context.optimizer(dij,state.cst,pln,initialWeights);
            [resultGUI,dvh,qi] = context.analyzer( ...
                ct,state.cst,stf,pln,resultGUI,false);

            targetIx = ...
                planWorkflow.precompute.DosePullingUtils.findQiTargets( ...
                qi,targetNames);
            values = planWorkflow.precompute.DosePulling.qiValues( ...
                qi,targetIx,criteria);
            doseCube = ...
                planWorkflow.precompute.DosePullingScoring.analysisDoseCube( ...
                resultGUI);
            oarScore = ...
                planWorkflow.precompute.DosePullingScoring.oarObjectiveScoreFromDose( ...
                state.cst,doseCube,pln,1,targetNames);
            result = ...
                planWorkflow.precompute.DosePullingScoring.resultFromValues( ...
                step,values,limits,oarScore);
            result.targetNames = targetNames;
            result.criteria = criteria;
            result.criteriaLabels = ...
                planWorkflow.precompute.DosePulling.criteriaLabels( ...
                criteria,targetNames);
            result.rectumPull = ...
                planWorkflow.precompute.DosePullingScoring.dosePullingVmax( ...
                state.cst,'RECTUM',1);
            result.bladderPull = ...
                planWorkflow.precompute.DosePullingScoring.dosePullingVmax( ...
                state.cst,'BLADDER',1);
            result.channelObjective = ...
                planWorkflow.precompute.DosePullingScoring.dosePullingPenalty( ...
                state.cst,targetNames{1},1);
            result.isFeasible = ...
                planWorkflow.precompute.DosePullingScoring.oarObjectiveFeasible( ...
                state.cst,1,targetNames,context.runConfig);
            planWorkflow.precompute.DosePulling.logCandidate( ...
                context,1,result);

            state.step = step;
            state.weights = ...
                planWorkflow.precompute.DosePulling.resultWeight(resultGUI);
            state.resultGUI = resultGUI;
            state.dvh = dvh;
            state.qi = qi;
        end

        function [state,result] = evaluateRobustStep( ...
                context,state,step,numVariants)
            if step < state.step
                error(['planWorkflow:precompute:DosePulling:' ...
                    'NonMonotoneStepEvaluation'], ...
                    'Cannot evaluate dose-pulling step %d after step %d.', ...
                    step,state.step);
            end

            [state.robustData,~] = ...
                planWorkflow.precompute.DosePulling.applyPullsToRobustData( ...
                state.robustData,2,step - state.step,numVariants);
            targetNames = ...
                planWorkflow.precompute.DosePullingUtils.asCellstr( ...
                context.runConfig.dose_pulling2_target);
            resultGUIByVariant = cell(1,numVariants);
            metricsByVariant = cell(1,numVariants);
            nextWeights = cell(1,numVariants);
            values = [];
            limits = [];
            oarScore = 0;
            optimizationInput = ...
                planWorkflow.precompute.OptimizationInput.require( ...
                state.robustData,'robust dose pulling');

            for variantIx = 1:numVariants
                planForOptimization = ...
                    planWorkflow.optimization.VariantPlanFactory.build( ...
                    state.robustData,variantIx);
                cstForVariant = ...
                    planWorkflow.precompute.RobustDataFactory.cstForVariant( ...
                    state.robustData,variantIx);
                initialWeights = ...
                    planWorkflow.precompute.DosePulling.variantWarmStartWeights( ...
                    context.runConfig,state.weights,variantIx);
                resultGUI = context.optimizer( ...
                    optimizationInput.dij,cstForVariant, ...
                    planForOptimization,initialWeights);
                resultGUIByVariant{variantIx} = resultGUI;
                nextWeights{variantIx} = ...
                    planWorkflow.precompute.DosePulling.resultWeight( ...
                    resultGUI);
                metrics = context.metrics( ...
                    cstForVariant,planForOptimization,resultGUI, ...
                    state.robustData.ctScenProb,step,state.robustData);
                metrics.planIndex = variantIx;
                metricsByVariant{variantIx} = metrics;
                values = [values metrics.selectedValues]; %#ok<AGROW>
                limits = [limits metrics.limits]; %#ok<AGROW>
                doseCube = ...
                    planWorkflow.precompute.DosePullingScoring.robustCenterDoseCube( ...
                    resultGUI,state.robustData);
                oarScore = oarScore + ...
                    planWorkflow.precompute.DosePullingScoring.oarObjectiveScoreFromDose( ...
                    cstForVariant,doseCube,planForOptimization, ...
                    2,targetNames);
            end

            result = ...
                planWorkflow.precompute.DosePullingScoring.resultFromValues( ...
                step,values,limits,oarScore);
            representativeMetrics = metricsByVariant{1};
            result.targetNames = representativeMetrics.targetNames;
            result.criteria = representativeMetrics.criteria;
            result.criteriaLabels = ...
                planWorkflow.precompute.DosePulling.robustCriteriaLabels( ...
                representativeMetrics);
            result.meanQiTarget = representativeMetrics.meanQiTarget;
            result.minQiTarget = representativeMetrics.minQiTarget;
            result.rectumPull = ...
                planWorkflow.precompute.DosePulling.robustDosePullingVmax( ...
                state.robustData,numVariants,'RECTUM',2);
            result.bladderPull = ...
                planWorkflow.precompute.DosePulling.robustDosePullingVmax( ...
                state.robustData,numVariants,'BLADDER',2);
            result.channelObjective = ...
                planWorkflow.precompute.DosePulling.robustDosePullingPenalty( ...
                state.robustData,numVariants,targetNames{1},2);
            result.metricsByVariant = metricsByVariant;
            result.isFeasible = ...
                planWorkflow.precompute.DosePulling.robustOarObjectiveFeasible( ...
                state.robustData,numVariants,2,targetNames, ...
                context.runConfig);
            planWorkflow.precompute.DosePulling.logCandidate( ...
                context,2,result);

            state.step = step;
            state.weights = nextWeights;
            state.resultGUIByVariant = resultGUIByVariant;
        end

        function state = emptySearchState()
            state = struct();
            state.step = 0;
            state.cst = [];
            state.robustData = [];
            state.weights = [];
            state.resultGUI = [];
            state.resultGUIByVariant = {};
            state.dvh = [];
            state.qi = [];
        end

        function [cst,flag] = applyPulls(cst,pullingStep,numPulls)
            if numPulls < 0 || abs(numPulls - round(numPulls)) > eps(numPulls)
                error(['planWorkflow:precompute:DosePulling:' ...
                    'InvalidPullCount'], ...
                    'Dose pulling requires a nonnegative integer pull count.');
            end
            flag = numPulls == 0;
            for i = 1:numPulls
                [cst,updated] = planWorkflow.structures.pullDose( ...
                    cst,pullingStep);
                flag = flag || updated;
            end
        end

        function [cstByVariant,flag] = applyPullsByVariant( ...
                cstByVariant,pullingStep,numPulls)
            flag = numPulls == 0;
            for variantIx = 1:numel(cstByVariant)
                [cstByVariant{variantIx},variantFlag] = ...
                    planWorkflow.precompute.DosePulling.applyPulls( ...
                    cstByVariant{variantIx},pullingStep,numPulls);
                flag = flag || variantFlag;
            end
        end

        function [robustData,flag] = applyPullsToRobustData( ...
                robustData,pullingStep,numPulls,numVariants)
            cstByVariant = ...
                planWorkflow.precompute.DosePulling.cstByVariant( ...
                robustData,numVariants);
            [cstByVariant,flag] = ...
                planWorkflow.precompute.DosePulling.applyPullsByVariant( ...
                cstByVariant,pullingStep,numPulls);
            robustData = ...
                planWorkflow.precompute.RobustDataFactory.setCstByVariant( ...
                robustData,cstByVariant);
        end

        function values = qiValues(qi,targetIx,criteria)
            values = zeros(1,numel(targetIx));
            for i = 1:numel(targetIx)
                values(i) = qi(targetIx(i)).(criteria{i});
            end
        end

        function weights = warmStartWeights(runConfig,previousWeights)
            if isfield(runConfig,'dose_pulling_use_warm_start') && ...
                    runConfig.dose_pulling_use_warm_start
                weights = previousWeights;
            else
                weights = [];
            end
        end

        function cstByVariant = cstByVariant(robustData,numVariants)
            cstByVariant = cell(1,numVariants);
            for variantIx = 1:numVariants
                cstByVariant{variantIx} = ...
                    planWorkflow.precompute.RobustDataFactory.cstForVariant( ...
                    robustData,variantIx);
            end
        end

        function value = robustDosePullingVmax( ...
                robustData,numVariants,structureName,pullingStep)
            values = NaN(1,numVariants);
            for variantIx = 1:numVariants
                cst = ...
                    planWorkflow.precompute.RobustDataFactory.cstForVariant( ...
                    robustData,variantIx);
                values(variantIx) = ...
                    planWorkflow.precompute.DosePullingScoring.dosePullingVmax( ...
                    cst,structureName,pullingStep);
            end
            value = planWorkflow.precompute.DosePulling.maxFiniteOrNaN(values);
        end

        function value = robustDosePullingPenalty( ...
                robustData,numVariants,structureName,pullingStep)
            values = NaN(1,numVariants);
            for variantIx = 1:numVariants
                cst = ...
                    planWorkflow.precompute.RobustDataFactory.cstForVariant( ...
                    robustData,variantIx);
                values(variantIx) = ...
                    planWorkflow.precompute.DosePullingScoring.dosePullingPenalty( ...
                    cst,structureName,pullingStep);
            end
            value = planWorkflow.precompute.DosePulling.maxFiniteOrNaN(values);
        end

        function tf = robustOarObjectiveFeasible( ...
                robustData,numVariants,pullingStep,targetNames,runConfig)
            tf = true;
            for variantIx = 1:numVariants
                cst = ...
                    planWorkflow.precompute.RobustDataFactory.cstForVariant( ...
                    robustData,variantIx);
                if ~planWorkflow.precompute.DosePullingScoring.oarObjectiveFeasible( ...
                        cst,pullingStep,targetNames,runConfig)
                    tf = false;
                    return;
                end
            end
        end

        function value = maxFiniteOrNaN(values)
            values = values(isfinite(values));
            if isempty(values)
                value = NaN;
            else
                value = max(values);
            end
        end

        function weights = variantWarmStartWeights( ...
                runConfig,previousWeights,variantIx)
            weights = [];
            if ~(isfield(runConfig,'dose_pulling_use_warm_start') && ...
                    runConfig.dose_pulling_use_warm_start)
                return;
            end
            if iscell(previousWeights) && numel(previousWeights) >= variantIx
                weights = previousWeights{variantIx};
            end
        end

        function weights = resultWeight(resultGUI)
            weights = [];
            if isstruct(resultGUI) && isfield(resultGUI,'w')
                weights = resultGUI.w;
            end
        end

        function labels = criteriaLabels(criteria,targetNames)
            labels = cell(1,numel(criteria));
            for i = 1:numel(criteria)
                labels{i} = sprintf('%s_%s',criteria{i},targetNames{i});
            end
        end

        function labels = robustCriteriaLabels(metrics)
            labels = cell(1,numel(metrics.criteria));
            for i = 1:numel(metrics.criteria)
                labels{i} = sprintf('%s(%s)_%s', ...
                    metrics.selectedCriterion,metrics.criteria{i}, ...
                    metrics.targetNames{i});
            end
        end

        function logCandidate(context,channel,result)
            valueText = ...
                planWorkflow.precompute.DosePulling.formatStepValues( ...
                result);
            context.log(sprintf(['Dose pulling channel %d step=%d %s ' ...
                'primaryScore=%.6g limitDiffSq=%.6g oarScore=%.6g ' ...
                'RectumV=%.6g BladderV=%.6g objectivePenalty=%.6g ' ...
                'ok=%s feasible=%s.'], ...
                channel,result.step,valueText,result.primaryScore, ...
                result.limitDiffSq,result.oarScore,result.rectumPull, ...
                result.bladderPull,result.channelObjective, ...
                planWorkflow.precompute.DosePulling.logicalText( ...
                result.isSatisfied), ...
                planWorkflow.precompute.DosePulling.logicalText( ...
                result.isFeasible)));
        end

        function text = formatStepValues(result)
            labels = result.criteriaLabels;
            if isempty(labels)
                labels = ...
                    planWorkflow.precompute.DosePulling.criteriaLabels( ...
                    result.criteria,result.targetNames);
            end
            if isempty(labels)
                labels = repmat({'criterion'},1,numel(result.values));
            end
            parts = cell(1,numel(result.values));
            for i = 1:numel(result.values)
                label = labels{mod(i - 1,numel(labels)) + 1};
                parts{i} = sprintf('%s=%.6g limit=%.6g', ...
                    label,result.values(i),result.limits(i));
            end
            text = strjoin(parts,' ');
        end

        function text = logicalText(value)
            if value
                text = 'true';
            else
                text = 'false';
            end
        end

        function history = robustHistoryForVariant(results,variantIx)
            history = [];
            for resultIx = 1:numel(results)
                if numel(results(resultIx).metricsByVariant) < variantIx
                    continue;
                end
                history = planWorkflow.precompute.DosePulling.appendHistory( ...
                    history,results(resultIx).metricsByVariant{variantIx});
            end
        end

        function [resultGUIByVariant,metricsByVariant,histories] = ...
                evaluateRobustVariants(context,robustData,cstByVariant, ...
                previousWeights,iteration,histories,numVariants,label)
            resultGUIByVariant = cell(1,numVariants);
            metricsByVariant = cell(1,numVariants);
            optimizationInput = ...
                planWorkflow.precompute.OptimizationInput.require( ...
                robustData,'robust dose pulling');
            for variantIx = 1:numVariants
                planForOptimization = ...
                    planWorkflow.optimization.VariantPlanFactory.build( ...
                    robustData,variantIx);
                cst = cstByVariant{variantIx};
                initialWeights = [];
                if numel(previousWeights) >= variantIx
                    initialWeights = previousWeights{variantIx};
                end
                resultGUI = context.optimizer( ...
                    optimizationInput.dij,cst,planForOptimization, ...
                    initialWeights);
                resultGUIByVariant{variantIx} = resultGUI;
                metrics = context.metrics( ...
                    cst,planForOptimization,resultGUI, ...
                    robustData.ctScenProb,iteration,robustData);
                metrics.planIndex = variantIx;
                metricsByVariant{variantIx} = metrics;
                histories{variantIx} = ...
                    planWorkflow.precompute.DosePulling.appendHistory( ...
                    histories{variantIx},metrics);
                planWorkflow.precompute.DosePulling.logRobustProgress( ...
                    context,metrics,variantIx,numVariants,label);
            end
        end

        function history = appendHistory(history,metrics)
            if isempty(history)
                history = metrics;
            else
                history(end + 1) = metrics;
            end
        end

        function tf = anyRobustVariantNeedsUpdate(context,metricsByVariant)
            tf = false;
            for variantIx = 1:numel(metricsByVariant)
                if context.policy(metricsByVariant{variantIx})
                    tf = true;
                    return;
                end
            end
        end

        function weights = resultWeights(resultGUIByVariant)
            weights = cell(1,numel(resultGUIByVariant));
            for variantIx = 1:numel(resultGUIByVariant)
                resultGUI = resultGUIByVariant{variantIx};
                if isstruct(resultGUI) && isfield(resultGUI,'w')
                    weights{variantIx} = resultGUI.w;
                end
            end
        end

        function history = referenceHistory(qi,targetIx,criteria, ...
                iteration,targetNames,limits)
            values = zeros(1,numel(targetIx));
            for i = 1:numel(targetIx)
                values(i) = qi(targetIx(i)).(criteria{i});
            end

            history = struct();
            history.step = 1;
            history.iteration = iteration;
            history.targetNames = targetNames;
            history.criteria = criteria;
            history.limits = limits;
            history.values = values;
            history.isSatisfied = all(values >= limits);
        end

        function tf = referenceNeedsUpdate(qi,targetIx,criteria,limits)
            values = zeros(1,numel(targetIx));
            for i = 1:numel(targetIx)
                values(i) = qi(targetIx(i)).(criteria{i});
            end
            tf = any(values < limits);
        end

        function logReferenceProgress(context,entry,label)
            if entry.iteration == 0
                iterationText = 'initial criteria';
            else
                iterationText = sprintf('%s, iteration %d',label,entry.iteration);
            end
            context.log(sprintf('Dose pulling step 1 %s: %s.', ...
                iterationText, ...
                planWorkflow.precompute.DosePulling.formatCriteria( ...
                entry.targetNames,entry.criteria,entry.values,entry.limits)));
        end

        function logRobustProgress(context,metrics,planIx,numPlans,label)
            if metrics.iteration == 0
                iterationText = 'initial criteria';
            else
                iterationText = sprintf('%s, iteration %d',label,metrics.iteration);
            end
            context.log(sprintf('Dose pulling step 2 plan %d/%d %s: %s.', ...
                planIx,numPlans,iterationText, ...
                planWorkflow.precompute.DosePulling.formatRobustCriteria( ...
                metrics)));
        end

        function logSummary(context,step,converged,numPulls,planIx,numPlans)
            if converged
                statusText = 'converged';
            else
                statusText = 'stopped without convergence';
            end

            if nargin < 5
                context.log(sprintf('Dose pulling step %d %s after %d pulls.', ...
                    step,statusText,numPulls));
            else
                context.log(sprintf(['Dose pulling step %d plan %d/%d %s after ' ...
                    '%d pulls.'],step,planIx,numPlans,statusText,numPulls));
            end
        end

        function text = formatCriteria(targetNames,criteria,values,limits)
            parts = cell(1,numel(values));
            for i = 1:numel(values)
                if values(i) >= limits(i)
                    statusText = 'ok';
                else
                    statusText = 'below limit';
                end
                parts{i} = sprintf('%s(%s)=%.6g, limit=%.6g, gap=%+.6g [%s]', ...
                    criteria{i},targetNames{i},values(i),limits(i), ...
                    values(i) - limits(i),statusText);
            end
            text = strjoin(parts,'; ');
        end

        function text = formatRobustCriteria(metrics)
            parts = cell(1,numel(metrics.selectedValues));
            for i = 1:numel(metrics.selectedValues)
                if metrics.selectedValues(i) >= metrics.limits(i)
                    statusText = 'ok';
                else
                    statusText = 'below limit';
                end

                if strcmp(metrics.selectedCriterion,'meanQiTarget')
                    companionText = sprintf('minQiTarget=%.6g', ...
                        metrics.minQiTarget(i));
                else
                    companionText = sprintf('meanQiTarget=%.6g', ...
                        metrics.meanQiTarget(i));
                end

                metricLabel = sprintf('%s(%s)_%s', ...
                    metrics.selectedCriterion,metrics.criteria{i}, ...
                    metrics.targetNames{i});
                parts{i} = sprintf(['%s=%.6g, %s, limit=%.6g, ' ...
                    'gap=%+.6g [%s]'],metricLabel, ...
                    metrics.selectedValues(i),companionText,metrics.limits(i), ...
                    metrics.selectedValues(i) - metrics.limits(i),statusText);
            end
            text = strjoin(parts,'; ');
        end

        function value = requireFunction(value,name)
            if ~isa(value,'function_handle')
                error('planWorkflow:precompute:DosePulling:InvalidContext', ...
                    'DosePulling context requires function "%s".',name);
            end
        end
    end
end
