classdef IntervalDoseInfluence
    % IntervalDoseInfluence Owns INTERVAL2/INTERVAL3 dij_interval flow.

    methods (Static)
        function [cacheHit,robustData] = loadCached(context,robustData)
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.ensurePlanContext( ...
                context,robustData);
            cacheHit = false;
            cacheContext = ...
                planWorkflow.precompute.IntervalDoseInfluence.cacheContext( ...
                context,robustData);
            cacheFile = context.cache.file( ...
                planWorkflow.precompute.IntervalDoseInfluence.cacheTag( ...
                robustData),robustData.pln,cacheContext);
            if ~context.runConfig.useCache || ~isfile(cacheFile)
                return;
            end

            cached = load(cacheFile);
            if ~isfield(cached,'dij_interval') || ...
                    ~isfield(cached,'dijIntervalContext')
                context.log(sprintf( ...
                    'Ignoring stale interval dij cache: %s.',cacheFile));
                return;
            end

            if ~planWorkflow.precompute.IntervalDoseInfluence.isCacheCompatible( ...
                    context,cached,robustData)
                context.log(sprintf( ...
                    'Ignoring stale interval dij cache: %s.',cacheFile));
                return;
            end
            dijPrecomputingTiming = ...
                planWorkflow.performance.PrecomputeTiming.fromCacheMetadata( ...
                cached.cacheMetadata);
            dijPrecomputingSize = ...
                planWorkflow.performance.PrecomputeSize.fromCacheMetadata( ...
                cached.cacheMetadata);
            if isempty(dijPrecomputingTiming) || ...
                    isempty(dijPrecomputingSize)
                context.log(sprintf( ...
                    'Ignoring stale interval dij cache: %s.',cacheFile));
                return;
            end

            robustData.dijIntervalContext = cached.dijIntervalContext;
            robustData.dij_interval = cached.dij_interval;
            robustData.dijCacheRefs.interval = ...
                planWorkflow.cache.DoseInfluenceCacheRef.create( ...
                'interval', ...
                planWorkflow.precompute.IntervalDoseInfluence.cacheTag( ...
                robustData),cacheFile,context.cache.cachePath, ...
                cached.cacheMetadata, ...
                {'dij_interval','dijIntervalContext'}, ...
                planWorkflow.cache.DoseInfluenceCacheRef.totalNumOfBixels( ...
                cached.dijIntervalContext));
            robustData.dijPrecomputingTiming = dijPrecomputingTiming;
            robustData.dijPrecomputingSize = dijPrecomputingSize;
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.stripStoredIntervalPlanPayload( ...
                robustData);
            if planWorkflow.precompute.IntervalDoseInfluence.needsRobustNominalDij( ...
                    robustData)
                [nominalCompatible,robustData] = ...
                    planWorkflow.precompute.IntervalDoseInfluence.tryAttachCachedNominalDij( ...
                    context,robustData,cacheFile);
                if ~nominalCompatible
                    return;
                end
            end
            cacheHit = true;
            context.log(sprintf('Loaded cached interval dij: %s.', ...
                cacheFile));
        end

        function robustData = precompute(context,robustData)
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.ensurePlanContext( ...
                context,robustData);
            useScenarioBatch = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.useScenarioBatchPrecompute( ...
                robustData.planConfig);
            intervalConfig = ...
                planWorkflow.precompute.IntervalDoseInfluence.doseConfig( ...
                context,robustData,useScenarioBatch);
            context.log(sprintf( ...
                'Precomputing %s interval dose influence data using %s.', ...
                robustData.strategy.name, ...
                planWorkflow.precompute.IntervalDoseInfluence.executionModeLabel( ...
                useScenarioBatch)));

            switch robustData.strategy.name
                case {'INTERVAL2','INTERVAL3'}
                    wallTimer = tic;
                    intervalConfig.IntervalMode = robustData.strategy.name;
                    if useScenarioBatch
                        [plnForOptimization,dijIntervalContext] = ...
                            matRad_calcDoseInterval( ...
                            robustData.ct,robustData.cst,robustData.stf, ...
                            robustData.pln,intervalConfig);
                    else
                        planWorkflow.precompute.IntervalDoseInfluence.requireRobustInput( ...
                            robustData);
                        [plnForOptimization,dijIntervalContext] = ...
                            matRad_calcDoseInterval( ...
                            robustData.ct,robustData.cst,robustData.stf, ...
                            robustData.pln,robustData.dijRobust, ...
                            intervalConfig);
                    end
                    derivedTimeSeconds = toc(wallTimer);
                otherwise
                    error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                        'UnsupportedStrategy'], ...
                        'Unsupported interval strategy "%s".', ...
                        robustData.strategy.name);
            end

            robustData.dij_interval = plnForOptimization.propOpt.dij_interval;
            clear plnForOptimization;
            robustData.dijIntervalContext = dijIntervalContext;
            robustData.dijPrecomputingTiming = ...
                planWorkflow.performance.PrecomputeTiming.combine( ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.inputTiming( ...
                robustData), ...
                'derived','dij_interval',derivedTimeSeconds, ...
                robustData.planConfig.label, ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.referenceTiming( ...
                context,robustData));
            robustData.dijPrecomputingSize = ...
                planWorkflow.performance.PrecomputeSize.combine( ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.inputSize( ...
                robustData), ...
                'derived','dij_interval',robustData.dij_interval, ...
                robustData.planConfig.label, ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.referenceSize( ...
                context,robustData));
            if planWorkflow.precompute.ScenarioFreeDoseInfluence.isReferencePlan( ...
                    robustData)
                robustData.dijPrecomputingTiming = ...
                    planWorkflow.performance.PrecomputeTiming.asReference( ...
                    robustData.dijPrecomputingTiming, ...
                    robustData.planConfig.label);
                robustData.dijPrecomputingSize = ...
                    planWorkflow.performance.PrecomputeSize.asReference( ...
                    robustData.dijPrecomputingSize, ...
                    robustData.planConfig.label);
            end
            if planWorkflow.precompute.IntervalDoseInfluence.needsRobustNominalDij( ...
                    robustData)
                robustData = ...
                    planWorkflow.precompute.IntervalDoseInfluence.attachNominalDijFromContext( ...
                    robustData);
            end
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.stripStoredIntervalPlanPayload( ...
                robustData);
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.stripTransientRobustInput( ...
                robustData);
            robustData = planWorkflow.precompute.IntervalDoseInfluence.cache( ...
                context,robustData);
        end

        function robustData = cache(context,robustData)
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.ensurePlanContext( ...
                context,robustData);
            if ~context.runConfig.writeCache
                return;
            end

            cacheContext = ...
                planWorkflow.precompute.IntervalDoseInfluence.cacheContext( ...
                context,robustData);
            tag = planWorkflow.precompute.IntervalDoseInfluence.cacheTag( ...
                robustData);
            cacheFile = context.cache.file(tag,robustData.pln, ...
                cacheContext);
            dij_interval = robustData.dij_interval;
            dijIntervalContext = robustData.dijIntervalContext; %#ok<NASGU>
            cacheMetadata = context.cache.metadata( ...
                tag,robustData.pln,cacheContext);
            cacheMetadata.intervalMode = robustData.strategy.name;
            cacheMetadata.intervalQuantity = dij_interval.quantity;
            cacheMetadata.intervalQuantityField = dij_interval.quantityField;
            if isfield(dij_interval,'radiusMode')
                cacheMetadata.intervalRadiusMode = dij_interval.radiusMode;
            end
            if ~isfield(robustData,'dijPrecomputingTiming') || ...
                    ~planWorkflow.performance.PrecomputeTiming.isValid( ...
                    robustData.dijPrecomputingTiming)
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingPrecomputeTiming'], ...
                    'INTERVAL cache requires dijPrecomputingTiming metadata.');
            end
            cacheMetadata.dijPrecomputingTiming = ...
                robustData.dijPrecomputingTiming;
            if ~isfield(robustData,'dijPrecomputingSize') || ...
                    ~planWorkflow.performance.PrecomputeSize.isValid( ...
                    robustData.dijPrecomputingSize)
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingPrecomputeSize'], ...
                    'INTERVAL cache requires dijPrecomputingSize metadata.');
            end
            cacheMetadata.dijPrecomputingSize = ...
                robustData.dijPrecomputingSize;
            context.cache.ensureFileFolder(cacheFile);
            if planWorkflow.precompute.IntervalDoseInfluence.needsRobustNominalDij( ...
                    robustData) && (~isfield(robustData,'dijNominal') || ...
                    isempty(robustData.dijNominal))
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingCacheNominalDij'], ...
                    ['INTERVAL cache for nominal objectives requires ' ...
                    'dijNominal from dijIntervalContext.']);
            end
            if isfield(robustData,'dijNominal') && ...
                    ~isempty(robustData.dijNominal)
                cacheMetadata.hasNominalDijContext = true;
                builtin('save',cacheFile,'dij_interval', ...
                    'dijIntervalContext','cacheMetadata','-v7.3');
            else
                cacheMetadata.hasNominalDijContext = false;
                builtin('save',cacheFile,'dij_interval', ...
                    'dijIntervalContext','cacheMetadata','-v7.3');
            end
            context.log(sprintf('Cached interval dij: %s.', ...
                cacheFile));
            robustData.dijCacheRefs.interval = ...
                planWorkflow.cache.DoseInfluenceCacheRef.create( ...
                'interval',tag,cacheFile,context.cache.cachePath, ...
                cacheMetadata,{'dij_interval','dijIntervalContext'}, ...
                planWorkflow.cache.DoseInfluenceCacheRef.totalNumOfBixels( ...
                robustData.dijIntervalContext));
        end

        function robustData = useForOptimization(robustData)
            if ~isfield(robustData,'dijIntervalContext') || ...
                    isempty(robustData.dijIntervalContext)
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingIntervalDijContext'], ...
                    'INTERVAL optimization requires dijIntervalContext.');
            end
            if ~isfield(robustData,'plnForOptimization') || ...
                    isempty(robustData.plnForOptimization)
                robustData.plnForOptimization = ...
                    planWorkflow.precompute.IntervalDoseInfluence.createOptimizationPlan( ...
                    robustData);
            end
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.stripStoredIntervalPlanPayload( ...
                robustData);
            robustData.usesIntervalDijForOptimization = true;
        end

        function pln = optimizationPlan(robustData)
            if isfield(robustData,'plnForOptimization') && ...
                    ~isempty(robustData.plnForOptimization)
                pln = robustData.plnForOptimization;
            else
                pln = robustData.pln;
            end
            if isfield(robustData,'dij_interval') && ...
                    ~isempty(robustData.dij_interval)
                pln = ...
                    planWorkflow.precompute.IntervalDoseInfluence.attachIntervalDijToPlan( ...
                    pln,robustData.dij_interval);
            end
        end

        function robustData = restoreOptimizationPlan(robustData)
            if ~isfield(robustData,'dij_interval') || ...
                    isempty(robustData.dij_interval)
                return;
            end
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.stripStoredIntervalPlanPayload( ...
                robustData);
            if isfield(robustData,'dijIntervalContext') && ...
                    ~isempty(robustData.dijIntervalContext)
                robustData.plnForOptimization = ...
                    planWorkflow.precompute.IntervalDoseInfluence.createOptimizationPlan( ...
                    robustData);
            end
        end

        function pln = createOptimizationPlan(robustData)
            pln = robustData.pln;
            if ~isfield(pln,'propOpt') || ~isstruct(pln.propOpt)
                pln.propOpt = struct();
            end
            pln = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.removePlanPayload( ...
                pln,'dij_interval');
            pln.multScen = robustData.dijIntervalContext.scenarioModel;
        end

        function contextOut = cacheContext(context,robustData)
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.ensurePlanContext( ...
                context,robustData);
            contextOut = struct();
            if isfield(robustData,'cst')
                contextOut.cst = robustData.cst;
            end
            interval = struct();
            interval.mode = robustData.strategy.name;
            if isfield(context.data,'quantityOpt') && ...
                    ~isempty(context.data.quantityOpt)
                interval.quantity = context.data.quantityOpt;
            else
                interval.quantity = '';
            end
            interval.refScen = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.effectiveRefScen( ...
                planWorkflow.precompute.IntervalDoseInfluence.ctForRefScen( ...
                robustData));
            interval.scen4D = 1;
            if isfield(robustData,'pln') && ...
                    isfield(robustData.pln,'propOpt') && ...
                    isstruct(robustData.pln.propOpt) && ...
                    isfield(robustData.pln.propOpt,'scen4D') && ...
                    ~isempty(robustData.pln.propOpt.scen4D)
                interval.scen4D = robustData.pln.propOpt.scen4D;
            end
            if isfield(robustData,'objectiveInfo')
                interval.targetName = ...
                    planWorkflow.precompute.IntervalDoseInfluence.optionalStructField( ...
                    robustData.objectiveInfo,'targetName','');
                interval.robustOarNames = ...
                    planWorkflow.precompute.IntervalDoseInfluence.optionalStructField( ...
                    robustData.objectiveInfo,'robustOarNames',{});
            else
                interval.targetName = '';
                interval.robustOarNames = {};
            end
            if strcmp(robustData.strategy.name,'INTERVAL3')
                interval.radiusMode = ...
                    robustData.planConfig.robustnessOptions.radiusMode;
                if strcmpi(char(interval.radiusMode),'std')
                    interval.KMode = ...
                        robustData.planConfig.robustnessOptions.KMode;
                    interval.kmax = robustData.planConfig.robustnessOptions.kmax;
                    interval.retentionThreshold = ...
                        robustData.planConfig.robustnessOptions.retentionThreshold;
                end
            elseif strcmp(robustData.strategy.name,'INTERVAL2')
                interval.radiusMode = ...
                    robustData.planConfig.robustnessOptions.radiusMode;
            end
            contextOut.interval = interval;
            if isfield(robustData,'stf') && ~isempty(robustData.stf)
                contextOut.stf = context.cache.stfSignature( ...
                    robustData.stf);
            end
        end

        function tag = cacheTag(robustData)
            if ~isfield(robustData,'planConfig') || ...
                    ~isfield(robustData.planConfig,'id') || ...
                    isempty(robustData.planConfig.id)
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingRobustPlanId'], ...
                    'Interval dose cache tag requires a robust plan id.');
            end
            tag = ['interval_' char(robustData.planConfig.id)];
        end

        function intervalConfig = doseConfig(context,robustData, ...
                includeScenarioBatchConfig)
            if nargin < 3 || isempty(includeScenarioBatchConfig)
                includeScenarioBatchConfig = false;
            end
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.ensurePlanContext( ...
                context,robustData);
            intervalConfig = struct();
            if isfield(context.data,'quantityOpt') && ...
                    ~isempty(context.data.quantityOpt)
                intervalConfig.Quantity = context.data.quantityOpt;
            end
            intervalConfig.refScen = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.effectiveRefScen( ...
                planWorkflow.precompute.IntervalDoseInfluence.ctForRefScen( ...
                robustData));
            intervalConfig.ProgressLevel = 'summary';
            if isfield(robustData.planConfig,'robustnessOptions') && ...
                    isfield(robustData.planConfig.robustnessOptions, ...
                    'radiusMode')
                intervalConfig.RadiusMode = ...
                    robustData.planConfig.robustnessOptions.radiusMode;
            end
            intervalConfig.targetStructSel = ...
                robustData.cst(robustData.objectiveInfo.ixTarget,2);
            intervalConfig.OARStructSel = ...
                planWorkflow.precompute.IntervalDoseInfluence.asCellstr( ...
                robustData.objectiveInfo.robustOarNames);

            if strcmp(robustData.strategy.name,'INTERVAL3')
                intervalConfig.UseParallel = true;
                intervalConfig = ...
                    planWorkflow.precompute.IntervalDoseInfluence.applyParallelOptions( ...
                    intervalConfig,context);
                if ~isfield(intervalConfig,'RadiusMode') || ...
                        strcmpi(char(intervalConfig.RadiusMode),'std')
                    intervalConfig.KMode = ...
                        robustData.planConfig.robustnessOptions.KMode;
                    intervalConfig.KMax = ...
                        robustData.planConfig.robustnessOptions.kmax;
                    intervalConfig.RetentionThreshold = ...
                        robustData.planConfig.robustnessOptions.retentionThreshold;
                end
            end
            if includeScenarioBatchConfig
                intervalConfig = ...
                    planWorkflow.precompute.ScenarioFreeDoseInfluence.mergeScenarioBatchConfig( ...
                    intervalConfig,robustData.planConfig,context,'doseInterval');
                intervalConfig.UseParallel = true;
                intervalConfig = ...
                    planWorkflow.precompute.IntervalDoseInfluence.applyParallelOptions( ...
                    intervalConfig,context);
            end
        end

        function tf = isCacheCompatible(context,cached,robustData)
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.ensurePlanContext( ...
                context,robustData);
            tf = isfield(cached,'cacheMetadata') && ...
                context.cache.isIdentityCompatible(cached, ...
                planWorkflow.precompute.IntervalDoseInfluence.cacheTag( ...
                robustData),robustData.pln, ...
                planWorkflow.precompute.IntervalDoseInfluence.cacheContext( ...
                context,robustData)) && ...
                planWorkflow.precompute.IntervalDoseInfluence.isCachePayloadCompatible( ...
                cached,robustData);
        end

        function [tf,reason] = isCachePayloadCompatible( ...
                cached,robustData,compatibilityMode,ref,rehydrateContext)
            if nargin < 3 || isempty(compatibilityMode)
                compatibilityMode = 'discovery';
            end
            if nargin < 4
                ref = struct();
            end
            if nargin < 5 || isempty(rehydrateContext)
                rehydrateContext = struct();
            end
            tf = false;
            reason = '';
            if ~isfield(cached,'cacheMetadata')
                reason = 'missing cache metadata';
                return;
            end
            [tf,reason] = ...
                planWorkflow.precompute.IntervalDoseInfluence.isCacheMetadataCompatible( ...
                cached.cacheMetadata,robustData,compatibilityMode,ref, ...
                rehydrateContext);
            if ~tf
                return;
            end

            if strcmp(char(compatibilityMode),'rehydrate')
                [tf,reason] = ...
                    planWorkflow.precompute.IntervalDoseInfluence.isRehydratedCacheVariableCompatible( ...
                    cached,ref);
                return;
            end

            if ~isfield(cached,'dij_interval') || ...
                    ~planWorkflow.precompute.IntervalDoseInfluence.isIntervalDijUsable( ...
                    cached.dij_interval,robustData.strategy.name)
                reason = 'cached interval dij payload is not usable';
                return;
            end
            if ~isfield(cached,'dijIntervalContext') || ...
                    ~planWorkflow.precompute.IntervalDoseInfluence.isIntervalDijContextUsable( ...
                    cached.dijIntervalContext,cached.dij_interval)
                reason = 'cached interval dij context is not usable';
                return;
            end
            if ~planWorkflow.precompute.IntervalDoseInfluence.isCachedNominalDijContextUsable( ...
                    cached,robustData,cached.dij_interval)
                reason = 'cached nominal interval dij context is not usable';
                return;
            end
            if ~planWorkflow.precompute.IntervalDoseInfluence.isIntervalDijContextCompatibleWithStf( ...
                    cached.dijIntervalContext,robustData.stf)
                reason = 'cached interval dij context bixels do not match STF';
                return;
            end
            tf = true;
        end

        function [tf,reason] = isCacheMetadataCompatible( ...
                cacheMetadata,robustData,compatibilityMode,ref, ...
                rehydrateContext)
            if nargin < 3 || isempty(compatibilityMode)
                compatibilityMode = 'discovery';
            end
            if nargin < 4
                ref = struct();
            end
            if nargin < 5 || isempty(rehydrateContext)
                rehydrateContext = struct();
            end
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.ensurePlanContext( ...
                [],robustData);
            tf = false;
            reason = '';
            if ~isstruct(cacheMetadata)
                reason = 'missing cache metadata';
                return;
            end
            if ~planWorkflow.precompute.IntervalDoseInfluence.isMetadataForPlan( ...
                    cacheMetadata,robustData)
                reason = 'cache plan metadata does not match';
                return;
            end
            if ~isfield(cacheMetadata,'intervalMode') || ...
                    ~strcmp(cacheMetadata.intervalMode,robustData.strategy.name)
                reason = 'cache is not the requested interval payload';
                return;
            end
            switch char(compatibilityMode)
                case 'discovery'
                    if ~planWorkflow.precompute.IntervalDoseInfluence.isMetadataCstCompatible( ...
                            cacheMetadata,robustData)
                        reason = 'cache CST metadata does not match';
                        return;
                    end
                    if ~planWorkflow.precompute.IntervalDoseInfluence.isMetadataStfCompatible( ...
                            cacheMetadata,robustData)
                        reason = 'cache STF metadata does not match';
                        return;
                    end
                    if ~planWorkflow.precompute.IntervalDoseInfluence.isMetadataIntervalContextCompatible( ...
                            cacheMetadata,robustData)
                        reason = 'cache interval context metadata does not match';
                        return;
                    end
                    [tf,reason] = ...
                        planWorkflow.precompute.PrecomputeCacheCompatibility.isDiscoveryScenarioCompatible( ...
                        cacheMetadata,robustData);
                case 'rehydrate'
                    [tf,reason] = ...
                        planWorkflow.precompute.PrecomputeCacheCompatibility.isPersistedRefClinicalContextCompatible( ...
                        cacheMetadata,ref,rehydrateContext,'interval');
                otherwise
                    tf = false;
                    reason = sprintf( ...
                        'unknown cache compatibility mode "%s"', ...
                        char(compatibilityMode));
            end
        end

        function [tf,reason] = isRehydratedCacheVariableCompatible( ...
                cached,ref)
            tf = false;
            reason = '';
            if ~isstruct(ref) || ~isfield(ref,'variableName') || ...
                    isempty(ref.variableName)
                strategyName = 'INTERVAL2';
                if isfield(cached,'cacheMetadata') && ...
                        isstruct(cached.cacheMetadata) && ...
                        isfield(cached.cacheMetadata,'intervalMode') && ...
                        ~isempty(cached.cacheMetadata.intervalMode)
                    strategyName = char(cached.cacheMetadata.intervalMode);
                end
                if isfield(cached,'dij_interval') && ...
                        planWorkflow.precompute.IntervalDoseInfluence.isIntervalDijUsable( ...
                        cached.dij_interval,strategyName) && ...
                        isfield(cached,'dijIntervalContext') && ...
                        planWorkflow.precompute.IntervalDoseInfluence.isIntervalDijContextUsable( ...
                        cached.dijIntervalContext,cached.dij_interval)
                    tf = true;
                else
                    reason = ['persisted ref does not declare a cache ' ...
                        'variable and full interval payload is not usable'];
                end
                return;
            end
            variableName = char(ref.variableName);
            if ~isfield(cached,variableName)
                reason = sprintf('cache does not contain variable "%s"', ...
                    variableName);
                return;
            end
            switch variableName
                case 'dij_interval'
                    strategyName = 'INTERVAL2';
                    if isfield(cached,'cacheMetadata') && ...
                            isstruct(cached.cacheMetadata) && ...
                            isfield(cached.cacheMetadata,'intervalMode') && ...
                            ~isempty(cached.cacheMetadata.intervalMode)
                        strategyName = char(cached.cacheMetadata.intervalMode);
                    end
                    tf = planWorkflow.precompute.IntervalDoseInfluence.isIntervalDijUsable( ...
                        cached.dij_interval,strategyName);
                    if ~tf
                        reason = 'cached interval dij payload is not usable';
                    end
                case 'dijIntervalContext'
                    tf = planWorkflow.precompute.IntervalDoseInfluence.isStandaloneIntervalDijContextUsable( ...
                        cached.dijIntervalContext,ref);
                    if ~tf
                        reason = 'cached interval dij context is not usable';
                    end
                otherwise
                    reason = sprintf( ...
                        'unsupported interval cache variable "%s"', ...
                        variableName);
            end
        end

        function pln = createNominalOptimizationPlan(robustData,dijNominal)
            pln = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.createNominalOptimizationPlan( ...
                robustData.pln,dijNominal,'dij_interval');
        end
    end

    methods (Static, Access = private)
        function robustData = ensurePlanContext(~,robustData)
            if ~isfield(robustData,'planConfig') || ...
                    isempty(robustData.planConfig)
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingRobustPlanConfig'], ...
                    'Robust data must contain an explicit planConfig.');
            end
            if ~isfield(robustData,'strategy') || isempty(robustData.strategy)
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingStrategy'], ...
                    'Robust data must contain an explicit strategy.');
            end
        end

        function ct = ctForRefScen(robustData)
            ct = struct();
            if isstruct(robustData) && isfield(robustData,'ct')
                ct = robustData.ct;
            end
        end

        function requireRobustInput(robustData)
            if ~isfield(robustData,'dijRobust') || ...
                    isempty(robustData.dijRobust)
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingRobustInputDij'], ...
                    ['INTERVAL legacy precompute requires explicit ' ...
                    'robustData.dijRobust as input.']);
            end
        end

        function robustData = stripTransientRobustInput(robustData)
            if isfield(robustData,'dijRobust')
                robustData = rmfield(robustData,'dijRobust');
            end
            if isfield(robustData,'dijRobustPrecomputingTiming')
                robustData = rmfield(robustData,'dijRobustPrecomputingTiming');
            end
            if isfield(robustData,'dijRobustPrecomputingSize')
                robustData = rmfield(robustData,'dijRobustPrecomputingSize');
            end
        end

        function values = asCellstr(values)
            if ischar(values) || (isstring(values) && isscalar(values))
                values = {char(values)};
            elseif isstring(values)
                values = cellstr(values);
            elseif isempty(values)
                values = {};
            end
        end

        function config = applyParallelOptions(config,context)
            runConfig = [];
            if isstruct(context) && isfield(context,'runConfig')
                runConfig = context.runConfig;
            end
            parallelOptions = ...
                planWorkflow.config.Resources.doseParallelOptions( ...
                runConfig);
            if ~isempty(fieldnames(parallelOptions))
                config.parallelOptions = parallelOptions;
            end
        end

        function tf = isIntervalDijUsable(dijInterval,strategyName)
            tf = isstruct(dijInterval) && isfield(dijInterval,'center') && ...
                isfield(dijInterval,'radius') && ...
                isfield(dijInterval,'quantity') && ...
                isfield(dijInterval,'quantityField');
            if tf && strcmp(strategyName,'INTERVAL3')
                tf = isfield(dijInterval,'OARSubIx') && ...
                    isfield(dijInterval,'OARRadiusFactor') && ...
                    isfield(dijInterval,'OARRadiusRank');
            end
        end

        function tf = isIntervalDijContextUsable( ...
                dijIntervalContext,dij_interval)
            tf = isstruct(dijIntervalContext) && ...
                isfield(dijIntervalContext,'totalNumOfBixels') && ...
                dijIntervalContext.totalNumOfBixels == ...
                size(dij_interval.center,2) && ...
                isfield(dijIntervalContext,'physicalDose') && ...
                iscell(dijIntervalContext.physicalDose) && ...
                ~isempty(dijIntervalContext.physicalDose) && ...
                isequal(size(dijIntervalContext.physicalDose{1}), ...
                size(dij_interval.center));
        end

        function tf = isStandaloneIntervalDijContextUsable( ...
                dijIntervalContext,ref)
            tf = isstruct(dijIntervalContext) && ...
                isfield(dijIntervalContext,'totalNumOfBixels') && ...
                isfield(dijIntervalContext,'physicalDose') && ...
                iscell(dijIntervalContext.physicalDose) && ...
                ~isempty(dijIntervalContext.physicalDose);
            if ~tf
                return;
            end
            if isstruct(ref) && isfield(ref,'totalNumOfBixels') && ...
                    ~isempty(ref.totalNumOfBixels)
                tf = dijIntervalContext.totalNumOfBixels == ...
                    ref.totalNumOfBixels;
            end
        end

        function tf = isIntervalDijContextCompatibleWithStf( ...
                dijIntervalContext,stf)
            tf = isstruct(dijIntervalContext) && ...
                isfield(dijIntervalContext,'totalNumOfBixels') && ...
                ~isempty(stf) && isstruct(stf) && ...
                isfield(stf,'totalNumOfBixels') && ...
                dijIntervalContext.totalNumOfBixels == ...
                sum([stf.totalNumOfBixels]);
        end

        function tf = isCachedNominalDijContextUsable( ...
                cached,robustData,dij_interval)
            if ~planWorkflow.precompute.IntervalDoseInfluence.needsRobustNominalDij( ...
                    robustData)
                tf = true;
                return;
            end

            tf = isfield(cached,'dijIntervalContext') && ...
                planWorkflow.precompute.IntervalDoseInfluence.isNominalDijContextUsable( ...
                cached.dijIntervalContext,dij_interval);
        end

        function tf = isMetadataForPlan(cacheMetadata,robustData)
            tf = isstruct(cacheMetadata);
            if ~tf
                return;
            end
            if isfield(cacheMetadata,'planId') && ...
                    isfield(robustData.planConfig,'id') && ...
                    ~strcmp(char(cacheMetadata.planId), ...
                    char(robustData.planConfig.id))
                tf = false;
                return;
            end
            if isfield(cacheMetadata,'robustnessMode') && ...
                    isfield(robustData.planConfig,'robustnessMode') && ...
                    ~strcmp(char(cacheMetadata.robustnessMode), ...
                    char(robustData.planConfig.robustnessMode))
                tf = false;
            end
        end

        function [tf,reason] = isScenarioCompatibleForMode( ...
                cacheMetadata,robustData,compatibilityMode,ref)
            switch char(compatibilityMode)
                case 'discovery'
                    [tf,reason] = ...
                        planWorkflow.precompute.PrecomputeCacheCompatibility.isDiscoveryScenarioCompatible( ...
                        cacheMetadata,robustData);
                case 'rehydrate'
                    [tf,reason] = ...
                        planWorkflow.precompute.PrecomputeCacheCompatibility.isPersistedRefScenarioCompatible( ...
                        cacheMetadata,ref);
                otherwise
                    tf = false;
                    reason = sprintf( ...
                        'unknown cache compatibility mode "%s"', ...
                        char(compatibilityMode));
            end
        end

        function tf = isMetadataIntervalContextCompatible( ...
                cacheMetadata,robustData)
            tf = true;
            if ~isfield(cacheMetadata,'cacheIdentity') || ...
                    ~isstruct(cacheMetadata.cacheIdentity) || ...
                    ~isfield(cacheMetadata.cacheIdentity,'interval') || ...
                    ~isstruct(cacheMetadata.cacheIdentity.interval)
                return;
            end
            intervalIdentity = cacheMetadata.cacheIdentity.interval;
            expected = ...
                planWorkflow.precompute.IntervalDoseInfluence.expectedIntervalIdentity( ...
                robustData);
            fields = {'mode','quantity','refScen','scen4D', ...
                'targetName','radiusMode','KMode','kmax', ...
                'retentionThreshold'};
            for fieldIx = 1:numel(fields)
                fieldName = fields{fieldIx};
                if isfield(intervalIdentity,fieldName) && ...
                        isfield(expected,fieldName) && ...
                        ~isequal(intervalIdentity.(fieldName), ...
                        expected.(fieldName))
                    tf = false;
                    return;
                end
            end
            if isfield(intervalIdentity,'robustOarNames') && ...
                    isfield(expected,'robustOarNames') && ...
                    ~isequal(intervalIdentity.robustOarNames, ...
                    expected.robustOarNames)
                tf = false;
            end
        end

        function tf = isMetadataCstCompatible(cacheMetadata,robustData)
            tf = true;
            if ~isfield(cacheMetadata,'cacheIdentity') || ...
                    ~isstruct(cacheMetadata.cacheIdentity) || ...
                    ~isfield(cacheMetadata.cacheIdentity,'cst') || ...
                    ~isfield(robustData,'cst')
                return;
            end
            tf = strcmp( ...
                planWorkflow.cache.CacheIdentity.valueHash( ...
                cacheMetadata.cacheIdentity.cst), ...
                planWorkflow.cache.CacheIdentity.valueHash( ...
                planWorkflow.cache.CacheIdentity.cstIdentity( ...
                robustData.cst)));
        end

        function tf = isMetadataStfCompatible(cacheMetadata,robustData)
            tf = true;
            if ~isfield(cacheMetadata,'cacheIdentity') || ...
                    ~isstruct(cacheMetadata.cacheIdentity) || ...
                    ~isfield(cacheMetadata.cacheIdentity,'stf') || ...
                    ~isfield(robustData,'stf') || isempty(robustData.stf)
                return;
            end
            tf = strcmp( ...
                planWorkflow.cache.CacheIdentity.valueHash( ...
                cacheMetadata.cacheIdentity.stf), ...
                planWorkflow.cache.CacheIdentity.valueHash( ...
                planWorkflow.cache.DoseInfluenceCache.stfSignature( ...
                robustData.stf)));
        end

        function expected = expectedIntervalIdentity(robustData)
            expected = struct();
            expected.mode = robustData.strategy.name;
            if isfield(robustData,'quantityOpt') && ...
                    ~isempty(robustData.quantityOpt)
                expected.quantity = robustData.quantityOpt;
            end
            expected.refScen = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.effectiveRefScen( ...
                planWorkflow.precompute.IntervalDoseInfluence.ctForRefScen( ...
                robustData));
            expected.scen4D = 1;
            if isfield(robustData,'pln') && ...
                    isfield(robustData.pln,'propOpt') && ...
                    isstruct(robustData.pln.propOpt) && ...
                    isfield(robustData.pln.propOpt,'scen4D') && ...
                    ~isempty(robustData.pln.propOpt.scen4D)
                expected.scen4D = robustData.pln.propOpt.scen4D;
            end
            if isfield(robustData,'objectiveInfo')
                expected.targetName = ...
                    planWorkflow.precompute.IntervalDoseInfluence.optionalStructField( ...
                    robustData.objectiveInfo,'targetName','');
                expected.robustOarNames = ...
                    planWorkflow.precompute.IntervalDoseInfluence.optionalStructField( ...
                    robustData.objectiveInfo,'robustOarNames',{});
            end
            if isfield(robustData.planConfig,'robustnessOptions') && ...
                    isfield(robustData.planConfig.robustnessOptions, ...
                    'radiusMode')
                expected.radiusMode = ...
                    robustData.planConfig.robustnessOptions.radiusMode;
            end
            if strcmp(robustData.strategy.name,'INTERVAL3') && ...
                    isfield(robustData.planConfig,'robustnessOptions') && ...
                    isfield(robustData.planConfig.robustnessOptions, ...
                    'KMode')
                expected.KMode = ...
                    robustData.planConfig.robustnessOptions.KMode;
                expected.kmax = ...
                    robustData.planConfig.robustnessOptions.kmax;
                expected.retentionThreshold = ...
                    robustData.planConfig.robustnessOptions.retentionThreshold;
            end
        end

        function tf = isNominalDijContextUsable(dijContext,dij_interval)
            tf = false;
            if ~isstruct(dijContext) || ~isstruct(dij_interval) || ...
                    ~isfield(dij_interval,'center') || ...
                    ~isfield(dijContext,'totalNumOfBixels') || ...
                    dijContext.totalNumOfBixels ~= size(dij_interval.center,2)
                return;
            end

            quantityField = ...
                planWorkflow.precompute.IntervalDoseInfluence.intervalQuantityField( ...
                dij_interval);
            tf = ...
                planWorkflow.precompute.IntervalDoseInfluence.isDijQuantityUsable( ...
                dijContext,quantityField,size(dij_interval.center));
        end

        function tf = needsRobustNominalDij(robustData)
            tf = isstruct(robustData) && ...
                isfield(robustData,'planConfig') && ...
                isstruct(robustData.planConfig) && ...
                isfield(robustData.planConfig,'requiresIntervalDij') && ...
                logical(robustData.planConfig.requiresIntervalDij) && ...
                isfield(robustData.planConfig,'hasNominalObjectives') && ...
                logical(robustData.planConfig.hasNominalObjectives);
        end

        function robustData = attachNominalDijFromContext(robustData)
            if ~isfield(robustData,'dijIntervalContext') || ...
                    isempty(robustData.dijIntervalContext)
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingNominalDijContext'], ...
                    ['INTERVAL optimization with nominal objectives ' ...
                    'requires dijIntervalContext from matRad.']);
            end
            if ~planWorkflow.precompute.IntervalDoseInfluence.isNominalDijContextUsable( ...
                    robustData.dijIntervalContext,robustData.dij_interval)
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'InconsistentNominalDijContext'], ...
                    ['dijIntervalContext returned by matRad is not ' ...
                    'compatible with dij_interval.']);
            end
            robustData.dijNominal = robustData.dijIntervalContext;
            robustData.plnNominal = ...
                planWorkflow.precompute.IntervalDoseInfluence.createNominalOptimizationPlan( ...
                robustData,robustData.dijNominal);
            robustData.stfNominal = robustData.stf;
        end

        function [tf,robustData] = tryAttachCachedNominalDij( ...
                context,robustData,cacheFile)
            tf = true;
            try
                robustData = ...
                    planWorkflow.precompute.IntervalDoseInfluence.attachNominalDijFromContext( ...
                    robustData);
            catch ME
                expectedErrors = { ...
                    ['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingNominalDijContext'], ...
                    ['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'InconsistentNominalDijContext']};
                if ~any(strcmp(ME.identifier,expectedErrors))
                    rethrow(ME);
                end
                context.log(sprintf( ...
                    'Ignoring stale interval dij cache: %s.',cacheFile));
                tf = false;
            end
        end

        function robustData = stripStoredIntervalPlanPayload(robustData)
            if isfield(robustData,'pln')
                robustData.pln = ...
                    planWorkflow.precompute.IntervalDoseInfluence.removeIntervalDijFromPlan( ...
                    robustData.pln);
            end
            if isfield(robustData,'plnForOptimization')
                robustData.plnForOptimization = ...
                    planWorkflow.precompute.IntervalDoseInfluence.removeIntervalDijFromPlan( ...
                    robustData.plnForOptimization);
            end
            if isfield(robustData,'plnNominal')
                robustData.plnNominal = ...
                    planWorkflow.precompute.IntervalDoseInfluence.removeIntervalDijFromPlan( ...
                    robustData.plnNominal);
            end
        end

        function pln = removeIntervalDijFromPlan(pln)
            pln = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.removePlanPayload( ...
                pln,'dij_interval');
        end

        function pln = attachIntervalDijToPlan(pln,dij_interval)
            pln = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.attachPlanPayload( ...
                pln,'dij_interval',dij_interval);
        end

        function quantityField = intervalQuantityField(dij_interval)
            quantityField = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.quantityField( ...
                dij_interval,'physicalDose');
        end

        function tf = isDijQuantityUsable(dij,quantityField,expectedSize)
            tf = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.isDijQuantityUsable( ...
                dij,quantityField,expectedSize);
        end

        function value = optionalStructField(input,fieldName,defaultValue)
            if isstruct(input) && isfield(input,fieldName)
                value = input.(fieldName);
            else
                value = defaultValue;
            end
        end

        function label = executionModeLabel(useScenarioBatch)
            if logical(useScenarioBatch)
                label = 'scenario-batch';
            else
                label = 'precomputed robust dij';
            end
        end
    end
end
