classdef IntervalDoseInfluence
    % IntervalDoseInfluence Owns INTERVAL2/INTERVAL3 dij_interval flow.

    methods (Static)
        function [cacheHit,robustData] = loadCached(context,robustData)
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.ensurePlanContext( ...
                context,robustData);
            cacheHit = false;
            cacheContext = ...
                planWorkflow.precompute.IntervalDoseInfluence.cacheContext( ...
                context,robustData);
            cacheFile = context.cache.file( ...
                planWorkflow.precompute.IntervalDoseInfluence.cacheTag( ...
                robustData),robustData.pln,cacheContext);
            if ~context.runConfig.useCache || ~isfile(cacheFile)
                return;
            end

            cached = load(cacheFile);
            if ~isfield(cached,'dij_interval') || ...
                    ~isfield(cached,'dij_intervalContext')
                context.log(sprintf( ...
                    'Ignoring stale interval dij cache: %s.',cacheFile));
                return;
            end

            if ~planWorkflow.precompute.IntervalDoseInfluence.isCacheCompatible( ...
                    context,cached,robustData)
                context.log(sprintf( ...
                    'Ignoring stale interval dij cache: %s.',cacheFile));
                return;
            end

            robustData.dij_interval = cached.dij_interval;
            if ~isfield(robustData.pln,'propOpt') || ...
                    ~isstruct(robustData.pln.propOpt)
                robustData.pln.propOpt = struct();
            end
            robustData.pln.propOpt.dij_interval = cached.dij_interval;
            robustData.dij_intervalContext = cached.dij_intervalContext;
            robustData.plnForOptimization = ...
                planWorkflow.precompute.IntervalDoseInfluence.createOptimizationPlan( ...
                robustData);
            cacheHit = true;
            context.log(sprintf('Loaded cached interval dij: %s.', ...
                cacheFile));
        end

        function robustData = precompute(context,robustData)
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.ensurePlanContext( ...
                context,robustData);
            intervalConfig = ...
                planWorkflow.precompute.IntervalDoseInfluence.doseConfig( ...
                context,robustData);
            context.log(sprintf( ...
                'Precomputing %s interval dose influence data.', ...
                robustData.strategy.name));

            switch robustData.strategy.name
                case 'INTERVAL2'
                    [plnForOptimization,dij_intervalContext] = ...
                        matRad_calcDoseInterval2( ...
                        robustData.ct,robustData.cst,robustData.stf, ...
                        robustData.pln,robustData.dij,intervalConfig);
                case 'INTERVAL3'
                    [plnForOptimization,dij_intervalContext] = ...
                        matRad_calcDoseInterval3( ...
                        robustData.ct,robustData.cst,robustData.stf, ...
                        robustData.pln,robustData.dij,intervalConfig);
                otherwise
                    error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                        'UnsupportedStrategy'], ...
                        'Unsupported interval strategy "%s".', ...
                        robustData.strategy.name);
            end

            robustData.plnForOptimization = plnForOptimization;
            robustData.dij_interval = plnForOptimization.propOpt.dij_interval;
            robustData.pln.propOpt.dij_interval = robustData.dij_interval;
            robustData.dij_intervalContext = dij_intervalContext;
            planWorkflow.precompute.IntervalDoseInfluence.cache( ...
                context,robustData);
        end

        function cache(context,robustData)
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.ensurePlanContext( ...
                context,robustData);
            if ~context.runConfig.writeCache
                return;
            end

            cacheContext = ...
                planWorkflow.precompute.IntervalDoseInfluence.cacheContext( ...
                context,robustData);
            tag = planWorkflow.precompute.IntervalDoseInfluence.cacheTag( ...
                robustData);
            cacheFile = context.cache.file(tag,robustData.pln, ...
                cacheContext);
            dij_interval = robustData.dij_interval; %#ok<NASGU>
            dij_intervalContext = robustData.dij_intervalContext; %#ok<NASGU>
            cacheMetadata = context.cache.metadata( ...
                tag,robustData.pln,cacheContext); %#ok<NASGU>
            cacheMetadata.intervalMode = robustData.strategy.name;
            cacheMetadata.intervalQuantity = dij_interval.quantity;
            cacheMetadata.intervalQuantityField = dij_interval.quantityField;
            context.cache.ensureFileFolder(cacheFile);
            builtin('save',cacheFile,'dij_interval', ...
                'dij_intervalContext','cacheMetadata','-v7.3');
            context.log(sprintf('Cached interval dij: %s.', ...
                cacheFile));
        end

        function robustData = useForOptimization(robustData)
            if ~isfield(robustData,'dij_intervalContext') || ...
                    isempty(robustData.dij_intervalContext)
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingIntervalDijContext'], ...
                    'INTERVAL optimization requires dij_intervalContext.');
            end
            robustData.dij = robustData.dij_intervalContext;
            if ~isfield(robustData,'plnForOptimization') || ...
                    isempty(robustData.plnForOptimization)
                robustData.plnForOptimization = ...
                    planWorkflow.precompute.IntervalDoseInfluence.createOptimizationPlan( ...
                    robustData);
            end
            robustData.usesIntervalDijForOptimization = true;
        end

        function pln = optimizationPlan(robustData)
            if isfield(robustData,'plnForOptimization') && ...
                    ~isempty(robustData.plnForOptimization)
                pln = robustData.plnForOptimization;
            else
                pln = robustData.pln;
            end
        end

        function robustData = restoreOptimizationPlan(robustData)
            if ~isfield(robustData,'dij_interval') || ...
                    isempty(robustData.dij_interval)
                return;
            end
            if ~isfield(robustData.pln,'propOpt') || ...
                    ~isstruct(robustData.pln.propOpt)
                robustData.pln.propOpt = struct();
            end
            robustData.pln.propOpt.dij_interval = robustData.dij_interval;
            if isfield(robustData,'dij_intervalContext') && ...
                    ~isempty(robustData.dij_intervalContext)
                robustData.plnForOptimization = ...
                    planWorkflow.precompute.IntervalDoseInfluence.createOptimizationPlan( ...
                    robustData);
            end
        end

        function pln = createOptimizationPlan(robustData)
            pln = robustData.pln;
            if ~isfield(pln,'propOpt') || ~isstruct(pln.propOpt)
                pln.propOpt = struct();
            end
            pln.propOpt.dij_interval = robustData.dij_interval;
            pln.multScen = robustData.dij_intervalContext.scenarioModel;
        end

        function contextOut = cacheContext(context,robustData)
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.ensurePlanContext( ...
                context,robustData);
            contextOut = struct();
            if isfield(robustData,'cst')
                contextOut.cst = robustData.cst;
            end
            interval = struct();
            interval.mode = robustData.strategy.name;
            if isfield(context.data,'quantityOpt') && ...
                    ~isempty(context.data.quantityOpt)
                interval.quantity = context.data.quantityOpt;
            else
                interval.quantity = '';
            end
            if isfield(robustData,'ct') && isfield(robustData.ct,'refScen')
                interval.refScen = robustData.ct.refScen;
            else
                interval.refScen = [];
            end
            interval.scen4D = 1;
            if isfield(robustData,'pln') && ...
                    isfield(robustData.pln,'propOpt') && ...
                    isstruct(robustData.pln.propOpt) && ...
                    isfield(robustData.pln.propOpt,'scen4D') && ...
                    ~isempty(robustData.pln.propOpt.scen4D)
                interval.scen4D = robustData.pln.propOpt.scen4D;
            end
            if isfield(robustData,'objectiveInfo')
                interval.targetName = ...
                    planWorkflow.precompute.IntervalDoseInfluence.optionalStructField( ...
                    robustData.objectiveInfo,'targetName','');
                interval.robustOarNames = ...
                    planWorkflow.precompute.IntervalDoseInfluence.optionalStructField( ...
                    robustData.objectiveInfo,'robustOarNames',{});
            else
                interval.targetName = '';
                interval.robustOarNames = {};
            end
            if strcmp(robustData.strategy.name,'INTERVAL3')
                interval.KMode = robustData.planConfig.strategyOptions.KMode;
                interval.kmax = robustData.planConfig.strategyOptions.kmax;
                interval.retentionThreshold = ...
                    robustData.planConfig.strategyOptions.retentionThreshold;
            end
            contextOut.interval = interval;
            if isfield(robustData,'stf') && ~isempty(robustData.stf)
                contextOut.stf = context.cache.stfSignature( ...
                    robustData.stf);
            end
        end

        function tag = cacheTag(robustData)
            if ~isfield(robustData,'planConfig') || ...
                    ~isfield(robustData.planConfig,'id') || ...
                    isempty(robustData.planConfig.id)
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingRobustPlanId'], ...
                    'Interval dose cache tag requires a robust plan id.');
            end
            tag = ['interval_' char(robustData.planConfig.id)];
        end

        function intervalConfig = doseConfig(context,robustData)
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.ensurePlanContext( ...
                context,robustData);
            intervalConfig = struct();
            if isfield(context.data,'quantityOpt') && ...
                    ~isempty(context.data.quantityOpt)
                intervalConfig.Quantity = context.data.quantityOpt;
            end
            if isfield(robustData.ct,'refScen') && ...
                    ~isempty(robustData.ct.refScen)
                intervalConfig.refScen = robustData.ct.refScen;
            end
            intervalConfig.ProgressLevel = 'summary';
            intervalConfig.targetStructSel = ...
                robustData.cst(robustData.objectiveInfo.ixTarget,2);
            intervalConfig.OARStructSel = ...
                planWorkflow.precompute.IntervalDoseInfluence.asCellstr( ...
                robustData.objectiveInfo.robustOarNames);

            if strcmp(robustData.strategy.name,'INTERVAL3')
                intervalConfig.UseParallel = true;
                intervalConfig.KMode = ...
                    robustData.planConfig.strategyOptions.KMode;
                intervalConfig.KMax = ...
                    robustData.planConfig.strategyOptions.kmax;
                intervalConfig.RetentionThreshold = ...
                    robustData.planConfig.strategyOptions.retentionThreshold;
            end
        end

        function tf = isCacheCompatible(context,cached,robustData)
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.ensurePlanContext( ...
                context,robustData);
            tf = isfield(cached,'cacheMetadata') && ...
                context.cache.isIdentityCompatible(cached, ...
                planWorkflow.precompute.IntervalDoseInfluence.cacheTag( ...
                robustData),robustData.pln, ...
                planWorkflow.precompute.IntervalDoseInfluence.cacheContext( ...
                context,robustData)) && ...
                isfield(cached.cacheMetadata,'intervalMode') && ...
                strcmp(cached.cacheMetadata.intervalMode, ...
                robustData.strategy.name) && ...
                isfield(cached.cacheMetadata,'scenarioFingerprint') && ...
                strcmp(cached.cacheMetadata.scenarioFingerprint, ...
                robustData.pln.multScen.fingerprint()) && ...
                planWorkflow.precompute.IntervalDoseInfluence.isIntervalDijUsable( ...
                cached.dij_interval,robustData.strategy.name) && ...
                planWorkflow.precompute.IntervalDoseInfluence.isIntervalDijContextUsable( ...
                cached.dij_intervalContext,cached.dij_interval) && ...
                planWorkflow.precompute.IntervalDoseInfluence.isIntervalDijContextCompatibleWithStf( ...
                cached.dij_intervalContext,robustData.stf);
        end
    end

    methods (Static, Access = private)
        function robustData = ensurePlanContext(context,robustData)
            if ~isfield(robustData,'planConfig') || ...
                    isempty(robustData.planConfig)
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingRobustPlanConfig'], ...
                    'Robust data must contain an explicit planConfig.');
            end
            if ~isfield(robustData,'strategy') || isempty(robustData.strategy)
                error(['planWorkflow:precompute:IntervalDoseInfluence:' ...
                    'MissingStrategy'], ...
                    'Robust data must contain an explicit strategy.');
            end
        end

        function values = asCellstr(values)
            if ischar(values) || (isstring(values) && isscalar(values))
                values = {char(values)};
            elseif isstring(values)
                values = cellstr(values);
            elseif isempty(values)
                values = {};
            end
        end

        function tf = isIntervalDijUsable(dijInterval,strategyName)
            tf = isstruct(dijInterval) && isfield(dijInterval,'center') && ...
                isfield(dijInterval,'radius') && ...
                isfield(dijInterval,'quantity') && ...
                isfield(dijInterval,'quantityField');
            if tf && strcmp(strategyName,'INTERVAL3')
                tf = isfield(dijInterval,'OARSubIx') && ...
                    isfield(dijInterval,'U') && ...
                    isfield(dijInterval,'S') && ...
                    isfield(dijInterval,'V');
            end
        end

        function tf = isIntervalDijContextUsable( ...
                dij_intervalContext,dij_interval)
            tf = isstruct(dij_intervalContext) && ...
                isfield(dij_intervalContext,'totalNumOfBixels') && ...
                dij_intervalContext.totalNumOfBixels == ...
                size(dij_interval.center,2) && ...
                isfield(dij_intervalContext,'physicalDose') && ...
                iscell(dij_intervalContext.physicalDose) && ...
                ~isempty(dij_intervalContext.physicalDose) && ...
                isequal(size(dij_intervalContext.physicalDose{1}), ...
                size(dij_interval.center));
        end

        function tf = isIntervalDijContextCompatibleWithStf( ...
                dij_intervalContext,stf)
            tf = isstruct(dij_intervalContext) && ...
                isfield(dij_intervalContext,'totalNumOfBixels') && ...
                ~isempty(stf) && isstruct(stf) && ...
                isfield(stf,'totalNumOfBixels') && ...
                dij_intervalContext.totalNumOfBixels == ...
                sum([stf.totalNumOfBixels]);
        end

        function value = optionalStructField(input,fieldName,defaultValue)
            if isstruct(input) && isfield(input,fieldName)
                value = input.(fieldName);
            else
                value = defaultValue;
            end
        end
    end
end
