classdef PrepareService
    % PrepareService Owns geometry, template and reference plan preparation.

    methods (Static)
        function prepared = run(context)
            runConfig = context.runConfig;
            context.log('Preparing robust workflow geometry, objectives, plan, and stf.');

            [ct,cst] = planWorkflow.io.loadGeometry(runConfig,"optimization");
            [cst,normalizationReport] = ...
                planWorkflow.structures.normalizeNames(cst,runConfig,ct);
            planWorkflow.structures.NormalizationReportLogger.log( ...
                context.log,'Optimization structure normalization', ...
                normalizationReport);
            [ct,cst] = planWorkflow.precompute.PrepareService.ensureDeformationFields( ...
                ct,cst);
            [cst,objectiveInfo] = ...
                planWorkflow.precompute.PrepareService.prepareReferenceObjectives( ...
                runConfig,context.planTemplate,ct,cst);
            [pln,quantityOpt,quantityVis] = planWorkflow.plan.Plan.create( ...
                runConfig,ct,cst,context.planTemplate);
            [cst,pln] = ...
                planWorkflow.precompute.PrepareService.applyReferenceRobustness( ...
                runConfig,cst,pln,objectiveInfo);

            analysis = planWorkflow.config.Analysis.normalize(runConfig.analysis);
            analysis = planWorkflow.config.Analysis.applyPrescriptionDefaults( ...
                analysis,objectiveInfo.prescriptionDose,pln);
            stf = matRad_generateStf(ct,cst,pln);

            prepared = struct();
            prepared.ct = ct;
            prepared.cst = cst;
            prepared.pln = pln;
            prepared.stf = stf;
            prepared.quantityOpt = quantityOpt;
            prepared.quantityVis = quantityVis;
            prepared.objectiveInfo = objectiveInfo;
            prepared.analysis = analysis;
            prepared.structureNormalizationReport = normalizationReport;
        end

        function [cst,objectiveInfo] = prepareReferenceObjectives( ...
                runConfig,template,ct,cst)
            [cst,objectiveInfo] = planWorkflow.templates.PlanTemplate.applyObjectives( ...
                runConfig,[],cst,template,'reference');
            planWorkflow.io.saveGeometry(runConfig,"optimization",ct,cst);

            cst{objectiveInfo.ixTarget,5}.Visible = true;
            [cst,objectiveInfo] = ...
                planWorkflow.precompute.PrepareService.addDefaultRings( ...
                runConfig,template,cst,ct,objectiveInfo);
        end

        function [cst,objectiveInfo] = prepareTemplateStructures( ...
                runConfig,template,ct,cst)
            [cst,objectiveInfo] = planWorkflow.templates.PlanTemplate.applyObjectives( ...
                runConfig,[],cst,template,'reference');
            [cst,objectiveInfo] = ...
                planWorkflow.precompute.PrepareService.addDefaultRings( ...
                runConfig,template,cst,ct,objectiveInfo);
        end

        function [cst,objectiveInfo] = addDefaultRings( ...
                runConfig,template,cst,ct,objectiveInfo)
            [cst,objectiveInfo] = ...
                planWorkflow.templates.PlanTemplate.addDerivedStructures( ...
                runConfig,cst,ct,objectiveInfo,template);
        end

        function [cst,pln] = applyReferenceRobustness( ...
                runConfig,cst,pln,objectiveInfo)
            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            referenceStrategy = ...
                planWorkflow.robustness.AbstractStrategy.create( ...
                reference.strategy);
            if referenceStrategy.requiresIntervalDij()
                error(['planWorkflow:precompute:PrepareService:' ...
                    'ReferenceIntervalUnsupported'], ...
                    ['Reference INTERVAL robustness requires a dedicated ' ...
                     'reference interval optimization flow. Use INTERVAL ' ...
                     'in the robust plan until that flow is implemented.']);
            end

            [cst,pln] = referenceStrategy.apply( ...
                cst,pln,objectiveInfo, ...
                planWorkflow.precompute.PrepareService.referenceRunConfig( ...
                runConfig,reference));
        end

        function runConfig = referenceRunConfig(runConfig,reference)
            plan = struct('strategy',reference.strategy, ...
                'strategyOptions',reference.strategyOptions, ...
                'variants',reference.variants);
            runConfig = ...
                planWorkflow.config.RobustPlanConfig.variantRunConfig( ...
                runConfig,plan,1);
        end

        function multScen = referenceScenarioModel(runConfig,data)
            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            scenarioConfig = ...
                planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                reference.scenario);
            scenarioConfig = planWorkflow.config.ScenarioSpec.withBeamCount( ...
                scenarioConfig,data.pln);
            multScen = planWorkflow.scenario.createModel(data.ct, ...
                scenarioConfig.scen_mode,scenarioConfig,'optimization');
        end

        function [ct,cst] = ensureDeformationFields(ct,cst)
            if ct.numOfCtScen > 1
                needsContours = ct.numOfCtScen > numel(cst{1,4});
                if needsContours
                    metadata.nItera = 100;
                    metadata.dvfType = 'push';
                    register = matRad_ElasticImageRegistration(ct,cst,1, ...
                        metadata);
                    [ct,cst] = register.propContours();
                end

                if ~planWorkflow.precompute.PrepareService.hasDvfType(ct, ...
                        'pull')
                    metadata.nItera = 100;
                    metadata.dvfType = 'pull';
                    register = matRad_ElasticImageRegistration(ct,cst,1, ...
                        metadata);
                    ct = register.calcDVF();
                end
            end
        end

        function tf = hasDvfType(ct,dvfType)
            if ~isfield(ct,'dvf') || isempty(ct.dvf)
                tf = false;
                return;
            end

            currentDvfType = '';
            if isfield(ct,'dvfMetadata') && ...
                    isfield(ct.dvfMetadata,'dvfType') && ...
                    ~isempty(ct.dvfMetadata.dvfType)
                currentDvfType = char(ct.dvfMetadata.dvfType);
            elseif isfield(ct,'dvfType') && ~isempty(ct.dvfType)
                currentDvfType = char(ct.dvfType);
            end

            tf = strcmp(currentDvfType,dvfType);
        end
    end
end
