classdef ProbDoseInfluence
    % ProbDoseInfluence Owns probabilistic dij_prob flow.

    methods (Static)
        function [cacheHit,robustData] = loadCached(context,robustData)
            robustData = ...
                planWorkflow.precompute.ProbDoseInfluence.ensurePlanContext( ...
                context,robustData);
            cacheHit = false;
            cacheContext = ...
                planWorkflow.precompute.ProbDoseInfluence.cacheContext( ...
                context,robustData);
            cacheFile = context.cache.file( ...
                planWorkflow.precompute.ProbDoseInfluence.cacheTag( ...
                robustData),robustData.pln,cacheContext);
            if ~context.runConfig.useCache || ~isfile(cacheFile)
                return;
            end

            cached = load(cacheFile);
            if ~isfield(cached,'dij_prob') || ...
                    ~isfield(cached,'dijProbContext')
                context.log(sprintf( ...
                    'Ignoring stale PROB2 dij cache: %s.',cacheFile));
                return;
            end

            if ~planWorkflow.precompute.ProbDoseInfluence.isCacheCompatible( ...
                    context,cached,robustData)
                context.log(sprintf( ...
                    'Ignoring stale PROB2 dij cache: %s.',cacheFile));
                return;
            end
            dijPrecomputingTiming = ...
                planWorkflow.performance.PrecomputeTiming.fromCacheMetadata( ...
                cached.cacheMetadata);
            dijPrecomputingSize = ...
                planWorkflow.performance.PrecomputeSize.fromCacheMetadata( ...
                cached.cacheMetadata);
            if isempty(dijPrecomputingTiming) || ...
                    isempty(dijPrecomputingSize)
                context.log(sprintf( ...
                    'Ignoring stale PROB2 dij cache: %s.',cacheFile));
                return;
            end

            robustData.dijProbContext = cached.dijProbContext;
            robustData.dij_prob = cached.dij_prob;
            robustData.dijCacheRefs.prob = ...
                planWorkflow.cache.DoseInfluenceCacheRef.create( ...
                'prob', ...
                planWorkflow.precompute.ProbDoseInfluence.cacheTag( ...
                robustData),cacheFile,context.cache.cachePath, ...
                cached.cacheMetadata,{'dij_prob','dijProbContext'}, ...
                planWorkflow.cache.DoseInfluenceCacheRef.totalNumOfBixels( ...
                cached.dijProbContext));
            robustData.dijPrecomputingTiming = dijPrecomputingTiming;
            robustData.dijPrecomputingSize = dijPrecomputingSize;
            robustData = ...
                planWorkflow.precompute.ProbDoseInfluence.stripStoredProbPlanPayload( ...
                robustData);
            if planWorkflow.precompute.ProbDoseInfluence.needsRobustNominalDij( ...
                    robustData)
                robustData = ...
                    planWorkflow.precompute.ProbDoseInfluence.attachNominalDijFromContext( ...
                    robustData);
            end
            cacheHit = true;
            context.log(sprintf('Loaded cached PROB2 dij: %s.',cacheFile));
        end

        function robustData = precompute(context,robustData)
            robustData = ...
                planWorkflow.precompute.ProbDoseInfluence.ensurePlanContext( ...
                context,robustData);
            useScenarioBatch = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.useScenarioBatchPrecompute( ...
                robustData.planConfig);
            probConfig = ...
                planWorkflow.precompute.ProbDoseInfluence.doseConfig( ...
                context,robustData,useScenarioBatch);
            context.log(sprintf( ...
                'Precomputing PROB2 probabilistic dose influence data using %s.', ...
                planWorkflow.precompute.ProbDoseInfluence.executionModeLabel( ...
                useScenarioBatch)));

            wallTimer = tic;
            if useScenarioBatch
                [plnForOptimization,dijProbContext] = ...
                    matRad_calculateProbabilisticQuantities( ...
                    robustData.ct,robustData.cst,robustData.stf, ...
                    robustData.pln,probConfig);
            else
                planWorkflow.precompute.ProbDoseInfluence.requireRobustInput( ...
                    robustData);
                [plnForOptimization,dijProbContext] = ...
                    matRad_calculateProbabilisticQuantities( ...
                    robustData.ct,robustData.cst,robustData.stf, ...
                    robustData.pln,robustData.dijRobust,probConfig);
            end
            derivedTimeSeconds = toc(wallTimer);

            robustData.dij_prob = plnForOptimization.propOpt.dij_prob;
            clear plnForOptimization;
            robustData.dijProbContext = dijProbContext;
            robustData.dijPrecomputingTiming = ...
                planWorkflow.performance.PrecomputeTiming.combine( ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.inputTiming( ...
                robustData), ...
                'derived','dij_prob',derivedTimeSeconds, ...
                robustData.planConfig.label, ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.referenceTiming( ...
                context,robustData));
            robustData.dijPrecomputingSize = ...
                planWorkflow.performance.PrecomputeSize.combine( ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.inputSize( ...
                robustData), ...
                'derived','dij_prob',robustData.dij_prob, ...
                robustData.planConfig.label, ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.referenceSize( ...
                context,robustData));
            if planWorkflow.precompute.ScenarioFreeDoseInfluence.isReferencePlan( ...
                    robustData)
                robustData.dijPrecomputingTiming = ...
                    planWorkflow.performance.PrecomputeTiming.asReference( ...
                    robustData.dijPrecomputingTiming, ...
                    robustData.planConfig.label);
                robustData.dijPrecomputingSize = ...
                    planWorkflow.performance.PrecomputeSize.asReference( ...
                    robustData.dijPrecomputingSize, ...
                    robustData.planConfig.label);
            end
            if planWorkflow.precompute.ProbDoseInfluence.needsRobustNominalDij( ...
                    robustData)
                robustData = ...
                    planWorkflow.precompute.ProbDoseInfluence.attachNominalDijFromContext( ...
                    robustData);
            end
            robustData = ...
                planWorkflow.precompute.ProbDoseInfluence.stripStoredProbPlanPayload( ...
                robustData);
            robustData = ...
                planWorkflow.precompute.ProbDoseInfluence.stripTransientRobustInput( ...
                robustData);
            robustData = planWorkflow.precompute.ProbDoseInfluence.cache( ...
                context,robustData);
        end

        function robustData = cache(context,robustData)
            robustData = ...
                planWorkflow.precompute.ProbDoseInfluence.ensurePlanContext( ...
                context,robustData);
            if ~context.runConfig.writeCache
                return;
            end

            cacheContext = ...
                planWorkflow.precompute.ProbDoseInfluence.cacheContext( ...
                context,robustData);
            tag = planWorkflow.precompute.ProbDoseInfluence.cacheTag( ...
                robustData);
            cacheFile = context.cache.file(tag,robustData.pln, ...
                cacheContext);
            dij_prob = robustData.dij_prob;
            dijProbContext = robustData.dijProbContext; %#ok<NASGU>
            cacheMetadata = context.cache.metadata( ...
                tag,robustData.pln,cacheContext);
            cacheMetadata.probabilisticMode = 'PROB';
            cacheMetadata.probabilisticQuantity = dij_prob.quantity;
            cacheMetadata.probabilisticQuantityField = ...
                dij_prob.quantityField;
            if ~isfield(robustData,'dijPrecomputingTiming') || ...
                    ~planWorkflow.performance.PrecomputeTiming.isValid( ...
                    robustData.dijPrecomputingTiming)
                error(['planWorkflow:precompute:ProbDoseInfluence:' ...
                    'MissingPrecomputeTiming'], ...
                    'PROB2 cache requires dijPrecomputingTiming metadata.');
            end
            cacheMetadata.dijPrecomputingTiming = ...
                robustData.dijPrecomputingTiming;
            if ~isfield(robustData,'dijPrecomputingSize') || ...
                    ~planWorkflow.performance.PrecomputeSize.isValid( ...
                    robustData.dijPrecomputingSize)
                error(['planWorkflow:precompute:ProbDoseInfluence:' ...
                    'MissingPrecomputeSize'], ...
                    'PROB2 cache requires dijPrecomputingSize metadata.');
            end
            cacheMetadata.dijPrecomputingSize = ...
                robustData.dijPrecomputingSize;
            context.cache.ensureFileFolder(cacheFile);
            if planWorkflow.precompute.ProbDoseInfluence.needsRobustNominalDij( ...
                    robustData) && (~isfield(robustData,'dijNominal') || ...
                    isempty(robustData.dijNominal))
                error(['planWorkflow:precompute:ProbDoseInfluence:' ...
                    'MissingCacheNominalDij'], ...
                    ['PROB2 cache for nominal objectives requires ' ...
                    'dijNominal from dijProbContext.']);
            end
            if isfield(robustData,'dijNominal') && ...
                    ~isempty(robustData.dijNominal)
                cacheMetadata.hasNominalDijContext = true;
                builtin('save',cacheFile,'dij_prob', ...
                    'dijProbContext','cacheMetadata','-v7.3');
            else
                cacheMetadata.hasNominalDijContext = false;
                builtin('save',cacheFile,'dij_prob', ...
                    'dijProbContext','cacheMetadata','-v7.3');
            end
            context.log(sprintf('Cached PROB2 dij: %s.',cacheFile));
            robustData.dijCacheRefs.prob = ...
                planWorkflow.cache.DoseInfluenceCacheRef.create( ...
                'prob',tag,cacheFile,context.cache.cachePath, ...
                cacheMetadata,{'dij_prob','dijProbContext'}, ...
                planWorkflow.cache.DoseInfluenceCacheRef.totalNumOfBixels( ...
                robustData.dijProbContext));
        end

        function robustData = useForOptimization(robustData)
            if ~isfield(robustData,'dijProbContext') || ...
                    isempty(robustData.dijProbContext)
                error(['planWorkflow:precompute:ProbDoseInfluence:' ...
                    'MissingProbDijContext'], ...
                    'PROB2 optimization requires dijProbContext.');
            end
            if ~isfield(robustData,'plnForOptimization') || ...
                    isempty(robustData.plnForOptimization)
                robustData.plnForOptimization = ...
                    planWorkflow.precompute.ProbDoseInfluence.createOptimizationPlan( ...
                    robustData);
            end
            robustData = ...
                planWorkflow.precompute.ProbDoseInfluence.stripStoredProbPlanPayload( ...
                robustData);
            robustData.usesProbDijForOptimization = true;
        end

        function pln = optimizationPlan(robustData)
            if isfield(robustData,'plnForOptimization') && ...
                    ~isempty(robustData.plnForOptimization)
                pln = robustData.plnForOptimization;
            else
                pln = robustData.pln;
            end
            if isfield(robustData,'dij_prob') && ...
                    ~isempty(robustData.dij_prob)
                pln = ...
                    planWorkflow.precompute.ProbDoseInfluence.attachProbDijToPlan( ...
                    pln,robustData.dij_prob);
            end
        end

        function robustData = restoreOptimizationPlan(robustData)
            if ~isfield(robustData,'dij_prob') || ...
                    isempty(robustData.dij_prob)
                return;
            end
            robustData = ...
                planWorkflow.precompute.ProbDoseInfluence.stripStoredProbPlanPayload( ...
                robustData);
            if isfield(robustData,'dijProbContext') && ...
                    ~isempty(robustData.dijProbContext)
                robustData.plnForOptimization = ...
                    planWorkflow.precompute.ProbDoseInfluence.createOptimizationPlan( ...
                    robustData);
            end
        end

        function pln = createOptimizationPlan(robustData)
            pln = robustData.pln;
            if ~isfield(pln,'propOpt') || ~isstruct(pln.propOpt)
                pln.propOpt = struct();
            end
            pln = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.removePlanPayload( ...
                pln,'dij_prob');
            pln.multScen = robustData.dijProbContext.scenarioModel;
        end

        function contextOut = cacheContext(context,robustData)
            robustData = ...
                planWorkflow.precompute.ProbDoseInfluence.ensurePlanContext( ...
                context,robustData);
            contextOut = struct();
            if isfield(robustData,'cst')
                contextOut.cst = robustData.cst;
            end
            prob = struct();
            prob.mode = 'PROB2';
            if isfield(context.data,'quantityOpt') && ...
                    ~isempty(context.data.quantityOpt)
                prob.quantity = context.data.quantityOpt;
            else
                prob.quantity = '';
            end
            prob.refScen = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.effectiveRefScen( ...
                planWorkflow.precompute.ProbDoseInfluence.ctForRefScen( ...
                robustData));
            prob.scen4D = 1;
            if isfield(robustData,'pln') && ...
                    isfield(robustData.pln,'propOpt') && ...
                    isstruct(robustData.pln.propOpt) && ...
                    isfield(robustData.pln.propOpt,'scen4D') && ...
                    ~isempty(robustData.pln.propOpt.scen4D)
                prob.scen4D = robustData.pln.propOpt.scen4D;
            end
            if isfield(robustData,'objectiveInfo')
                prob.targetName = ...
                    planWorkflow.precompute.ProbDoseInfluence.optionalStructField( ...
                    robustData.objectiveInfo,'targetName','');
                prob.robustOarNames = ...
                    planWorkflow.precompute.ProbDoseInfluence.optionalStructField( ...
                    robustData.objectiveInfo,'robustOarNames',{});
            else
                prob.targetName = '';
                prob.robustOarNames = {};
            end
            contextOut.prob = prob;
            if isfield(robustData,'stf') && ~isempty(robustData.stf)
                contextOut.stf = context.cache.stfSignature( ...
                    robustData.stf);
            end
        end

        function tag = cacheTag(robustData)
            if ~isfield(robustData,'planConfig') || ...
                    ~isfield(robustData.planConfig,'id') || ...
                    isempty(robustData.planConfig.id)
                error(['planWorkflow:precompute:ProbDoseInfluence:' ...
                    'MissingRobustPlanId'], ...
                    'PROB2 dose cache tag requires a robust plan id.');
            end
            tag = ['prob_' char(robustData.planConfig.id)];
        end

        function probConfig = doseConfig(context,robustData, ...
                includeScenarioBatchConfig)
            if nargin < 3 || isempty(includeScenarioBatchConfig)
                includeScenarioBatchConfig = false;
            end
            robustData = ...
                planWorkflow.precompute.ProbDoseInfluence.ensurePlanContext( ...
                context,robustData);
            probConfig = struct();
            if isfield(context.data,'quantityOpt') && ...
                    ~isempty(context.data.quantityOpt)
                probConfig.Quantity = context.data.quantityOpt;
            end
            probConfig.refScen = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.effectiveRefScen( ...
                planWorkflow.precompute.ProbDoseInfluence.ctForRefScen( ...
                robustData));
            probConfig.ProgressLevel = 'summary';
            probConfig.targetStructSel = ...
                robustData.cst(robustData.objectiveInfo.ixTarget,2);
            probConfig.OARStructSel = ...
                planWorkflow.precompute.ProbDoseInfluence.asCellstr( ...
                robustData.objectiveInfo.robustOarNames);
            if includeScenarioBatchConfig
                probConfig = ...
                    planWorkflow.precompute.ScenarioFreeDoseInfluence.mergeScenarioBatchConfig( ...
                    probConfig,robustData.planConfig,context,'doseProb');
                probConfig.UseParallel = true;
                probConfig = ...
                    planWorkflow.precompute.ProbDoseInfluence.applyParallelOptions( ...
                    probConfig,context);
            end
        end

        function tf = isCacheCompatible(context,cached,robustData)
            robustData = ...
                planWorkflow.precompute.ProbDoseInfluence.ensurePlanContext( ...
                context,robustData);
            tf = isfield(cached,'cacheMetadata') && ...
                context.cache.isIdentityCompatible(cached, ...
                planWorkflow.precompute.ProbDoseInfluence.cacheTag( ...
                robustData),robustData.pln, ...
                planWorkflow.precompute.ProbDoseInfluence.cacheContext( ...
                context,robustData)) && ...
                planWorkflow.precompute.ProbDoseInfluence.isCachePayloadCompatible( ...
                cached,robustData);
        end

        function tf = isCachePayloadCompatible(cached,robustData)
            robustData = ...
                planWorkflow.precompute.ProbDoseInfluence.ensurePlanContext( ...
                [],robustData);
            tf = isfield(cached,'cacheMetadata') && ...
                planWorkflow.precompute.ProbDoseInfluence.isMetadataForPlan( ...
                cached.cacheMetadata,robustData) && ...
                planWorkflow.precompute.ProbDoseInfluence.isMetadataCstCompatible( ...
                cached.cacheMetadata,robustData) && ...
                planWorkflow.precompute.ProbDoseInfluence.isMetadataStfCompatible( ...
                cached.cacheMetadata,robustData) && ...
                isfield(cached.cacheMetadata,'probabilisticMode') && ...
                strcmp(cached.cacheMetadata.probabilisticMode,'PROB') && ...
                planWorkflow.precompute.ProbDoseInfluence.isMetadataProbContextCompatible( ...
                cached.cacheMetadata,robustData) && ...
                planWorkflow.precompute.ProbDoseInfluence.isMetadataScenarioCompatible( ...
                cached.cacheMetadata,cached,'dijProbContext') && ...
                planWorkflow.precompute.ProbDoseInfluence.isProbDijUsable( ...
                cached.dij_prob) && ...
                planWorkflow.precompute.ProbDoseInfluence.isProbDijContextUsable( ...
                cached.dijProbContext,cached.dij_prob) && ...
                planWorkflow.precompute.ProbDoseInfluence.isCachedNominalDijContextUsable( ...
                cached,robustData,cached.dij_prob) && ...
                planWorkflow.precompute.ProbDoseInfluence.isProbDijContextCompatibleWithStf( ...
                cached.dijProbContext,robustData.stf);
        end

        function pln = createNominalOptimizationPlan(robustData,dijNominal)
            pln = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.createNominalOptimizationPlan( ...
                robustData.pln,dijNominal,'dij_prob');
        end
    end

    methods (Static, Access = private)
        function robustData = ensurePlanContext(context,robustData) %#ok<INUSD>
            if ~isfield(robustData,'planConfig') || ...
                    isempty(robustData.planConfig)
                error(['planWorkflow:precompute:ProbDoseInfluence:' ...
                    'MissingRobustPlanConfig'], ...
                    'Robust data must contain an explicit planConfig.');
            end
            if ~isfield(robustData,'strategy') || isempty(robustData.strategy)
                error(['planWorkflow:precompute:ProbDoseInfluence:' ...
                    'MissingStrategy'], ...
                    'Robust data must contain an explicit strategy.');
            end
        end

        function ct = ctForRefScen(robustData)
            ct = struct();
            if isstruct(robustData) && isfield(robustData,'ct')
                ct = robustData.ct;
            end
        end

        function requireRobustInput(robustData)
            if ~isfield(robustData,'dijRobust') || ...
                    isempty(robustData.dijRobust)
                error(['planWorkflow:precompute:ProbDoseInfluence:' ...
                    'MissingRobustInputDij'], ...
                    ['PROB2 legacy precompute requires explicit ' ...
                    'robustData.dijRobust as input.']);
            end
        end

        function robustData = stripTransientRobustInput(robustData)
            if isfield(robustData,'dijRobust')
                robustData = rmfield(robustData,'dijRobust');
            end
            if isfield(robustData,'dijRobustPrecomputingTiming')
                robustData = rmfield(robustData,'dijRobustPrecomputingTiming');
            end
            if isfield(robustData,'dijRobustPrecomputingSize')
                robustData = rmfield(robustData,'dijRobustPrecomputingSize');
            end
        end

        function values = asCellstr(values)
            if ischar(values) || (isstring(values) && isscalar(values))
                values = {char(values)};
            elseif isstring(values)
                values = cellstr(values);
            elseif isempty(values)
                values = {};
            end
        end

        function config = applyParallelOptions(config,context)
            runConfig = [];
            if isstruct(context) && isfield(context,'runConfig')
                runConfig = context.runConfig;
            end
            parallelOptions = ...
                planWorkflow.config.Resources.doseParallelOptions( ...
                runConfig);
            if ~isempty(fieldnames(parallelOptions))
                config.parallelOptions = parallelOptions;
            end
        end

        function tf = isProbDijUsable(dijProb)
            tf = isstruct(dijProb) && isfield(dijProb,'expected') && ...
                isfield(dijProb,'Omega') && isfield(dijProb,'voiSubIx') && ...
                isfield(dijProb,'quantity') && ...
                isfield(dijProb,'quantityField') && ...
                isfield(dijProb,'probabilisticMode') && ...
                strcmp(char(dijProb.probabilisticMode),'PROB');
        end

        function tf = isProbDijContextUsable(dijProbContext,dijProb)
            tf = isstruct(dijProbContext) && ...
                isfield(dijProbContext,'totalNumOfBixels') && ...
                dijProbContext.totalNumOfBixels == ...
                size(dijProb.expected,2) && ...
                isfield(dijProbContext,'physicalDose') && ...
                iscell(dijProbContext.physicalDose) && ...
                ~isempty(dijProbContext.physicalDose) && ...
                isequal(size(dijProbContext.physicalDose{1}), ...
                size(dijProb.expected));
        end

        function tf = isProbDijContextCompatibleWithStf( ...
                dijProbContext,stf)
            tf = isstruct(dijProbContext) && ...
                isfield(dijProbContext,'totalNumOfBixels') && ...
                ~isempty(stf) && isstruct(stf) && ...
                isfield(stf,'totalNumOfBixels') && ...
                dijProbContext.totalNumOfBixels == ...
                sum([stf.totalNumOfBixels]);
        end

        function tf = isCachedNominalDijContextUsable( ...
                cached,robustData,dijProb)
            if ~planWorkflow.precompute.ProbDoseInfluence.needsRobustNominalDij( ...
                    robustData)
                tf = true;
                return;
            end

            tf = isfield(cached,'dijProbContext') && ...
                planWorkflow.precompute.ProbDoseInfluence.isNominalDijContextUsable( ...
                cached.dijProbContext,dijProb);
        end

        function tf = isMetadataForPlan(cacheMetadata,robustData)
            tf = isstruct(cacheMetadata);
            if ~tf
                return;
            end
            if isfield(cacheMetadata,'planId') && ...
                    isfield(robustData.planConfig,'id') && ...
                    ~strcmp(char(cacheMetadata.planId), ...
                    char(robustData.planConfig.id))
                tf = false;
                return;
            end
            if isfield(cacheMetadata,'robustnessMode') && ...
                    isfield(robustData.planConfig,'robustnessMode') && ...
                    ~strcmp(char(cacheMetadata.robustnessMode), ...
                    char(robustData.planConfig.robustnessMode))
                tf = false;
            end
        end

        function tf = isMetadataProbContextCompatible( ...
                cacheMetadata,robustData)
            tf = true;
            if ~isfield(cacheMetadata,'cacheIdentity') || ...
                    ~isstruct(cacheMetadata.cacheIdentity) || ...
                    ~isfield(cacheMetadata.cacheIdentity,'prob') || ...
                    ~isstruct(cacheMetadata.cacheIdentity.prob)
                return;
            end
            probIdentity = cacheMetadata.cacheIdentity.prob;
            expected = ...
                planWorkflow.precompute.ProbDoseInfluence.expectedProbIdentity( ...
                robustData);
            fields = {'quantity','refScen','scen4D','targetName'};
            for fieldIx = 1:numel(fields)
                fieldName = fields{fieldIx};
                if isfield(probIdentity,fieldName) && ...
                        isfield(expected,fieldName) && ...
                        ~isequal(probIdentity.(fieldName), ...
                        expected.(fieldName))
                    tf = false;
                    return;
                end
            end
            if isfield(probIdentity,'robustOarNames') && ...
                    isfield(expected,'robustOarNames') && ...
                    ~isequal(probIdentity.robustOarNames, ...
                    expected.robustOarNames)
                tf = false;
            end
        end

        function tf = isMetadataCstCompatible(cacheMetadata,robustData)
            tf = true;
            if ~isfield(cacheMetadata,'cacheIdentity') || ...
                    ~isstruct(cacheMetadata.cacheIdentity) || ...
                    ~isfield(cacheMetadata.cacheIdentity,'cst') || ...
                    ~isfield(robustData,'cst')
                return;
            end
            tf = strcmp( ...
                planWorkflow.cache.CacheIdentity.valueHash( ...
                cacheMetadata.cacheIdentity.cst), ...
                planWorkflow.cache.CacheIdentity.valueHash( ...
                planWorkflow.cache.CacheIdentity.cstIdentity( ...
                robustData.cst)));
        end

        function tf = isMetadataStfCompatible(cacheMetadata,robustData)
            tf = true;
            if ~isfield(cacheMetadata,'cacheIdentity') || ...
                    ~isstruct(cacheMetadata.cacheIdentity) || ...
                    ~isfield(cacheMetadata.cacheIdentity,'stf') || ...
                    ~isfield(robustData,'stf') || isempty(robustData.stf)
                return;
            end
            tf = strcmp( ...
                planWorkflow.cache.CacheIdentity.valueHash( ...
                cacheMetadata.cacheIdentity.stf), ...
                planWorkflow.cache.CacheIdentity.valueHash( ...
                planWorkflow.cache.DoseInfluenceCache.stfSignature( ...
                robustData.stf)));
        end

        function expected = expectedProbIdentity(robustData)
            expected = struct();
            if isfield(robustData,'quantityOpt') && ...
                    ~isempty(robustData.quantityOpt)
                expected.quantity = robustData.quantityOpt;
            end
            expected.refScen = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.effectiveRefScen( ...
                planWorkflow.precompute.ProbDoseInfluence.ctForRefScen( ...
                robustData));
            expected.scen4D = 1;
            if isfield(robustData,'pln') && ...
                    isfield(robustData.pln,'propOpt') && ...
                    isstruct(robustData.pln.propOpt) && ...
                    isfield(robustData.pln.propOpt,'scen4D') && ...
                    ~isempty(robustData.pln.propOpt.scen4D)
                expected.scen4D = robustData.pln.propOpt.scen4D;
            end
            if isfield(robustData,'objectiveInfo')
                expected.targetName = ...
                    planWorkflow.precompute.ProbDoseInfluence.optionalStructField( ...
                    robustData.objectiveInfo,'targetName','');
                expected.robustOarNames = ...
                    planWorkflow.precompute.ProbDoseInfluence.optionalStructField( ...
                    robustData.objectiveInfo,'robustOarNames',{});
            end
        end

        function tf = isMetadataScenarioCompatible( ...
                cacheMetadata,cached,contextField)
            tf = true;
            if ~isfield(cacheMetadata,'scenarioFingerprint') || ...
                    ~isfield(cached,contextField) || ...
                    ~isstruct(cached.(contextField)) || ...
                    ~isfield(cached.(contextField),'scenarioModel') || ...
                    ~isa(cached.(contextField).scenarioModel, ...
                    'matRad_ScenarioModel')
                return;
            end
            tf = strcmp(cacheMetadata.scenarioFingerprint, ...
                planWorkflow.cache.CacheIdentity.scenarioFingerprint( ...
                cached.(contextField).scenarioModel));
        end

        function tf = isNominalDijContextUsable(dijContext,dijProb)
            tf = false;
            if ~isstruct(dijContext) || ~isstruct(dijProb) || ...
                    ~isfield(dijProb,'expected') || ...
                    ~isfield(dijContext,'totalNumOfBixels') || ...
                    dijContext.totalNumOfBixels ~= size(dijProb.expected,2)
                return;
            end

            quantityField = ...
                planWorkflow.precompute.ProbDoseInfluence.probQuantityField( ...
                dijProb);
            tf = ...
                planWorkflow.precompute.ProbDoseInfluence.isDijQuantityUsable( ...
                dijContext,quantityField,size(dijProb.expected));
        end

        function tf = needsRobustNominalDij(robustData)
            tf = isstruct(robustData) && ...
                isfield(robustData,'planConfig') && ...
                isstruct(robustData.planConfig) && ...
                isfield(robustData.planConfig,'requiresProbDij') && ...
                logical(robustData.planConfig.requiresProbDij) && ...
                isfield(robustData.planConfig,'hasNominalObjectives') && ...
                logical(robustData.planConfig.hasNominalObjectives);
        end

        function robustData = attachNominalDijFromContext(robustData)
            if ~isfield(robustData,'dijProbContext') || ...
                    isempty(robustData.dijProbContext)
                error(['planWorkflow:precompute:ProbDoseInfluence:' ...
                    'MissingNominalDijContext'], ...
                    ['PROB2 optimization with nominal objectives requires ' ...
                    'dijProbContext from matRad.']);
            end
            if ~planWorkflow.precompute.ProbDoseInfluence.isNominalDijContextUsable( ...
                    robustData.dijProbContext,robustData.dij_prob)
                error(['planWorkflow:precompute:ProbDoseInfluence:' ...
                    'InconsistentNominalDijContext'], ...
                    ['dijProbContext returned by matRad is not ' ...
                    'compatible with dij_prob.']);
            end
            robustData.dijNominal = robustData.dijProbContext;
            robustData.plnNominal = ...
                planWorkflow.precompute.ProbDoseInfluence.createNominalOptimizationPlan( ...
                robustData,robustData.dijNominal);
            robustData.stfNominal = robustData.stf;
        end

        function robustData = stripStoredProbPlanPayload(robustData)
            if isfield(robustData,'pln')
                robustData.pln = ...
                    planWorkflow.precompute.ProbDoseInfluence.removeProbDijFromPlan( ...
                    robustData.pln);
            end
            if isfield(robustData,'plnForOptimization')
                robustData.plnForOptimization = ...
                    planWorkflow.precompute.ProbDoseInfluence.removeProbDijFromPlan( ...
                    robustData.plnForOptimization);
            end
            if isfield(robustData,'plnNominal')
                robustData.plnNominal = ...
                    planWorkflow.precompute.ProbDoseInfluence.removeProbDijFromPlan( ...
                    robustData.plnNominal);
            end
        end

        function pln = removeProbDijFromPlan(pln)
            pln = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.removePlanPayload( ...
                pln,'dij_prob');
        end

        function pln = attachProbDijToPlan(pln,dijProb)
            pln = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.attachPlanPayload( ...
                pln,'dij_prob',dijProb);
        end

        function quantityField = probQuantityField(dijProb)
            quantityField = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.quantityField( ...
                dijProb,'physicalDose');
        end

        function tf = isDijQuantityUsable(dij,quantityField,expectedSize)
            tf = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.isDijQuantityUsable( ...
                dij,quantityField,expectedSize);
        end

        function value = optionalStructField(input,fieldName,defaultValue)
            if isstruct(input) && isfield(input,fieldName)
                value = input.(fieldName);
            else
                value = defaultValue;
            end
        end

        function label = executionModeLabel(useScenarioBatch)
            if logical(useScenarioBatch)
                label = 'scenario-batch';
            else
                label = 'precomputed robust dij';
            end
        end
    end
end
