classdef Prob2DoseInfluence
    % Prob2DoseInfluence Owns PROB2 dij_prob2 flow.

    methods (Static)
        function [cacheHit,robustData] = loadCached(context,robustData)
            robustData = ...
                planWorkflow.precompute.Prob2DoseInfluence.ensurePlanContext( ...
                context,robustData);
            cacheHit = false;
            cacheContext = ...
                planWorkflow.precompute.Prob2DoseInfluence.cacheContext( ...
                context,robustData);
            cacheFile = context.cache.file( ...
                planWorkflow.precompute.Prob2DoseInfluence.cacheTag( ...
                robustData),robustData.pln,cacheContext);
            if ~context.runConfig.useCache || ~isfile(cacheFile)
                return;
            end

            cached = load(cacheFile);
            if ~isfield(cached,'dij_prob2') || ...
                    ~isfield(cached,'dijProb2Context')
                context.log(sprintf( ...
                    'Ignoring stale PROB2 dij cache: %s.',cacheFile));
                return;
            end

            if ~planWorkflow.precompute.Prob2DoseInfluence.isCacheCompatible( ...
                    context,cached,robustData)
                context.log(sprintf( ...
                    'Ignoring stale PROB2 dij cache: %s.',cacheFile));
                return;
            end
            dijPrecomputingTiming = ...
                planWorkflow.performance.PrecomputeTiming.fromCacheMetadata( ...
                cached.cacheMetadata);
            dijPrecomputingSize = ...
                planWorkflow.performance.PrecomputeSize.fromCacheMetadata( ...
                cached.cacheMetadata);
            if isempty(dijPrecomputingTiming) || ...
                    isempty(dijPrecomputingSize)
                context.log(sprintf( ...
                    'Ignoring stale PROB2 dij cache: %s.',cacheFile));
                return;
            end

            robustData.dijProb2Context = cached.dijProb2Context;
            robustData.dij_prob2 = cached.dij_prob2;
            robustData.dijCacheRefs.prob2 = ...
                planWorkflow.cache.DoseInfluenceCacheRef.create( ...
                'prob2', ...
                planWorkflow.precompute.Prob2DoseInfluence.cacheTag( ...
                robustData),cacheFile,context.cache.cachePath, ...
                cached.cacheMetadata,{'dij_prob2','dijProb2Context'}, ...
                planWorkflow.cache.DoseInfluenceCacheRef.totalNumOfBixels( ...
                cached.dijProb2Context));
            robustData.dijPrecomputingTiming = dijPrecomputingTiming;
            robustData.dijPrecomputingSize = dijPrecomputingSize;
            robustData = ...
                planWorkflow.precompute.Prob2DoseInfluence.stripStoredProb2PlanPayload( ...
                robustData);
            if planWorkflow.precompute.Prob2DoseInfluence.needsRobustNominalDij( ...
                    robustData)
                robustData = ...
                    planWorkflow.precompute.Prob2DoseInfluence.attachNominalDijFromContext( ...
                    robustData);
            end
            cacheHit = true;
            context.log(sprintf('Loaded cached PROB2 dij: %s.',cacheFile));
        end

        function robustData = precompute(context,robustData)
            robustData = ...
                planWorkflow.precompute.Prob2DoseInfluence.ensurePlanContext( ...
                context,robustData);
            useStreaming = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.useStreamingPrecompute( ...
                robustData.planConfig);
            prob2Config = ...
                planWorkflow.precompute.Prob2DoseInfluence.doseConfig( ...
                context,robustData,useStreaming);
            context.log(sprintf( ...
                'Precomputing PROB2 probabilistic dose influence data using %s.', ...
                planWorkflow.precompute.Prob2DoseInfluence.executionModeLabel( ...
                useStreaming)));

            wallTimer = tic;
            if useStreaming
                [plnForOptimization,dijProb2Context] = ...
                    planWorkflow.precompute.Prob2DoseInfluence.callStreamingProb2( ...
                    robustData,prob2Config);
            else
                planWorkflow.precompute.Prob2DoseInfluence.requireRobustInput( ...
                    robustData);
                [plnForOptimization,dijProb2Context] = matRad_calcDoseProb2( ...
                    robustData.ct,robustData.cst,robustData.stf, ...
                    robustData.pln,robustData.dijRobust,prob2Config);
            end
            derivedTimeSeconds = toc(wallTimer);

            robustData.dij_prob2 = plnForOptimization.propOpt.dij_prob2;
            clear plnForOptimization;
            robustData.dijProb2Context = dijProb2Context;
            robustData.dijPrecomputingTiming = ...
                planWorkflow.performance.PrecomputeTiming.combine( ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.inputTiming( ...
                robustData), ...
                'derived','dij_prob2',derivedTimeSeconds, ...
                robustData.planConfig.label);
            robustData.dijPrecomputingSize = ...
                planWorkflow.performance.PrecomputeSize.combine( ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.inputSize( ...
                robustData), ...
                'derived','dij_prob2',robustData.dij_prob2, ...
                robustData.planConfig.label, ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.referenceSize( ...
                context,robustData));
            if planWorkflow.precompute.ScenarioFreeDoseInfluence.isReferencePlan( ...
                    robustData)
                robustData.dijPrecomputingTiming = ...
                    planWorkflow.performance.PrecomputeTiming.asReference( ...
                    robustData.dijPrecomputingTiming, ...
                    robustData.planConfig.label);
                robustData.dijPrecomputingSize = ...
                    planWorkflow.performance.PrecomputeSize.asReference( ...
                    robustData.dijPrecomputingSize, ...
                    robustData.planConfig.label);
            end
            if planWorkflow.precompute.Prob2DoseInfluence.needsRobustNominalDij( ...
                    robustData)
                robustData = ...
                    planWorkflow.precompute.Prob2DoseInfluence.attachNominalDijFromContext( ...
                    robustData);
            end
            robustData = ...
                planWorkflow.precompute.Prob2DoseInfluence.stripStoredProb2PlanPayload( ...
                robustData);
            robustData = ...
                planWorkflow.precompute.Prob2DoseInfluence.stripTransientRobustInput( ...
                robustData);
            robustData = planWorkflow.precompute.Prob2DoseInfluence.cache( ...
                context,robustData);
        end

        function robustData = cache(context,robustData)
            robustData = ...
                planWorkflow.precompute.Prob2DoseInfluence.ensurePlanContext( ...
                context,robustData);
            if ~context.runConfig.writeCache
                return;
            end

            cacheContext = ...
                planWorkflow.precompute.Prob2DoseInfluence.cacheContext( ...
                context,robustData);
            tag = planWorkflow.precompute.Prob2DoseInfluence.cacheTag( ...
                robustData);
            cacheFile = context.cache.file(tag,robustData.pln, ...
                cacheContext);
            dij_prob2 = robustData.dij_prob2;
            dijProb2Context = robustData.dijProb2Context; %#ok<NASGU>
            cacheMetadata = context.cache.metadata( ...
                tag,robustData.pln,cacheContext);
            cacheMetadata.probabilisticMode = 'PROB2';
            cacheMetadata.probabilisticQuantity = dij_prob2.quantity;
            cacheMetadata.probabilisticQuantityField = ...
                dij_prob2.quantityField;
            if ~isfield(robustData,'dijPrecomputingTiming') || ...
                    ~planWorkflow.performance.PrecomputeTiming.isValid( ...
                    robustData.dijPrecomputingTiming)
                error(['planWorkflow:precompute:Prob2DoseInfluence:' ...
                    'MissingPrecomputeTiming'], ...
                    'PROB2 cache requires dijPrecomputingTiming metadata.');
            end
            cacheMetadata.dijPrecomputingTiming = ...
                robustData.dijPrecomputingTiming;
            if ~isfield(robustData,'dijPrecomputingSize') || ...
                    ~planWorkflow.performance.PrecomputeSize.isValid( ...
                    robustData.dijPrecomputingSize)
                error(['planWorkflow:precompute:Prob2DoseInfluence:' ...
                    'MissingPrecomputeSize'], ...
                    'PROB2 cache requires dijPrecomputingSize metadata.');
            end
            cacheMetadata.dijPrecomputingSize = ...
                robustData.dijPrecomputingSize;
            context.cache.ensureFileFolder(cacheFile);
            if planWorkflow.precompute.Prob2DoseInfluence.needsRobustNominalDij( ...
                    robustData) && (~isfield(robustData,'dijNominal') || ...
                    isempty(robustData.dijNominal))
                error(['planWorkflow:precompute:Prob2DoseInfluence:' ...
                    'MissingCacheNominalDij'], ...
                    ['PROB2 cache for nominal objectives requires ' ...
                    'dijNominal from dijProb2Context.']);
            end
            if isfield(robustData,'dijNominal') && ...
                    ~isempty(robustData.dijNominal)
                cacheMetadata.hasNominalDijContext = true;
                builtin('save',cacheFile,'dij_prob2', ...
                    'dijProb2Context','cacheMetadata','-v7.3');
            else
                cacheMetadata.hasNominalDijContext = false;
                builtin('save',cacheFile,'dij_prob2', ...
                    'dijProb2Context','cacheMetadata','-v7.3');
            end
            context.log(sprintf('Cached PROB2 dij: %s.',cacheFile));
            robustData.dijCacheRefs.prob2 = ...
                planWorkflow.cache.DoseInfluenceCacheRef.create( ...
                'prob2',tag,cacheFile,context.cache.cachePath, ...
                cacheMetadata,{'dij_prob2','dijProb2Context'}, ...
                planWorkflow.cache.DoseInfluenceCacheRef.totalNumOfBixels( ...
                robustData.dijProb2Context));
        end

        function robustData = useForOptimization(robustData)
            if ~isfield(robustData,'dijProb2Context') || ...
                    isempty(robustData.dijProb2Context)
                error(['planWorkflow:precompute:Prob2DoseInfluence:' ...
                    'MissingProb2DijContext'], ...
                    'PROB2 optimization requires dijProb2Context.');
            end
            if ~isfield(robustData,'plnForOptimization') || ...
                    isempty(robustData.plnForOptimization)
                robustData.plnForOptimization = ...
                    planWorkflow.precompute.Prob2DoseInfluence.createOptimizationPlan( ...
                    robustData);
            end
            robustData = ...
                planWorkflow.precompute.Prob2DoseInfluence.stripStoredProb2PlanPayload( ...
                robustData);
            robustData.usesProb2DijForOptimization = true;
        end

        function pln = optimizationPlan(robustData)
            if isfield(robustData,'plnForOptimization') && ...
                    ~isempty(robustData.plnForOptimization)
                pln = robustData.plnForOptimization;
            else
                pln = robustData.pln;
            end
            if isfield(robustData,'dij_prob2') && ...
                    ~isempty(robustData.dij_prob2)
                pln = ...
                    planWorkflow.precompute.Prob2DoseInfluence.attachProb2DijToPlan( ...
                    pln,robustData.dij_prob2);
            end
        end

        function robustData = restoreOptimizationPlan(robustData)
            if ~isfield(robustData,'dij_prob2') || ...
                    isempty(robustData.dij_prob2)
                return;
            end
            robustData = ...
                planWorkflow.precompute.Prob2DoseInfluence.stripStoredProb2PlanPayload( ...
                robustData);
            if isfield(robustData,'dijProb2Context') && ...
                    ~isempty(robustData.dijProb2Context)
                robustData.plnForOptimization = ...
                    planWorkflow.precompute.Prob2DoseInfluence.createOptimizationPlan( ...
                    robustData);
            end
        end

        function pln = createOptimizationPlan(robustData)
            pln = robustData.pln;
            if ~isfield(pln,'propOpt') || ~isstruct(pln.propOpt)
                pln.propOpt = struct();
            end
            pln = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.removePlanPayload( ...
                pln,'dij_prob2');
            pln.multScen = robustData.dijProb2Context.scenarioModel;
        end

        function contextOut = cacheContext(context,robustData)
            robustData = ...
                planWorkflow.precompute.Prob2DoseInfluence.ensurePlanContext( ...
                context,robustData);
            contextOut = struct();
            if isfield(robustData,'cst')
                contextOut.cst = robustData.cst;
            end
            prob2 = struct();
            prob2.mode = 'PROB2';
            if isfield(context.data,'quantityOpt') && ...
                    ~isempty(context.data.quantityOpt)
                prob2.quantity = context.data.quantityOpt;
            else
                prob2.quantity = '';
            end
            if isfield(robustData,'ct') && isfield(robustData.ct,'refScen')
                prob2.refScen = robustData.ct.refScen;
            else
                prob2.refScen = [];
            end
            prob2.scen4D = 1;
            if isfield(robustData,'pln') && ...
                    isfield(robustData.pln,'propOpt') && ...
                    isstruct(robustData.pln.propOpt) && ...
                    isfield(robustData.pln.propOpt,'scen4D') && ...
                    ~isempty(robustData.pln.propOpt.scen4D)
                prob2.scen4D = robustData.pln.propOpt.scen4D;
            end
            if isfield(robustData,'objectiveInfo')
                prob2.targetName = ...
                    planWorkflow.precompute.Prob2DoseInfluence.optionalStructField( ...
                    robustData.objectiveInfo,'targetName','');
                prob2.robustOarNames = ...
                    planWorkflow.precompute.Prob2DoseInfluence.optionalStructField( ...
                    robustData.objectiveInfo,'robustOarNames',{});
            else
                prob2.targetName = '';
                prob2.robustOarNames = {};
            end
            contextOut.prob2 = prob2;
            if isfield(robustData,'stf') && ~isempty(robustData.stf)
                contextOut.stf = context.cache.stfSignature( ...
                    robustData.stf);
            end
        end

        function tag = cacheTag(robustData)
            if ~isfield(robustData,'planConfig') || ...
                    ~isfield(robustData.planConfig,'id') || ...
                    isempty(robustData.planConfig.id)
                error(['planWorkflow:precompute:Prob2DoseInfluence:' ...
                    'MissingRobustPlanId'], ...
                    'PROB2 dose cache tag requires a robust plan id.');
            end
            tag = ['prob2_' char(robustData.planConfig.id)];
        end

        function prob2Config = doseConfig(context,robustData, ...
                includeStreamingConfig)
            if nargin < 3 || isempty(includeStreamingConfig)
                includeStreamingConfig = false;
            end
            robustData = ...
                planWorkflow.precompute.Prob2DoseInfluence.ensurePlanContext( ...
                context,robustData);
            prob2Config = struct();
            if isfield(context.data,'quantityOpt') && ...
                    ~isempty(context.data.quantityOpt)
                prob2Config.Quantity = context.data.quantityOpt;
            end
            if isfield(robustData.ct,'refScen') && ...
                    ~isempty(robustData.ct.refScen)
                prob2Config.refScen = robustData.ct.refScen;
            end
            prob2Config.ProgressLevel = 'summary';
            prob2Config.targetStructSel = ...
                robustData.cst(robustData.objectiveInfo.ixTarget,2);
            prob2Config.OARStructSel = ...
                planWorkflow.precompute.Prob2DoseInfluence.asCellstr( ...
                robustData.objectiveInfo.robustOarNames);
            if includeStreamingConfig
                prob2Config = ...
                    planWorkflow.precompute.ScenarioFreeDoseInfluence.mergeStreamingConfig( ...
                    prob2Config,robustData.planConfig);
                prob2Config.UseParallel = true;
                prob2Config = ...
                    planWorkflow.precompute.Prob2DoseInfluence.applyParallelOptions( ...
                    prob2Config,context);
            end
        end

        function tf = isCacheCompatible(context,cached,robustData)
            robustData = ...
                planWorkflow.precompute.Prob2DoseInfluence.ensurePlanContext( ...
                context,robustData);
            tf = isfield(cached,'cacheMetadata') && ...
                context.cache.isIdentityCompatible(cached, ...
                planWorkflow.precompute.Prob2DoseInfluence.cacheTag( ...
                robustData),robustData.pln, ...
                planWorkflow.precompute.Prob2DoseInfluence.cacheContext( ...
                context,robustData)) && ...
                isfield(cached.cacheMetadata,'probabilisticMode') && ...
                strcmp(cached.cacheMetadata.probabilisticMode,'PROB2') && ...
                isfield(cached.cacheMetadata,'scenarioFingerprint') && ...
                strcmp(cached.cacheMetadata.scenarioFingerprint, ...
                robustData.pln.multScen.fingerprint()) && ...
                planWorkflow.precompute.Prob2DoseInfluence.isProb2DijUsable( ...
                cached.dij_prob2) && ...
                planWorkflow.precompute.Prob2DoseInfluence.isProb2DijContextUsable( ...
                cached.dijProb2Context,cached.dij_prob2) && ...
                planWorkflow.precompute.Prob2DoseInfluence.isCachedNominalDijContextUsable( ...
                cached,robustData,cached.dij_prob2) && ...
                planWorkflow.precompute.Prob2DoseInfluence.isProb2DijContextCompatibleWithStf( ...
                cached.dijProb2Context,robustData.stf);
        end

        function pln = createNominalOptimizationPlan(robustData,dijNominal)
            pln = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.createNominalOptimizationPlan( ...
                robustData.pln,dijNominal,'dij_prob2');
        end
    end

    methods (Static, Access = private)
        function robustData = ensurePlanContext(context,robustData) %#ok<INUSD>
            if ~isfield(robustData,'planConfig') || ...
                    isempty(robustData.planConfig)
                error(['planWorkflow:precompute:Prob2DoseInfluence:' ...
                    'MissingRobustPlanConfig'], ...
                    'Robust data must contain an explicit planConfig.');
            end
            if ~isfield(robustData,'strategy') || isempty(robustData.strategy)
                error(['planWorkflow:precompute:Prob2DoseInfluence:' ...
                    'MissingStrategy'], ...
                    'Robust data must contain an explicit strategy.');
            end
        end

        function requireRobustInput(robustData)
            if ~isfield(robustData,'dijRobust') || ...
                    isempty(robustData.dijRobust)
                error(['planWorkflow:precompute:Prob2DoseInfluence:' ...
                    'MissingRobustInputDij'], ...
                    ['PROB2 legacy precompute requires explicit ' ...
                    'robustData.dijRobust as input.']);
            end
        end

        function robustData = stripTransientRobustInput(robustData)
            if isfield(robustData,'dijRobust')
                robustData = rmfield(robustData,'dijRobust');
            end
            if isfield(robustData,'dijRobustPrecomputingTiming')
                robustData = rmfield(robustData,'dijRobustPrecomputingTiming');
            end
            if isfield(robustData,'dijRobustPrecomputingSize')
                robustData = rmfield(robustData,'dijRobustPrecomputingSize');
            end
        end

        function values = asCellstr(values)
            if ischar(values) || (isstring(values) && isscalar(values))
                values = {char(values)};
            elseif isstring(values)
                values = cellstr(values);
            elseif isempty(values)
                values = {};
            end
        end

        function config = applyParallelOptions(config,context)
            runConfig = [];
            if isstruct(context) && isfield(context,'runConfig')
                runConfig = context.runConfig;
            end
            parallelOptions = ...
                planWorkflow.config.Resources.doseParallelOptions( ...
                runConfig);
            if ~isempty(fieldnames(parallelOptions))
                config.parallelOptions = parallelOptions;
            end
        end

        function tf = isProb2DijUsable(dijProb2)
            tf = isstruct(dijProb2) && isfield(dijProb2,'expected') && ...
                isfield(dijProb2,'Omega') && isfield(dijProb2,'voiSubIx') && ...
                isfield(dijProb2,'quantity') && ...
                isfield(dijProb2,'quantityField') && ...
                isfield(dijProb2,'probabilisticMode') && ...
                strcmp(char(dijProb2.probabilisticMode),'PROB2');
        end

        function tf = isProb2DijContextUsable(dijProb2Context,dijProb2)
            tf = isstruct(dijProb2Context) && ...
                isfield(dijProb2Context,'totalNumOfBixels') && ...
                dijProb2Context.totalNumOfBixels == ...
                size(dijProb2.expected,2) && ...
                isfield(dijProb2Context,'physicalDose') && ...
                iscell(dijProb2Context.physicalDose) && ...
                ~isempty(dijProb2Context.physicalDose) && ...
                isequal(size(dijProb2Context.physicalDose{1}), ...
                size(dijProb2.expected));
        end

        function tf = isProb2DijContextCompatibleWithStf( ...
                dijProb2Context,stf)
            tf = isstruct(dijProb2Context) && ...
                isfield(dijProb2Context,'totalNumOfBixels') && ...
                ~isempty(stf) && isstruct(stf) && ...
                isfield(stf,'totalNumOfBixels') && ...
                dijProb2Context.totalNumOfBixels == ...
                sum([stf.totalNumOfBixels]);
        end

        function tf = isCachedNominalDijContextUsable( ...
                cached,robustData,dijProb2)
            if ~planWorkflow.precompute.Prob2DoseInfluence.needsRobustNominalDij( ...
                    robustData)
                tf = true;
                return;
            end

            tf = isfield(cached,'dijProb2Context') && ...
                planWorkflow.precompute.Prob2DoseInfluence.isNominalDijContextUsable( ...
                cached.dijProb2Context,dijProb2);
        end

        function tf = isNominalDijContextUsable(dijContext,dijProb2)
            tf = false;
            if ~isstruct(dijContext) || ~isstruct(dijProb2) || ...
                    ~isfield(dijProb2,'expected') || ...
                    ~isfield(dijContext,'totalNumOfBixels') || ...
                    dijContext.totalNumOfBixels ~= size(dijProb2.expected,2)
                return;
            end

            quantityField = ...
                planWorkflow.precompute.Prob2DoseInfluence.prob2QuantityField( ...
                dijProb2);
            tf = ...
                planWorkflow.precompute.Prob2DoseInfluence.isDijQuantityUsable( ...
                dijContext,quantityField,size(dijProb2.expected));
        end

        function tf = needsRobustNominalDij(robustData)
            tf = isstruct(robustData) && ...
                isfield(robustData,'planConfig') && ...
                isstruct(robustData.planConfig) && ...
                isfield(robustData.planConfig,'requiresProb2Dij') && ...
                logical(robustData.planConfig.requiresProb2Dij) && ...
                isfield(robustData.planConfig,'hasNominalObjectives') && ...
                logical(robustData.planConfig.hasNominalObjectives);
        end

        function robustData = attachNominalDijFromContext(robustData)
            if ~isfield(robustData,'dijProb2Context') || ...
                    isempty(robustData.dijProb2Context)
                error(['planWorkflow:precompute:Prob2DoseInfluence:' ...
                    'MissingNominalDijContext'], ...
                    ['PROB2 optimization with nominal objectives requires ' ...
                    'dijProb2Context from matRad.']);
            end
            if ~planWorkflow.precompute.Prob2DoseInfluence.isNominalDijContextUsable( ...
                    robustData.dijProb2Context,robustData.dij_prob2)
                error(['planWorkflow:precompute:Prob2DoseInfluence:' ...
                    'InconsistentNominalDijContext'], ...
                    ['dijProb2Context returned by matRad is not ' ...
                    'compatible with dij_prob2.']);
            end
            robustData.dijNominal = robustData.dijProb2Context;
            robustData.plnNominal = ...
                planWorkflow.precompute.Prob2DoseInfluence.createNominalOptimizationPlan( ...
                robustData,robustData.dijNominal);
            robustData.stfNominal = robustData.stf;
        end

        function robustData = stripStoredProb2PlanPayload(robustData)
            if isfield(robustData,'pln')
                robustData.pln = ...
                    planWorkflow.precompute.Prob2DoseInfluence.removeProb2DijFromPlan( ...
                    robustData.pln);
            end
            if isfield(robustData,'plnForOptimization')
                robustData.plnForOptimization = ...
                    planWorkflow.precompute.Prob2DoseInfluence.removeProb2DijFromPlan( ...
                    robustData.plnForOptimization);
            end
            if isfield(robustData,'plnNominal')
                robustData.plnNominal = ...
                    planWorkflow.precompute.Prob2DoseInfluence.removeProb2DijFromPlan( ...
                    robustData.plnNominal);
            end
        end

        function pln = removeProb2DijFromPlan(pln)
            pln = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.removePlanPayload( ...
                pln,'dij_prob2');
        end

        function pln = attachProb2DijToPlan(pln,dijProb2)
            pln = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.attachPlanPayload( ...
                pln,'dij_prob2',dijProb2);
        end

        function quantityField = prob2QuantityField(dijProb2)
            quantityField = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.quantityField( ...
                dijProb2,'physicalDose');
        end

        function tf = isDijQuantityUsable(dij,quantityField,expectedSize)
            tf = ...
                planWorkflow.precompute.ScenarioFreeDoseInfluence.isDijQuantityUsable( ...
                dij,quantityField,expectedSize);
        end

        function value = optionalStructField(input,fieldName,defaultValue)
            if isstruct(input) && isfield(input,fieldName)
                value = input.(fieldName);
            else
                value = defaultValue;
            end
        end

        function [plnForOptimization,dijProb2Context] = ...
                callStreamingProb2(robustData,prob2Config)
            [plnForOptimization,dijProb2Context] = ...
                matRad_calcDoseProb2Streaming( ...
                robustData.ct,robustData.cst,robustData.stf, ...
                robustData.pln,prob2Config);
        end

        function label = executionModeLabel(useStreaming)
            if logical(useStreaming)
                label = 'streaming';
            else
                label = 'legacy robust dij';
            end
        end
    end
end
