classdef RobustDataFactory
    % RobustDataFactory Builds robust-plan precompute data explicitly.

    methods (Static)
        function robustData = build(runConfig,planTemplate, ...
                robustPlanConfig,sourceData)
            [sourceData,scenarioForComputation,ctReferenceView] = ...
                planWorkflow.precompute.CtReferenceDataView.apply( ...
                sourceData,robustPlanConfig.scenario);
            variants = ...
                planWorkflow.config.RobustPlanConfig.variantsWithPenalties( ...
                robustPlanConfig);
            cstByVariant = cell(1,numel(variants));
            objectiveInfoByVariant = cell(1,numel(variants));
            for variantIx = 1:numel(variants)
                [cstVariant,objectiveInfo] = ...
                    planWorkflow.precompute.RobustDataFactory.buildVariantCst( ...
                    runConfig,planTemplate,robustPlanConfig, ...
                    sourceData,variants(variantIx));
                cstByVariant{variantIx} = cstVariant;
                objectiveInfoByVariant{variantIx} = objectiveInfo;
            end
            cstRobust = cstByVariant{1};
            objectiveInfo = objectiveInfoByVariant{1};

            plnRobust = sourceData.pln;
            robustScenarioConfig = ...
                planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                scenarioForComputation);
            robustScenarioConfig = ...
                planWorkflow.config.ScenarioSpec.withBeamCount( ...
                robustScenarioConfig,plnRobust);
            multScen = planWorkflow.scenario.createModel(sourceData.ct, ...
                robustScenarioConfig.scen_mode,robustScenarioConfig, ...
                'optimization');
            plnRobust.multScen = multScen;
            plnRobust = planWorkflow.plan.Plan.applyDoseParallelism( ...
                plnRobust,runConfig);
            stfRobust = matRad_generateStf(sourceData.ct,cstRobust, ...
                plnRobust);

            robustData = struct();
            robustData.ct = sourceData.ct;
            robustData.cst = cstRobust;
            robustData.pln = plnRobust;
            robustData.stf = stfRobust;
            robustData.ctScenProb = multScen.ctScenProb(:,2)';
            robustData.ctReferenceView = ctReferenceView;
            robustData.objectiveInfo = objectiveInfo;
            robustData.cstByVariant = cstByVariant;
            robustData.objectiveInfoByVariant = objectiveInfoByVariant;
            robustData.planConfig = robustPlanConfig;
            robustData.strategy = ...
                planWorkflow.robustness.AbstractStrategy.create( ...
                robustPlanConfig.robustnessMode);
        end

        function robustData = applyFirstVariant(runConfig,robustData)
            variantRunConfig = ...
                planWorkflow.config.RobustPlanConfig.variantRunConfig( ...
                runConfig,robustData.planConfig,1);
            [robustData.cst,robustData.pln] = robustData.strategy.apply( ...
                robustData.cst,robustData.pln,robustData.objectiveInfo, ...
                variantRunConfig);
            if isfield(robustData,'cstByVariant') && ...
                    iscell(robustData.cstByVariant) && ...
                    ~isempty(robustData.cstByVariant)
                robustData.cstByVariant{1} = robustData.cst;
            end
            robustData.pln = ...
                planWorkflow.optimization.PlanOptimizationService.apply4DConfig( ...
                robustData.pln,robustData.planConfig);
        end

        function robustData = refreshAfterReferencePulling(runConfig, ...
                planTemplate,robustData,sourceData)
            refreshedData = ...
                planWorkflow.precompute.RobustDataFactory.build( ...
                runConfig,planTemplate,robustData.planConfig,sourceData);
            refreshedData = ...
                planWorkflow.precompute.RobustDataFactory.applyFirstVariant( ...
                runConfig,refreshedData);

            robustData.cst = refreshedData.cst;
            robustData.pln = refreshedData.pln;
            robustData.ct = refreshedData.ct;
            if isfield(robustData.planConfig,'requiresProbDij') && ...
                    logical(robustData.planConfig.requiresProbDij)
                robustData = ...
                    planWorkflow.precompute.ProbDoseInfluence.restoreOptimizationPlan( ...
                    robustData);
            elseif isfield(robustData.planConfig,'requiresIntervalDij') && ...
                    logical(robustData.planConfig.requiresIntervalDij)
                robustData = ...
                    planWorkflow.precompute.IntervalDoseInfluence.restoreOptimizationPlan( ...
                    robustData);
            end
            robustData.stf = refreshedData.stf;
            robustData.ctScenProb = refreshedData.ctScenProb;
            robustData.ctReferenceView = refreshedData.ctReferenceView;
            if isfield(robustData,'optimizationInput')
                robustData = rmfield(robustData,'optimizationInput');
            end
            robustData.objectiveInfo = refreshedData.objectiveInfo;
            robustData.cstByVariant = refreshedData.cstByVariant;
            robustData.objectiveInfoByVariant = ...
                refreshedData.objectiveInfoByVariant;
        end

        function cst = cstForVariant(robustData,variantIx)
            if isstruct(robustData) && isfield(robustData,'cstByVariant') && ...
                    iscell(robustData.cstByVariant) && ...
                    numel(robustData.cstByVariant) >= variantIx && ...
                    ~isempty(robustData.cstByVariant{variantIx})
                cst = robustData.cstByVariant{variantIx};
            else
                cst = robustData.cst;
            end
        end

        function objectiveInfo = objectiveInfoForVariant( ...
                robustData,variantIx)
            if isstruct(robustData) && ...
                    isfield(robustData,'objectiveInfoByVariant') && ...
                    iscell(robustData.objectiveInfoByVariant) && ...
                    numel(robustData.objectiveInfoByVariant) >= variantIx && ...
                    ~isempty(robustData.objectiveInfoByVariant{variantIx})
                objectiveInfo = robustData.objectiveInfoByVariant{variantIx};
            else
                objectiveInfo = robustData.objectiveInfo;
            end
        end

        function robustData = setCstByVariant(robustData,cstByVariant)
            robustData.cstByVariant = cstByVariant;
            if ~isempty(cstByVariant)
                robustData.cst = cstByVariant{1};
            end
        end
    end

    methods (Static, Access = private)
        function [cstVariant,objectiveInfo] = buildVariantCst( ...
                runConfig,planTemplate,robustPlanConfig,sourceData, ...
                variant)
            cstVariant = sourceData.cst;
            [cstVariant,objectiveInfo] = ...
                planWorkflow.templates.PlanTemplate.applyObjectives( ...
                runConfig,[],cstVariant,planTemplate, ...
                robustPlanConfig.objectiveSetName,variant);

            cstVariant = ...
                planWorkflow.precompute.RobustDataFactory.restoreRobustOarObjectives( ...
                cstVariant,sourceData.cst,objectiveInfo.robustOarNames, ...
                variant);
            [cstVariant,objectiveInfo] = ...
                planWorkflow.precompute.PrepareService.addDefaultRings( ...
                runConfig,planTemplate,cstVariant,sourceData.ct, ...
                objectiveInfo,variant);
        end

        function cstRobust = restoreRobustOarObjectives( ...
                cstRobust,sourceCst,robustOarNames,variant)
            if nargin < 4
                variant = [];
            end
            penaltyAssignments = ...
                planWorkflow.precompute.RobustDataFactory.structurePenaltyAssignments( ...
                variant);
            for oarIx = 1:numel(robustOarNames)
                for structureIx = 1:size(cstRobust,1)
                    if strcmp(sourceCst{structureIx,2}, ...
                            robustOarNames{oarIx})
                        robustObjectives = cstRobust{structureIx,6};
                        cstRobust{structureIx,6} = ...
                            planWorkflow.precompute.RobustDataFactory.copyObjectivesPreservingRobustness( ...
                            sourceCst{structureIx,6},robustObjectives, ...
                            sourceCst{structureIx,2},penaltyAssignments);
                    end
                end
            end
        end

        function objectives = copyObjectivesPreservingRobustness( ...
                sourceObjectives,robustObjectives,structureName, ...
                penaltyAssignments)
            if nargin < 3
                structureName = '';
            end
            if nargin < 4
                penaltyAssignments = [];
            end
            objectives = sourceObjectives;
            if isempty(sourceObjectives) || isempty(robustObjectives)
                return;
            end
            numObjectives = min(numel(sourceObjectives),numel(robustObjectives));
            for objectiveIx = 1:numObjectives
                sourceObjective = ...
                    planWorkflow.precompute.RobustDataFactory.objectiveAt( ...
                    objectives,objectiveIx);
                robustObjective = ...
                    planWorkflow.precompute.RobustDataFactory.objectiveAt( ...
                    robustObjectives,objectiveIx);
                robustness = ...
                    planWorkflow.precompute.RobustDataFactory.objectiveRobustness( ...
                    robustObjective);
                if planWorkflow.precompute.RobustDataFactory.hasPenaltyAssignment( ...
                        penaltyAssignments,structureName,objectiveIx)
                    sourceObjective = ...
                        planWorkflow.precompute.RobustDataFactory.copyObjectivePenalty( ...
                        sourceObjective,robustObjective);
                end
                sourceObjective = ...
                    planWorkflow.precompute.RobustDataFactory.setObjectiveRobustness( ...
                    sourceObjective,robustness);
                objectives = ...
                    planWorkflow.precompute.RobustDataFactory.setObjectiveAt( ...
                    objectives,objectiveIx,sourceObjective);
            end
        end

        function objective = objectiveAt(objectives,index)
            if iscell(objectives)
                objective = objectives{index};
            else
                objective = objectives(index);
            end
        end

        function objectives = setObjectiveAt(objectives,index,objective)
            if iscell(objectives)
                objectives{index} = objective;
            else
                objectives(index) = objective;
            end
        end

        function assignments = structurePenaltyAssignments(variant)
            assignments = repmat(struct( ...
                'groupField','', ...
                'groupIx',0, ...
                'objectiveIx',0, ...
                'structureName','', ...
                'value',0),1,0);
            if ~isstruct(variant) || ~isfield(variant,'penaltyAssignments') || ...
                    isempty(variant.penaltyAssignments)
                return;
            end
            candidateAssignments = variant.penaltyAssignments;
            for assignmentIx = 1:numel(candidateAssignments)
                assignment = candidateAssignments(assignmentIx);
                if isfield(assignment,'groupField') && ...
                        strcmp(char(assignment.groupField), ...
                        'structureObjectives')
                    assignments(end + 1) = assignment; %#ok<AGROW>
                end
            end
        end

        function tf = hasPenaltyAssignment( ...
                assignments,structureName,objectiveIx)
            tf = false;
            for assignmentIx = 1:numel(assignments)
                assignment = assignments(assignmentIx);
                if isfield(assignment,'structureName') && ...
                        isfield(assignment,'objectiveIx') && ...
                        strcmp(char(assignment.structureName), ...
                        char(structureName)) && ...
                        assignment.objectiveIx == objectiveIx
                    tf = true;
                    return;
                end
            end
        end

        function objective = copyObjectivePenalty(objective,sourceObjective)
            [penalty,hasPenalty] = ...
                planWorkflow.precompute.RobustDataFactory.objectiveField( ...
                sourceObjective,'penalty');
            if hasPenalty
                objective = ...
                    planWorkflow.precompute.RobustDataFactory.setObjectiveField( ...
                    objective,'penalty',penalty);
            end

            [sourceParameters,hasSourceParameters] = ...
                planWorkflow.precompute.RobustDataFactory.objectiveField( ...
                sourceObjective,'parameters');
            [parameters,hasParameters] = ...
                planWorkflow.precompute.RobustDataFactory.objectiveField( ...
                objective,'parameters');
            if hasSourceParameters && hasParameters && ...
                    isstruct(sourceParameters) && ...
                    isfield(sourceParameters,'penalty') && ...
                    isstruct(parameters)
                parameters.penalty = sourceParameters.penalty;
                objective = ...
                    planWorkflow.precompute.RobustDataFactory.setObjectiveField( ...
                    objective,'parameters',parameters);
            end
        end

        function [value,hasField] = objectiveField(objective,fieldName)
            value = [];
            if isstruct(objective) && isfield(objective,fieldName)
                value = objective.(fieldName);
                hasField = true;
            elseif isobject(objective) && isprop(objective,fieldName)
                value = objective.(fieldName);
                hasField = true;
            else
                hasField = false;
            end
        end

        function objective = setObjectiveField(objective,fieldName,value)
            if isstruct(objective) || ...
                    (isobject(objective) && isprop(objective,fieldName))
                objective.(fieldName) = value;
            end
        end

        function robustness = objectiveRobustness(objective)
            robustness = '';
            if isstruct(objective) && isfield(objective,'robustness')
                robustness = objective.robustness;
            elseif isobject(objective) && isprop(objective,'robustness')
                robustness = objective.robustness;
            end
        end

        function objective = setObjectiveRobustness(objective,robustness)
            if isempty(robustness)
                return;
            end
            if isstruct(objective) || ...
                    (isobject(objective) && isprop(objective,'robustness'))
                objective.robustness = char(robustness);
            end
        end
    end
end
