classdef RobustDataFactory
    % RobustDataFactory Builds robust-plan precompute data explicitly.

    methods (Static)
        function robustData = build(runConfig,planTemplate, ...
                robustPlanConfig,sourceData)
            cstRobust = sourceData.cst;
            [cstRobust,objectiveInfo] = ...
                planWorkflow.templates.PlanTemplate.applyObjectives( ...
                runConfig,[],cstRobust,planTemplate, ...
                robustPlanConfig.objectiveSetName);

            cstRobust = ...
                planWorkflow.precompute.RobustDataFactory.restoreRobustOarObjectives( ...
                cstRobust,sourceData.cst,objectiveInfo.robustOarNames);
            cstRobust = planWorkflow.structures.scaleDoseObjectives( ...
                cstRobust,objectiveInfo.robustOarNames, ...
                runConfig.scale_factor);
            [cstRobust,objectiveInfo] = ...
                planWorkflow.precompute.PrepareService.addDefaultRings( ...
                runConfig,planTemplate,cstRobust,sourceData.ct, ...
                objectiveInfo);

            plnRobust = sourceData.pln;
            robustScenarioConfig = ...
                planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                robustPlanConfig.scenario);
            robustScenarioConfig = ...
                planWorkflow.config.ScenarioSpec.withBeamCount( ...
                robustScenarioConfig,plnRobust);
            multScen = planWorkflow.scenario.createModel(sourceData.ct, ...
                robustScenarioConfig.scen_mode,robustScenarioConfig, ...
                'optimization');
            plnRobust.multScen = multScen;
            stfRobust = matRad_generateStf(sourceData.ct,cstRobust, ...
                plnRobust);

            robustData = struct();
            robustData.ct = sourceData.ct;
            robustData.cst = cstRobust;
            robustData.pln = plnRobust;
            robustData.stf = stfRobust;
            robustData.ctScenProb = multScen.ctScenProb(:,2)';
            robustData.objectiveInfo = objectiveInfo;
            robustData.planConfig = robustPlanConfig;
            robustData.strategy = ...
                planWorkflow.robustness.AbstractStrategy.create( ...
                robustPlanConfig.strategy);
        end

        function robustData = applyFirstVariant(runConfig,robustData)
            variantRunConfig = ...
                planWorkflow.config.RobustPlanConfig.variantRunConfig( ...
                runConfig,robustData.planConfig,1);
            [robustData.cst,robustData.pln] = robustData.strategy.apply( ...
                robustData.cst,robustData.pln,robustData.objectiveInfo, ...
                variantRunConfig);
            robustData.pln = ...
                planWorkflow.optimization.PlanOptimizationService.apply4DConfig( ...
                robustData.pln,robustData.planConfig);
        end

        function robustData = refreshAfterReferencePulling(runConfig, ...
                planTemplate,robustData,sourceData)
            refreshedData = ...
                planWorkflow.precompute.RobustDataFactory.build( ...
                runConfig,planTemplate,robustData.planConfig,sourceData);
            refreshedData = ...
                planWorkflow.precompute.RobustDataFactory.applyFirstVariant( ...
                runConfig,refreshedData);

            robustData.cst = refreshedData.cst;
            robustData.pln = refreshedData.pln;
            robustData = ...
                planWorkflow.precompute.IntervalDoseInfluence.restoreOptimizationPlan( ...
                robustData);
            robustData.stf = refreshedData.stf;
            robustData.ctScenProb = refreshedData.ctScenProb;
            robustData.objectiveInfo = refreshedData.objectiveInfo;
        end
    end

    methods (Static, Access = private)
        function cstRobust = restoreRobustOarObjectives( ...
                cstRobust,sourceCst,robustOarNames)
            for oarIx = 1:numel(robustOarNames)
                for structureIx = 1:size(cstRobust,1)
                    if strcmp(sourceCst{structureIx,2}, ...
                            robustOarNames{oarIx})
                        cstRobust{structureIx,6} = ...
                            sourceCst{structureIx,6};
                    end
                end
            end
        end
    end
end
