classdef RobustDataFactory
    % RobustDataFactory Builds robust-plan precompute data explicitly.

    methods (Static)
        function robustData = build(runConfig,planTemplate, ...
                robustPlanConfig,sourceData)
            cstRobust = sourceData.cst;
            [cstRobust,objectiveInfo] = ...
                planWorkflow.templates.PlanTemplate.applyObjectives( ...
                runConfig,[],cstRobust,planTemplate, ...
                robustPlanConfig.objectiveSetName);

            cstRobust = ...
                planWorkflow.precompute.RobustDataFactory.restoreRobustOarObjectives( ...
                cstRobust,sourceData.cst,objectiveInfo.robustOarNames);
            [cstRobust,objectiveInfo] = ...
                planWorkflow.precompute.PrepareService.addDefaultRings( ...
                runConfig,planTemplate,cstRobust,sourceData.ct, ...
                objectiveInfo);

            plnRobust = sourceData.pln;
            robustScenarioConfig = ...
                planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                robustPlanConfig.scenario);
            robustScenarioConfig = ...
                planWorkflow.config.ScenarioSpec.withBeamCount( ...
                robustScenarioConfig,plnRobust);
            multScen = planWorkflow.scenario.createModel(sourceData.ct, ...
                robustScenarioConfig.scen_mode,robustScenarioConfig, ...
                'optimization');
            plnRobust.multScen = multScen;
            stfRobust = matRad_generateStf(sourceData.ct,cstRobust, ...
                plnRobust);

            robustData = struct();
            robustData.ct = sourceData.ct;
            robustData.cst = cstRobust;
            robustData.pln = plnRobust;
            robustData.stf = stfRobust;
            robustData.ctScenProb = multScen.ctScenProb(:,2)';
            robustData.objectiveInfo = objectiveInfo;
            robustData.planConfig = robustPlanConfig;
            robustData.strategy = ...
                planWorkflow.robustness.AbstractStrategy.create( ...
                robustPlanConfig.robustnessMode);
        end

        function robustData = applyFirstVariant(runConfig,robustData)
            variantRunConfig = ...
                planWorkflow.config.RobustPlanConfig.variantRunConfig( ...
                runConfig,robustData.planConfig,1);
            [robustData.cst,robustData.pln] = robustData.strategy.apply( ...
                robustData.cst,robustData.pln,robustData.objectiveInfo, ...
                variantRunConfig);
            robustData.pln = ...
                planWorkflow.optimization.PlanOptimizationService.apply4DConfig( ...
                robustData.pln,robustData.planConfig);
        end

        function robustData = refreshAfterReferencePulling(runConfig, ...
                planTemplate,robustData,sourceData)
            refreshedData = ...
                planWorkflow.precompute.RobustDataFactory.build( ...
                runConfig,planTemplate,robustData.planConfig,sourceData);
            refreshedData = ...
                planWorkflow.precompute.RobustDataFactory.applyFirstVariant( ...
                runConfig,refreshedData);

            robustData.cst = refreshedData.cst;
            robustData.pln = refreshedData.pln;
            if isfield(robustData.planConfig,'requiresProb2Dij') && ...
                    logical(robustData.planConfig.requiresProb2Dij)
                robustData = ...
                    planWorkflow.precompute.Prob2DoseInfluence.restoreOptimizationPlan( ...
                    robustData);
            elseif isfield(robustData.planConfig,'requiresIntervalDij') && ...
                    logical(robustData.planConfig.requiresIntervalDij)
                robustData = ...
                    planWorkflow.precompute.IntervalDoseInfluence.restoreOptimizationPlan( ...
                    robustData);
            end
            robustData.stf = refreshedData.stf;
            robustData.ctScenProb = refreshedData.ctScenProb;
            robustData.objectiveInfo = refreshedData.objectiveInfo;
        end
    end

    methods (Static, Access = private)
        function cstRobust = restoreRobustOarObjectives( ...
                cstRobust,sourceCst,robustOarNames)
            for oarIx = 1:numel(robustOarNames)
                for structureIx = 1:size(cstRobust,1)
                    if strcmp(sourceCst{structureIx,2}, ...
                            robustOarNames{oarIx})
                        robustObjectives = cstRobust{structureIx,6};
                        cstRobust{structureIx,6} = ...
                            planWorkflow.precompute.RobustDataFactory.copyObjectivesPreservingRobustness( ...
                            sourceCst{structureIx,6},robustObjectives);
                    end
                end
            end
        end

        function objectives = copyObjectivesPreservingRobustness( ...
                sourceObjectives,robustObjectives)
            objectives = sourceObjectives;
            if isempty(sourceObjectives) || isempty(robustObjectives)
                return;
            end
            numObjectives = min(numel(sourceObjectives),numel(robustObjectives));
            for objectiveIx = 1:numObjectives
                sourceObjective = ...
                    planWorkflow.precompute.RobustDataFactory.objectiveAt( ...
                    objectives,objectiveIx);
                robustObjective = ...
                    planWorkflow.precompute.RobustDataFactory.objectiveAt( ...
                    robustObjectives,objectiveIx);
                robustness = ...
                    planWorkflow.precompute.RobustDataFactory.objectiveRobustness( ...
                    robustObjective);
                sourceObjective = ...
                    planWorkflow.precompute.RobustDataFactory.setObjectiveRobustness( ...
                    sourceObjective,robustness);
                objectives = ...
                    planWorkflow.precompute.RobustDataFactory.setObjectiveAt( ...
                    objectives,objectiveIx,sourceObjective);
            end
        end

        function objective = objectiveAt(objectives,index)
            if iscell(objectives)
                objective = objectives{index};
            else
                objective = objectives(index);
            end
        end

        function objectives = setObjectiveAt(objectives,index,objective)
            if iscell(objectives)
                objectives{index} = objective;
            else
                objectives(index) = objective;
            end
        end

        function robustness = objectiveRobustness(objective)
            robustness = '';
            if isstruct(objective) && isfield(objective,'robustness')
                robustness = objective.robustness;
            elseif isobject(objective) && isprop(objective,'robustness')
                robustness = objective.robustness;
            end
        end

        function objective = setObjectiveRobustness(objective,robustness)
            if isempty(robustness)
                return;
            end
            if isstruct(objective) || ...
                    (isobject(objective) && isprop(objective,'robustness'))
                objective.robustness = char(robustness);
            end
        end
    end
end
