classdef TemplateValidator
    % TemplateValidator Owns plan-template structural validation.

    methods (Static)
        function validateComponents(beams,structures,objectives)
            planWorkflow.templates.TemplateValidator.validateBeamComponent(beams);
            planWorkflow.templates.TemplateValidator.validateStructureComponent( ...
                structures);
            planWorkflow.templates.TemplateValidator.validateRingComponent( ...
                structures);
            planWorkflow.templates.TemplateValidator.validateObjectiveComponent( ...
                objectives,structures);
        end

        function validateTemplate(template,expectedId)
            planWorkflow.templates.TemplateValidator.requireScalarStruct( ...
                template,'template');
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                template,{'schemaVersion','id','description', ...
                'prescriptionDose','dosePulling','radiationModes', ...
                'beamSets','targets','primaryTarget','structures', ...
                'rings','objectiveSets'},'template');
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                template,{'schemaVersion','id','description', ...
                'prescriptionDose','dosePulling','radiationModes', ...
                'beamSets','targets','primaryTarget','structures', ...
                'rings','objectiveSets'},'template');

            if template.schemaVersion ~= 1
                error('planWorkflow:templates:PlanTemplate:UnsupportedSchema', ...
                    'Unsupported plan template schema version %g.', ...
                    template.schemaVersion);
            end
            if ~strcmp(char(template.id),expectedId)
                error('planWorkflow:templates:PlanTemplate:TemplateIdMismatch', ...
                    'Expected plan template "%s" but JSON defines "%s".', ...
                    expectedId,char(template.id));
            end

            planWorkflow.templates.TemplateValidator.validateBeamSets( ...
                template.beamSets);
            planWorkflow.templates.TemplateValidator.validateRadiationModes( ...
                template.radiationModes,template.beamSets, ...
                'template.radiationModes');
            planWorkflow.templates.TemplateValidator.validateDosePullingChannels( ...
                template.dosePulling,'template.dosePulling');
            planWorkflow.templates.TemplateValidator.validateStructureSpecs( ...
                template.structures);
            planWorkflow.templates.TemplateValidator.validateRingSpecs( ...
                template.rings);
            planWorkflow.templates.TemplateValidator.validateObjectiveSets( ...
                template.objectiveSets,template.structures,template.rings, ...
                template.dosePulling,'template.objectiveSets');
            planWorkflow.templates.TemplateValidator.assertSupportedTarget( ...
                template,template.primaryTarget);
        end

        function validateMetadataComponent(metadata)
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                metadata,{'schemaVersion','id','description','components'}, ...
                'metadata.json');
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                metadata,{'schemaVersion','id','description'}, ...
                'metadata.json');
            planWorkflow.templates.TemplateValidator.validateFiniteScalar( ...
                metadata.schemaVersion,'metadata.json.schemaVersion');
            planWorkflow.templates.TemplateValidator.validateTextScalar( ...
                metadata.id,'metadata.json.id');
            planWorkflow.templates.TemplateValidator.validateTextScalar( ...
                metadata.description,'metadata.json.description');
            if ~isfield(metadata,'components')
                return;
            end
            planWorkflow.templates.TemplateValidator.requireScalarStruct( ...
                metadata.components,'metadata.json.components');
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                metadata.components,{'beams','objectives','structures'}, ...
                'metadata.json.components');
            componentNames = fieldnames(metadata.components);
            for i = 1:numel(componentNames)
                planWorkflow.templates.TemplateValidator.validateComponentReference( ...
                    metadata.components.(componentNames{i}), ...
                    sprintf('metadata.json.components.%s', ...
                    componentNames{i}),metadata.description);
            end
        end

        function validateBeamSets(beamSets)
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                beamSets,{'id','numOfFractions','gantryAngles', ...
                'couchAngles','bixelWidth'},'template.beamSets');
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                beamSets,{'id','numOfFractions','gantryAngles', ...
                'bixelWidth'},'template.beamSets');
            planWorkflow.templates.TemplateValidator.assertUniqueTextField( ...
                beamSets,'id','template.beamSets');
            for i = 1:numel(beamSets)
                context = sprintf('template.beamSets(%d)',i);
                planWorkflow.templates.TemplateValidator.validateFiniteScalar( ...
                    beamSets(i).numOfFractions,[context '.numOfFractions']);
                planWorkflow.templates.TemplateValidator.validateFiniteVector( ...
                    beamSets(i).gantryAngles,[context '.gantryAngles']);
                planWorkflow.templates.TemplateValidator.validateFiniteScalar( ...
                    beamSets(i).bixelWidth,[context '.bixelWidth']);
                if isfield(beamSets(i),'couchAngles') && ...
                        ~isempty(beamSets(i).couchAngles)
                    planWorkflow.templates.TemplateValidator.validateFiniteVector( ...
                        beamSets(i).couchAngles,[context '.couchAngles']);
                    if numel(beamSets(i).couchAngles) ~= ...
                            numel(beamSets(i).gantryAngles)
                        error('planWorkflow:templates:PlanTemplate:InvalidBeamSet', ...
                            '%s.couchAngles must match gantryAngles length.', ...
                            context);
                    end
                end
            end
        end

        function validateBeamComponent(beams)
            planWorkflow.templates.TemplateValidator.requireScalarStruct( ...
                beams,'beams');
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                beams,{'radiationModes','beamSets'},'beams');
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                beams,{'radiationModes','beamSets'},'beams');
        end

        function validateStructureComponent(structures)
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                structures,{'structures','rings'},'structures.json');
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                structures,{'structures','rings'},'structures.json');
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                structures.structures,{'name','role','priority', ...
                'visibleColor','operation'},'structures.json.structures');
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                structures.structures,{'name','role','priority'}, ...
                'structures.json.structures');
            planWorkflow.templates.TemplateValidator.assertUniqueTextField( ...
                structures.structures,'name','structures.json.structures');
            planWorkflow.templates.TemplateValidator.validateStructureColors( ...
                structures.structures,'structures.json.structures');
            planWorkflow.templates.TemplateValidator.validateBooleanOperations( ...
                structures.structures,'structures.json.structures');
        end

        function validateRingComponent(structures)
            if isempty(structures.rings)
                return;
            end
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                structures.rings,{'name','role','visibleColor', ...
                'innerMarginMm','outerMarginMm','priority'}, ...
                'structures.json.rings');
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                structures.rings,{'name','role','visibleColor', ...
                'innerMarginMm','outerMarginMm','priority'}, ...
                'structures.json.rings');
            planWorkflow.templates.TemplateValidator.assertUniqueTextField( ...
                structures.rings,'name','structures.json.rings');
            planWorkflow.templates.TemplateValidator.validateStructureColors( ...
                structures.rings,'structures.json.rings');
        end

        function validateObjectiveComponent(objectives,structures)
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                objectives,{'target','prescriptionDose','dosePulling', ...
                'objectiveSets'},'objectives.json');
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                objectives,{'target','prescriptionDose','dosePulling', ...
                'objectiveSets'},'objectives.json');
            if ~ischar(objectives.target) && ~isstring(objectives.target)
                error('planWorkflow:templates:PlanTemplate:InvalidTarget', ...
                    'objectives.json.target must be text.');
            end
            planWorkflow.templates.TemplateValidator.validateFiniteScalar( ...
                objectives.prescriptionDose,'objectives.json.prescriptionDose');
            planWorkflow.templates.TemplateValidator.validateDosePullingChannels( ...
                objectives.dosePulling,'objectives.json.dosePulling');
            planWorkflow.templates.TemplateValidator.validateObjectiveSets( ...
                objectives.objectiveSets,structures.structures, ...
                structures.rings,objectives.dosePulling, ...
                'objectives.json.objectiveSets');
        end

        function validateDosePullingChannels(channels,context)
            planWorkflow.templates.TemplateValidator.requireScalarStruct( ...
                channels,context);
            channelNames = fieldnames(channels);
            if isempty(channelNames)
                error('planWorkflow:templates:PlanTemplate:MissingDosePullingChannel', ...
                    '%s must define at least one dose pulling channel.',context);
            end
            for i = 1:numel(channelNames)
                channel = channels.(channelNames{i});
                channelContext = [context '.' channelNames{i}];
                planWorkflow.templates.TemplateValidator.requireScalarStruct( ...
                    channel,channelContext);
                planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                    channel,{'step','startConfig'},channelContext);
                planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                    channel,{'step','startConfig'},channelContext);
                planWorkflow.templates.TemplateValidator.validateFiniteScalar( ...
                    channel.step,[channelContext '.step']);
                if ~ischar(channel.startConfig) && ...
                        ~isstring(channel.startConfig)
                    error('planWorkflow:templates:PlanTemplate:InvalidDosePullingConfig', ...
                        '%s.startConfig must be text.',channelContext);
                end
            end
        end

        function validateStructureSpecs(structures)
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                structures,{'name','role','priority','visibleColor', ...
                'operation'},'template.structures');
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                structures,{'name','role','priority'},'template.structures');
            planWorkflow.templates.TemplateValidator.assertUniqueTextField( ...
                structures,'name','template.structures');
            planWorkflow.templates.TemplateValidator.validateStructureColors( ...
                structures,'template.structures');
            planWorkflow.templates.TemplateValidator.validateBooleanOperations( ...
                structures,'template.structures');
        end

        function validateRingSpecs(rings)
            if isempty(rings)
                return;
            end
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                rings,{'name','role','visibleColor','innerMarginMm', ...
                'outerMarginMm','priority'},'template.rings');
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                rings,{'name','role','visibleColor','innerMarginMm', ...
                'outerMarginMm','priority'},'template.rings');
            planWorkflow.templates.TemplateValidator.assertUniqueTextField( ...
                rings,'name','template.rings');
            planWorkflow.templates.TemplateValidator.validateStructureColors( ...
                rings,'template.rings');
        end

        function validateObjectiveSets( ...
                objectiveSets,structures,rings,dosePullingChannels,context)
            planWorkflow.templates.TemplateValidator.requireScalarStruct( ...
                objectiveSets,context);
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                objectiveSets,{'reference','robustPlans'},context);
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                objectiveSets,{'reference'},context);

            planWorkflow.templates.TemplateValidator.validateObjectiveSet( ...
                objectiveSets.reference,structures,rings,dosePullingChannels, ...
                [context '.reference'],false,false);

            if ~isfield(objectiveSets,'robustPlans') || ...
                    isempty(objectiveSets.robustPlans)
                return;
            end
            robustPlans = objectiveSets.robustPlans;
            if ~isstruct(robustPlans)
                error('planWorkflow:templates:PlanTemplate:InvalidStruct', ...
                    '%s.robustPlans must be a struct array.',context);
            end
            planWorkflow.templates.TemplateValidator.assertUniqueTextField( ...
                robustPlans,'id',[context '.robustPlans']);
            for planIx = 1:numel(robustPlans)
                setContext = sprintf('%s.robustPlans(%d)',context,planIx);
                planWorkflow.templates.TemplateValidator.validateObjectiveSet( ...
                    robustPlans(planIx),structures,rings, ...
                    dosePullingChannels,setContext,true,true);
                planWorkflow.templates.ObjectivePenaltyVariants.assertPenaltyCombinationLimit( ...
                    robustPlans(planIx),setContext);
            end
        end

        function assertSupportedTarget(template,targetName)
            targetNames = planWorkflow.templates.TemplateValidator.textCell( ...
                template.targets);
            if ~any(strcmp(targetNames,char(targetName)))
                error('planWorkflow:templates:PlanTemplate:UnknownTarget', ...
                    'Plan template "%s" does not define target "%s".', ...
                    char(template.id),char(targetName));
            end
        end
    end

    methods (Static)
        function validateObjectiveSet( ...
                objectiveSet,structures,rings,dosePullingChannels, ...
                setContext,requiresIdentity,allowPenaltyVectors)
            if nargin < 7
                allowPenaltyVectors = false;
            end
            planWorkflow.templates.TemplateValidator.requireScalarStruct( ...
                objectiveSet,setContext);
            fields = {'structureObjectives','ringObjectives'};
            if requiresIdentity
                fields = [{'id','label'},fields];
            end
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                objectiveSet,fields,setContext);
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                objectiveSet,fields,setContext);
            if requiresIdentity
                planWorkflow.templates.TemplateValidator.validateTextScalar( ...
                    objectiveSet.id,[setContext '.id']);
                if ~isvarname(char(objectiveSet.id))
                    error('planWorkflow:templates:PlanTemplate:InvalidObjectiveSetId', ...
                        '%s.id must be a valid MATLAB identifier.', ...
                        setContext);
                end
                planWorkflow.templates.TemplateValidator.validateTextScalar( ...
                    objectiveSet.label,[setContext '.label']);
            end
            planWorkflow.templates.TemplateValidator.validateNamedObjectiveGroups( ...
                objectiveSet.structureObjectives,structures, ...
                dosePullingChannels,[setContext '.structureObjectives'], ...
                allowPenaltyVectors);
            planWorkflow.templates.TemplateValidator.validateNamedObjectiveGroups( ...
                objectiveSet.ringObjectives,rings, ...
                dosePullingChannels,[setContext '.ringObjectives'], ...
                allowPenaltyVectors);
        end

        function validateNamedObjectiveGroups( ...
                groups,baseSpecs,dosePullingChannels,context, ...
                allowPenaltyVectors)
            if nargin < 5
                allowPenaltyVectors = false;
            end
            planWorkflow.templates.TemplateValidator.assertUniqueTextField( ...
                groups,'name',context);
            baseNames = cell(1,numel(baseSpecs));
            for i = 1:numel(baseSpecs)
                baseNames{i} = char(baseSpecs(i).name);
            end
            for i = 1:numel(groups)
                groupName = char(groups(i).name);
                if ~any(strcmp(baseNames,groupName))
                    error('planWorkflow:templates:PlanTemplate:UnknownObjectiveGroup', ...
                        '%s defines objectives for unknown entry "%s".', ...
                        context,groupName);
                end
            end
            for i = 1:numel(baseSpecs)
                structureName = char(baseSpecs(i).name);
                if planWorkflow.templates.TemplateValidator.findTextField( ...
                        groups,'name',structureName) == 0
                    error('planWorkflow:templates:PlanTemplate:MissingObjectives', ...
                        '%s must define objectives for "%s".', ...
                        context,structureName);
                end
            end
            planWorkflow.templates.TemplateValidator.validateObjectiveGroups( ...
                groups,dosePullingChannels,context,allowPenaltyVectors);
        end

        function validateObjectiveGroups(groups,dosePullingChannels,context, ...
                allowPenaltyVectors)
            if nargin < 4
                allowPenaltyVectors = false;
            end
            if isempty(groups)
                return;
            end
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                groups,{'name','objectives'},context);
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                groups,{'name','objectives'},context);
            for i = 1:numel(groups)
                planWorkflow.templates.TemplateValidator.validateObjectives( ...
                    groups(i).objectives,dosePullingChannels, ...
                    [context '.objectives'],allowPenaltyVectors);
            end
        end

        function validateObjectives(objectives,dosePullingChannels,context, ...
                allowPenaltyVectors)
            if nargin < 4
                allowPenaltyVectors = false;
            end
            if isempty(objectives)
                return;
            end
            for i = 1:numel(objectives)
                objectiveSpec = ...
                    planWorkflow.templates.TemplateValidator.objectiveAt( ...
                    objectives,i);
                planWorkflow.templates.TemplateValidator.requireScalarStruct( ...
                    objectiveSpec,context);
                planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                    objectiveSpec,{'enabled','type','parameters', ...
                    'properties','dosePulling'},context);
                planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                    objectiveSpec,{'enabled','type','parameters', ...
                    'properties'},context);
                planWorkflow.templates.TemplateValidator.validateLogicalScalar( ...
                    objectiveSpec.enabled,[context '.enabled']);
                parameterNames = ...
                    planWorkflow.templates.ObjectiveFactory.parameterNamesForObjectiveType( ...
                    objectiveSpec.type);
                planWorkflow.templates.TemplateValidator.validateParameterMap( ...
                    objectiveSpec.parameters,parameterNames, ...
                    [context '.parameters'],allowPenaltyVectors);
                planWorkflow.templates.TemplateValidator.validateObjectiveProperties( ...
                    objectiveSpec.type,objectiveSpec.properties, ...
                    [context '.properties']);
                if isfield(objectiveSpec,'dosePulling') && ...
                        ~isempty(objectiveSpec.dosePulling)
                    planWorkflow.templates.TemplateValidator.validateObjectiveDosePulling( ...
                        objectiveSpec.dosePulling,parameterNames, ...
                        dosePullingChannels,[context '.dosePulling']);
                    planWorkflow.templates.TemplateValidator.validatePenaltyVectorDosePulling( ...
                        objectiveSpec,dosePullingChannels,context);
                end
            end
        end

        function validateParameterMap(parameters,parameterNames,context, ...
                allowPenaltyVectors)
            if nargin < 4
                allowPenaltyVectors = false;
            end
            planWorkflow.templates.TemplateValidator.requireScalarStruct( ...
                parameters,context);
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                parameters,parameterNames,context);
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                parameters,parameterNames,context);
            for i = 1:numel(parameterNames)
                planWorkflow.templates.TemplateValidator.validateParameterValue( ...
                    parameters.(parameterNames{i}), ...
                    [context '.' parameterNames{i}],parameterNames{i}, ...
                    allowPenaltyVectors);
            end
        end

        function validateParameterValue(value,context,parameterName, ...
                allowPenaltyVectors)
            if nargin < 4
                allowPenaltyVectors = false;
            end
            if isnumeric(value)
                if strcmp(char(parameterName),'penalty') && ...
                        logical(allowPenaltyVectors)
                    planWorkflow.templates.TemplateValidator.validateFiniteVector( ...
                        value,context);
                else
                    planWorkflow.templates.TemplateValidator.validateFiniteScalar( ...
                        value,context);
                end
                return;
            end
            if (ischar(value) || isstring(value)) && strcmp(parameterName,'fDiff')
                return;
            end
            planWorkflow.templates.TemplateValidator.requireScalarStruct( ...
                value,context);
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                value,{'ref','scale','offset'},context);
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                value,{'ref'},context);
            if ~strcmp(char(value.ref),'prescriptionDose')
                error('planWorkflow:templates:PlanTemplate:UnknownParameterSource', ...
                    '%s references unsupported source "%s".', ...
                    context,char(value.ref));
            end
            if isfield(value,'scale')
                planWorkflow.templates.TemplateValidator.validateFiniteScalar( ...
                    value.scale,[context '.scale']);
            end
            if isfield(value,'offset')
                planWorkflow.templates.TemplateValidator.validateFiniteScalar( ...
                    value.offset,[context '.offset']);
            end
        end

        function validateObjectiveProperties(objectiveType,properties,context)
            planWorkflow.templates.TemplateValidator.requireScalarStruct( ...
                properties,context);
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                properties,{'robustness'},context);
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                properties,{'robustness'},context);
            if ~ischar(properties.robustness) && ...
                    ~isstring(properties.robustness)
                error('planWorkflow:templates:PlanTemplate:InvalidRobustness', ...
                    '%s.robustness must be text.',context);
            end
            robustness = char(properties.robustness);
            if ~planWorkflow.matRadCapabilitiesReader.supportsObjectiveRobustness( ...
                    objectiveType,robustness)
                error('planWorkflow:templates:PlanTemplate:UnsupportedRobustness', ...
                    ['%s.robustness "%s" is not supported by objective ' ...
                    'type "%s".'],context,robustness,char(objectiveType));
            end
        end

        function validateObjectiveDosePulling( ...
                dosePulling,parameterNames,dosePullingChannels,context)
            planWorkflow.templates.TemplateValidator.requireScalarStruct( ...
                dosePulling,context);
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                dosePulling,{'channel','rates'},context);
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                dosePulling,{'channel','rates'},context);

            channelName = char(dosePulling.channel);
            if ~isfield(dosePullingChannels,channelName)
                error('planWorkflow:templates:PlanTemplate:UnknownDosePullingChannel', ...
                    '%s references unknown dose pulling channel "%s".', ...
                    context,channelName);
            end

            planWorkflow.templates.TemplateValidator.requireScalarStruct( ...
                dosePulling.rates,[context '.rates']);
            rateNames = fieldnames(dosePulling.rates);
            if isempty(rateNames)
                error('planWorkflow:templates:PlanTemplate:MissingDosePullingRate', ...
                    '%s.rates must define at least one rate.',context);
            end
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                dosePulling.rates,parameterNames,[context '.rates']);
            for i = 1:numel(rateNames)
                planWorkflow.templates.TemplateValidator.validateFiniteScalar( ...
                    dosePulling.rates.(rateNames{i}), ...
                    [context '.rates.' rateNames{i}]);
            end
        end

        function validatePenaltyVectorDosePulling( ...
                objectiveSpec,dosePullingChannels,context)
            if ~isfield(objectiveSpec,'parameters') || ...
                    ~isfield(objectiveSpec.parameters,'penalty') || ...
                    ~isnumeric(objectiveSpec.parameters.penalty) || ...
                    numel(objectiveSpec.parameters.penalty) <= 1
                return;
            end
            channelName = char(objectiveSpec.dosePulling.channel);
            if ~isfield(dosePullingChannels,channelName)
                return;
            end
            channel = dosePullingChannels.(channelName);
            if ~isfield(channel,'step') || ~isnumeric(channel.step) || ...
                    ~isscalar(channel.step) || channel.step ~= 2
                return;
            end
            error(['planWorkflow:templates:PlanTemplate:' ...
                'PenaltyVectorDosePulling2'], ...
                ['%s cannot use dose_pulling step 2 when ' ...
                'parameters.penalty contains multiple values. Disable ' ...
                'dosePulling for that objective or use a scalar penalty.'], ...
                context);
        end

        function validateBooleanOperations(structures,context)
            if ~isfield(structures,'operation')
                return;
            end
            for i = 1:numel(structures)
                if isempty(structures(i).operation)
                    continue;
                end
                if ~ischar(structures(i).operation) && ...
                        ~isstring(structures(i).operation)
                    error('planWorkflow:templates:PlanTemplate:InvalidBooleanOperation', ...
                        '%s.operation must be text.',context);
                end
                planWorkflow.templates.TemplateValidator.parseBooleanOperation( ...
                    structures(i).operation);
            end
        end

        function validateStructureColors(structures,context)
            if ~isfield(structures,'visibleColor')
                return;
            end
            for i = 1:numel(structures)
                if isempty(structures(i).visibleColor)
                    continue;
                end
                color = double(structures(i).visibleColor(:)');
                if numel(color) ~= 3 || any(~isfinite(color)) || ...
                        any(color < 0) || any(color > 1)
                    error('planWorkflow:templates:PlanTemplate:InvalidVisibleColor', ...
                        ['%s.visibleColor must contain three RGB values ' ...
                         'between 0 and 1.'],context);
                end
            end
        end

        function validateRadiationMode(value,context)
            if ~(ischar(value) || (isstring(value) && isscalar(value)))
                error('planWorkflow:templates:PlanTemplate:InvalidRadiationMode', ...
                    '%s must be a text scalar.',context);
            end
            supportedModes = ...
                planWorkflow.matRadCapabilitiesReader.supportedRadiationModes();
            if ~any(strcmp(char(value),supportedModes))
                error('planWorkflow:templates:PlanTemplate:InvalidRadiationMode', ...
                    '%s "%s" is not supported by the installed matRad.', ...
                    context,char(value));
            end
        end

        function validateRadiationModes(values,beamSets,context)
            if ~isstruct(values) || isempty(values)
                error('planWorkflow:templates:PlanTemplate:InvalidRadiationMode', ...
                    '%s must define at least one radiation mode struct.', ...
                    context);
            end
            planWorkflow.templates.TemplateValidator.assertAllowedFields( ...
                values,{'id','defaultBeamSet','machine','bioModel'}, ...
                context);
            planWorkflow.templates.TemplateValidator.assertRequiredFields( ...
                values,{'id','defaultBeamSet','machine','bioModel'}, ...
                context);
            ids = cell(1,numel(values));
            for i = 1:numel(values)
                itemContext = sprintf('%s(%d)',context,i);
                planWorkflow.templates.TemplateValidator.validateRadiationMode( ...
                    values(i).id,[itemContext '.id']);
                ids{i} = char(values(i).id);
                planWorkflow.templates.TemplateValidator.validateTextScalar( ...
                    values(i).defaultBeamSet,[itemContext '.defaultBeamSet']);
                planWorkflow.templates.TemplateValidator.validateTextScalar( ...
                    values(i).machine,[itemContext '.machine']);
                planWorkflow.templates.TemplateValidator.validateTextScalar( ...
                    values(i).bioModel,[itemContext '.bioModel']);
                defaultBeamSet = char(values(i).defaultBeamSet);
                beamSetIds = {beamSets.id};
                if ~any(strcmp(defaultBeamSet,beamSetIds))
                    error('planWorkflow:templates:PlanTemplate:InvalidRadiationMode', ...
                        ['template.radiationModes(%d).defaultBeamSet "%s" ' ...
                         'does not exist in template.beamSets.'], ...
                        i,defaultBeamSet);
                end
                machines = ...
                    planWorkflow.matRadCapabilitiesReader.supportedMachines( ...
                    values(i).id);
                if ~any(strcmp(char(values(i).machine),machines))
                    error('planWorkflow:templates:PlanTemplate:InvalidRadiationMode', ...
                        ['template.radiationModes(%d).machine "%s" is not ' ...
                         'available for radiationMode "%s".'],i, ...
                        char(values(i).machine),char(values(i).id));
                end
                bioModels = ...
                    planWorkflow.matRadCapabilitiesReader.supportedBioModels( ...
                    values(i).id);
                if ~any(strcmp(char(values(i).bioModel),bioModels))
                    error('planWorkflow:templates:PlanTemplate:InvalidRadiationMode', ...
                        ['template.radiationModes(%d).bioModel "%s" is not ' ...
                         'available for radiationMode "%s".'],i, ...
                        char(values(i).bioModel),char(values(i).id));
                end
            end
            if numel(unique(ids)) ~= numel(ids)
                error('planWorkflow:templates:PlanTemplate:InvalidRadiationMode', ...
                    '%s must not contain duplicate radiation modes.',context);
            end
        end

        function parts = validateComponentReference( ...
                componentReference,context,description)
            planWorkflow.templates.TemplateValidator.validateTextScalar( ...
                componentReference,context);
            componentReference = strrep(char(componentReference),'\','/');
            parts = strsplit(componentReference,'/');
            invalidPart = isempty(componentReference) || ...
                any(cellfun(@isempty,parts)) || any(strcmp(parts,'.')) || ...
                any(strcmp(parts,'..')) || startsWith(componentReference,'/') || ...
                ~endsWith(componentReference,'.json');
            if invalidPart
                error('planWorkflow:templates:PlanTemplate:InvalidComponentReference', ...
                    '%s must be a relative JSON path inside json/%s.', ...
                    context,char(description));
            end
        end

        function objectiveSpec = objectiveAt(objectives,index)
            if iscell(objectives)
                objectiveSpec = objectives{index};
            else
                objectiveSpec = objectives(index);
            end
        end

        function [operands,operators] = parseBooleanOperation(operation)
            operation = strtrim(char(operation));
            if isempty(operation)
                error('planWorkflow:templates:PlanTemplate:InvalidBooleanOperation', ...
                    'Boolean structure operation must not be empty.');
            end
            tokens = regexp(operation,'([^\+\-]+|[\+\-])','match');
            tokens = cellfun(@strtrim,tokens,'UniformOutput',false);
            tokens = tokens(~cellfun(@isempty,tokens));
            if numel(tokens) < 3 || mod(numel(tokens),2) == 0
                error('planWorkflow:templates:PlanTemplate:InvalidBooleanOperation', ...
                    ['Boolean structure operation "%s" must use structure ' ...
                    'names separated by + or -.'],operation);
            end
            operands = tokens(1:2:end);
            operators = tokens(2:2:end);
            validOperators = ismember(operators,{'+','-'});
            if any(cellfun(@isempty,operands)) || any(~validOperators)
                error('planWorkflow:templates:PlanTemplate:InvalidBooleanOperation', ...
                    'Boolean structure operation "%s" is invalid.',operation);
            end
        end

        function assertUniqueTextField(values,fieldName,context)
            names = cell(1,numel(values));
            for i = 1:numel(values)
                names{i} = char(values(i).(fieldName));
            end
            [~,uniqueIx] = unique(names,'stable');
            if numel(uniqueIx) ~= numel(names)
                error('planWorkflow:templates:PlanTemplate:DuplicateFieldValue', ...
                    '%s has duplicate %s values.',context,fieldName);
            end
        end

        function assertAllowedFields(value,allowedFields,context)
            fields = fieldnames(value);
            invalid = setdiff(fields,allowedFields);
            if ~isempty(invalid)
                error('planWorkflow:templates:PlanTemplate:UnsupportedField', ...
                    '%s contains unsupported field "%s".', ...
                    context,invalid{1});
            end
        end

        function assertRequiredFields(value,requiredFields,context)
            fields = fieldnames(value);
            for i = 1:numel(requiredFields)
                if ~any(strcmp(fields,requiredFields{i}))
                    error('planWorkflow:templates:PlanTemplate:MissingField', ...
                        '%s must define field "%s".',context,requiredFields{i});
                end
            end
        end

        function requireScalarStruct(value,context)
            if ~isstruct(value) || ~isscalar(value)
                error('planWorkflow:templates:PlanTemplate:InvalidStruct', ...
                    '%s must be a scalar struct.',context);
            end
        end

        function validateFiniteScalar(value,context)
            if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value)
                error('planWorkflow:templates:PlanTemplate:InvalidNumericValue', ...
                    '%s must be a finite numeric scalar.',context);
            end
        end

        function validateFiniteVector(value,context)
            if ~isnumeric(value) || isempty(value) || ~isvector(value) || ...
                    any(~isfinite(value(:)))
                error('planWorkflow:templates:PlanTemplate:InvalidNumericValue', ...
                    '%s must be a finite numeric vector.',context);
            end
        end

        function validateLogicalScalar(value,context)
            if ~islogical(value) || ~isscalar(value)
                error('planWorkflow:templates:PlanTemplate:InvalidLogicalValue', ...
                    '%s must be a logical scalar.',context);
            end
        end

        function validateTextScalar(value,context)
            if ~(ischar(value) || (isstring(value) && isscalar(value)))
                error('planWorkflow:templates:PlanTemplate:InvalidTextValue', ...
                    '%s must be a text scalar.',context);
            end
        end

        function ix = findTextField(values,fieldName,needle)
            ix = 0;
            for i = 1:numel(values)
                if strcmp(char(values(i).(fieldName)),char(needle))
                    ix = i;
                    return;
                end
            end
        end

        function values = textCell(value)
            if iscell(value)
                values = cellfun(@char,value(:)','UniformOutput',false);
            elseif isstring(value)
                values = cellstr(value(:)');
            elseif ischar(value)
                values = {value};
            else
                error('planWorkflow:templates:PlanTemplate:InvalidTextArray', ...
                    'Expected a text array.');
            end
        end
    end
end
