classdef AnalyzeStage
    % AnalyzeStage Builds final analysis results for reference/robust plans.

    methods (Static)
        function context = workflowContext(varargin)
            if nargin == 3 && ...
                    planWorkflow.stages.WorkflowRuntime.isRuntime(varargin{3})
                runConfig = varargin{1};
                data = varargin{2};
                runtime = varargin{3};
                taskRunner = runtime.taskRunner();
                logFn = runtime.logFn();
                rootPath = ...
                    planWorkflow.results.WorkflowIdentity.rootPath( ...
                    runConfig);
            else
                [runConfig,data,taskRunner,logFn,rootPath] = varargin{:};
            end
            context = planWorkflow.stages.AnalyzeStage.context( ...
                runConfig,data,taskRunner,logFn,rootPath, ...
                @(ct,cst,stf,pln,w) ...
                matRad_calcDoseForward(ct,cst,stf,pln,w));
        end

        function context = context(runConfig,data,taskRunner,logFn, ...
                rootPath,forwardDoseForAnalysis)
            data = planWorkflow.stages.ContextValidator.dataSlice( ...
                data,{'ct','cst','stf','pln','resultGUIReference'}, ...
                {'robustPlans','sampling','objectiveInfo', ...
                'structureNormalizationReport','quantityOpt','quantityVis'}, ...
                'analysis');
            context = planWorkflow.stages.ContextValidator.base( ...
                'analysis',runConfig,data,taskRunner,logFn);
            context.rootPath = rootPath;
            context.forwardDoseForAnalysis = forwardDoseForAnalysis;
            planWorkflow.stages.ContextValidator.requireFields( ...
                context,{'rootPath','forwardDoseForAnalysis'}, ...
                'analysis');
        end

        function patch = run(context)
            data = context.data;
            logFn = context.log;

            logFn('Analyzing robust workflow results.');
            analysis = planWorkflow.analysis.AnalysisService.completeConfig( ...
                context.runConfig,data);
            context.runConfig.analysis = analysis;
            results = struct();
            results.runConfig = context.runConfig;
            results.runConfig.analysis = analysis;
            results.robustnessMode = ...
                planWorkflow.config.RobustPlanConfig.robustnessModeNames( ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                context.runConfig));
            if isfield(data,'structureNormalizationReport')
                results.structureNormalizationReport = ...
                    data.structureNormalizationReport;
            end

            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                context.runConfig);
            referenceLabel = ...
                planWorkflow.results.PlanLabels.referencePlanDisplayLabel( ...
                reference);
            [resultGUIReferenceAnalysis,dvhReference,qiReference] = ...
                context.runMeasuredPlanTask( ...
                'analyze','reference',referenceLabel,'planAnalysis', ...
                '','',@() planWorkflow.analysis.AnalysisService.runFromOptimizationResult( ...
                context,data.ct,data.cst,data.stf,data.pln, ...
                data.resultGUIReference,true));
            results.reference.label = referenceLabel;
            results.reference.qi = qiReference;
            results.reference.dvh = dvhReference;
            results.reference = ...
                planWorkflow.analysis.AnalysisService.attachAnalysisMetadata( ...
                results.reference,resultGUIReferenceAnalysis,dvhReference);

            if planWorkflow.stages.AnalyzeStage.hasRobustDataPlans(data)
                results.robust = cell( ...
                    1,planWorkflow.stages.AnalyzeStage.robustResultCount(data));
                resultIx = 0;
                for robustPlanIx = 1:numel(data.robustPlans)
                    robustData = data.robustPlans{robustPlanIx};
                    variantResults = ...
                        planWorkflow.results.VariantResults.requireComplete( ...
                        robustData,'analysis');
                    for variantIx = 1:numel(variantResults)
                        resultIx = resultIx + 1;
                        variantResult = variantResults(variantIx);
                        planLabel = variantResult.label;
                        [variantStf,variantPln] = ...
                            planWorkflow.analysis.NominalForwardInputs.robustVariant( ...
                            robustData,variantResult);
                        [resultGUIRobustAnalysis,dvhRobust,qiRobust] = ...
                            context.runMeasuredPlanTask( ...
                            'analyze','robust',planLabel,'planAnalysis', ...
                            variantResult.planId,variantResult.variantId, ...
                            @() planWorkflow.analysis.AnalysisService.runFromOptimizationResult( ...
                            context,robustData.ct,robustData.cst,variantStf, ...
                            variantPln,variantResult.resultGUI,true));
                        results.robust{resultIx}.label = planLabel;
                        results.robust{resultIx}.robustPlanId = ...
                            variantResult.planId;
                        results.robust{resultIx}.variantId = ...
                            variantResult.variantId;
                        results.robust{resultIx}.dvh = dvhRobust;
                        results.robust{resultIx}.qi = qiRobust;
                        results.robust{resultIx} = ...
                            planWorkflow.analysis.AnalysisService.attachAnalysisMetadata( ...
                            results.robust{resultIx}, ...
                            resultGUIRobustAnalysis,dvhRobust);
                        variantResults(variantIx).dvh = dvhRobust;
                        variantResults(variantIx).qi = qiRobust;
                        variantMetadata = ...
                            planWorkflow.analysis.AnalysisService.attachAnalysisMetadata( ...
                            struct(),resultGUIRobustAnalysis,dvhRobust);
                        variantMetadataFields = fieldnames(variantMetadata);
                        for metadataIx = 1:numel(variantMetadataFields)
                            fieldName = variantMetadataFields{metadataIx};
                            variantResults(variantIx).(fieldName) = ...
                                variantMetadata.(fieldName);
                        end
                    end
                    robustData.variantResults = variantResults;
                    data.robustPlans{robustPlanIx} = robustData;
                end
            end

            results.analysis = analysis;
            if isfield(data,'sampling')
                results.sampling = ...
                    planWorkflow.analysis.AnalysisService.analyzeSamplingData( ...
                    context,data.sampling);
            end
            planWorkflow.analysis.AnalysisService.logResults(context,results);

            patch = struct();
            patch.runConfig = struct('analysis',analysis);
            patch.data = struct();
            patch.data.dvhReference = dvhReference;
            patch.data.qiReference = qiReference;
            patch.data.results = results;
            if isfield(data,'robustPlans')
                patch.data.robustPlans = data.robustPlans;
            end
        end
    end

    methods (Static, Access = private)
        function tf = hasRobustDataPlans(data)
            tf = isfield(data,'robustPlans') && ~isempty(data.robustPlans);
        end

        function count = robustResultCount(data)
            count = 0;
            if ~planWorkflow.stages.AnalyzeStage.hasRobustDataPlans(data)
                return;
            end
            for robustPlanIx = 1:numel(data.robustPlans)
                robustData = data.robustPlans{robustPlanIx};
                count = count + ...
                    numel(planWorkflow.results.VariantResults.requireComplete( ...
                    robustData,'analysis'));
            end
        end
    end
end
