classdef OptimizeStage
    % OptimizeStage Runs reference and robust fluence optimization.

    methods (Static)
        function context = workflowContext(varargin)
            if nargin == 3 && ...
                    planWorkflow.stages.WorkflowRuntime.isRuntime(varargin{3})
                runConfig = varargin{1};
                data = varargin{2};
                runtime = varargin{3};
                taskRunner = runtime.taskRunner();
                logFn = runtime.logFn();
            else
                [runConfig,data,taskRunner,logFn] = varargin{:};
            end
            context = planWorkflow.stages.OptimizeStage.context( ...
                runConfig,data,taskRunner,logFn, ...
                @(ct,cst,stf,pln,w) ...
                matRad_calcDoseForward(ct,cst,stf,pln,w));
        end

        function context = context(runConfig,data,taskRunner,logFn, ...
                forwardDoseForAnalysis)
            data = planWorkflow.stages.ContextValidator.dataSlice( ...
                data,{'ct','cst','dij','stf','pln'}, ...
                {'dosePulling','robustPlans','objectiveInfo','quantityOpt'}, ...
                'optimize');
            context = planWorkflow.stages.ContextValidator.base( ...
                'optimize',runConfig,data,taskRunner,logFn);
            context.forwardDoseForAnalysis = forwardDoseForAnalysis;
            planWorkflow.stages.ContextValidator.requireFields( ...
                context,{'forwardDoseForAnalysis'},'optimize');
        end

        function patch = run(context)
            data = context.data;
            logFn = context.log;
            analysis = planWorkflow.analysis.AnalysisService.completeConfig( ...
                context.runConfig,data);
            context.runConfig.analysis = analysis;

            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                context.runConfig);
            referenceLabel = ...
                planWorkflow.results.PlanLabels.referencePlanDisplayLabel( ...
                reference);
            logFn(sprintf('Running %s optimization.',referenceLabel));
            referenceInitialWeights = ...
                planWorkflow.stages.OptimizeStage.referenceInitialWeights( ...
                data);
            data.pln = ...
                planWorkflow.optimization.PlanOptimizationService.apply4DConfig( ...
                data.pln,reference);

            resultGUIReference = context.runMeasuredPlanTask( ...
                'optimize','reference',referenceLabel, ...
                'fluenceOptimization','','', ...
                @() planWorkflow.optimization.PlanOptimizationService.runFluenceOptimization( ...
                context.runConfig,data.dij,data.cst,data.pln, ...
                referenceInitialWeights));
            [~,dvhReference,qiReference] = ...
                context.runMeasuredPlanTask( ...
                'optimize','reference',referenceLabel,'planAnalysis', ...
                '','',@() planWorkflow.analysis.AnalysisService.runFromOptimizationResult( ...
                context,data.ct,data.cst,data.stf,data.pln, ...
                resultGUIReference,true));

            data.resultGUIReference = resultGUIReference;
            data.resultGUI = resultGUIReference;
            data.dvhReference = dvhReference;
            data.qiReference = qiReference;

            if planWorkflow.stages.OptimizeStage.hasRobustDataPlans(data)
                for robustPlanIx = 1:numel(data.robustPlans)
                    robustData = data.robustPlans{robustPlanIx};
                    logFn(sprintf(['Running robust optimization plan "%s" ' ...
                        'with strategy %s.'], ...
                        char(robustData.planConfig.label), ...
                        robustData.strategy.name));
                    numVariants = numel(robustData.planConfig.variants);
                    robustData.variantResults = ...
                        planWorkflow.results.VariantResults.empty(0);

                    for variantIx = 1:numVariants
                        initialWeights = ...
                            planWorkflow.stages.OptimizeStage.initialWeightsForVariant( ...
                            robustData,variantIx);
                        planForOptimization = ...
                            planWorkflow.optimization.VariantPlanFactory.build( ...
                            robustData,variantIx);
                        variantConfig = robustData.planConfig.variants( ...
                            variantIx);
                        resultGUI = ...
                            context.runMeasuredPlanTask( ...
                            'optimize','robust', ...
                            planWorkflow.results.PlanLabels.robustResultLabel( ...
                            robustData.planConfig,variantIx), ...
                            'fluenceOptimization', ...
                            char(robustData.planConfig.id), ...
                            char(variantConfig.id), ...
                            @() planWorkflow.optimization.PlanOptimizationService.runFluenceOptimization( ...
                            context.runConfig,robustData.dij,robustData.cst, ...
                            planForOptimization,initialWeights));
                        robustData.variantResults(end + 1) = ...
                            planWorkflow.results.VariantResults.create( ...
                            robustData,variantIx,resultGUI);
                    end

                    data.robustPlans{robustPlanIx} = robustData;
                end
            end

            patch = struct();
            patch.runConfig = struct('analysis',analysis);
            patch.data = struct();
            patch.data.pln = data.pln;
            patch.data.resultGUIReference = data.resultGUIReference;
            patch.data.resultGUI = data.resultGUI;
            patch.data.dvhReference = data.dvhReference;
            patch.data.qiReference = data.qiReference;
            if isfield(data,'robustPlans')
                patch.data.robustPlans = data.robustPlans;
            end
        end
    end

    methods (Static, Access = private)
        function tf = hasRobustDataPlans(data)
            tf = isfield(data,'robustPlans') && ~isempty(data.robustPlans);
        end

        function weights = referenceInitialWeights(data)
            weights = [];
            if isfield(data,'dosePulling') && ...
                    isfield(data.dosePulling,'reference') && ...
                    isfield(data.dosePulling.reference,'initialWeights')
                weights = data.dosePulling.reference.initialWeights;
            end
        end

        function weights = initialWeightsForVariant(robustData,variantIx)
            weights = [];
            if isfield(robustData,'initialWeights') && ...
                    numel(robustData.initialWeights) >= variantIx
                weights = robustData.initialWeights{variantIx};
            elseif variantIx > 1
                previousResults = ...
                    planWorkflow.results.VariantResults.optional( ...
                    robustData);
                if numel(previousResults) >= variantIx - 1 && ...
                        isfield(previousResults(variantIx - 1).resultGUI,'w')
                    weights = previousResults(variantIx - 1).resultGUI.w;
                end
            end
        end
    end
end
