classdef PrecomputeStage
    % PrecomputeStage Owns reference and robust dose influence precompute.

    methods (Static)
        function context = workflowContext(varargin)
            if nargin == 3 && ...
                    planWorkflow.stages.WorkflowRuntime.isRuntime(varargin{3})
                runConfig = varargin{1};
                data = varargin{2};
                runtime = varargin{3};
                taskRunner = runtime.taskRunner();
                logFn = runtime.logFn();
                planTemplate = ...
                    planWorkflow.stages.ContextValidator.planTemplate( ...
                    runConfig,data);
                cachePath = char(runConfig.cacheRootPath);
            else
                [runConfig,data,taskRunner,logFn,planTemplate, ...
                    cachePath] = varargin{:};
            end
            cache = planWorkflow.cache.DoseInfluenceCacheService( ...
                runConfig,cachePath,logFn);
            context = planWorkflow.stages.PrecomputeStage.context( ...
                runConfig,data,taskRunner,logFn,planTemplate,cachePath, ...
                cache);
        end

        function context = context(runConfig,data,taskRunner,logFn, ...
                planTemplate,cachePath,cache)
            data = planWorkflow.stages.ContextValidator.dataSlice( ...
                data,{'ct','cst','pln','stf'}, ...
                {'quantityOpt','objectiveInfo','planTemplate', ...
                'planTemplateHash'},'precompute');
            context = planWorkflow.stages.ContextValidator.base( ...
                'precompute',runConfig,data,taskRunner,logFn);
            context.planTemplate = planTemplate;
            context.cachePath = cachePath;
            context.cache = cache;
            planWorkflow.stages.ContextValidator.requireFields( ...
                context,{'planTemplate','cachePath','cache'},'precompute');
            planWorkflow.stages.ContextValidator.requireObjectMethods( ...
                cache,{'getOrCreate','getOrCalculateTransient', ...
                'getOrCreateTimed','getOrCalculateTransientTimed','file', ...
                'metadata','isIdentityCompatible','stfSignature', ...
                'ensureFileFolder'},'precompute.cache');
        end

        function patch = run(context)
            data = context.data;
            runConfig = context.runConfig;
            logFn = context.log;

            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            referenceLabel = ...
                planWorkflow.results.PlanLabels.referencePlanDisplayLabel( ...
                reference);
            data.pln = planWorkflow.plan.Plan.applyDoseResolution( ...
                runConfig,data.pln);
            basePrecomputeData = data;
            basePrecomputeData.pln = ...
                planWorkflow.stages.PrecomputeStage.cleanBasePlan( ...
                basePrecomputeData.pln);
            referenceData = ...
                context.runMeasuredPlanTask( ...
                    'precompute','reference',referenceLabel, ...
                    'prepareReferenceData', ...
                    '','',@() planWorkflow.stages.PrecomputeStage.referenceData( ...
                    context,data,reference,referenceLabel));

            if planWorkflow.precompute.ScenarioFreeDoseInfluence.requiresCompactPrecompute( ...
                    referenceData.planConfig)
                [data,referenceData] = ...
                    planWorkflow.stages.PrecomputeStage.precomputeReferenceCompactDoseInfluence( ...
                    context,data,referenceData);
            else
                logFn(sprintf('Precomputing %s dose influence matrix.', ...
                    referenceLabel));
                referenceTimingOptions = ...
                    planWorkflow.performance.PrecomputeTiming.cacheOptions( ...
                    'reference',referenceLabel,'dij',[]);
                [data.dij,data.dijPrecomputingTiming, ...
                    data.dijPrecomputingSize] = ...
                    context.runMeasuredPlanTask( ...
                    'precompute','reference',referenceLabel, ...
                    'doseInfluence','','', ...
                    @() context.cache.getOrCreateTimed( ...
                    'reference',referenceData.ct,referenceData.cst, ...
                    referenceData.stf,referenceData.pln, ...
                    referenceTimingOptions));
                data.pln = referenceData.pln;
                data.stf = referenceData.stf;
                data.referenceUsesNominalDijForOptimization = false;
            end

            robustPlanConfigs = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            if ~isempty(robustPlanConfigs)
                data.robustPlans = cell(1,numel(robustPlanConfigs));
            end

            for robustPlanIx = 1:numel(robustPlanConfigs)
                robustPlanConfig = robustPlanConfigs(robustPlanIx);
                robustStrategy = ...
                    planWorkflow.robustness.AbstractStrategy.create( ...
                    robustPlanConfig.robustnessMode);
                logFn(sprintf(['Preparing robust plan "%s" with ' ...
                    'objective robustness %s.'],char(robustPlanConfig.label), ...
                    robustStrategy.name));

                robustPlanLabel = char(robustPlanConfig.label);
                robustPlanId = char(robustPlanConfig.id);
                robustData = context.runMeasuredPlanTask( ...
                    'precompute','robust',robustPlanLabel, ...
                    'prepareRobustData',robustPlanId,'', ...
                    @() planWorkflow.precompute.RobustDataFactory.build( ...
                    runConfig,context.planTemplate,robustPlanConfig, ...
                    basePrecomputeData));
                robustData = context.runMeasuredPlanTask( ...
                    'precompute','robust',robustPlanLabel, ...
                    'applyRobustness',robustPlanId,'', ...
                    @() planWorkflow.precompute.RobustDataFactory.applyFirstVariant( ...
                    runConfig,robustData));
                referenceSize = data.dijPrecomputingSize;
                robustData.referenceDijPrecomputingSize = referenceSize;

                requiresCompact = ...
                    planWorkflow.precompute.ScenarioFreeDoseInfluence.requiresCompactPrecompute( ...
                    robustPlanConfig);
                useStreaming = ...
                    planWorkflow.precompute.ScenarioFreeDoseInfluence.useStreamingPrecompute( ...
                    robustPlanConfig);

                if robustPlanConfig.requiresIntervalDij
                    [cacheHit,robustData] = ...
                        context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'intervalDoseInfluenceCacheRead', ...
                        robustPlanId,'', ...
                        @() planWorkflow.precompute.IntervalDoseInfluence.loadCached( ...
                        context,robustData));
                elseif robustPlanConfig.requiresProb2Dij
                    [cacheHit,robustData] = ...
                        context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'prob2DoseInfluenceCacheRead', ...
                        robustPlanId,'', ...
                        @() planWorkflow.precompute.Prob2DoseInfluence.loadCached( ...
                        context,robustData));
                else
                    cacheHit = false;
                end
                if cacheHit
                    if robustPlanConfig.requiresIntervalDij
                        logFn(sprintf(['Using dij_interval for %s ' ...
                            'optimization; robust scenario dij is not kept ' ...
                            'in memory.'],robustData.strategy.name));
                    else
                        logFn(sprintf(['Using dij_prob2 for %s ' ...
                            'optimization; robust scenario dij is not kept ' ...
                            'in memory.'],robustData.strategy.name));
                    end
                    robustData = ...
                        planWorkflow.stages.PrecomputeStage.selectOptimizationDoseInfluence( ...
                        robustData);
                    data.robustPlans{robustPlanIx} = robustData;
                    continue;
                end

                if robustPlanConfig.requiresNominalDij && ~requiresCompact
                    robustData = ...
                        planWorkflow.stages.PrecomputeStage.ensureNominalPlan( ...
                        robustData);
                    [robustData.dijNominal, ...
                        robustData.dijNominalPrecomputingTiming, ...
                        robustData.dijNominalPrecomputingSize] = ...
                        context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'nominalDoseInfluence',robustPlanId,'', ...
                        @() planWorkflow.stages.PrecomputeStage.getNominalDoseInfluence( ...
                        context,robustData,data.dijPrecomputingTiming, ...
                        referenceSize));
                    robustData.dijPrecomputingTiming = ...
                        robustData.dijNominalPrecomputingTiming;
                    robustData.dijPrecomputingSize = ...
                        robustData.dijNominalPrecomputingSize;
                end

                if robustPlanConfig.requiresScenarioDij || ...
                        (requiresCompact && ~useStreaming)
                    logFn(sprintf(['Precomputing robust dose influence ' ...
                        'matrix for plan "%s" (%s).'], ...
                        char(robustPlanConfig.label),robustStrategy.name));
                    [dijRobust,dijRobustPrecomputingTiming, ...
                        dijRobustPrecomputingSize] = ...
                        context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'robustDoseInfluence',robustPlanId,'', ...
                        @() planWorkflow.stages.PrecomputeStage.getRobustDoseInfluence( ...
                        context,robustData,data.dijPrecomputingTiming, ...
                        referenceSize));
                    robustData = ...
                        planWorkflow.precompute.RobustDoseInfluence.attach( ...
                        robustData,dijRobust);
                    robustData.dijRobustPrecomputingTiming = ...
                        dijRobustPrecomputingTiming;
                    robustData.dijRobustPrecomputingSize = ...
                        dijRobustPrecomputingSize;
                    robustData.dijPrecomputingTiming = ...
                        dijRobustPrecomputingTiming;
                    robustData.dijPrecomputingSize = ...
                        dijRobustPrecomputingSize;
                end

                if robustPlanConfig.requiresIntervalDij && ~cacheHit
                    robustData = context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'intervalDoseInfluence',robustPlanId,'', ...
                        @() planWorkflow.precompute.IntervalDoseInfluence.precompute( ...
                        context,robustData));
                    logFn(sprintf(['Using dij_interval for %s ' ...
                        'optimization; robust scenario dij is not kept ' ...
                        'in memory.'],robustData.strategy.name));
                end
                if robustPlanConfig.requiresProb2Dij && ~cacheHit
                    robustData = context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'prob2DoseInfluence',robustPlanId,'', ...
                        @() planWorkflow.precompute.Prob2DoseInfluence.precompute( ...
                        context,robustData));
                    logFn(sprintf(['Using dij_prob2 for %s ' ...
                        'optimization; robust scenario dij is not kept ' ...
                        'in memory.'],robustData.strategy.name));
                end

                robustData = ...
                    planWorkflow.stages.PrecomputeStage.selectOptimizationDoseInfluence( ...
                    robustData);

                data.robustPlans{robustPlanIx} = robustData;
            end

            patch = struct();
            patch.data = struct();
            patch.data.pln = data.pln;
            patch.data.stf = data.stf;
            patch.data.dij = data.dij;
            patch.data.dijPrecomputingTiming = data.dijPrecomputingTiming;
            patch.data.dijPrecomputingSize = data.dijPrecomputingSize;
            patch.data.referenceUsesNominalDijForOptimization = ...
                data.referenceUsesNominalDijForOptimization;
            if isfield(data,'robustPlans')
                patch.data.robustPlans = data.robustPlans;
            end
        end

        function robustData = selectOptimizationDoseInfluence(robustData)
            planConfig = robustData.planConfig;
            if planConfig.requiresIntervalDij
                if planConfig.hasNominalObjectives
                    planWorkflow.stages.PrecomputeStage.requireNominalOptimizationDoseInfluence( ...
                        robustData,'MissingIntervalNominalDij', ...
                        'MissingIntervalNominalPlan', ...
                        ['INTERVAL optimization with nominal ' ...
                        'objectives']);
                    robustData.dij = robustData.dijNominal;
                    robustData.plnForOptimization = robustData.plnNominal;
                    robustData.usesNominalDijForOptimization = true;
                else
                    robustData = ...
                        planWorkflow.precompute.IntervalDoseInfluence.useForOptimization( ...
                        robustData);
                end
                return;
            end

            if planConfig.requiresProb2Dij
                if planConfig.hasNominalObjectives
                    planWorkflow.stages.PrecomputeStage.requireNominalOptimizationDoseInfluence( ...
                        robustData,'MissingProb2NominalDij', ...
                        'MissingProb2NominalPlan', ...
                        'PROB2 optimization with nominal objectives');
                    robustData.dij = robustData.dijNominal;
                    robustData.plnForOptimization = robustData.plnNominal;
                    robustData.usesNominalDijForOptimization = true;
                else
                    robustData = ...
                        planWorkflow.precompute.Prob2DoseInfluence.useForOptimization( ...
                        robustData);
                end
                return;
            end

            if planConfig.requiresScenarioDij
                robustData.dij = robustData.dijRobust;
                robustData.usesNominalDijForOptimization = false;
                return;
            end

            planWorkflow.stages.PrecomputeStage.requireNominalOptimizationDoseInfluence( ...
                robustData,'MissingNominalDij','MissingNominalPlan', ...
                'Nominal optimization');
            robustData.dij = robustData.dijNominal;
            robustData.plnForOptimization = robustData.plnNominal;
            robustData.usesNominalDijForOptimization = true;
        end

        function referenceData = selectReferenceOptimizationDoseInfluence( ...
                referenceData)
            referenceData = ...
                planWorkflow.stages.PrecomputeStage.selectOptimizationDoseInfluence( ...
                referenceData);
            planConfig = referenceData.planConfig;
            usesNominal = isfield(referenceData, ...
                'usesNominalDijForOptimization') && ...
                logical(referenceData.usesNominalDijForOptimization);
            if planConfig.requiresIntervalDij
                referenceData.plnForOptimization = ...
                    planWorkflow.precompute.IntervalDoseInfluence.optimizationPlan( ...
                    referenceData);
            elseif planConfig.requiresProb2Dij
                referenceData.plnForOptimization = ...
                    planWorkflow.precompute.Prob2DoseInfluence.optimizationPlan( ...
                    referenceData);
            elseif usesNominal
                return;
            end
        end
    end

    methods (Static, Access = private)
        function pln = cleanBasePlan(pln)
            if ~isstruct(pln) || ~isfield(pln,'propOpt') || ...
                    ~isstruct(pln.propOpt)
                return;
            end
            fields = {'useMaxApprox','p1','p2','theta1','theta2', ...
                'scen4D','dij_interval','dij_prob2'};
            for fieldIx = 1:numel(fields)
                if isfield(pln.propOpt,fields{fieldIx})
                    pln.propOpt = rmfield(pln.propOpt,fields{fieldIx});
                end
            end
        end

        function referenceData = referenceData( ...
                context,sourceData,reference,referenceLabel)
            referenceData = sourceData;
            referenceData.planConfig = ...
                planWorkflow.stages.PrecomputeStage.referencePlanConfig( ...
                context,reference,referenceLabel);
            referenceData.strategy = ...
                planWorkflow.robustness.AbstractStrategy.create( ...
                referenceData.planConfig.robustnessMode);
            referenceData.pln.multScen = ...
                planWorkflow.precompute.PrepareService.referenceScenarioModel( ...
                context.runConfig,sourceData);
            referenceData.pln = ...
                planWorkflow.optimization.PlanOptimizationService.apply4DConfig( ...
                referenceData.pln,referenceData.planConfig);
            if (isstruct(referenceData.pln.multScen) && ...
                    isfield(referenceData.pln.multScen,'ctScenProb')) || ...
                    (isobject(referenceData.pln.multScen) && ...
                    isprop(referenceData.pln.multScen,'ctScenProb'))
                referenceData.ctScenProb = ...
                    referenceData.pln.multScen.ctScenProb(:,2)';
            else
                referenceData.ctScenProb = [];
            end
        end

        function planConfig = referencePlanConfig( ...
                context,reference,referenceLabel)
            contract = ...
                planWorkflow.templates.ObjectiveRobustnessContract.forTemplateObjectiveSet( ...
                context.planTemplate,'reference');
            planConfig = planWorkflow.config.RobustPlanConfig.defaultPlan();
            planConfig.id = 'reference';
            planConfig.label = char(referenceLabel);
            planConfig.objectiveSetName = 'reference';
            planConfig.robustnessMode = reference.robustnessMode;
            planConfig.scenario = reference.scenario;
            planConfig.optimization4D = reference.optimization4D;
            planConfig.robustnessOptions = reference.robustnessOptions;
            planConfig.dosePrecompute = reference.dosePrecompute;
            planConfig.variants = reference.variants;
            planConfig = ...
                planWorkflow.config.RobustPlanConfig.normalizePlan( ...
                planConfig,1,contract);
        end

        function [data,referenceData] = ...
                precomputeReferenceCompactDoseInfluence( ...
                context,data,referenceData)
            planConfig = referenceData.planConfig;
            referenceLabel = char(planConfig.label);
            if planConfig.requiresIntervalDij
                [cacheHit,referenceData] = ...
                    context.runMeasuredPlanTask( ...
                    'precompute','reference',referenceLabel, ...
                    'intervalDoseInfluenceCacheRead','reference','', ...
                    @() planWorkflow.precompute.IntervalDoseInfluence.loadCached( ...
                    context,referenceData));
            elseif planConfig.requiresProb2Dij
                [cacheHit,referenceData] = ...
                    context.runMeasuredPlanTask( ...
                    'precompute','reference',referenceLabel, ...
                    'prob2DoseInfluenceCacheRead','reference','', ...
                    @() planWorkflow.precompute.Prob2DoseInfluence.loadCached( ...
                    context,referenceData));
            else
                cacheHit = false;
            end

            if cacheHit
                if planConfig.requiresIntervalDij
                    context.log(sprintf(['Using reference dij_interval for ' ...
                        '%s optimization; robust scenario dij is not kept ' ...
                        'in memory.'],referenceData.strategy.name));
                else
                    context.log(['Using reference dij_prob2 for PROB2 ' ...
                        'optimization; robust scenario dij is not kept in memory.']);
                end
            else
                useStreaming = ...
                    planWorkflow.precompute.ScenarioFreeDoseInfluence.useStreamingPrecompute( ...
                    planConfig);
                if ~useStreaming
                    context.log(sprintf(['Precomputing reference robust ' ...
                        'dose influence matrix for %s.'], ...
                        referenceData.strategy.name));
                    [dijRobust,dijRobustPrecomputingTiming, ...
                        dijRobustPrecomputingSize] = ...
                        context.runMeasuredPlanTask( ...
                        'precompute','reference',referenceLabel, ...
                        'robustDoseInfluence','reference','', ...
                        @() planWorkflow.stages.PrecomputeStage.getRobustDoseInfluence( ...
                        context,referenceData,[],[]));
                    referenceData = ...
                        planWorkflow.precompute.RobustDoseInfluence.attach( ...
                        referenceData,dijRobust);
                    referenceData.dijRobustPrecomputingTiming = ...
                        dijRobustPrecomputingTiming;
                    referenceData.dijRobustPrecomputingSize = ...
                        dijRobustPrecomputingSize;
                    referenceData.dijPrecomputingTiming = ...
                        dijRobustPrecomputingTiming;
                    referenceData.dijPrecomputingSize = ...
                        dijRobustPrecomputingSize;
                end

                if planConfig.requiresIntervalDij
                    referenceData = context.runMeasuredPlanTask( ...
                        'precompute','reference',referenceLabel, ...
                        'intervalDoseInfluence','reference','', ...
                        @() planWorkflow.precompute.IntervalDoseInfluence.precompute( ...
                        context,referenceData));
                    context.log(sprintf(['Using reference dij_interval for ' ...
                        '%s optimization; robust scenario dij is not kept ' ...
                        'in memory.'],referenceData.strategy.name));
                elseif planConfig.requiresProb2Dij
                    referenceData = context.runMeasuredPlanTask( ...
                        'precompute','reference',referenceLabel, ...
                        'prob2DoseInfluence','reference','', ...
                        @() planWorkflow.precompute.Prob2DoseInfluence.precompute( ...
                        context,referenceData));
                    context.log(['Using reference dij_prob2 for PROB2 ' ...
                        'optimization; robust scenario dij is not kept in memory.']);
                end
            end

            referenceData = ...
                planWorkflow.stages.PrecomputeStage.selectReferenceOptimizationDoseInfluence( ...
                referenceData);
            data = ...
                planWorkflow.stages.PrecomputeStage.assignReferenceOptimizationDoseInfluence( ...
                data,referenceData);
        end

        function data = assignReferenceOptimizationDoseInfluence( ...
                data,referenceData)
            data.dij = referenceData.dij;
            data.dijPrecomputingTiming = referenceData.dijPrecomputingTiming;
            data.dijPrecomputingSize = referenceData.dijPrecomputingSize;
            if isfield(referenceData,'plnForOptimization') && ...
                    ~isempty(referenceData.plnForOptimization)
                data.pln = referenceData.plnForOptimization;
            else
                data.pln = referenceData.pln;
            end
            if isfield(referenceData,'usesNominalDijForOptimization') && ...
                    logical(referenceData.usesNominalDijForOptimization) && ...
                    isfield(referenceData,'stfNominal') && ...
                    ~isempty(referenceData.stfNominal)
                data.stf = referenceData.stfNominal;
            else
                data.stf = referenceData.stf;
            end
            data.referenceUsesNominalDijForOptimization = ...
                isfield(referenceData,'usesNominalDijForOptimization') && ...
                logical(referenceData.usesNominalDijForOptimization);
        end

        function [dij,dijPrecomputingTiming,dijPrecomputingSize] = ...
                getRobustDoseInfluence(context,robustData,referenceTiming, ...
                referenceSize)
            if nargin < 4
                referenceSize = [];
            end
            tag = ['robust_' char(robustData.planConfig.id)];
            componentRole = 'robust';
            if robustData.planConfig.requiresIntervalDij || ...
                    robustData.planConfig.requiresProb2Dij
                componentRole = 'input';
            end
            timingOptions = ...
                planWorkflow.performance.PrecomputeTiming.cacheOptions( ...
                componentRole,char(robustData.planConfig.label), ...
                'dij_robust',referenceTiming,referenceSize);
            if robustData.planConfig.requiresIntervalDij || ...
                    robustData.planConfig.requiresProb2Dij
                [dij,dijPrecomputingTiming,dijPrecomputingSize] = ...
                    context.cache.getOrCalculateTransientTimed( ...
                    tag,robustData,robustData.ct,robustData.cst, ...
                    robustData.stf,robustData.pln,timingOptions);
            else
                [dij,dijPrecomputingTiming,dijPrecomputingSize] = ...
                    context.cache.getOrCreateTimed( ...
                    tag,robustData.ct,robustData.cst,robustData.stf, ...
                    robustData.pln,timingOptions);
            end
        end

        function [dij,dijPrecomputingTiming,dijPrecomputingSize] = ...
                getNominalDoseInfluence(context,robustData,referenceTiming, ...
                referenceSize)
            if nargin < 4
                referenceSize = [];
            end
            robustData = ...
                planWorkflow.stages.PrecomputeStage.ensureNominalPlan( ...
                robustData);
            tag = ['robustNominal_' char(robustData.planConfig.id)];
            timingOptions = ...
                planWorkflow.performance.PrecomputeTiming.cacheOptions( ...
                'robust',char(robustData.planConfig.label), ...
                'dij_nominal',referenceTiming,referenceSize);
            [dij,dijPrecomputingTiming,dijPrecomputingSize] = ...
                context.cache.getOrCreateTimed( ...
                tag,robustData.ct,robustData.cst,robustData.stfNominal, ...
                robustData.plnNominal,timingOptions);
        end

        function robustData = ensureNominalPlan(robustData)
            if isfield(robustData,'plnNominal') && ...
                    isfield(robustData,'stfNominal') && ...
                    ~isempty(robustData.plnNominal) && ...
                    ~isempty(robustData.stfNominal)
                return;
            end
            nominalScenario = ...
                planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                planWorkflow.config.RobustPlanConfig.defaultScenario( ...
                'nomScen'));
            if isfield(robustData,'ct') && isfield(robustData.ct,'refScen') && ...
                    ~isempty(robustData.ct.refScen)
                nominalScenario.ctReferenceScenId = robustData.ct.refScen;
            elseif isfield(robustData,'planConfig') && ...
                    isfield(robustData.planConfig,'scenario') && ...
                    isfield(robustData.planConfig.scenario,'ctReferenceScenId') && ...
                    ~isempty(robustData.planConfig.scenario.ctReferenceScenId)
                nominalScenario.ctReferenceScenId = ...
                    robustData.planConfig.scenario.ctReferenceScenId;
            end
            nominalScenario = ...
                planWorkflow.config.ScenarioSpec.withBeamCount( ...
                nominalScenario,robustData.pln);
            plnNominal = robustData.pln;
            plnNominal.multScen = planWorkflow.scenario.createModel( ...
                robustData.ct,nominalScenario.scen_mode, ...
                nominalScenario,'optimization');
            if isfield(plnNominal,'propOpt') && ...
                    isstruct(plnNominal.propOpt) && ...
                    isfield(plnNominal.propOpt,'scen4D')
                plnNominal.propOpt = rmfield(plnNominal.propOpt,'scen4D');
            end
            robustData.plnNominal = plnNominal;
            robustData.stfNominal = matRad_generateStf( ...
                robustData.ct,robustData.cst,robustData.plnNominal);
        end

        function requireNominalOptimizationDoseInfluence( ...
                robustData,dijErrorId,plnErrorId,description)
            if ~isfield(robustData,'dijNominal') || ...
                    isempty(robustData.dijNominal)
                error(['planWorkflow:stages:PrecomputeStage:' ...
                    char(dijErrorId)], ...
                    '%s requires plan-specific dijNominal.', ...
                    char(description));
            end
            if ~isfield(robustData,'plnNominal') || ...
                    isempty(robustData.plnNominal)
                error(['planWorkflow:stages:PrecomputeStage:' ...
                    char(plnErrorId)], ...
                    '%s requires plan-specific plnNominal.', ...
                    char(description));
            end
        end
    end
end
