classdef PrecomputeStage
    % PrecomputeStage Owns reference and robust dose influence precompute.

    methods (Static)
        function context = workflowContext(varargin)
            if nargin == 3 && ...
                    planWorkflow.stages.WorkflowRuntime.isRuntime(varargin{3})
                runConfig = varargin{1};
                data = varargin{2};
                runtime = varargin{3};
                taskRunner = runtime.taskRunner();
                logFn = runtime.logFn();
                planTemplate = ...
                    planWorkflow.stages.ContextValidator.planTemplate( ...
                    runConfig,data);
                cachePath = char(runConfig.cacheRootPath);
            else
                [runConfig,data,taskRunner,logFn,planTemplate, ...
                    cachePath] = varargin{:};
            end
            cache = planWorkflow.cache.DoseInfluenceCacheService( ...
                runConfig,cachePath,logFn);
            context = planWorkflow.stages.PrecomputeStage.context( ...
                runConfig,data,taskRunner,logFn,planTemplate,cachePath, ...
                cache);
        end

        function context = context(runConfig,data,taskRunner,logFn, ...
                planTemplate,cachePath,cache)
            data = planWorkflow.stages.ContextValidator.dataSlice( ...
                data,{'ct','cst','pln','stf'}, ...
                {'quantityOpt','objectiveInfo','planTemplate', ...
                'planTemplateHash'},'precompute');
            context = planWorkflow.stages.ContextValidator.base( ...
                'precompute',runConfig,data,taskRunner,logFn);
            context.planTemplate = planTemplate;
            context.cachePath = cachePath;
            context.cache = cache;
            planWorkflow.stages.ContextValidator.requireFields( ...
                context,{'planTemplate','cachePath','cache'},'precompute');
            planWorkflow.stages.ContextValidator.requireObjectMethods( ...
                cache,{'getOrCreate','getOrCalculateTransient','file', ...
                'metadata','isIdentityCompatible','stfSignature', ...
                'ensureFileFolder'},'precompute.cache');
        end

        function patch = run(context)
            data = context.data;
            runConfig = context.runConfig;
            logFn = context.log;

            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            referenceLabel = ...
                planWorkflow.results.PlanLabels.referencePlanDisplayLabel( ...
                reference);
            logFn(sprintf('Precomputing %s dose influence matrix.', ...
                referenceLabel));
            data.pln = planWorkflow.plan.Plan.applyDoseResolution( ...
                runConfig,data.pln);
            data.pln.multScen = ...
                planWorkflow.precompute.PrepareService.referenceScenarioModel( ...
                runConfig,data);
            data.pln = ...
                planWorkflow.optimization.PlanOptimizationService.apply4DConfig( ...
                data.pln,reference);
            data.dij = context.runMeasuredPlanTask( ...
                'precompute','reference',referenceLabel,'doseInfluence', ...
                '','',@() context.cache.getOrCreate( ...
                'reference',data.ct,data.cst,data.stf,data.pln));

            robustPlanConfigs = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            if ~isempty(robustPlanConfigs)
                data.robustPlans = cell(1,numel(robustPlanConfigs));
            end

            for robustPlanIx = 1:numel(robustPlanConfigs)
                robustPlanConfig = robustPlanConfigs(robustPlanIx);
                robustStrategy = ...
                    planWorkflow.robustness.AbstractStrategy.create( ...
                    robustPlanConfig.robustnessMode);
                logFn(sprintf(['Preparing robust plan "%s" with ' ...
                    'objective robustness %s.'],char(robustPlanConfig.label), ...
                    robustStrategy.name));

                robustPlanLabel = char(robustPlanConfig.label);
                robustPlanId = char(robustPlanConfig.id);
                robustData = context.runMeasuredPlanTask( ...
                    'precompute','robust',robustPlanLabel, ...
                    'prepareRobustData',robustPlanId,'', ...
                    @() planWorkflow.precompute.RobustDataFactory.build( ...
                    runConfig,context.planTemplate,robustPlanConfig,data));
                robustData = context.runMeasuredPlanTask( ...
                    'precompute','robust',robustPlanLabel, ...
                    'applyRobustness',robustPlanId,'', ...
                    @() planWorkflow.precompute.RobustDataFactory.applyFirstVariant( ...
                    runConfig,robustData));

                if robustPlanConfig.requiresNominalDij && ...
                        ~robustPlanConfig.requiresIntervalDij && ...
                        ~robustPlanConfig.requiresProb2Dij
                    robustData = ...
                        planWorkflow.stages.PrecomputeStage.ensureNominalPlan( ...
                        robustData);
                    robustData.dijNominal = context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'nominalDoseInfluence',robustPlanId,'', ...
                        @() planWorkflow.stages.PrecomputeStage.getNominalDoseInfluence( ...
                        context,robustData));
                end

                if robustPlanConfig.requiresIntervalDij
                    [cacheHit,robustData] = ...
                        context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'intervalDoseInfluenceCacheRead', ...
                        robustPlanId,'', ...
                        @() planWorkflow.precompute.IntervalDoseInfluence.loadCached( ...
                        context,robustData));
                elseif robustPlanConfig.requiresProb2Dij
                    [cacheHit,robustData] = ...
                        context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'prob2DoseInfluenceCacheRead', ...
                        robustPlanId,'', ...
                        @() planWorkflow.precompute.Prob2DoseInfluence.loadCached( ...
                        context,robustData));
                else
                    cacheHit = false;
                end
                if cacheHit
                    if robustPlanConfig.requiresIntervalDij
                        logFn(sprintf(['Using dij_interval for %s ' ...
                            'optimization; robust scenario dij is not kept ' ...
                            'in memory.'],robustData.strategy.name));
                    else
                        logFn(sprintf(['Using dij_prob2 for %s ' ...
                            'optimization; robust scenario dij is not kept ' ...
                            'in memory.'],robustData.strategy.name));
                    end
                    robustData = ...
                        planWorkflow.stages.PrecomputeStage.selectOptimizationDoseInfluence( ...
                        robustData);
                    data.robustPlans{robustPlanIx} = robustData;
                    continue;
                end

                if robustPlanConfig.requiresScenarioDij || ...
                        ((robustPlanConfig.requiresIntervalDij || ...
                        robustPlanConfig.requiresProb2Dij) && ~cacheHit)
                    logFn(sprintf(['Precomputing robust dose influence ' ...
                        'matrix for plan "%s" (%s).'], ...
                        char(robustPlanConfig.label),robustStrategy.name));
                    dijRobust = context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'robustDoseInfluence',robustPlanId,'', ...
                        @() planWorkflow.stages.PrecomputeStage.getRobustDoseInfluence( ...
                        context,robustData));
                    robustData = ...
                        planWorkflow.precompute.RobustDoseInfluence.attach( ...
                        robustData,dijRobust);
                end

                if robustPlanConfig.requiresIntervalDij && ~cacheHit
                    robustData = context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'intervalDoseInfluence',robustPlanId,'', ...
                        @() planWorkflow.precompute.IntervalDoseInfluence.precompute( ...
                        context,robustData));
                    logFn(sprintf(['Using dij_interval for %s ' ...
                        'optimization; robust scenario dij is not kept ' ...
                        'in memory.'],robustData.strategy.name));
                end
                if robustPlanConfig.requiresProb2Dij && ~cacheHit
                    robustData = context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'prob2DoseInfluence',robustPlanId,'', ...
                        @() planWorkflow.precompute.Prob2DoseInfluence.precompute( ...
                        context,robustData));
                    logFn(sprintf(['Using dij_prob2 for %s ' ...
                        'optimization; robust scenario dij is not kept ' ...
                        'in memory.'],robustData.strategy.name));
                end

                robustData = ...
                    planWorkflow.stages.PrecomputeStage.selectOptimizationDoseInfluence( ...
                    robustData);

                data.robustPlans{robustPlanIx} = robustData;
            end

            patch = struct();
            patch.data = struct();
            patch.data.pln = data.pln;
            patch.data.dij = data.dij;
            if isfield(data,'robustPlans')
                patch.data.robustPlans = data.robustPlans;
            end
        end

        function robustData = selectOptimizationDoseInfluence(robustData)
            planConfig = robustData.planConfig;
            if planConfig.requiresIntervalDij
                if planConfig.hasNominalObjectives
                    planWorkflow.stages.PrecomputeStage.requireNominalOptimizationDoseInfluence( ...
                        robustData,'MissingIntervalNominalDij', ...
                        'MissingIntervalNominalPlan', ...
                        ['INTERVAL optimization with nominal ' ...
                        'objectives']);
                    robustData.dij = robustData.dijNominal;
                    robustData.plnForOptimization = robustData.plnNominal;
                    robustData.usesNominalDijForOptimization = true;
                else
                    robustData = ...
                        planWorkflow.precompute.IntervalDoseInfluence.useForOptimization( ...
                        robustData);
                end
                return;
            end

            if planConfig.requiresProb2Dij
                if planConfig.hasNominalObjectives
                    planWorkflow.stages.PrecomputeStage.requireNominalOptimizationDoseInfluence( ...
                        robustData,'MissingProb2NominalDij', ...
                        'MissingProb2NominalPlan', ...
                        'PROB2 optimization with nominal objectives');
                    robustData.dij = robustData.dijNominal;
                    robustData.plnForOptimization = robustData.plnNominal;
                    robustData.usesNominalDijForOptimization = true;
                else
                    robustData = ...
                        planWorkflow.precompute.Prob2DoseInfluence.useForOptimization( ...
                        robustData);
                end
                return;
            end

            if planConfig.requiresScenarioDij
                robustData.dij = robustData.dijRobust;
                robustData.usesNominalDijForOptimization = false;
                return;
            end

            planWorkflow.stages.PrecomputeStage.requireNominalOptimizationDoseInfluence( ...
                robustData,'MissingNominalDij','MissingNominalPlan', ...
                'Nominal optimization');
            robustData.dij = robustData.dijNominal;
            robustData.plnForOptimization = robustData.plnNominal;
            robustData.usesNominalDijForOptimization = true;
        end
    end

    methods (Static, Access = private)
        function dij = getRobustDoseInfluence(context,robustData)
            tag = ['robust_' char(robustData.planConfig.id)];
            if robustData.planConfig.requiresIntervalDij || ...
                    robustData.planConfig.requiresProb2Dij
                dij = context.cache.getOrCalculateTransient( ...
                    tag,robustData,robustData.ct,robustData.cst, ...
                    robustData.stf,robustData.pln);
            else
                dij = context.cache.getOrCreate( ...
                    tag,robustData.ct,robustData.cst,robustData.stf, ...
                    robustData.pln);
            end
        end

        function dij = getNominalDoseInfluence(context,robustData)
            robustData = ...
                planWorkflow.stages.PrecomputeStage.ensureNominalPlan( ...
                robustData);
            tag = ['robustNominal_' char(robustData.planConfig.id)];
            dij = context.cache.getOrCreate( ...
                tag,robustData.ct,robustData.cst,robustData.stfNominal, ...
                robustData.plnNominal);
        end

        function robustData = ensureNominalPlan(robustData)
            if isfield(robustData,'plnNominal') && ...
                    isfield(robustData,'stfNominal') && ...
                    ~isempty(robustData.plnNominal) && ...
                    ~isempty(robustData.stfNominal)
                return;
            end
            nominalScenario = ...
                planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                planWorkflow.config.RobustPlanConfig.defaultScenario( ...
                'nomScen'));
            nominalScenario = ...
                planWorkflow.config.ScenarioSpec.withBeamCount( ...
                nominalScenario,robustData.pln);
            plnNominal = robustData.pln;
            plnNominal.multScen = planWorkflow.scenario.createModel( ...
                robustData.ct,nominalScenario.scen_mode, ...
                nominalScenario,'optimization');
            if isfield(plnNominal,'propOpt') && ...
                    isstruct(plnNominal.propOpt) && ...
                    isfield(plnNominal.propOpt,'scen4D')
                plnNominal.propOpt = rmfield(plnNominal.propOpt,'scen4D');
            end
            robustData.plnNominal = plnNominal;
            robustData.stfNominal = matRad_generateStf( ...
                robustData.ct,robustData.cst,robustData.plnNominal);
        end

        function requireNominalOptimizationDoseInfluence( ...
                robustData,dijErrorId,plnErrorId,description)
            if ~isfield(robustData,'dijNominal') || ...
                    isempty(robustData.dijNominal)
                error(['planWorkflow:stages:PrecomputeStage:' ...
                    char(dijErrorId)], ...
                    '%s requires plan-specific dijNominal.', ...
                    char(description));
            end
            if ~isfield(robustData,'plnNominal') || ...
                    isempty(robustData.plnNominal)
                error(['planWorkflow:stages:PrecomputeStage:' ...
                    char(plnErrorId)], ...
                    '%s requires plan-specific plnNominal.', ...
                    char(description));
            end
        end
    end
end
