classdef PrecomputeStage
    % PrecomputeStage Owns reference and robust dose influence precompute.

    methods (Static)
        function context = workflowContext(varargin)
            if nargin == 3 && ...
                    planWorkflow.stages.WorkflowRuntime.isRuntime(varargin{3})
                runConfig = varargin{1};
                data = varargin{2};
                runtime = varargin{3};
                taskRunner = runtime.taskRunner();
                logFn = runtime.logFn();
                planTemplate = ...
                    planWorkflow.stages.ContextValidator.planTemplate( ...
                    runConfig,data);
                cachePath = char(runConfig.cacheRootPath);
            else
                [runConfig,data,taskRunner,logFn,planTemplate, ...
                    cachePath] = varargin{:};
            end
            cache = planWorkflow.cache.DoseInfluenceCacheService( ...
                runConfig,cachePath,logFn);
            context = planWorkflow.stages.PrecomputeStage.context( ...
                runConfig,data,taskRunner,logFn,planTemplate,cachePath, ...
                cache);
        end

        function context = context(runConfig,data,taskRunner,logFn, ...
                planTemplate,cachePath,cache)
            data = planWorkflow.stages.ContextValidator.dataSlice( ...
                data,{'ct','cst','pln','stf'}, ...
                {'quantityOpt','objectiveInfo','planTemplate', ...
                'planTemplateHash'},'precompute');
            context = planWorkflow.stages.ContextValidator.base( ...
                'precompute',runConfig,data,taskRunner,logFn);
            context.planTemplate = planTemplate;
            context.cachePath = cachePath;
            context.cache = cache;
            planWorkflow.stages.ContextValidator.requireFields( ...
                context,{'planTemplate','cachePath','cache'},'precompute');
            planWorkflow.stages.ContextValidator.requireObjectMethods( ...
                cache,{'getOrCreate','getOrCalculateTransient', ...
                'getOrCreateTimed','getOrCreateLazyTimed', ...
                'getOrCalculateTransientTimed','file','metadata', ...
                'isIdentityCompatible','stfSignature','ensureFileFolder'}, ...
                'precompute.cache');
        end

        function patch = run(context)
            data = context.data;
            runConfig = context.runConfig;
            logFn = context.log;

            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            referenceLabel = ...
                planWorkflow.results.PlanLabels.referencePlanDisplayLabel( ...
                reference);
            data.pln = planWorkflow.plan.Plan.applyDoseResolution( ...
                runConfig,data.pln);
            basePrecomputeData = data;
            basePrecomputeData.pln = ...
                planWorkflow.stages.PrecomputeStage.cleanBasePlan( ...
                basePrecomputeData.pln);
            referenceData = ...
                context.runMeasuredPlanTask( ...
                    'precompute','reference',referenceLabel, ...
                    'prepareReferenceData', ...
                    '','',@() planWorkflow.stages.PrecomputeStage.referenceData( ...
                    context,data,reference,referenceLabel));

            if planWorkflow.precompute.ScenarioFreeDoseInfluence.requiresCompactPrecompute( ...
                    referenceData.planConfig)
                [data,~] = ...
                    planWorkflow.stages.PrecomputeStage.precomputeReferenceCompactDoseInfluence( ...
                    context,data,referenceData);
            else
                logFn(sprintf('Precomputing %s dose influence matrix.', ...
                    referenceLabel));
                referenceTimingOptions = ...
                    planWorkflow.performance.PrecomputeTiming.cacheOptions( ...
                    'reference',referenceLabel,'dij',[]);
                [dijReference,data.dijPrecomputingTiming, ...
                    data.dijPrecomputingSize,referenceCacheRef] = ...
                    context.runMeasuredPlanTask( ...
                    'precompute','reference',referenceLabel, ...
                    'doseInfluence','','', ...
                    @() context.cache.getOrCreateTimed( ...
                    'reference',referenceData.ct,referenceData.cst, ...
                    referenceData.stf,referenceData.pln, ...
                    referenceTimingOptions));
                data.dijCacheRefs.dij = referenceCacheRef;
                data.ct = referenceData.ct;
                data.cst = referenceData.cst;
                data.pln = referenceData.pln;
                data.stf = referenceData.stf;
                data.optimizationInput = ...
                    planWorkflow.precompute.OptimizationInput.build( ...
                    data.ct,data.cst,data.pln,data.stf,dijReference, ...
                    planWorkflow.stages.PrecomputeStage.optimizationDijKind( ...
                    referenceData.planConfig), ...
                    'reference',referenceData.ctReferenceView);
            end

            robustPlanConfigs = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            if ~isempty(robustPlanConfigs)
                data.robustPlans = cell(1,numel(robustPlanConfigs));
            end

            for robustPlanIx = 1:numel(robustPlanConfigs)
                robustPlanConfig = robustPlanConfigs(robustPlanIx);
                robustStrategy = ...
                    planWorkflow.robustness.AbstractStrategy.create( ...
                    robustPlanConfig.robustnessMode);
                logFn(sprintf(['Preparing robust plan "%s" with ' ...
                    'objective robustness %s.'],char(robustPlanConfig.label), ...
                    robustStrategy.name));

                robustPlanLabel = char(robustPlanConfig.label);
                robustPlanId = char(robustPlanConfig.id);
                robustData = context.runMeasuredPlanTask( ...
                    'precompute','robust',robustPlanLabel, ...
                    'prepareRobustData',robustPlanId,'', ...
                    @() planWorkflow.precompute.RobustDataFactory.build( ...
                    runConfig,context.planTemplate,robustPlanConfig, ...
                    basePrecomputeData));
                robustData = context.runMeasuredPlanTask( ...
                    'precompute','robust',robustPlanLabel, ...
                    'applyRobustness',robustPlanId,'', ...
                    @() planWorkflow.precompute.RobustDataFactory.applyFirstVariant( ...
                    runConfig,robustData));
                referenceSize = data.dijPrecomputingSize;
                robustData.referenceDijPrecomputingSize = referenceSize;

                requiresCompact = ...
                    planWorkflow.precompute.ScenarioFreeDoseInfluence.requiresCompactPrecompute( ...
                    robustPlanConfig);
                useScenarioBatch = ...
                    planWorkflow.precompute.ScenarioFreeDoseInfluence.useScenarioBatchPrecompute( ...
                    robustPlanConfig);

                if robustPlanConfig.requiresIntervalDij
                    [cacheHit,robustData] = ...
                        context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'intervalDoseInfluenceCacheRead', ...
                        robustPlanId,'', ...
                        @() planWorkflow.precompute.IntervalDoseInfluence.loadCached( ...
                        context,robustData));
                elseif robustPlanConfig.requiresProbDij
                    [cacheHit,robustData] = ...
                        context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'probDoseInfluenceCacheRead', ...
                        robustPlanId,'', ...
                        @() planWorkflow.precompute.ProbDoseInfluence.loadCached( ...
                        context,robustData));
                else
                    cacheHit = false;
                end
                if cacheHit
                    if robustPlanConfig.requiresIntervalDij
                        logFn(sprintf(['Using dij_interval for %s ' ...
                            'optimization; robust scenario dij is not kept ' ...
                            'in memory.'],robustData.strategy.name));
                    else
                        logFn(sprintf(['Using dij_prob for %s ' ...
                            'optimization; robust scenario dij is not kept ' ...
                            'in memory.'],robustData.strategy.name));
                    end
                    robustData = ...
                        planWorkflow.stages.PrecomputeStage.selectOptimizationDoseInfluence( ...
                        robustData);
                    data.robustPlans{robustPlanIx} = robustData;
                    continue;
                end

                if robustPlanConfig.requiresNominalDij && ~requiresCompact
                    robustData = ...
                        planWorkflow.stages.PrecomputeStage.ensureNominalPlan( ...
                        robustData,context.runConfig);
                    [robustData.dijNominal, ...
                        robustData.dijNominalPrecomputingTiming, ...
                        robustData.dijNominalPrecomputingSize, ...
                        dijNominalCacheRef] = ...
                        context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'nominalDoseInfluence',robustPlanId,'', ...
                        @() planWorkflow.stages.PrecomputeStage.getNominalDoseInfluence( ...
                        context,robustData,data.dijPrecomputingTiming, ...
                        referenceSize));
                    robustData.dijCacheRefs.dijNominal = dijNominalCacheRef;
                    robustData.dijPrecomputingTiming = ...
                        robustData.dijNominalPrecomputingTiming;
                    robustData.dijPrecomputingSize = ...
                        robustData.dijNominalPrecomputingSize;
                end

                if robustPlanConfig.requiresScenarioDij || ...
                        (requiresCompact && ~useScenarioBatch)
                    logFn(sprintf(['Precomputing robust dose influence ' ...
                        'matrix for plan "%s" (%s).'], ...
                        char(robustPlanConfig.label),robustStrategy.name));
                    [dijRobust,dijRobustPrecomputingTiming, ...
                        dijRobustPrecomputingSize,dijRobustCacheRef, ...
                        dijRobustLazyCacheHit] = ...
                        context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'robustDoseInfluence',robustPlanId,'', ...
                        @() planWorkflow.stages.PrecomputeStage.getRobustDoseInfluence( ...
                        context,robustData,data.dijPrecomputingTiming, ...
                        referenceSize));
                    if ~isempty(dijRobustCacheRef)
                        robustData.dijCacheRefs.dijRobust = ...
                            dijRobustCacheRef;
                    end
                    if dijRobustLazyCacheHit
                        robustData.dijRobust = ...
                            planWorkflow.persistence.WorkflowDataArtifact.cachedDijArtifact( ...
                            robustData,'dijRobust',runConfig, ...
                            context.cachePath,data);
                    else
                        robustData = ...
                            planWorkflow.precompute.RobustDoseInfluence.attach( ...
                            robustData,dijRobust);
                    end
                    robustData.dijRobustPrecomputingTiming = ...
                        dijRobustPrecomputingTiming;
                    robustData.dijRobustPrecomputingSize = ...
                        dijRobustPrecomputingSize;
                    robustData.dijPrecomputingTiming = ...
                        dijRobustPrecomputingTiming;
                    robustData.dijPrecomputingSize = ...
                        dijRobustPrecomputingSize;
                end

                if robustPlanConfig.requiresIntervalDij && ~cacheHit
                    robustData = context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'intervalDoseInfluence',robustPlanId,'', ...
                        @() planWorkflow.precompute.IntervalDoseInfluence.precompute( ...
                        context,robustData));
                    logFn(sprintf(['Using dij_interval for %s ' ...
                        'optimization; robust scenario dij is not kept ' ...
                        'in memory.'],robustData.strategy.name));
                end
                if robustPlanConfig.requiresProbDij && ~cacheHit
                    robustData = context.runMeasuredPlanTask( ...
                        'precompute','robust',robustPlanLabel, ...
                        'probDoseInfluence',robustPlanId,'', ...
                        @() planWorkflow.precompute.ProbDoseInfluence.precompute( ...
                        context,robustData));
                    logFn(sprintf(['Using dij_prob for %s ' ...
                        'optimization; robust scenario dij is not kept ' ...
                        'in memory.'],robustData.strategy.name));
                end

                robustData = ...
                    planWorkflow.stages.PrecomputeStage.selectOptimizationDoseInfluence( ...
                    robustData);

                data.robustPlans{robustPlanIx} = robustData;
            end

            patch = struct();
            patch.data = struct();
            patch.data.ct = data.ct;
            patch.data.cst = data.cst;
            patch.data.pln = data.pln;
            patch.data.stf = data.stf;
            patch.data.dijPrecomputingTiming = data.dijPrecomputingTiming;
            patch.data.dijPrecomputingSize = data.dijPrecomputingSize;
            if isfield(data,'dijCacheRefs')
                patch.data.dijCacheRefs = data.dijCacheRefs;
            end
            patch.data.optimizationInput = data.optimizationInput;
            if isfield(data,'robustPlans')
                patch.data.robustPlans = data.robustPlans;
            end
        end

        function robustData = selectOptimizationDoseInfluence( ...
                robustData,previousOptimizationInput)
            if nargin < 2
                previousOptimizationInput = [];
            end
            planConfig = robustData.planConfig;
            if planConfig.requiresIntervalDij
                if planConfig.hasNominalObjectives
                    planWorkflow.stages.PrecomputeStage.requireNominalOptimizationDoseInfluence( ...
                        robustData,'MissingIntervalNominalDij', ...
                        'MissingIntervalNominalPlan', ...
                        ['INTERVAL optimization with nominal ' ...
                        'objectives']);
                    dij = robustData.dijNominal;
                    pln = robustData.plnNominal;
                    stf = ...
                        planWorkflow.stages.PrecomputeStage.requireStf( ...
                        robustData,'stf','MissingIntervalOptimizationStf', ...
                        ['INTERVAL optimization with nominal ' ...
                        'objectives']);
                    dijKind = 'nominal';
                    source = 'interval-nominal';
                else
                    robustData = ...
                        planWorkflow.precompute.IntervalDoseInfluence.useForOptimization( ...
                        robustData);
                    dij = robustData.dijIntervalContext;
                    pln = robustData.plnForOptimization;
                    stf = ...
                        planWorkflow.stages.PrecomputeStage.requireStf( ...
                        robustData,'stf','MissingIntervalOptimizationStf', ...
                        'INTERVAL optimization');
                    dijKind = 'interval';
                    source = 'interval';
                end
                pln = planWorkflow.stages.PrecomputeStage.compactOptimizationPlan( ...
                    robustData,pln,'interval');
                robustData = ...
                    planWorkflow.stages.PrecomputeStage.setOptimizationInput( ...
                    robustData,dij,pln,stf,dijKind,source);
                return;
            end

            if planConfig.requiresProbDij
                if planConfig.hasNominalObjectives
                    planWorkflow.stages.PrecomputeStage.requireNominalOptimizationDoseInfluence( ...
                        robustData,'MissingProb2NominalDij', ...
                        'MissingProb2NominalPlan', ...
                        'PROB2 optimization with nominal objectives');
                    dij = robustData.dijNominal;
                    pln = robustData.plnNominal;
                    stf = ...
                        planWorkflow.stages.PrecomputeStage.requireStf( ...
                        robustData,'stf','MissingProb2OptimizationStf', ...
                        'PROB2 optimization with nominal objectives');
                    dijKind = 'nominal';
                    source = 'prob-nominal';
                else
                    robustData = ...
                        planWorkflow.precompute.ProbDoseInfluence.useForOptimization( ...
                        robustData);
                    dij = robustData.dijProbContext;
                    pln = robustData.plnForOptimization;
                    stf = ...
                        planWorkflow.stages.PrecomputeStage.requireStf( ...
                        robustData,'stf','MissingProb2OptimizationStf', ...
                        'PROB2 optimization');
                    dijKind = 'prob';
                    source = 'prob';
                end
                pln = planWorkflow.stages.PrecomputeStage.compactOptimizationPlan( ...
                    robustData,pln,'prob');
                robustData = ...
                    planWorkflow.stages.PrecomputeStage.setOptimizationInput( ...
                    robustData,dij,pln,stf,dijKind,source);
                return;
            end

            if planConfig.requiresScenarioDij
                pln = robustData.pln;
                stf = ...
                    planWorkflow.stages.PrecomputeStage.requireStf( ...
                    robustData,'stf','MissingScenarioOptimizationStf', ...
                    'Scenario optimization');
                [artifact,hasArtifact] = ...
                    planWorkflow.stages.PrecomputeStage.lazyDijArtifact( ...
                    robustData,previousOptimizationInput,'scenario', ...
                    'dijRobust');
                if hasArtifact && ...
                        ~planWorkflow.stages.PrecomputeStage.hasMaterializedDij( ...
                        robustData,'dijRobust')
                    robustData = ...
                        planWorkflow.stages.PrecomputeStage.setLazyOptimizationInput( ...
                        robustData,artifact,pln,stf,'scenario','scenario');
                    return;
                end
                if ~planWorkflow.stages.PrecomputeStage.hasMaterializedDij( ...
                        robustData,'dijRobust')
                    error(['planWorkflow:stages:PrecomputeStage:' ...
                        'MissingScenarioOptimizationDij'], ...
                        'Scenario optimization requires robustData.dijRobust.');
                end
                dij = robustData.dijRobust;
                robustData = ...
                    planWorkflow.stages.PrecomputeStage.setOptimizationInput( ...
                    robustData,dij,pln,stf,'scenario','scenario');
                return;
            end

            planWorkflow.stages.PrecomputeStage.requireNominalOptimizationDoseInfluence( ...
                robustData,'MissingNominalDij','MissingNominalPlan', ...
                'Nominal optimization');
            dij = robustData.dijNominal;
            pln = robustData.plnNominal;
            stf = ...
                planWorkflow.stages.PrecomputeStage.requireStf( ...
                robustData,'stfNominal','MissingNominalOptimizationStf', ...
                'Nominal optimization');
            robustData = ...
                planWorkflow.stages.PrecomputeStage.setOptimizationInput( ...
                robustData,dij,pln,stf,'nominal','nominal');
        end

        function referenceData = selectReferenceOptimizationDoseInfluence( ...
                referenceData)
            referenceData = ...
                planWorkflow.stages.PrecomputeStage.selectOptimizationDoseInfluence( ...
                referenceData);
            planConfig = referenceData.planConfig;
            if planConfig.requiresIntervalDij
                referenceData.plnForOptimization = ...
                    referenceData.optimizationInput.pln;
                referenceData.plnForOptimization = ...
                    planWorkflow.precompute.IntervalDoseInfluence.optimizationPlan( ...
                    referenceData);
                referenceData.optimizationInput.pln = ...
                    referenceData.plnForOptimization;
            elseif planConfig.requiresProbDij
                referenceData.plnForOptimization = ...
                    referenceData.optimizationInput.pln;
                referenceData.plnForOptimization = ...
                    planWorkflow.precompute.ProbDoseInfluence.optimizationPlan( ...
                    referenceData);
                referenceData.optimizationInput.pln = ...
                    referenceData.plnForOptimization;
            end
            referenceData = ...
                planWorkflow.stages.PrecomputeStage.stripOptimizationSelectionFields( ...
                referenceData);
        end
    end

    methods (Static, Access = private)
        function stf = requireStf(robustData,fieldName,identifier,context)
            if ~isfield(robustData,fieldName) || isempty(robustData.(fieldName))
                error(['planWorkflow:stages:PrecomputeStage:' identifier], ...
                    '%s requires robustData.%s.',context,fieldName);
            end
            stf = robustData.(fieldName);
        end

        function robustData = setOptimizationInput( ...
                robustData,dij,pln,stf,dijKind,source)
            robustData.optimizationInput = ...
                planWorkflow.precompute.OptimizationInput.build( ...
                robustData.ct,robustData.cst,pln,stf,dij,dijKind, ...
                source,planWorkflow.stages.PrecomputeStage.ctReferenceView( ...
                robustData));
            robustData = ...
                planWorkflow.stages.PrecomputeStage.stripOptimizationSelectionFields( ...
                robustData);
        end

        function robustData = setLazyOptimizationInput( ...
                robustData,dijArtifact,pln,stf,dijKind,source)
            input = struct();
            input.ct = robustData.ct;
            input.cst = robustData.cst;
            input.pln = pln;
            input.stf = stf;
            input.dijKind = char(dijKind);
            input.source = char(source);
            input.ctReferenceView = ...
                planWorkflow.stages.PrecomputeStage.ctReferenceView( ...
                robustData);
            if planWorkflow.stages.PrecomputeStage.isDijRefArtifact( ...
                    dijArtifact)
                input.dijRef = dijArtifact;
            elseif planWorkflow.stages.PrecomputeStage.isDijInlineArtifact( ...
                    dijArtifact)
                input.dijInline = dijArtifact;
            else
                error(['planWorkflow:stages:PrecomputeStage:' ...
                    'InvalidLazyDijArtifact'], ...
                    'Cannot select a lazy optimizationInput from this artifact.');
            end
            planWorkflow.precompute.OptimizationInput.validateLight( ...
                input,[char(source) ' optimizationInput']);
            robustData.optimizationInput = input;
            robustData = ...
                planWorkflow.stages.PrecomputeStage.stripOptimizationSelectionFields( ...
                robustData);
        end

        function [artifact,hasArtifact] = lazyDijArtifact( ...
                robustData,previousOptimizationInput,dijKind,fieldName)
            artifact = [];
            hasArtifact = false;
            [artifact,hasArtifact] = ...
                planWorkflow.stages.PrecomputeStage.lazyDijArtifactFromInput( ...
                previousOptimizationInput,dijKind);
            if hasArtifact
                return;
            end
            if isstruct(robustData) && isfield(robustData,'optimizationInput')
                [artifact,hasArtifact] = ...
                    planWorkflow.stages.PrecomputeStage.lazyDijArtifactFromInput( ...
                    robustData.optimizationInput,dijKind);
                if hasArtifact
                    return;
                end
            end
            if isstruct(robustData) && isfield(robustData,fieldName) && ...
                    planWorkflow.stages.PrecomputeStage.isLazyDijArtifact( ...
                    robustData.(fieldName))
                artifact = robustData.(fieldName);
                hasArtifact = ...
                    planWorkflow.stages.PrecomputeStage.artifactMatchesDijKind( ...
                    artifact,dijKind);
            end
        end

        function [artifact,hasArtifact] = lazyDijArtifactFromInput( ...
                input,dijKind)
            artifact = [];
            hasArtifact = false;
            if ~isstruct(input) || ~isfield(input,'dijKind') || ...
                    ~strcmp(char(input.dijKind),char(dijKind))
                return;
            end
            if isfield(input,'dijRef') && ...
                    planWorkflow.stages.PrecomputeStage.artifactMatchesDijKind( ...
                    input.dijRef,dijKind)
                artifact = input.dijRef;
                hasArtifact = true;
                return;
            end
            if isfield(input,'dijInline') && ...
                    planWorkflow.stages.PrecomputeStage.artifactMatchesDijKind( ...
                    input.dijInline,dijKind)
                artifact = input.dijInline;
                hasArtifact = true;
            end
        end

        function tf = hasMaterializedDij(data,fieldName)
            tf = isstruct(data) && isfield(data,fieldName) && ...
                ~isempty(data.(fieldName)) && ...
                ~planWorkflow.stages.PrecomputeStage.isLazyDijArtifact( ...
                data.(fieldName));
        end

        function tf = artifactMatchesDijKind(artifact,dijKind)
            tf = planWorkflow.stages.PrecomputeStage.isLazyDijArtifact( ...
                artifact);
            if tf && isfield(artifact,'dijKind') && ...
                    ~isempty(artifact.dijKind)
                tf = strcmp(char(artifact.dijKind),char(dijKind));
            end
        end

        function tf = isLazyDijArtifact(value)
            tf = planWorkflow.stages.PrecomputeStage.isDijRefArtifact(value) || ...
                planWorkflow.stages.PrecomputeStage.isDijInlineArtifact(value);
        end

        function tf = isDijRefArtifact(value)
            tf = isstruct(value) && isfield(value,'artifactKind') && ...
                strcmp(char(value.artifactKind), ...
                planWorkflow.persistence.WorkflowDataArtifact.RefKind);
        end

        function tf = isDijInlineArtifact(value)
            tf = isstruct(value) && isfield(value,'artifactKind') && ...
                strcmp(char(value.artifactKind), ...
                planWorkflow.persistence.WorkflowDataArtifact.InlineKind);
        end

        function data = stripOptimizationSelectionFields(data)
            fields = {'plnForOptimization','stfForOptimization', ...
                'usesNominalDijForOptimization'};
            for fieldIx = 1:numel(fields)
                if isfield(data,fields{fieldIx})
                    data = rmfield(data,fields{fieldIx});
                end
            end
        end

        function metadata = ctReferenceView(data)
            if isstruct(data) && isfield(data,'ctReferenceView') && ...
                    ~isempty(data.ctReferenceView)
                metadata = data.ctReferenceView;
            else
                metadata = ...
                    planWorkflow.precompute.OptimizationInput.emptyCtReferenceView();
            end
        end

        function pln = compactOptimizationPlan(robustData,pln,dijKind)
            tempData = robustData;
            tempData.plnForOptimization = pln;
            switch char(dijKind)
                case 'interval'
                    pln = ...
                        planWorkflow.precompute.IntervalDoseInfluence.optimizationPlan( ...
                        tempData);
                case 'prob'
                    pln = ...
                        planWorkflow.precompute.ProbDoseInfluence.optimizationPlan( ...
                        tempData);
            end
        end

        function dijKind = optimizationDijKind(planConfig)
            if isfield(planConfig,'requiresIntervalDij') && ...
                    logical(planConfig.requiresIntervalDij)
                dijKind = 'interval';
            elseif isfield(planConfig,'requiresProbDij') && ...
                    logical(planConfig.requiresProbDij)
                dijKind = 'prob';
            elseif isfield(planConfig,'requiresScenarioDij') && ...
                    logical(planConfig.requiresScenarioDij)
                dijKind = 'scenario';
            else
                dijKind = 'nominal';
            end
        end

        function pln = cleanBasePlan(pln)
            if ~isstruct(pln) || ~isfield(pln,'propOpt') || ...
                    ~isstruct(pln.propOpt)
                return;
            end
            fields = {'useMaxApprox','p1','p2','theta1','theta2', ...
                'scen4D','dij_interval','dij_prob'};
            for fieldIx = 1:numel(fields)
                if isfield(pln.propOpt,fields{fieldIx})
                    pln.propOpt = rmfield(pln.propOpt,fields{fieldIx});
                end
            end
        end

        function referenceData = referenceData( ...
                context,sourceData,reference,referenceLabel)
            referenceData = sourceData;
            referenceData.planConfig = ...
                planWorkflow.stages.PrecomputeStage.referencePlanConfig( ...
                context,reference,referenceLabel);
            [referenceData,scenarioForComputation,ctReferenceView] = ...
                planWorkflow.precompute.CtReferenceDataView.apply( ...
                referenceData,referenceData.planConfig.scenario);
            referenceData.ctReferenceView = ctReferenceView;
            referenceData.strategy = ...
                planWorkflow.robustness.AbstractStrategy.create( ...
                referenceData.planConfig.robustnessMode);
            scenarioConfig = ...
                planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                scenarioForComputation);
            scenarioConfig = planWorkflow.config.ScenarioSpec.withBeamCount( ...
                scenarioConfig,referenceData.pln);
            referenceData.pln.multScen = planWorkflow.scenario.createModel( ...
                referenceData.ct,scenarioConfig.scen_mode,scenarioConfig, ...
                'optimization');
            referenceData.pln = ...
                planWorkflow.optimization.PlanOptimizationService.apply4DConfig( ...
                referenceData.pln,referenceData.planConfig);
            referenceData.pln = ...
                planWorkflow.plan.Plan.applyDoseParallelism( ...
                referenceData.pln,context.runConfig);
            if ctReferenceView.active
                referenceData.stf = matRad_generateStf( ...
                    referenceData.ct,referenceData.cst,referenceData.pln);
            end
            if (isstruct(referenceData.pln.multScen) && ...
                    isfield(referenceData.pln.multScen,'ctScenProb')) || ...
                    (isobject(referenceData.pln.multScen) && ...
                    isprop(referenceData.pln.multScen,'ctScenProb'))
                referenceData.ctScenProb = ...
                    referenceData.pln.multScen.ctScenProb(:,2)';
            else
                referenceData.ctScenProb = [];
            end
        end

        function planConfig = referencePlanConfig( ...
                context,reference,referenceLabel)
            contract = ...
                planWorkflow.templates.ObjectiveRobustnessContract.forTemplateObjectiveSet( ...
                context.planTemplate,'reference');
            planConfig = planWorkflow.config.RobustPlanConfig.defaultPlan();
            planConfig.id = 'reference';
            planConfig.label = char(referenceLabel);
            planConfig.objectiveSetName = 'reference';
            planConfig.robustnessMode = reference.robustnessMode;
            planConfig.scenario = reference.scenario;
            planConfig.optimization4D = reference.optimization4D;
            planConfig.robustnessOptions = reference.robustnessOptions;
            planConfig.dosePrecompute = reference.dosePrecompute;
            planConfig.variants = reference.variants;
            planConfig = ...
                planWorkflow.config.RobustPlanConfig.normalizePlan( ...
                planConfig,1,contract);
        end

        function [data,referenceData] = ...
                precomputeReferenceCompactDoseInfluence( ...
                context,data,referenceData)
            planConfig = referenceData.planConfig;
            referenceLabel = char(planConfig.label);
            if planConfig.requiresIntervalDij
                [cacheHit,referenceData] = ...
                    context.runMeasuredPlanTask( ...
                    'precompute','reference',referenceLabel, ...
                    'intervalDoseInfluenceCacheRead','reference','', ...
                    @() planWorkflow.precompute.IntervalDoseInfluence.loadCached( ...
                    context,referenceData));
            elseif planConfig.requiresProbDij
                [cacheHit,referenceData] = ...
                    context.runMeasuredPlanTask( ...
                    'precompute','reference',referenceLabel, ...
                    'probDoseInfluenceCacheRead','reference','', ...
                    @() planWorkflow.precompute.ProbDoseInfluence.loadCached( ...
                    context,referenceData));
            else
                cacheHit = false;
            end

            if cacheHit
                if planConfig.requiresIntervalDij
                    context.log(sprintf(['Using reference dij_interval for ' ...
                        '%s optimization; robust scenario dij is not kept ' ...
                        'in memory.'],referenceData.strategy.name));
                else
                    context.log(['Using reference dij_prob for PROB2 ' ...
                        'optimization; robust scenario dij is not kept in memory.']);
                end
            else
                useScenarioBatch = ...
                    planWorkflow.precompute.ScenarioFreeDoseInfluence.useScenarioBatchPrecompute( ...
                    planConfig);
                if ~useScenarioBatch
                    context.log(sprintf(['Precomputing reference robust ' ...
                        'dose influence matrix for %s.'], ...
                        referenceData.strategy.name));
                    [dijRobust,dijRobustPrecomputingTiming, ...
                        dijRobustPrecomputingSize,dijRobustCacheRef] = ...
                        context.runMeasuredPlanTask( ...
                        'precompute','reference',referenceLabel, ...
                        'robustDoseInfluence','reference','', ...
                        @() planWorkflow.stages.PrecomputeStage.getRobustDoseInfluence( ...
                        context,referenceData,[],[]));
                    referenceData = ...
                        planWorkflow.precompute.RobustDoseInfluence.attach( ...
                        referenceData,dijRobust);
                    if ~isempty(dijRobustCacheRef)
                        referenceData.dijCacheRefs.dijRobust = ...
                            dijRobustCacheRef;
                    end
                    referenceData.dijRobustPrecomputingTiming = ...
                        dijRobustPrecomputingTiming;
                    referenceData.dijRobustPrecomputingSize = ...
                        dijRobustPrecomputingSize;
                    referenceData.dijPrecomputingTiming = ...
                        dijRobustPrecomputingTiming;
                    referenceData.dijPrecomputingSize = ...
                        dijRobustPrecomputingSize;
                end

                if planConfig.requiresIntervalDij
                    referenceData = context.runMeasuredPlanTask( ...
                        'precompute','reference',referenceLabel, ...
                        'intervalDoseInfluence','reference','', ...
                        @() planWorkflow.precompute.IntervalDoseInfluence.precompute( ...
                        context,referenceData));
                    context.log(sprintf(['Using reference dij_interval for ' ...
                        '%s optimization; robust scenario dij is not kept ' ...
                        'in memory.'],referenceData.strategy.name));
                elseif planConfig.requiresProbDij
                    referenceData = context.runMeasuredPlanTask( ...
                        'precompute','reference',referenceLabel, ...
                        'probDoseInfluence','reference','', ...
                        @() planWorkflow.precompute.ProbDoseInfluence.precompute( ...
                        context,referenceData));
                    context.log(['Using reference dij_prob for PROB2 ' ...
                        'optimization; robust scenario dij is not kept in memory.']);
                end
            end

            referenceData = ...
                planWorkflow.stages.PrecomputeStage.selectReferenceOptimizationDoseInfluence( ...
                referenceData);
            data = ...
                planWorkflow.stages.PrecomputeStage.assignReferenceOptimizationDoseInfluence( ...
                data,referenceData);
        end

        function data = assignReferenceOptimizationDoseInfluence( ...
                data,referenceData)
            optimizationInput = ...
                planWorkflow.precompute.OptimizationInput.require( ...
                referenceData,'reference precompute');
            data.ct = optimizationInput.ct;
            data.cst = optimizationInput.cst;
            data.dijPrecomputingTiming = referenceData.dijPrecomputingTiming;
            data.dijPrecomputingSize = referenceData.dijPrecomputingSize;
            data.pln = optimizationInput.pln;
            data.stf = optimizationInput.stf;
            data.optimizationInput = optimizationInput;
            if isfield(referenceData,'dijCacheRefs')
                data.dijCacheRefs = referenceData.dijCacheRefs;
            end
        end

        function [dij,dijPrecomputingTiming,dijPrecomputingSize, ...
                cacheRef,lazyCacheHit] = ...
                getRobustDoseInfluence(context,robustData,referenceTiming, ...
                referenceSize)
            if nargin < 4
                referenceSize = [];
            end
            lazyCacheHit = false;
            tag = ['robust_' char(robustData.planConfig.id)];
            componentRole = 'robust';
            if robustData.planConfig.requiresIntervalDij || ...
                    robustData.planConfig.requiresProbDij
                componentRole = 'input';
            end
            timingOptions = ...
                planWorkflow.performance.PrecomputeTiming.cacheOptions( ...
                componentRole,char(robustData.planConfig.label), ...
                'dij_robust',referenceTiming,referenceSize);
            if robustData.planConfig.requiresIntervalDij || ...
                    robustData.planConfig.requiresProbDij
                [dij,dijPrecomputingTiming,dijPrecomputingSize] = ...
                    context.cache.getOrCalculateTransientTimed( ...
                    tag,robustData,robustData.ct,robustData.cst, ...
                    robustData.stf,robustData.pln,timingOptions);
                cacheRef = [];
            else
                [dij,dijPrecomputingTiming,dijPrecomputingSize, ...
                    cacheRef,lazyCacheHit] = ...
                    context.cache.getOrCreateLazyTimed( ...
                    tag,robustData.ct,robustData.cst,robustData.stf, ...
                    robustData.pln,timingOptions);
            end
        end

        function [dij,dijPrecomputingTiming,dijPrecomputingSize,cacheRef] = ...
                getNominalDoseInfluence(context,robustData,referenceTiming, ...
                referenceSize)
            if nargin < 4
                referenceSize = [];
            end
            robustData = ...
                planWorkflow.stages.PrecomputeStage.ensureNominalPlan( ...
                robustData,context.runConfig);
            tag = ['robustNominal_' char(robustData.planConfig.id)];
            timingOptions = ...
                planWorkflow.performance.PrecomputeTiming.cacheOptions( ...
                'robust',char(robustData.planConfig.label), ...
                'dij_nominal',referenceTiming,referenceSize);
            [dij,dijPrecomputingTiming,dijPrecomputingSize,cacheRef] = ...
                context.cache.getOrCreateTimed( ...
                tag,robustData.ct,robustData.cst,robustData.stfNominal, ...
                robustData.plnNominal,timingOptions);
        end

        function robustData = ensureNominalPlan(robustData,runConfig)
            if nargin < 2
                runConfig = [];
            end
            if isfield(robustData,'plnNominal') && ...
                    isfield(robustData,'stfNominal') && ...
                    ~isempty(robustData.plnNominal) && ...
                    ~isempty(robustData.stfNominal)
                return;
            end
            nominalScenario = ...
                planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                planWorkflow.config.RobustPlanConfig.defaultScenario( ...
                'nomScen'));
            if isfield(robustData,'ct') && isfield(robustData.ct,'refScen') && ...
                    ~isempty(robustData.ct.refScen)
                nominalScenario.ctReferenceScenId = robustData.ct.refScen;
            elseif isfield(robustData,'planConfig') && ...
                    isfield(robustData.planConfig,'scenario') && ...
                    isfield(robustData.planConfig.scenario,'ctReferenceScenId') && ...
                    ~isempty(robustData.planConfig.scenario.ctReferenceScenId)
                nominalScenario.ctReferenceScenId = ...
                    robustData.planConfig.scenario.ctReferenceScenId;
            end
            nominalScenario = ...
                planWorkflow.config.ScenarioSpec.withBeamCount( ...
                nominalScenario,robustData.pln);
            plnNominal = robustData.pln;
            plnNominal.multScen = planWorkflow.scenario.createModel( ...
                robustData.ct,nominalScenario.scen_mode, ...
                nominalScenario,'optimization');
            if isfield(plnNominal,'propOpt') && ...
                    isstruct(plnNominal.propOpt) && ...
                    isfield(plnNominal.propOpt,'scen4D')
                plnNominal.propOpt = rmfield(plnNominal.propOpt,'scen4D');
            end
            plnNominal = planWorkflow.plan.Plan.applyDoseParallelism( ...
                plnNominal,runConfig);
            robustData.plnNominal = plnNominal;
            robustData.stfNominal = matRad_generateStf( ...
                robustData.ct,robustData.cst,robustData.plnNominal);
        end

        function requireNominalOptimizationDoseInfluence( ...
                robustData,dijErrorId,plnErrorId,description)
            if ~isfield(robustData,'dijNominal') || ...
                    isempty(robustData.dijNominal)
                error(['planWorkflow:stages:PrecomputeStage:' ...
                    char(dijErrorId)], ...
                    '%s requires plan-specific dijNominal.', ...
                    char(description));
            end
            if ~isfield(robustData,'plnNominal') || ...
                    isempty(robustData.plnNominal)
                error(['planWorkflow:stages:PrecomputeStage:' ...
                    char(plnErrorId)], ...
                    '%s requires plan-specific plnNominal.', ...
                    char(description));
            end
        end
    end
end
