classdef SamplingPlanSet
    % SamplingPlanSet Describes plans sampled with one workflow sampling config.

    methods (Static)
        function planSet = fromData(runConfig,data)
            entries = planWorkflow.sampling.SamplingPlanSet.referenceEntry( ...
                runConfig,data);
            if planWorkflow.sampling.SamplingPlanSet.hasRobustPlans(data)
                robustEntries = ...
                    planWorkflow.sampling.SamplingPlanSet.robustEntries(data);
                entries = [entries robustEntries]; %#ok<AGROW>
            end

            planSet = struct();
            planSet.entries = entries;
            planSet.metadata = ...
                planWorkflow.sampling.SamplingPlanSet.entryMetadata(entries);
            planSet.samplingConfig = ...
                planWorkflow.config.StageConfigSchema.mapFromRunConfig( ...
                'sampling', ...
                planWorkflow.config.StageConfigSchema.fields('sampling'), ...
                runConfig);
        end

        function metadata = entryMetadata(entries)
            metadata = repmat(struct( ...
                'role','', ...
                'planId','', ...
                'variantId','', ...
                'planLabel','', ...
                'label','', ...
                'robustnessMode','', ...
                'scenario',struct(), ...
                'optimization4D',struct()),1,numel(entries));
            for entryIx = 1:numel(entries)
                entry = entries(entryIx);
                metadata(entryIx).role = entry.role;
                metadata(entryIx).planId = entry.planId;
                metadata(entryIx).variantId = entry.variantId;
                metadata(entryIx).planLabel = entry.planLabel;
                metadata(entryIx).label = entry.label;
                metadata(entryIx).robustnessMode = entry.robustnessMode;
                metadata(entryIx).scenario = entry.scenario;
                metadata(entryIx).optimization4D = entry.optimization4D;
            end
        end

        function scenarioConfig = withPlanSetBeamCount( ...
                scenarioConfig,planSet)
            if ~isfield(planSet,'entries') || isempty(planSet.entries)
                error(['planWorkflow:sampling:SamplingPlanSet:' ...
                    'EmptyPlanSet'], ...
                    'Sampling scenario configuration requires plan entries.');
            end
            scenarioConfig = planWorkflow.config.ScenarioSpec.withBeamCount( ...
                scenarioConfig,planSet.entries(1).pln);
            referenceBeamCount = scenarioConfig.numOfBeams;
            for entryIx = 2:numel(planSet.entries)
                entryBeamCount = ...
                    planWorkflow.plan.Plan.numOfBeams( ...
                    planSet.entries(entryIx).pln);
                if entryBeamCount ~= referenceBeamCount
                    error(['planWorkflow:sampling:SamplingPlanSet:' ...
                        'IncompatibleBeamCount'], ...
                        ['Sampling is a transversal comparison. Plan "%s" ' ...
                         '(planId "%s", variantId "%s") has %d beams, ' ...
                         'but the sampling basis has %d beams.'], ...
                        char(planSet.entries(entryIx).label), ...
                        char(planSet.entries(entryIx).planId), ...
                        char(planSet.entries(entryIx).variantId), ...
                        entryBeamCount,referenceBeamCount);
                end
            end
        end

        function basis = scenarioBasis(planSet,samplingScenarioConfig, ...
                effectiveCtScenProb)
            if nargin < 3
                effectiveCtScenProb = [];
            end
            basis = struct();
            basis.sampling = planWorkflow.config.ScenarioSpec.basisMetadata( ...
                samplingScenarioConfig,effectiveCtScenProb);
            basis.entries = planSet.metadata;
            basis.reference = repmat(struct(),1,0);
            basis.robustPlans = repmat(struct( ...
                'id','', ...
                'label','', ...
                'robustnessMode','', ...
                'scenario',struct(), ...
                'optimization4D',struct(), ...
                'variants',[]),1,0);
            if isempty(planSet.entries)
                return;
            end

            referenceIx = find(strcmp({planSet.entries.role}, ...
                'reference'),1);
            if ~isempty(referenceIx)
                referenceEntry = planSet.entries(referenceIx);
                basis.reference = struct( ...
                    'id',referenceEntry.planId, ...
                    'label',referenceEntry.label, ...
                    'robustnessMode',referenceEntry.robustnessMode, ...
                    'scenario',referenceEntry.scenario, ...
                    'optimization4D',referenceEntry.optimization4D);
            end

            robustEntries = planSet.entries( ...
                strcmp({planSet.entries.role},'robust'));
            planIds = unique({robustEntries.planId},'stable');
            basis.robustPlans = repmat(struct( ...
                'id','', ...
                'label','', ...
                'robustnessMode','', ...
                'scenario',struct(), ...
                'optimization4D',struct(), ...
                'variants',[]),1,numel(planIds));
            for planIx = 1:numel(planIds)
                planEntries = robustEntries( ...
                    strcmp({robustEntries.planId},planIds{planIx}));
                firstEntry = planEntries(1);
                basis.robustPlans(planIx).id = firstEntry.planId;
                basis.robustPlans(planIx).label = firstEntry.planLabel;
                basis.robustPlans(planIx).robustnessMode = ...
                    firstEntry.robustnessMode;
                basis.robustPlans(planIx).scenario = firstEntry.scenario;
                basis.robustPlans(planIx).optimization4D = ...
                    firstEntry.optimization4D;
                basis.robustPlans(planIx).variants = ...
                    planWorkflow.sampling.SamplingPlanSet.variantMetadata( ...
                    planEntries);
            end
        end
    end

    methods (Static, Access = private)
        function entry = referenceEntry(runConfig,data)
            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            label = ...
                planWorkflow.results.PlanLabels.referencePlanDisplayLabel( ...
                reference);
            scenario = ...
                planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                reference.scenario);
            entry = planWorkflow.sampling.SamplingPlanSet.emptyEntry();
            entry.role = 'reference';
            entry.planId = 'reference';
            entry.variantId = '';
            entry.planLabel = label;
            entry.label = label;
            entry.robustnessMode = char(reference.robustnessMode);
            entry.scenario = ...
                planWorkflow.config.ScenarioSpec.basisMetadata(scenario);
            entry.optimization4D = reference.optimization4D;
            optimizationInput = ...
                planWorkflow.precompute.OptimizationInput.requireLight( ...
                data,'reference sampling');
            planWorkflow.precompute.OptimizationInput.assertWeightSteeringMatch( ...
                optimizationInput,data.resultGUIReference,'reference','', ...
                'reference sampling');
            entry.stf = optimizationInput.stf;
            entry.pln = optimizationInput.pln;
            entry.resultGUI = data.resultGUIReference;
        end

        function entries = robustEntries(data)
            count = 0;
            for robustPlanIx = 1:numel(data.robustPlans)
                robustData = data.robustPlans{robustPlanIx};
                count = count + ...
                    numel(planWorkflow.results.VariantResults.requireComplete( ...
                    robustData,'sampling'));
            end

            entries = repmat( ...
                planWorkflow.sampling.SamplingPlanSet.emptyEntry(), ...
                1,count);
            entryIx = 0;
            for robustPlanIx = 1:numel(data.robustPlans)
                robustData = data.robustPlans{robustPlanIx};
                variantResults = ...
                    planWorkflow.results.VariantResults.requireComplete( ...
                    robustData,'sampling');
                scenario = ...
                    planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                    robustData.planConfig.scenario);
                scenario = planWorkflow.config.ScenarioSpec.basisMetadata( ...
                    scenario);
                for variantIx = 1:numel(variantResults)
                    entryIx = entryIx + 1;
                    variantResult = variantResults(variantIx);
                    entries(entryIx).role = 'robust';
                    entries(entryIx).planId = variantResult.planId;
                    entries(entryIx).variantId = variantResult.variantId;
                    entries(entryIx).planLabel = ...
                        char(robustData.planConfig.label);
                    entries(entryIx).label = variantResult.label;
                    entries(entryIx).robustnessMode = ...
                        variantResult.robustnessMode;
                    entries(entryIx).scenario = scenario;
                    entries(entryIx).optimization4D = ...
                        variantResult.optimization4D;
                    entries(entryIx).stf = ...
                        planWorkflow.sampling.SamplingPlanSet.stfForVariant( ...
                        robustData,variantResult);
                    entries(entryIx).pln = ...
                        planWorkflow.results.VariantPlanResolver.resolve( ...
                        robustData,variantResult);
                    entries(entryIx).resultGUI = variantResult.resultGUI;
                end
            end
        end

        function entry = emptyEntry()
            entry = struct( ...
                'role','', ...
                'planId','', ...
                'variantId','', ...
                'planLabel','', ...
                'label','', ...
                'robustnessMode','', ...
                'scenario',struct(), ...
                'optimization4D',struct(), ...
                'stf',[], ...
                'pln',[], ...
                'resultGUI',[]);
        end

        function tf = hasRobustPlans(data)
            tf = isfield(data,'robustPlans') && ~isempty(data.robustPlans);
        end

        function metadata = variantMetadata(entries)
            metadata = repmat(struct( ...
                'variantId','', ...
                'label','', ...
                'scenario',struct(), ...
                'optimization4D',struct()),1,numel(entries));
            for entryIx = 1:numel(entries)
                metadata(entryIx).variantId = entries(entryIx).variantId;
                metadata(entryIx).label = entries(entryIx).label;
                metadata(entryIx).scenario = entries(entryIx).scenario;
                metadata(entryIx).optimization4D = ...
                    entries(entryIx).optimization4D;
            end
        end

        function stf = stfForVariant(robustData,variantResult)
            optimizationInput = ...
                planWorkflow.precompute.OptimizationInput.requireLight( ...
                robustData,'robust sampling');
            planWorkflow.precompute.OptimizationInput.assertWeightSteeringMatch( ...
                optimizationInput,variantResult.resultGUI, ...
                planWorkflow.sampling.SamplingPlanSet.planId( ...
                robustData), ...
                planWorkflow.sampling.SamplingPlanSet.variantId( ...
                variantResult),'robust sampling');
            stf = optimizationInput.stf;
        end

        function id = planId(robustData)
            id = '<unknown>';
            if isstruct(robustData) && isfield(robustData,'planConfig') && ...
                    isstruct(robustData.planConfig) && ...
                    isfield(robustData.planConfig,'id') && ...
                    ~isempty(robustData.planConfig.id)
                id = char(robustData.planConfig.id);
            end
        end

        function id = variantId(variantResult)
            id = '<unknown>';
            if isstruct(variantResult) && isfield(variantResult,'variantId') && ...
                    ~isempty(variantResult.variantId)
                id = char(variantResult.variantId);
            end
        end
    end
end
