function key = normalizationKey(name)

key = lower(strtrim(char(name)));
replacements = { ...
    'á','a'; 'à','a'; 'ä','a'; 'â','a'; ...
    'é','e'; 'è','e'; 'ë','e'; 'ê','e'; ...
    'í','i'; 'ì','i'; 'ï','i'; 'î','i'; ...
    'ó','o'; 'ò','o'; 'ö','o'; 'ô','o'; ...
    'ú','u'; 'ù','u'; 'ü','u'; 'û','u'; ...
    'ñ','n'};

for replIx = 1:size(replacements,1)
    key = strrep(key,replacements{replIx,1},replacements{replIx,2});
end

key = regexprep(key,'[^a-z0-9]+',' ');
key = strtrim(regexprep(key,'\s+',' '));

end
