classdef VariantPlanResolver
    % VariantPlanResolver Rebuilds variant-specific optimization plans.

    methods (Static)
        function pln = resolve(robustData,variantResult)
            variantIx = ...
                planWorkflow.results.VariantPlanResolver.variantIndex( ...
                robustData,variantResult);
            pln = planWorkflow.optimization.VariantPlanFactory.build( ...
                robustData,variantIx);
        end
    end

    methods (Static, Access = private)
        function variantIx = variantIndex(robustData,variantResult)
            if isnumeric(variantResult)
                variantIx = variantResult;
                return;
            end
            if ~isstruct(robustData) || ~isfield(robustData,'planConfig') || ...
                    ~isfield(robustData.planConfig,'variants')
                error(['planWorkflow:results:VariantPlanResolver:' ...
                    'MissingPlanConfig'], ...
                    'Variant plan resolution requires robustData.planConfig.');
            end
            if ~isstruct(variantResult) || ...
                    ~isfield(variantResult,'variantId') || ...
                    isempty(variantResult.variantId)
                error(['planWorkflow:results:VariantPlanResolver:' ...
                    'MissingVariantId'], ...
                    'Variant plan resolution requires a variantId.');
            end
            variants = ...
                planWorkflow.config.RobustPlanConfig.variantsWithPenalties( ...
                robustData.planConfig);
            variantIds = {variants.id};
            variantIx = find(strcmp(variantIds,char(variantResult.variantId)), ...
                1);
            if isempty(variantIx)
                error(['planWorkflow:results:VariantPlanResolver:' ...
                    'UnknownVariantId'], ...
                    'Unknown variantId "%s" for robust plan "%s".', ...
                    char(variantResult.variantId), ...
                    char(robustData.planConfig.id));
            end
        end
    end
end
