classdef VariantResults
    % VariantResults Canonical robust optimization results by variant.

    methods (Static)
        function results = empty(count)
            if nargin < 1 || isempty(count)
                count = 0;
            end
            results = repmat(planWorkflow.results.VariantResults.emptyResult(), ...
                1,count);
        end

        function result = create(robustData,variantIx,resultGUI)
            planConfig = robustData.planConfig;
            variantConfig = planConfig.variants(variantIx);

            result = planWorkflow.results.VariantResults.emptyResult();
            result.planId = char(planConfig.id);
            result.variantId = char(variantConfig.id);
            result.label = planWorkflow.results.PlanLabels.robustResultLabel( ...
                planConfig,variantIx);
            result.resultGUI = resultGUI;
            result.strategy = char(planConfig.strategy);
            result.scenario = planConfig.scenario;
            result.optimization4D = planConfig.optimization4D;
            if isfield(robustData,'objectiveInfo')
                result.objectiveInfo = robustData.objectiveInfo;
            end
        end

        function results = optional(robustData)
            if isfield(robustData,'variantResults') && ...
                    ~isempty(robustData.variantResults)
                results = robustData.variantResults;
                return;
            end

            if isfield(robustData,'resultGUI') && ...
                    ~isempty(robustData.resultGUI)
                error(['planWorkflow:results:VariantResults:' ...
                    'MissingVariantResults'], ...
                    ['Robust optimization results must be stored in ' ...
                     'robustData.variantResults. robustData.resultGUI is ' ...
                     'a derived projection, not a canonical source.']);
            end

            results = planWorkflow.results.VariantResults.empty(0);
        end

        function results = requireComplete(robustData,purpose)
            if nargin < 2 || isempty(purpose)
                purpose = 'this workflow stage';
            end
            results = planWorkflow.results.VariantResults.optional( ...
                robustData);
            if isempty(results)
                error(['planWorkflow:results:VariantResults:' ...
                    'MissingVariantResults'], ...
                    ['Robust plan "%s" cannot enter %s before complete ' ...
                     'variantResults are available.'], ...
                    planWorkflow.results.VariantResults.planLabel( ...
                    robustData),char(purpose));
            end
            planWorkflow.results.VariantResults.assertComplete( ...
                robustData,results,purpose);
        end

        function results = fromRobustData(robustData)
            results = planWorkflow.results.VariantResults.requireComplete( ...
                robustData,'result consumption');
        end

        function count = count(robustData)
            count = numel(planWorkflow.results.VariantResults.optional( ...
                robustData));
        end

        function resultGUI = resultGUIList(robustData)
            results = planWorkflow.results.VariantResults.requireComplete( ...
                robustData,'resultGUI projection');
            resultGUI = cell(1,numel(results));
            for resultIx = 1:numel(results)
                resultGUI{resultIx} = results(resultIx).resultGUI;
            end
        end
    end

    methods (Static, Access = private)
        function result = emptyResult()
            result = struct( ...
                'planId','', ...
                'variantId','', ...
                'label','', ...
                'resultGUI',[], ...
                'strategy','', ...
                'scenario',struct(), ...
                'optimization4D',struct(), ...
                'objectiveInfo',struct(), ...
                'dvh',[], ...
                'qi',[]);
        end

        function assertComplete(robustData,results,purpose)
            if ~isstruct(robustData) || ~isfield(robustData,'planConfig') || ...
                    ~isfield(robustData.planConfig,'variants')
                error(['planWorkflow:results:VariantResults:' ...
                    'MissingPlanConfig'], ...
                    'Complete variantResults validation requires planConfig.');
            end
            planConfig = robustData.planConfig;
            expectedCount = numel(planConfig.variants);
            if numel(results) ~= expectedCount
                error(['planWorkflow:results:VariantResults:' ...
                    'IncompleteVariantResults'], ...
                    ['Robust plan "%s" has %d variantResults for %d ' ...
                     'configured variants before %s.'], ...
                    planWorkflow.results.VariantResults.planLabel( ...
                    robustData),numel(results),expectedCount,char(purpose));
            end
            variantIds = {planConfig.variants.id};
            for resultIx = 1:numel(results)
                result = results(resultIx);
                planWorkflow.results.VariantResults.assertTextField( ...
                    result,'planId',robustData,resultIx,purpose);
                planWorkflow.results.VariantResults.assertTextField( ...
                    result,'variantId',robustData,resultIx,purpose);
                planWorkflow.results.VariantResults.assertTextField( ...
                    result,'label',robustData,resultIx,purpose);
                if ~strcmp(char(result.planId),char(planConfig.id))
                    error(['planWorkflow:results:VariantResults:' ...
                        'PlanIdMismatch'], ...
                        ['Variant result %d belongs to planId "%s", not ' ...
                         'robust plan "%s".'],resultIx,char(result.planId), ...
                        char(planConfig.id));
                end
                if ~any(strcmp(variantIds,char(result.variantId)))
                    error(['planWorkflow:results:VariantResults:' ...
                        'UnknownVariantId'], ...
                        ['Variant result %d references unknown variantId ' ...
                         '"%s" for robust plan "%s".'], ...
                        resultIx,char(result.variantId), ...
                        char(planConfig.id));
                end
                if ~isfield(result,'resultGUI') || isempty(result.resultGUI) || ...
                        ~isstruct(result.resultGUI) || ...
                        ~isfield(result.resultGUI,'w') || ...
                        isempty(result.resultGUI.w)
                    error(['planWorkflow:results:VariantResults:' ...
                        'MissingVariantWeights'], ...
                        ['Variant result "%s" for robust plan "%s" has no ' ...
                         'optimized resultGUI.w before %s.'], ...
                        char(result.variantId),char(planConfig.id), ...
                        char(purpose));
                end
            end
        end

        function assertTextField(result,fieldName,robustData,resultIx,purpose)
            if ~isfield(result,fieldName) || isempty(result.(fieldName))
                error(['planWorkflow:results:VariantResults:' ...
                    'IncompleteVariantResult'], ...
                    ['Variant result %d for robust plan "%s" is missing ' ...
                     'field "%s" before %s.'], ...
                    resultIx, ...
                    planWorkflow.results.VariantResults.planLabel( ...
                    robustData),fieldName,char(purpose));
            end
        end

        function label = planLabel(robustData)
            label = '<unknown>';
            if isstruct(robustData) && isfield(robustData,'planConfig') && ...
                    isfield(robustData.planConfig,'id') && ...
                    ~isempty(robustData.planConfig.id)
                label = char(robustData.planConfig.id);
            end
        end
    end
end
