classdef WorkflowIdentity
    % WorkflowIdentity Builds stable aggregate workflow result identity.

    methods (Static)
        function identity = fromRunConfig(runConfig)
            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            robustPlans = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);

            identity = struct();
            identity.reference = ...
                planWorkflow.results.WorkflowIdentity.referenceMetadata( ...
                reference);
            identity.robustPlans = ...
                planWorkflow.results.WorkflowIdentity.robustPlanMetadata( ...
                robustPlans);
            identity.robustPlanCount = numel(robustPlans);
            identity.robustVariantCount = ...
                planWorkflow.results.WorkflowIdentity.variantCount( ...
                robustPlans);
            identity.hash = ...
                planWorkflow.results.WorkflowIdentity.shortHash( ...
                struct('reference',identity.reference, ...
                'robustPlans',identity.robustPlans));

            if isempty(robustPlans)
                defaultScenario = ...
                    planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                    planWorkflow.config.RobustPlanConfig.defaultScenario( ...
                    'wcScen'));
                identity.robustPathLabel = 'none';
                identity.robustScenarioPathLabel = 'robust_none';
                identity.robustShiftLabel = ...
                    planWorkflow.results.WorkflowIdentity.resolutionLabel( ...
                    defaultScenario.shiftSD);
            elseif numel(robustPlans) == 1
                scenario = ...
                    planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                    robustPlans(1).scenario);
                identity.robustPathLabel = ...
                    planWorkflow.results.WorkflowIdentity.hashedLabel( ...
                    planWorkflow.config.RobustPlanConfig.pathLabel( ...
                    robustPlans),identity.hash);
                identity.robustScenarioPathLabel = ...
                    planWorkflow.results.WorkflowIdentity.hashedLabel( ...
                    ['robust_' char(scenario.scen_mode)], ...
                    identity.hash);
                identity.robustShiftLabel = ...
                    planWorkflow.results.WorkflowIdentity.hashedLabel( ...
                    planWorkflow.results.WorkflowIdentity.resolutionLabel( ...
                    scenario.shiftSD),identity.hash);
            else
                identity.robustPathLabel = ...
                    ['robust_multi_' identity.hash];
                identity.robustScenarioPathLabel = ...
                    ['robust_multi_' identity.hash];
                identity.robustShiftLabel = ...
                    ['multi_shift_' identity.hash];
            end
        end

        function path = rootPath(runConfig)
            identity = planWorkflow.results.WorkflowIdentity.fromRunConfig( ...
                runConfig);
            referenceScenarioConfig = ...
                planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig).scenario);
            rootFolder = fullfile(runConfig.radiationMode, ...
                runConfig.description,runConfig.caseID, ...
                runConfig.workflowType,identity.robustPathLabel, ...
                runConfig.plan_template,runConfig.plan_beams, ...
                identity.robustShiftLabel, ...
                ['ref_' referenceScenarioConfig.scen_mode], ...
                identity.robustScenarioPathLabel,runConfig.runId);
            path = fullfile(runConfig.outputRootPath,rootFolder);
        end

        function metadata = referenceMetadata(reference)
            scenario = ...
                planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                reference.scenario);
            metadata = struct();
            metadata.label = char(reference.label);
            metadata.robustnessMode = char(reference.robustnessMode);
            metadata.scenario = ...
                planWorkflow.config.ScenarioSpec.basisMetadata(scenario);
            metadata.scenarioMode = char(scenario.scen_mode);
            metadata.optimization4D = reference.optimization4D;
            metadata.robustnessOptions = reference.robustnessOptions;
        end

        function metadata = robustPlanMetadata(plans)
            metadata = repmat(struct( ...
                'id','', ...
                'label','', ...
                'objectiveSetName','', ...
                'robustnessMode','', ...
                'hasNominalObjectives',false, ...
                'scenario',struct(), ...
                'scenarioMode','', ...
                'optimization4D',struct(), ...
                'robustnessOptions',struct(), ...
                'variants', ...
                planWorkflow.results.WorkflowIdentity.variantMetadata( ...
                planWorkflow.config.RobustPlanConfig.defaultPlan()), ...
                'variantCount',0),1,0);
            for planIx = 1:numel(plans)
                scenario = ...
                    planWorkflow.config.RobustPlanConfig.matRadScenario( ...
                    plans(planIx).scenario);
                metadata(planIx).id = char(plans(planIx).id);
                metadata(planIx).label = char(plans(planIx).label);
                metadata(planIx).objectiveSetName = ...
                    char(plans(planIx).objectiveSetName);
                metadata(planIx).robustnessMode = ...
                    char(plans(planIx).robustnessMode);
                metadata(planIx).hasNominalObjectives = ...
                    logical(plans(planIx).hasNominalObjectives);
                metadata(planIx).scenario = ...
                    planWorkflow.config.ScenarioSpec.basisMetadata( ...
                    scenario);
                metadata(planIx).scenarioMode = char(scenario.scen_mode);
                metadata(planIx).optimization4D = ...
                    plans(planIx).optimization4D;
                metadata(planIx).robustnessOptions = ...
                    plans(planIx).robustnessOptions;
                metadata(planIx).variants = ...
                    planWorkflow.results.WorkflowIdentity.variantMetadata( ...
                    plans(planIx));
                metadata(planIx).variantCount = ...
                    planWorkflow.config.RobustPlanConfig.variantWithPenaltyCount( ...
                    plans(planIx));
            end
        end

        function metadata = variantMetadata(plan)
            variantTemplate = struct( ...
                'id','', ...
                'label','', ...
                'parameters',struct());
            metadata = repmat(variantTemplate,1,0);
            if ~isstruct(plan)
                return;
            end

            variants = ...
                planWorkflow.config.RobustPlanConfig.variantsWithPenalties( ...
                plan);
            if isempty(variants)
                return;
            end
            parameterFields = ...
                planWorkflow.config.RobustStrategySpec.variantParameterFields( ...
                plan.robustnessMode);
            for variantIx = 1:numel(variants)
                variant = variants(variantIx);
                metadata(variantIx) = variantTemplate; %#ok<AGROW>
                metadata(variantIx).id = char(variant.id);
                metadata(variantIx).label = char(variant.label);
                parameters = struct();
                for fieldIx = 1:numel(parameterFields)
                    fieldName = parameterFields{fieldIx};
                    if isfield(variant,fieldName)
                        parameters.(fieldName) = variant.(fieldName);
                    end
                end
                penaltyValues = ...
                    planWorkflow.templates.ObjectivePenaltyVariants.penaltyValues( ...
                    variant);
                if ~isempty(penaltyValues)
                    parameters.penalties = penaltyValues;
                end
                metadata(variantIx).parameters = parameters;
            end
        end

        function count = variantCount(plans)
            count = 0;
            for planIx = 1:numel(plans)
                count = count + ...
                    planWorkflow.config.RobustPlanConfig.variantWithPenaltyCount( ...
                    plans(planIx));
            end
        end

        function label = resolutionLabel(values)
            values = values(:)';
            if numel(values) < 3
                values(end + 1:3) = 0;
            end
            label = sprintf('%gx%gx%g',values(1),values(2),values(3));
        end

        function label = hashedLabel(prefix,hash)
            label = [char(prefix) '_' char(hash)];
        end

        function hash = shortHash(value)
            text = jsonencode( ...
                planWorkflow.results.WorkflowIdentity.canonicalize(value));
            digest = java.security.MessageDigest.getInstance('SHA-256');
            digest.update(uint8(char(text)));
            bytes = typecast(digest.digest(),'uint8');
            hash = lower(sprintf('%02X',bytes(1:6)));
        end
    end

    methods (Static, Access = private)
        function value = canonicalize(value)
            if isstruct(value)
                for elementIx = 1:numel(value)
                    fields = fieldnames(value(elementIx));
                    for fieldIx = 1:numel(fields)
                        fieldName = fields{fieldIx};
                        value(elementIx).(fieldName) = ...
                            planWorkflow.results.WorkflowIdentity.canonicalize( ...
                            value(elementIx).(fieldName));
                    end
                end
                value = orderfields(value);
            elseif iscell(value)
                for i = 1:numel(value)
                    value{i} = ...
                        planWorkflow.results.WorkflowIdentity.canonicalize( ...
                        value{i});
                end
            end
        end
    end
end
