classdef ClinicalEndpointTableModel
    % ClinicalEndpointTableModel Converts evaluated endpoints to GUI rows.

    methods (Static)
        function columns = columnNames()
            columns = {'Structure','Metric','Mean','UncertHW','Min','Max', ...
                'Delta','Goal','PoR','Unit'};
        end

        function rows = rows(planResults,runConfig,referencePlanResults)
            if nargin < 3
                referencePlanResults = [];
            end

            rows = {};
            if ~isstruct(planResults) || ~isfield(planResults,'cstStat')
                return;
            end

            context = ...
                planWorkflow.analysis.PlanEvaluationContext.fromPlanResults( ...
                planResults);
            endpoints = ...
                planWorkflow.analysis.EndpointStructureContract.endpoints( ...
                runConfig,context.endpointQuantity);
            if isempty(endpoints)
                return;
            end

            endpointRows = ...
                planWorkflow.analysis.ClinicalEndpointEvaluator.evaluatePlan( ...
                planResults,endpoints,referencePlanResults);
            for rowIx = 1:numel(endpointRows)
                rows(end + 1,:) = { ...
                    endpointRows(rowIx).structure, ...
                    endpointRows(rowIx).metric, ...
                    endpointRows(rowIx).mean, ...
                    endpointRows(rowIx).uncertaintyHalfWidth, ...
                    endpointRows(rowIx).min, ...
                    endpointRows(rowIx).max, ...
                    endpointRows(rowIx).deltaFromReference, ...
                    endpointRows(rowIx).goal, ...
                    endpointRows(rowIx).por, ...
                    endpointRows(rowIx).unit}; %#ok<AGROW>
            end
        end
    end
end
