classdef HelpText
    % HelpText Shared GUI help copy for editor panels and reports.

    methods (Static)
        function text = parameter(fieldName)
            switch char(fieldName)
                case 'referencePlanLabel'
                    text = ['Display name appended to the Reference tab ' ...
                        'title and exported macro, e.g. Nominal renders ' ...
                        'as Reference (Nominal).'];
                case 'planLabel'
                    text = ['Display name for this robust plan in the ' ...
                        'workflow, exported macro, progress output, and ' ...
                        'result labels.'];
                case 'robustness'
                    text = ['Selects the robustness strategy used for ' ...
                        'precomputed dose influence data.'];
                case 'scen_mode'
                    text = ['Selects the uncertainty scenario model used ' ...
                        'to compute dose influence data.'];
                case 'p1'
                    text = ['First scenario rank included in the c-COWC ' ...
                        'cheap-minimax aggregation. Must be a positive ' ...
                        'integer and no larger than p2.'];
                case 'p2'
                    text = ['Last scenario rank included in the c-COWC ' ...
                        'cheap-minimax aggregation. Must be a positive ' ...
                        'integer and within the available optimization ' ...
                        'scenarios.'];
                case 'theta1'
                    text = ['Target interval weight for Bertoluzza ' ...
                        'INTERVAL2/INTERVAL3 objectives. Larger values ' ...
                        'put more emphasis on interval uncertainty.'];
                case 'theta2'
                    text = ['OAR interval radius weight for INTERVAL3 ' ...
                        'objectives. Larger values increase the OAR ' ...
                        'uncertainty contribution.'];
                case 'radiusMode'
                    text = ['Interval radius construction. std uses the ' ...
                        'weighted scenario covariance model; extreme uses ' ...
                        'the largest element-wise scenario deviation from ' ...
                        'the weighted mean.'];
                case 'KMode'
                    text = ['INTERVAL3 OAR radius factor truncation mode ' ...
                        'for std radius mode. Dynamic uses the retention ' ...
                        'threshold; static keeps up to KMax components.'];
                case 'kmax'
                    text = ['Maximum number of retained INTERVAL3 OAR ' ...
                        'radius factor components in std radius mode.'];
                case 'retentionThreshold'
                    text = ['Cumulative retention threshold used by ' ...
                        'dynamic INTERVAL3 OAR radius factor truncation ' ...
                        'in std radius mode.'];
                case 'doseResolution'
                    text = ['Sets the dose calculation grid resolution ' ...
                        'in millimeters for x, y, and z.'];
                case 'hlutFileName'
                    text = ['Selects the Hounsfield lookup table used to ' ...
                        'convert CT values into material and density ' ...
                        'information.'];
                case 'quantityOpt'
                    text = ['Selects the optimization dose quantity supported ' ...
                        'by the current radiation mode and radiobiological ' ...
                        'model. Optimization uses this quantity; clinical ' ...
                        'endpoints use the matRad visual quantity below.'];
                case 'bioOpt'
                    text = ['Read-only matRad bioOpt flag derived from the ' ...
                        'selected radiation mode, radiobiological model, ' ...
                        'and optimization quantity.'];
                case 'quantityVis'
                    text = ['Read-only matRad visual dose quantity used for ' ...
                        'DVH display and clinical endpoint filtering.'];
                case 'plan_template'
                    text = ['Selects the treatment plan template for the ' ...
                        'current description, including beams, ' ...
                        'structures, objectives, and dose pulling setup.'];
                case 'useCache'
                    text = 'Loads cached dose influence data when available.';
                case 'writeCache'
                    text = ['Writes computed dose influence data to cache ' ...
                        'for later runs.'];
                case 'robustPlans'
                    text = ['JSON array of robust plans. Each plan defines ' ...
                        'id, label, objectiveSetName, strategy, scenario, ' ...
                        'robustnessOptions, and variants for p/theta sweeps.'];
                case 'sampling_linkToOptimization'
                    text = ['Uses the same patient case and acquisition ' ...
                        'settings as the optimized plan.'];
                case 'sampling_scen_mode'
                    text = ['Selects the uncertainty scenario model used ' ...
                        'to generate sampling cases.'];
                case 'ctActive'
                    text = 'Uses all available CT scenarios in the scenario model.';
                case 'ctReferenceScenId'
                    text = ['Selects the single CT scenario id used when ' ...
                        'CT scenarios are inactive.'];
                case 'ctScenProb'
                    text = ['Optional probability vector for active CT ' ...
                        'scenarios. Leave empty to use uniform ' ...
                        'probabilities; otherwise provide one value per ' ...
                        'CT scenario and make the values sum to 1.'];
                case 'setupActive'
                    text = ['Enables setup-shift uncertainty components ' ...
                        'for scenario generation.'];
                case 'rangeActive'
                    text = 'Enables range uncertainty components for scenario generation.';
                case 'gantryActive'
                    text = ['Enables per-beam gantry angle uncertainty ' ...
                        'components for random scenario generation.'];
                case 'couchActive'
                    text = ['Enables per-beam couch angle uncertainty ' ...
                        'components for random scenario generation.'];
                case 'gantryAngleSD'
                    text = ['Standard deviation in degrees for active ' ...
                        'gantry angle uncertainty components.'];
                case 'couchAngleSD'
                    text = ['Standard deviation in degrees for active ' ...
                        'couch angle uncertainty components.'];
                case 'randomSeed'
                    text = ['Optional non-negative integer seed for ' ...
                        'reproducible random scenario generation. Leave ' ...
                        'empty to use matRad default random behavior.'];
                case 'robustnessTargetMode'
                    text = ['Controls whether robustness analysis uses all ' ...
                        'target structures or only selected targets.'];
	                case 'robustnessTargets'
	                    text = ['Select target structures included in ' ...
	                        'robustness analysis when the target mode is ' ...
	                        'selected.'];
	                case 'endpointsFile'
	                    text = ['Selects a clinical endpoint JSON file ' ...
	                        'compatible with the current visual dose ' ...
	                        'quantity. Leave none to use only inline ' ...
	                        'endpoints or description defaults.'];
                case 'dose_pulling1'
                    text = ['Enables reference dose pulling before robust ' ...
                        'optimization, using the selected targets, ' ...
                        'criteria, limits, and start iteration.'];
                case 'dose_pulling1_target'
                    text = ['Target structures evaluated for channel 1. ' ...
                        'Each target is matched against the criterion at ' ...
                        'the same position.'];
                case 'dose_pulling1_criteria'
                    text = ['Quality indicator criteria evaluated for ' ...
                        'channel 1, for example COV1.'];
                case 'dose_pulling1_limit'
                    text = ['Minimum accepted channel 1 criterion values. ' ...
                        'Dose pulling minimizes target shortfall against ' ...
                        'these limits.'];
                case 'dose_pulling1_start'
                    text = ['Initial channel 1 pull step applied before ' ...
                        'searching or threshold iteration begins.'];
                case 'dose_pulling2'
                    text = ['Enables robust dose pulling after robust data ' ...
                        'is available, using the selected criterion, ' ...
                        'limit, and start iteration.'];
                case 'dose_pulling2_target'
                    text = ['Target structures evaluated for channel 2 ' ...
                        'across robust variants.'];
                case 'dose_pulling2_criteria'
                    text = ['Robust aggregate used for channel 2, normally ' ...
                        'meanQiTarget or minQiTarget.'];
                case 'dose_pulling2_limit'
                    text = ['Minimum accepted channel 2 robust criterion ' ...
                        'value.'];
                case 'dose_pulling2_start'
                    text = ['Initial channel 2 pull step applied before ' ...
                        'searching or threshold iteration begins.'];
                case 'dose_pulling_max_iter'
                    text = ['Maximum dose-pulling step evaluated by ' ...
                        'Threshold or heuristic search.'];
                case 'dose_pulling_strategy'
                    text = ['Selects Threshold or heuristicMultiObjective ' ...
                        'dose-pulling step selection.'];
                case 'dose_pulling_search_schedule'
                    text = ['Selects the heuristic probe schedule. Only ' ...
                        'exponential is currently supported.'];
                case 'dose_pulling_local_window'
                    text = ['Strict local search radius around the best ' ...
                        'coarse heuristic step.'];
                case 'dose_pulling_patience'
                    text = ['Stops coarse heuristic probing after this many ' ...
                        'probes without primary-score improvement.'];
                case 'dose_pulling_target_tol'
                    text = ['Tolerance for treating target shortfall as ' ...
                        'satisfied during heuristic selection.'];
                case 'dose_pulling_selection_policy'
                    text = ['Selects how candidate steps balance target ' ...
                        'shortfall, OAR dose score, and step count.'];
                case 'dose_pulling_target_weight'
                    text = ['WeightedSum target-shortfall weight used by ' ...
                        'heuristic dose pulling.'];
                case 'dose_pulling_oar_weight'
                    text = ['WeightedSum OAR-score weight used by ' ...
                        'heuristic dose pulling.'];
                case 'dose_pulling_step_weight'
                    text = ['WeightedSum step-count weight used by ' ...
                        'heuristic dose pulling.'];
                case 'dose_pulling_max_vmax_percent'
                    text = ['Rejects candidates whose dose-pulling OAR ' ...
                        'MaxDVH vMaxPercent exceeds this value.'];
                case 'dose_pulling_use_warm_start'
                    text = ['Uses the previous candidate fluence weights ' ...
                        'as the next optimization start point.'];
                otherwise
                    text = '';
            end
        end

        function text = structure(topic)
            switch char(topic)
                case 'Operation'
                    text = ['Operation: use boolean expressions with base ' ...
                        'structures, e.g. CTV+PTV or PTV-CTV.'];
                case 'Margins mm'
                    text = ['Margins mm: rings use [inner outer] margins ' ...
                        'in millimeters, e.g. [0 20].'];
                otherwise
                    text = '';
            end
        end

        function text = objective(topic)
            switch char(topic)
                case 'Parameters JSON'
                    text = ['Parameters JSON: named matRad objective ' ...
                        'parameters, for example ' ...
                        '{"penalty":2,"dRef":60,"vMaxPercent":0}.'];
                case 'DosePulling JSON'
                    text = ['DosePulling JSON: optional channel and rate ' ...
                        'configuration, for example ' ...
                        '{"channel":"dose_pulling_1","rates":' ...
                        '{"vMaxPercent":0.375}}.'];
                otherwise
                    text = '';
            end
        end
    end
end
