classdef MacroRunnerFrame
    % MacroRunnerFrame Owns the planWorkflow macro runner widgets.

    methods (Static)
        function frame = create(options,callbacks)
            if nargin < 1
                options = struct();
            end
            if nargin < 2
                callbacks = struct();
            end

            fig = figure('Name','Plan workflow macro runner', ...
                'NumberTitle','off','MenuBar','none','ToolBar','none', ...
                'WindowStyle',planWorkflow.gui.EditorChrome.editorWindowStyle(), ...
                'Color',[0.94 0.94 0.94], ...
                'Position',[140 110 1120 760], ...
                'CloseRequestFcn', ...
                planWorkflow.gui.MacroRunnerFrame.callback(callbacks,'close'));

            tabGroup = uitabgroup('Parent',fig,'Units','normalized', ...
                'Position',[0.02 0.20 0.96 0.76]);
            frame.macroTab = uitab(tabGroup,'Title','Macro');
            frame.specTab = uitab(tabGroup,'Title','Spec');
            frame.optionsTab = uitab(tabGroup,'Title','Options');
            frame.resultsTab = [];
            frame.resultGroup = [];

            frame = planWorkflow.gui.MacroRunnerFrame.addMacroTab( ...
                frame,callbacks);
            frame = planWorkflow.gui.MacroRunnerFrame.addSpecTab(frame);
            frame = planWorkflow.gui.MacroRunnerFrame.addOptionsTab( ...
                frame,callbacks);
            frame = planWorkflow.gui.MacroRunnerFrame.addFooter( ...
                frame,fig,tabGroup,callbacks);

            frame.fig = fig;
            frame.tabGroup = tabGroup;

            if isfield(options,'macroFolder') && ~isempty(options.macroFolder)
                set(frame.folderEdit,'String',char(options.macroFolder));
            end
        end

        function frame = showResultsTab(frame,titleText,rows)
            frame = planWorkflow.gui.MacroRunnerFrame.deleteResultsTab(frame);
            frame.resultsTab = uitab(frame.tabGroup,'Title','Results');
            frame.resultGroup = uitabgroup('Parent',frame.resultsTab, ...
                'Units','normalized','Position',[0.02 0.10 0.96 0.87]);
            tab = uitab(frame.resultGroup,'Title',titleText);
            panel = planWorkflow.gui.MacroRunnerFrame.createReadOnlyPanel( ...
                tab,'planWorkflowMacroResultsPanel');
            planWorkflow.gui.MacroRunnerFrame.addPanelRows(panel,rows);
            try
                set(frame.tabGroup,'SelectedTab',frame.resultsTab);
            catch
            end
        end

        function frame = deleteResultsTab(frame)
            if isfield(frame,'resultsTab') && ~isempty(frame.resultsTab) && ...
                    ishandle(frame.resultsTab)
                delete(frame.resultsTab);
            end
            frame.resultsTab = [];
            frame.resultGroup = [];
        end
    end

    methods (Static, Access = private)
        function frame = addMacroTab(frame,callbacks)
            tab = frame.macroTab;
            uicontrol('Parent',tab,'Style','text','String','Macro folder', ...
                'Units','normalized','Position',[0.03 0.90 0.14 0.05], ...
                'HorizontalAlignment','left','FontWeight','bold');
            frame.folderEdit = uicontrol('Parent',tab,'Style','edit', ...
                'String','','Units','normalized', ...
                'Position',[0.17 0.90 0.58 0.05], ...
                'HorizontalAlignment','left','BackgroundColor',[1 1 1], ...
                'Callback', ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'folderChanged'));
            frame.browseFolderButton = uicontrol('Parent',tab, ...
                'Style','pushbutton','String','Browse', ...
                'Units','normalized','Position',[0.77 0.90 0.09 0.05], ...
                'Callback', ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'browseFolder'));
            frame.refreshButton = uicontrol('Parent',tab, ...
                'Style','pushbutton','String','Refresh', ...
                'Units','normalized','Position',[0.88 0.90 0.09 0.05], ...
                'Callback', ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'refresh'));

            uicontrol('Parent',tab,'Style','text','String','Search', ...
                'Units','normalized','Position',[0.03 0.83 0.14 0.05], ...
                'HorizontalAlignment','left');
            frame.searchEdit = uicontrol('Parent',tab,'Style','edit', ...
                'String','','Units','normalized', ...
                'Position',[0.17 0.83 0.69 0.05], ...
                'HorizontalAlignment','left','BackgroundColor',[1 1 1], ...
                'Callback', ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'searchChanged'), ...
                'KeyReleaseFcn', ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'searchChanged'));
            frame.clearSearchButton = uicontrol('Parent',tab, ...
                'Style','pushbutton','String','Clear search', ...
                'Units','normalized','Position',[0.88 0.83 0.09 0.05], ...
                'Callback', ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'clearSearch'));

            uicontrol('Parent',tab,'Style','text','String','Selected macro', ...
                'Units','normalized','Position',[0.03 0.07 0.14 0.05], ...
                'HorizontalAlignment','left');
            frame.selectedFileEdit = uicontrol('Parent',tab,'Style','edit', ...
                'String','','Units','normalized', ...
                'Position',[0.17 0.07 0.69 0.05], ...
                'HorizontalAlignment','left','Enable','inactive', ...
                'BackgroundColor',[1 1 1]);
            frame.selectFileButton = uicontrol('Parent',tab, ...
                'Style','pushbutton','String','Select file', ...
                'Units','normalized','Position',[0.88 0.07 0.09 0.05], ...
                'Callback', ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'selectFile'));

            frame.macroTable = uitable('Parent',tab,'Units','normalized', ...
                'Position',[0.03 0.16 0.94 0.63], ...
                'ColumnName',{'#','Function','Folder'}, ...
                'ColumnEditable',[false false false], ...
                'ColumnWidth',{45 260 620}, ...
                'Data',{}, ...
                'CellSelectionCallback', ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'macroSelected'));
        end

        function frame = addSpecTab(frame)
            tab = frame.specTab;
            uicontrol('Parent',tab,'Style','text','String','Macro metadata', ...
                'Units','normalized','Position',[0.03 0.90 0.30 0.05], ...
                'FontWeight','bold','HorizontalAlignment','left');
            frame.specTable = uitable('Parent',tab,'Units','normalized', ...
                'Position',[0.03 0.07 0.94 0.80], ...
                'ColumnName',{'Field','Value'}, ...
                'ColumnEditable',[false false], ...
                'ColumnWidth',{180 720}, ...
                'Data',{});
        end

        function frame = addOptionsTab(frame,callbacks)
            tab = frame.optionsTab;
            panel = planWorkflow.gui.MacroRunnerFrame.createParameterPanel( ...
                tab,'planWorkflowMacroOptionsPanel');
            y = 0.93;

            [~,rowHeight] = planWorkflow.gui.MacroRunnerFrame.addSectionRow( ...
                panel,y,'Execution options');
            y = y - planWorkflow.gui.MacroRunnerFrame.parameterRowStride( ...
                rowHeight,true);
            [frame.caseIdEdit,rowHeight] = ...
                planWorkflow.gui.MacroRunnerFrame.addEditRow( ...
                panel,y,'Case ID','',[], ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'optionsChanged'));
            y = y - planWorkflow.gui.MacroRunnerFrame.parameterRowStride( ...
                rowHeight,false);
            [frame.profilePopup,rowHeight] = ...
                planWorkflow.gui.MacroRunnerFrame.addPopupRow( ...
                panel,y,'Profile',{'prod','testing'}, ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'optionsChanged'));
            y = y - planWorkflow.gui.MacroRunnerFrame.parameterRowStride( ...
                rowHeight,false);
            [frame.rootPathEdit,rowHeight,frame.browseRootButton] = ...
                planWorkflow.gui.MacroRunnerFrame.addEditRow( ...
                panel,y,'Root path','','Browse', ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'browseRootPath'));
            y = y - planWorkflow.gui.MacroRunnerFrame.parameterRowStride( ...
                rowHeight,false);
            [frame.cacheRootPathEdit,rowHeight,frame.browseCacheButton] = ...
                planWorkflow.gui.MacroRunnerFrame.addEditRow( ...
                panel,y,'Cache root path','','Browse', ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'browseCacheRootPath'));
            y = y - planWorkflow.gui.MacroRunnerFrame.parameterRowStride( ...
                rowHeight,false);
            [frame.openGuiCheckbox,~] = ...
                planWorkflow.gui.MacroRunnerFrame.addCheckboxRow( ...
                panel,y,'Open workflow GUI',true, ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'optionsChanged'));
        end

        function frame = addFooter(frame,fig,tabGroup,callbacks)
            footerLayout = planWorkflow.gui.EditorChrome.footerLayout();
            statusText = uicontrol('Parent',fig,'Style','text', ...
                'String','0%  Ready to run macro.', ...
                'HorizontalAlignment','left','Units','normalized', ...
                'Position',footerLayout.statusText);
            progressBar = uipanel('Parent',fig,'Units','normalized', ...
                'Position',footerLayout.progressBar, ...
                'BorderType','line','BackgroundColor',[1 1 1]);
            progressFill = uipanel('Parent',progressBar, ...
                'Units','normalized','Position',[0 0 0 1], ...
                'BorderType','none','BackgroundColor',[0.18 0.45 0.75]);
            progressDetails = uicontrol('Parent',fig,'Style','listbox', ...
                'String',{},'Units','normalized', ...
                'Position',footerLayout.progressDetails, ...
                'BackgroundColor',[1 1 1]);

            frame.openFolderButton = uicontrol('Parent',fig, ...
                'Style','pushbutton','String','Open folder', ...
                'Units','normalized','Position',footerLayout.exportButton, ...
                'Callback', ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'openFolder'));
            frame.validateButton = uicontrol('Parent',fig, ...
                'Style','pushbutton','String','Validate', ...
                'Units','normalized','Position',footerLayout.calculateButton, ...
                'Callback', ...
                planWorkflow.gui.MacroRunnerFrame.callback( ...
                callbacks,'validate'));
            frame.runButton = uicontrol('Parent',fig, ...
                'Style','pushbutton','String','Run', ...
                'Units','normalized','Position',footerLayout.stopButton, ...
                'BackgroundColor',[21 128 61] / 255, ...
                'ForegroundColor',[1 1 1], ...
                'Callback', ...
                planWorkflow.gui.MacroRunnerFrame.callback(callbacks,'run'));
            frame.closeButton = uicontrol('Parent',fig,'Style','pushbutton', ...
                'String','Close','Units','normalized', ...
                'Position',footerLayout.cancelButton, ...
                'Callback', ...
                planWorkflow.gui.MacroRunnerFrame.callback(callbacks,'close'));
            frame.progressReporter = planWorkflow.gui.PlanProgressReporter( ...
                fig,progressFill,statusText,progressDetails,[],tabGroup);
            frame.progressReporter.ready();
        end

        function callback = callback(callbacks,name)
            if isstruct(callbacks) && isfield(callbacks,name) && ...
                    isa(callbacks.(name),'function_handle')
                callback = callbacks.(name);
            else
                callback = @(~,~) [];
            end
        end

        function panel = createParameterPanel(parent,tag)
            panel = uipanel('Parent',parent,'Units','normalized', ...
                'Position',[0.03 0.05 0.94 0.90], ...
                'BorderType','line','BackgroundColor',[1 1 1], ...
                'Tag',tag);
        end

        function [control,rowHeight,button] = addEditRow(panel,y,label, ...
                value,buttonText,callback)
            rowHeight = planWorkflow.gui.ParameterPanelLayout.controlHeight();
            planWorkflow.gui.MacroRunnerFrame.addParameterLabel( ...
                panel,y,label,rowHeight);
            width = 0.64;
            if ~isempty(buttonText)
                width = 0.52;
            end
            control = uicontrol('Parent',panel,'Style','edit', ...
                'String',char(value),'Units','normalized', ...
                'Position',[0.32 y width rowHeight], ...
                'HorizontalAlignment','left','BackgroundColor',[1 1 1], ...
                'Callback',callback);
            button = gobjects(0);
            if ~isempty(buttonText)
                button = uicontrol('Parent',panel,'Style','pushbutton', ...
                    'String',buttonText,'Units','normalized', ...
                    'Position',[0.86 y 0.10 rowHeight], ...
                    'Callback',callback);
            end
        end

        function [control,rowHeight] = addPopupRow(panel,y,label, ...
                values,callback)
            rowHeight = planWorkflow.gui.ParameterPanelLayout.controlHeight();
            planWorkflow.gui.MacroRunnerFrame.addParameterLabel( ...
                panel,y,label,rowHeight);
            control = uicontrol('Parent',panel,'Style','popupmenu', ...
                'String',values,'Units','normalized', ...
                'Position',[0.32 y 0.30 rowHeight], ...
                'BackgroundColor',[1 1 1], ...
                'Callback',callback);
        end

        function [control,rowHeight] = addCheckboxRow(panel,y,label, ...
                value,callback)
            rowHeight = planWorkflow.gui.ParameterPanelLayout.controlHeight();
            planWorkflow.gui.MacroRunnerFrame.addParameterLabel( ...
                panel,y,label,rowHeight);
            control = uicontrol('Parent',panel,'Style','checkbox', ...
                'String','','Units','normalized', ...
                'Position',[0.32 y 0.08 rowHeight], ...
                'BackgroundColor',[1 1 1], ...
                'Value',logical(value),'Callback',callback);
        end

        function [control,rowHeight] = addSectionRow(panel,y,label)
            rowHeight = planWorkflow.gui.ParameterPanelLayout.sectionHeight();
            control = uicontrol('Parent',panel,'Style','text', ...
                'String',char(label),'Units','normalized', ...
                'Position',[0.02 y 0.94 rowHeight], ...
                'HorizontalAlignment','left','FontWeight','bold', ...
                'BackgroundColor',[0.94 0.94 0.94]);
        end

        function labelControl = addParameterLabel(panel,y,label,rowHeight)
            labelControl = uicontrol('Parent',panel,'Style','text', ...
                'String',char(label),'Units','normalized', ...
                'Position',[0.02 y 0.27 rowHeight], ...
                'HorizontalAlignment','left','FontWeight','bold', ...
                'BackgroundColor',[1 1 1]);
        end

        function stride = parameterRowStride(rowHeight,isSection)
            if isSection
                stride = planWorkflow.gui.ParameterPanelLayout.sectionRowStride();
            else
                stride = max( ...
                    planWorkflow.gui.ParameterPanelLayout.baseRowStride(), ...
                    rowHeight + 0.013);
            end
        end

        function panel = createReadOnlyPanel(parent,tag)
            panel = uipanel('Parent',parent,'Units','normalized', ...
                'Position',[0.03 0.05 0.94 0.90], ...
                'BorderType','line','BackgroundColor',[1 1 1], ...
                'Tag',tag);
            planWorkflow.gui.PanelScroller.createSlider(panel);
        end

        function addPanelRows(panel,rows)
            rowControls = gobjects(0);
            y = 0.93;
            for i = 1:size(rows,1)
                [controls,rowHeight] = ...
                    planWorkflow.gui.MacroRunnerFrame.addPanelRow( ...
                    panel,i,y,rows{i,1},rows{i,2});
                rowControls = [rowControls controls(:)']; %#ok<AGROW>
                y = y - max(0.075,rowHeight + 0.020);
            end
            scrollSlider = planWorkflow.gui.PanelScroller.panelSlider(panel);
            if ~isempty(scrollSlider)
                planWorkflow.gui.PanelScroller.configure( ...
                    scrollSlider,rowControls,y);
            end
        end

        function [controls,rowHeight] = addPanelRow(panel,rowIndex,y, ...
                label,value)
            controlHeight = 0.050;
            rowHeight = controlHeight;
            labelControl = uicontrol('Parent',panel,'Style','text', ...
                'String',char(label),'Units','normalized', ...
                'Position',[0.02 y 0.27 controlHeight], ...
                'HorizontalAlignment','left','FontWeight','bold', ...
                'BackgroundColor',[1 1 1], ...
                'Tag',sprintf('planWorkflowMacroResultLabel%d',rowIndex));
            valueControl = uicontrol('Parent',panel,'Style','edit', ...
                'String',char(string(value)),'Units','normalized', ...
                'Position',[0.32 y 0.64 controlHeight], ...
                'HorizontalAlignment','left','Enable','inactive', ...
                'BackgroundColor',[1 1 1], ...
                'TooltipString',char(string(value)), ...
                'Tag',sprintf('planWorkflowMacroResultValue%d',rowIndex));
            controls = [labelControl valueControl];
        end
    end
end
