classdef ParameterPanelRenderer
    % ParameterPanelRenderer Owns editable parameter panel widgets/layout.

    methods (Static)
        function [tableHandle,templatePopup] = create(parent,position, ...
                specs,optionSets,selectedOptions,popupCallbacks)
            panel = uipanel('Parent',parent,'Units','normalized', ...
                'Position',position,'BorderType','line', ...
                'BackgroundColor',[1 1 1]);
            scrollSlider = planWorkflow.gui.PanelScroller.createSlider( ...
                panel);

            controlHeight = ...
                planWorkflow.gui.ParameterPanelLayout.controlHeight();
            rowCount = numel(specs);
            labels = gobjects(rowCount,1);
            notes = gobjects(rowCount,1);
            controls = gobjects(rowCount,1);
            templatePopup = gobjects(0);
            y = planWorkflow.gui.ParameterPanelRenderer.firstRowY();
            for i = 1:rowCount
                if planWorkflow.gui.ParameterPanelRenderer.isSectionSpec( ...
                        specs(i))
                    labels(i) = ...
                        planWorkflow.gui.ParameterPanelRenderer.createSectionRow( ...
                        panel,specs(i).name,y, ...
                        planWorkflow.gui.ParameterPanelLayout.controlHeightForType( ...
                        specs(i).type));
                    notes(i) = ...
                        planWorkflow.gui.ParameterPanelRenderer.createHiddenText( ...
                        panel);
                    controls(i) = ...
                        planWorkflow.gui.ParameterPanelRenderer.createHiddenText( ...
                        panel);
                    y = y - ...
                        planWorkflow.gui.ParameterPanelLayout.rowStride( ...
                        specs(i));
                    continue;
                end

                labels(i) = uicontrol('Parent',panel,'Style','text', ...
                    'String',specs(i).name,'Units','normalized', ...
                    'Position',[0.02 y 0.27 controlHeight], ...
                    'HorizontalAlignment','left', ...
                    'FontWeight','bold', ...
                    'BackgroundColor',[1 1 1]);
                notes(i) = ...
                    planWorkflow.gui.ParameterPanelRenderer.createHelpText( ...
                    panel,specs(i),y);
                [controls(i),templatePopup] = ...
                    planWorkflow.gui.ParameterPanelRenderer.createControl( ...
                    panel,specs(i),y,optionSets,selectedOptions, ...
                    popupCallbacks,templatePopup);
                y = y - ...
                    planWorkflow.gui.ParameterPanelLayout.rowStride( ...
                    specs(i));
            end

            tableHandle = struct();
            tableHandle.panel = panel;
            tableHandle.specs = specs;
            tableHandle.labels = labels;
            tableHandle.notes = notes;
            tableHandle.controls = controls;
            tableHandle.scrollSlider = scrollSlider;
            planWorkflow.gui.ParameterPanelRenderer.initializeVisibleFields( ...
                tableHandle);
            planWorkflow.gui.ParameterPanelRenderer.updateScroll(tableHandle,y);
            planWorkflow.gui.PanelScroller.bringToFront(scrollSlider);
        end

        function load(tableHandle,config,optionSets,selectedOptions)
            specs = tableHandle.specs;
            for i = 1:numel(specs)
                if planWorkflow.gui.ParameterPanelRenderer.isSectionSpec( ...
                        specs(i))
                    continue;
                end
                control = tableHandle.controls(i);
                fieldName = specs(i).field;
                if strcmp(get(control,'Style'),'listbox')
                    [labels,valueMap] = ...
                        planWorkflow.gui.ParameterPanelRenderer.optionLabelsAndValues( ...
                        optionSets,fieldName,specs(i));
                    selectedIx = ...
                        planWorkflow.gui.ParameterPanelRenderer.selectedMultiOptionIndices( ...
                        valueMap,config.(fieldName));
                    if isfield(selectedOptions,fieldName)
                        selectedIx = selectedOptions.(fieldName);
                    end
                    planWorkflow.gui.ParameterPanelRenderer.setControlIfChanged( ...
                        control,'String',labels,'Value',selectedIx);
                    planWorkflow.gui.ParameterPanelRenderer.storeOptionValueMap( ...
                        control,valueMap);
                elseif strcmp(get(control,'Style'),'popupmenu')
                    [labels,valueMap] = ...
                        planWorkflow.gui.ParameterPanelRenderer.optionLabelsAndValues( ...
                        optionSets,fieldName,specs(i));
                    selectedIx = ...
                        planWorkflow.gui.ParameterPanelRenderer.selectedOptionIndex( ...
                        valueMap,config.(fieldName));
                    if isfield(selectedOptions,fieldName)
                        selectedIx = selectedOptions.(fieldName);
                    end
                    if isempty(selectedIx)
                        selectedIx = 1;
                    end
                    planWorkflow.gui.ParameterPanelRenderer.setControlIfChanged( ...
                        control,'String',labels,'Value',selectedIx);
                    planWorkflow.gui.ParameterPanelRenderer.storeOptionValueMap( ...
                        control,valueMap);
                elseif strcmp(get(control,'Style'),'checkbox')
                    planWorkflow.gui.ParameterPanelRenderer.setControlIfChanged( ...
                        control,'Value',logical(config.(fieldName)));
                else
                    textValue = ...
                        planWorkflow.gui.OptionValues.valueToText( ...
                        config.(fieldName));
                    planWorkflow.gui.ParameterPanelRenderer.setControlIfChanged( ...
                        control,'String',textValue);
                end
            end
            planWorkflow.gui.ParameterPanelRenderer.refreshScroll(tableHandle);
        end

        function config = toConfig(config,tableHandle)
            config = planWorkflow.gui.ParameterPanelProjection.toConfig( ...
                config,tableHandle);
        end

        function controls = controls(tableHandles)
            controls = gobjects(0);
            for i = 1:numel(tableHandles)
                if isstruct(tableHandles(i)) && ...
                        isfield(tableHandles(i),'controls')
                    controls = [controls; ...
                        tableHandles(i).controls(:)]; %#ok<AGROW>
                end
            end
        end

        function value = fieldValue(tableHandle,fieldName)
            value = planWorkflow.gui.ParameterPanelProjection.fieldValue( ...
                tableHandle,fieldName);
        end

        function controlHandle = control(tableHandle,fieldName)
            fields = {tableHandle.specs.field};
            fieldIx = find(strcmp(fields,fieldName),1);
            if isempty(fieldIx)
                error('planWorkflow:gui:ParameterPanelRenderer:UnknownField', ...
                    'Parameter panel does not define field "%s".', ...
                    char(fieldName));
            end
            controlHandle = tableHandle.controls(fieldIx);
        end

        function setVisibleFields(tableHandle,visibleFields)
            y = planWorkflow.gui.ParameterPanelRenderer.firstRowY();
            planWorkflow.gui.ParameterPanelRenderer.storeVisibleFields( ...
                tableHandle,visibleFields);

            for i = 1:numel(tableHandle.specs)
                fieldName = tableHandle.specs(i).field;
                if any(strcmp(visibleFields,fieldName))
                    y = planWorkflow.gui.ParameterPanelRenderer.showRow( ...
                        tableHandle,i,y);
                else
                    planWorkflow.gui.ParameterPanelRenderer.hideRow( ...
                        tableHandle,i);
                end
            end
            planWorkflow.gui.ParameterPanelRenderer.updateScroll(tableHandle,y);
        end

        function setFieldHelpText(tableHandle,fieldName,helpText)
            overrides = ...
                planWorkflow.gui.ParameterPanelRenderer.helpOverrides( ...
                tableHandle);
            overrideField = matlab.lang.makeValidName(char(fieldName));
            overrides.(overrideField) = char(helpText);
            if isfield(tableHandle,'panel') && isgraphics(tableHandle.panel)
                setappdata(tableHandle.panel, ...
                    'planWorkflowHelpOverrides',overrides);
            end
            planWorkflow.gui.ParameterPanelRenderer.setVisibleFields( ...
                tableHandle, ...
                planWorkflow.gui.ParameterPanelRenderer.visibleFields( ...
                tableHandle));
        end

        function initializeVisibleFields(tableHandle)
            planWorkflow.gui.ParameterPanelProjection.initialize( ...
                tableHandle.panel,tableHandle.specs);
        end

        function fields = visibleFields(tableHandle)
            fields = planWorkflow.gui.ParameterPanelProjection.visibleFields( ...
                tableHandle.panel,tableHandle.specs);
        end

        function storeVisibleFields(tableHandle,visibleFields)
            planWorkflow.gui.ParameterPanelProjection.setVisibleFields( ...
                tableHandle.panel,visibleFields);
        end

        function updateScroll(tableHandle,contentBottomY)
            if ~isfield(tableHandle,'scrollSlider') || ...
                    ~ishandle(tableHandle.scrollSlider)
                return;
            end
            controls = [tableHandle.labels(:); tableHandle.notes(:); ...
                tableHandle.controls(:)];
            planWorkflow.gui.PanelScroller.configure( ...
                tableHandle.scrollSlider,controls,contentBottomY,true);
        end

        function refreshScroll(tableHandle)
            if ~isstruct(tableHandle) || ...
                    ~isfield(tableHandle,'scrollSlider') || ...
                    ~ishandle(tableHandle.scrollSlider)
                return;
            end
            planWorkflow.gui.PanelScroller.refresh(tableHandle.scrollSlider);
        end

        function scrollByWheel(tableHandle,scrollCount)
            if ~isstruct(tableHandle) || ...
                    ~isfield(tableHandle,'scrollSlider') || ...
                    ~ishandle(tableHandle.scrollSlider)
                return;
            end
            planWorkflow.gui.PanelScroller.scrollByWheel( ...
                tableHandle.scrollSlider,scrollCount);
        end
    end

    methods (Static, Access = private)
        function [control,templatePopup] = createControl(panel,spec,y, ...
                optionSets,selectedOptions,popupCallbacks,templatePopup)
            fieldName = spec.field;
            controlHeight = ...
                planWorkflow.gui.ParameterPanelLayout.controlHeight();
            switch planWorkflow.gui.ParameterPanelRenderer.controlKind(spec)
                case 'multiSelect'
                    [labels,valueMap] = ...
                        planWorkflow.gui.ParameterPanelRenderer.optionLabelsAndValues( ...
                        optionSets,fieldName,spec);
                    selectedIx = 1;
                    if isfield(selectedOptions,fieldName)
                        selectedIx = selectedOptions.(fieldName);
                    end
                    currentHeight = ...
                        planWorkflow.gui.ParameterPanelLayout.controlHeightForType( ...
                        spec.type);
                    control = uicontrol('Parent',panel, ...
                        'Style','listbox','String',labels, ...
                        'Min',0,'Max',2,'Value',selectedIx, ...
                        'Units','normalized', ...
                        'Position',[0.32 y - currentHeight + controlHeight ...
                        0.64 currentHeight]);
                    planWorkflow.gui.ParameterPanelRenderer.storeOptionValueMap( ...
                        control,valueMap);
                case 'selection'
                    [labels,valueMap] = ...
                        planWorkflow.gui.ParameterPanelRenderer.optionLabelsAndValues( ...
                        optionSets,fieldName,spec);
                    selectedIx = 1;
                    if isfield(selectedOptions,fieldName)
                        selectedIx = selectedOptions.(fieldName);
                    end
                    control = uicontrol('Parent',panel, ...
                        'Style','popupmenu','String',labels, ...
                        'Value',selectedIx,'Units','normalized', ...
                        'Position',[0.32 y 0.30 controlHeight]);
                    planWorkflow.gui.ParameterPanelRenderer.storeOptionValueMap( ...
                        control,valueMap);
                    if strcmp(fieldName,'plan_template')
                        templatePopup = control;
                    end
                case 'checkbox'
                    control = uicontrol('Parent',panel, ...
                        'Style','checkbox','String','', ...
                        'Units','normalized', ...
                        'Position',[0.32 y 0.08 controlHeight], ...
                        'BackgroundColor',[1 1 1]);
                case 'readOnly'
                    control = uicontrol('Parent',panel, ...
                        'Style','edit','Units','normalized', ...
                        'Position',[0.32 y 0.64 controlHeight], ...
                        'HorizontalAlignment','left', ...
                        'Enable','inactive', ...
                        'BackgroundColor',[0.95 0.95 0.95]);
                otherwise
                    control = uicontrol('Parent',panel, ...
                        'Style','edit','Units','normalized', ...
                        'Position',[0.32 y 0.64 controlHeight], ...
                        'HorizontalAlignment','left');
            end
            callback = ...
                planWorkflow.gui.ParameterPanelRenderer.controlCallback( ...
                popupCallbacks,fieldName);
            if ~isempty(callback)
                set(control,'Callback',callback);
            end
        end

        function callback = controlCallback(callbacks,fieldName)
            fieldCallback = [];
            defaultCallback = [];
            if isstruct(callbacks) && isfield(callbacks,fieldName)
                fieldCallback = callbacks.(fieldName);
            end
            if isstruct(callbacks) && isfield(callbacks,'defaultCallback')
                defaultCallback = callbacks.defaultCallback;
            end
            if isempty(fieldCallback) && isempty(defaultCallback)
                callback = [];
                return;
            end
            callback = @(source,event) ...
                planWorkflow.gui.ParameterPanelRenderer.runControlCallbacks( ...
                source,event,fieldCallback,defaultCallback);
        end

        function runControlCallbacks(source,event,fieldCallback, ...
                defaultCallback)
            if ~isempty(fieldCallback)
                fieldCallback(source,event);
            end
            if ~isempty(defaultCallback)
                defaultCallback(source,event);
            end
        end

        function control = createHelpText(panel,spec,y)
            helpText = planWorkflow.gui.ParameterPanelRenderer.specHelpText( ...
                spec);
            noteHeight = ...
                planWorkflow.gui.TextLayout.helpTextHeightForDisplay( ...
                helpText, ...
                planWorkflow.gui.TextLayout.parameterHelpTextWrapColumn());
            control = uicontrol('Parent',panel,'Style','text', ...
                'String',helpText, ...
                'Units','normalized', ...
                'Position',[0.02 y - noteHeight ...
                planWorkflow.gui.TextLayout.helpTextWidth() noteHeight], ...
                'HorizontalAlignment','left', ...
                'FontSize',planWorkflow.gui.TextLayout.helpTextFontSize(), ...
                'ForegroundColor',[0.35 0.35 0.35], ...
                'BackgroundColor',[1 1 1], ...
                'Visible', ...
                planWorkflow.gui.ParameterPanelRenderer.helpVisibleState( ...
                spec));
        end

        function y = showRow(tableHandle,rowIx,y)
            controlHeight = ...
                planWorkflow.gui.ParameterPanelLayout.controlHeight();
            spec = tableHandle.specs(rowIx);
            if planWorkflow.gui.ParameterPanelRenderer.isSectionSpec(spec)
                sectionHeight = ...
                    planWorkflow.gui.ParameterPanelLayout.controlHeightForType( ...
                    spec.type);
            set(tableHandle.labels(rowIx),'Visible','on', ...
                    'Position',[0.02 y 0.94 sectionHeight]);
                set(tableHandle.notes(rowIx),'Visible','off');
                set(tableHandle.controls(rowIx),'Visible','off');
                y = y - planWorkflow.gui.ParameterPanelLayout.rowStride( ...
                    spec);
                return;
            end

            currentHeight = ...
                planWorkflow.gui.ParameterPanelLayout.controlHeightForType( ...
                spec.type);
            set(tableHandle.labels(rowIx),'Visible','on', ...
                'Position',[0.02 y 0.27 controlHeight]);
            helpText = planWorkflow.gui.ParameterPanelRenderer.fieldHelpText( ...
                tableHandle,spec);
            noteHeight = ...
                planWorkflow.gui.TextLayout.helpTextHeightForDisplay( ...
                helpText, ...
                planWorkflow.gui.TextLayout.parameterHelpTextWrapColumn());
            set(tableHandle.notes(rowIx), ...
                'Visible', ...
                planWorkflow.gui.ParameterPanelRenderer.helpVisibleState( ...
                helpText), ...
                'String',helpText, ...
                'Position',[0.02 y - noteHeight ...
                planWorkflow.gui.TextLayout.helpTextWidth() noteHeight]);
            controlPosition = ...
                planWorkflow.gui.ParameterPanelRenderer.controlPosition( ...
                get(tableHandle.controls(rowIx),'Style'), ...
                y,currentHeight,controlHeight);
            set(tableHandle.controls(rowIx),'Visible','on', ...
                'Position',controlPosition);
            y = y - planWorkflow.gui.ParameterPanelLayout.rowStride(spec);
        end

        function hideRow(tableHandle,rowIx)
            hiddenPosition = [0 0 0.001 0.001];
            set(tableHandle.labels(rowIx),'Visible','off', ...
                'Position',hiddenPosition);
            set(tableHandle.notes(rowIx),'Visible','off', ...
                'Position',hiddenPosition);
            set(tableHandle.controls(rowIx),'Visible','off', ...
                'Position',hiddenPosition);
        end

        function label = createSectionRow(panel,title,y,rowHeight)
            label = uicontrol('Parent',panel,'Style','text', ...
                'String',char(title),'Units','normalized', ...
                'Position',[0.02 y 0.94 rowHeight], ...
                'HorizontalAlignment','left', ...
                'FontWeight','bold', ...
                'ForegroundColor',[0.15 0.15 0.15], ...
                'BackgroundColor',[0.93 0.95 0.97]);
        end

        function handle = createHiddenText(parent)
            handle = uicontrol('Parent',parent,'Style','text', ...
                'String','','Units','normalized', ...
                'Position',[0 0 0.001 0.001], ...
                'Visible','off');
        end

        function position = controlPosition(controlStyle,y,currentHeight, ...
                controlHeight)
            switch char(controlStyle)
                case 'listbox'
                    position = [0.32 y - currentHeight + controlHeight ...
                        0.64 currentHeight];
                case 'popupmenu'
                    position = [0.32 y 0.30 controlHeight];
                case 'checkbox'
                    position = [0.32 y 0.08 controlHeight];
                otherwise
                    position = [0.32 y 0.64 controlHeight];
            end
        end

        function y = firstRowY()
            y = 0.94;
        end

        function text = fieldHelpText(tableHandle,spec)
            overrides = ...
                planWorkflow.gui.ParameterPanelRenderer.helpOverrides( ...
                tableHandle);
            overrideField = matlab.lang.makeValidName(char(spec.field));
            if isfield(overrides,overrideField)
                text = planWorkflow.gui.TextLayout.helpTextForDisplay( ...
                    overrides.(overrideField), ...
                    planWorkflow.gui.TextLayout.parameterHelpTextWrapColumn());
                return;
            end
            text = planWorkflow.gui.ParameterPanelRenderer.specHelpText( ...
                spec);
        end

        function text = specHelpText(spec)
            text = '';
            if isfield(spec,'helpText')
                text = planWorkflow.gui.TextLayout.helpTextForDisplay( ...
                    spec.helpText, ...
                    planWorkflow.gui.TextLayout.parameterHelpTextWrapColumn());
            end
        end

        function state = helpVisibleState(value)
            if planWorkflow.gui.ParameterPanelRenderer.hasHelpText(value)
                state = 'on';
            else
                state = 'off';
            end
        end

        function value = hasHelpText(input)
            if isstruct(input)
                value = isfield(input,'helpText') && ...
                    ~isempty(char(input.helpText));
            else
                value = ~isempty(char(input));
            end
        end

        function tf = isSectionSpec(spec)
            tf = isfield(spec,'type') && strcmp(spec.type,'section');
        end

        function kind = controlKind(spec)
            if isfield(spec,'controlKind') && ~isempty(spec.controlKind)
                kind = char(spec.controlKind);
                return;
            end
            kind = ...
                planWorkflow.gui.ParameterPanelSpecAdapter.defaultControlKind( ...
                spec.type);
        end

        function values = optionValues(optionSets,fieldName,spec)
            optionKey = fieldName;
            if isfield(spec,'optionsKey') && ~isempty(spec.optionsKey)
                optionKey = char(spec.optionsKey);
            end
            if ~isfield(optionSets,optionKey)
                error(['planWorkflow:gui:ParameterPanelRenderer:' ...
                    'MissingOptionSet'], ...
                    ['Parameter "%s" is declared as a %s control, but ' ...
                     'no option set "%s" was provided.'], ...
                    char(fieldName), ...
                    planWorkflow.gui.ParameterPanelRenderer.controlKind( ...
                    spec),char(optionKey));
            end
            values = optionSets.(optionKey);
        end

        function [labels,values] = optionLabelsAndValues( ...
                optionSets,fieldName,spec)
            rawOptions = ...
                planWorkflow.gui.ParameterPanelRenderer.optionValues( ...
                optionSets,fieldName,spec);
            if isstruct(rawOptions) && isfield(rawOptions,'labels') && ...
                    isfield(rawOptions,'values')
                labels = ...
                    planWorkflow.gui.OptionValues.normalizeCellOptionValues( ...
                    rawOptions.labels);
                values = ...
                    planWorkflow.gui.OptionValues.normalizeCellOptionValues( ...
                    rawOptions.values);
            else
                labels = ...
                    planWorkflow.gui.OptionValues.normalizeCellOptionValues( ...
                    rawOptions);
                values = labels;
            end
            if numel(labels) ~= numel(values)
                error(['planWorkflow:gui:ParameterPanelRenderer:' ...
                    'InvalidOptionSet'], ...
                    ['Option set for "%s" must define the same number ' ...
                     'of labels and values.'],char(fieldName));
            end
        end

        function overrides = helpOverrides(tableHandle)
            overrides = struct();
            if isstruct(tableHandle) && isfield(tableHandle,'panel') && ...
                    isgraphics(tableHandle.panel)
                value = getappdata(tableHandle.panel, ...
                    'planWorkflowHelpOverrides');
                if isstruct(value)
                    overrides = value;
                end
            end
        end

        function selectedIx = selectedOptionIndex(values,currentValue)
            currentText = ...
                    planWorkflow.gui.OptionValues.valueToText( ...
                    currentValue);
            selectedIx = find(strcmp(values,currentText),1);
        end

        function storeOptionValueMap(control,values)
            if isgraphics(control)
                setappdata(control,'planWorkflowOptionValues',values);
            end
        end

        function selectedIx = selectedMultiOptionIndices(values,currentValues)
            currentValues = ...
                    planWorkflow.gui.OptionValues.normalizeCellOptionValues( ...
                    currentValues);
            selectedIx = [];
            for i = 1:numel(currentValues)
                ix = find(strcmp(values,currentValues{i}),1);
                if ~isempty(ix)
                    selectedIx(end + 1) = ix; %#ok<AGROW>
                end
            end
        end

        function text = valueToText(value)
            text = planWorkflow.gui.OptionValues.valueToText(value);
        end

        function text = joinCellText(values)
            text = planWorkflow.gui.OptionValues.joinCellText(values);
        end

        function setControlIfChanged(control,varargin)
            shouldSet = false;
            for argIx = 1:2:numel(varargin)
                propertyName = varargin{argIx};
                newValue = varargin{argIx + 1};
                try
                    currentValue = get(control,propertyName);
                    if ~isequaln(currentValue,newValue)
                        shouldSet = true;
                        break;
                    end
                catch
                    shouldSet = true;
                    break;
                end
            end
            if shouldSet
                set(control,varargin{:});
            end
        end
    end
end
