classdef PerformanceTableModel
    % PerformanceTableModel Converts performance telemetry into GUI rows.

    methods (Static)
        function columns = stageColumnNames()
            columns = {'Stage','Status','Attempts','Start','End', ...
                'Wall time (s)','CPU time (s)','Process start (MB)', ...
                'Process end (MB)','Process delta (MB)', ...
                'Process max (MB)','Data start (MB)','Data end (MB)', ...
                'Data delta (MB)','Memory source'};
        end

        function columns = planColumnNames()
            columns = {'Stage','Role','Plan','Task','Variant','Status', ...
                'Start','End','Wall time (s)','CPU time (s)', ...
                'Process delta (MB)','Process max (MB)', ...
                'Data delta (MB)','Memory source','Detail JSON','Error'};
        end

        function rows = stageRows(resources)
            columns = planWorkflow.gui.PerformanceTableModel.stageColumnNames();
            rows = cell(0,numel(columns));
            if ~isstruct(resources) || ~isfield(resources,'stageTimings') || ...
                    ~isstruct(resources.stageTimings)
                return;
            end

            stageTimings = resources.stageTimings;
            stageNames = ...
                planWorkflow.gui.PerformanceTableModel.orderedStageNames( ...
                stageTimings);
            for i = 1:numel(stageNames)
                stageName = stageNames{i};
                timing = stageTimings.(stageName);
                if ~isstruct(timing)
                    continue;
                end

                rows(end + 1,:) = { ...
                    planWorkflow.config.StageConfigSchema.stageLabel( ...
                    stageName), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'lastStatus','')), ...
                    planWorkflow.gui.ValueFormat.attempts( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'attempts',0)), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'lastStartTime','')), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'lastEndTime','')), ...
                    planWorkflow.gui.ValueFormat.seconds( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'lastWallTimeSeconds',NaN)), ...
                    planWorkflow.gui.ValueFormat.seconds( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'lastCpuTimeSeconds',NaN)), ...
                    planWorkflow.gui.ValueFormat.megabytes( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'lastStartProcessMemoryBytes',NaN)), ...
                    planWorkflow.gui.ValueFormat.megabytes( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'lastEndProcessMemoryBytes',NaN)), ...
                    planWorkflow.gui.ValueFormat.megabytes( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'lastProcessMemoryDeltaBytes',NaN)), ...
                    planWorkflow.gui.ValueFormat.megabytes( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'lastMaxObservedProcessMemoryBytes',NaN)), ...
                    planWorkflow.gui.ValueFormat.megabytes( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'lastStartDataMemoryBytes',NaN)), ...
                    planWorkflow.gui.ValueFormat.megabytes( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'lastEndDataMemoryBytes',NaN)), ...
                    planWorkflow.gui.ValueFormat.megabytes( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'lastDataMemoryDeltaBytes',NaN)), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'memorySource',''))}; %#ok<AGROW>
            end
        end

        function rows = planRows(performance)
            columns = planWorkflow.gui.PerformanceTableModel.planColumnNames();
            rows = cell(0,numel(columns));
            if ~isstruct(performance) || ...
                    ~isfield(performance,'planTimings') || ...
                    ~isstruct(performance.planTimings)
                return;
            end

            planTimings = performance.planTimings;
            for i = 1:numel(planTimings)
                timing = planTimings(i);
                if ~isstruct(timing)
                    continue;
                end

                rows(end + 1,:) = { ...
                    planWorkflow.config.StageConfigSchema.stageLabel( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'stage','')), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'role','')), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'label','')), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'task','')), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'variantId','')), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'status','')), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'startTime','')), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'endTime','')), ...
                    planWorkflow.gui.ValueFormat.seconds( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'wallTimeSeconds',NaN)), ...
                    planWorkflow.gui.ValueFormat.seconds( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'cpuTimeSeconds',NaN)), ...
                    planWorkflow.gui.ValueFormat.megabytes( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'processMemoryDeltaBytes',NaN)), ...
                    planWorkflow.gui.ValueFormat.megabytes( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'maxObservedProcessMemoryBytes',NaN)), ...
                    planWorkflow.gui.ValueFormat.megabytes( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'dataMemoryDeltaBytes',NaN)), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'memorySource','')), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'detail','')), ...
                    planWorkflow.gui.ValueFormat.text( ...
                    planWorkflow.gui.PerformanceTableModel.timingValue( ...
                    timing,'errorMessage',''))}; %#ok<AGROW>
            end
        end

        function stageNames = orderedStageNames(stageTimings)
            preferredOrder = ...
                planWorkflow.config.StageConfigSchema.engineStageNames();
            availableNames = fieldnames(stageTimings);
            stageNames = {};
            for i = 1:numel(preferredOrder)
                if any(strcmp(availableNames,preferredOrder{i}))
                    stageNames{end + 1} = preferredOrder{i}; %#ok<AGROW>
                end
            end
            remaining = setdiff(availableNames,stageNames,'stable');
            stageNames = [stageNames remaining(:)'];
        end

        function value = timingValue(timing,fieldName,defaultValue)
            value = defaultValue;
            if isstruct(timing) && isfield(timing,fieldName)
                value = timing.(fieldName);
            end
        end

    end
end
