classdef PlanPresetWriter
    % PlanPresetWriter Persist GUI-edited plan templates and macros.

    methods (Static)
        function result = save(template,runConfig,templateId,macroName, ...
                varargin)
            options = planWorkflow.gui.PlanPresetWriter.parseOptions( ...
                varargin{:});
            [template,templateId] = ...
                planWorkflow.gui.PlanPresetWriter.prepareTemplateForExport( ...
                template,runConfig,templateId);
            runConfig.plan_template = templateId;
            [template,runConfig] = ...
                planWorkflow.config.WorkflowContractValidator.validateAction( ...
                template,runConfig);
            macroName = planWorkflow.gui.PlanPresetWriter.validateMacroName( ...
                macroName);

            templateFolder = planWorkflow.gui.PlanPresetWriter.templateFolder( ...
                runConfig,templateId,options.templateRoot);
            macroFile = planWorkflow.gui.PlanPresetWriter.macroFile( ...
                runConfig,macroName,options.macroFolder);
            if isfolder(templateFolder)
                error('planWorkflow:templates:PlanTemplate:TemplateExists', ...
                    'Plan template folder already exists: %s.', ...
                    templateFolder);
            end
            if isfile(macroFile)
                error('planWorkflow:gui:PlanPresetWriter:MacroExists', ...
                    'Workflow macro already exists: %s.',macroFile);
            end
            planWorkflow.gui.PlanPresetWriter.assertUniqueTemplateValues( ...
                template,runConfig,options.templateRoot);
            planWorkflow.gui.PlanPresetWriter.assertUniqueMacroValues( ...
                runConfig,templateId,options.macroFolder);

            planWorkflow.templates.PlanTemplate.writeToFolder( ...
                template,templateFolder,runConfig.description,templateId);
            macroFolder = fileparts(macroFile);
            if ~isfolder(macroFolder)
                mkdir(macroFolder);
            end
            planWorkflow.gui.PlanPresetWriter.writeMacroFile( ...
                macroFile,macroName,runConfig,templateId);

            result = struct('templateId',templateId, ...
                'templateFolder',templateFolder, ...
                'macroName',macroName, ...
                'macroFile',macroFile, ...
                'template',template);
        end

        function result = saveTemplate(template,runConfig,templateId, ...
                varargin)
            options = planWorkflow.gui.PlanPresetWriter.parseOptions( ...
                varargin{:});
            [template,templateId] = ...
                planWorkflow.gui.PlanPresetWriter.prepareTemplateForExport( ...
                template,runConfig,templateId);
            runConfig.plan_template = templateId;
            [template,runConfig] = ...
                planWorkflow.config.WorkflowContractValidator.validateAction( ...
                template,runConfig);
            templateFolder = planWorkflow.gui.PlanPresetWriter.templateFolder( ...
                runConfig,templateId,options.templateRoot);
            if isfolder(templateFolder)
                error('planWorkflow:templates:PlanTemplate:TemplateExists', ...
                    'Plan template folder already exists: %s.', ...
                    templateFolder);
            end
            planWorkflow.gui.PlanPresetWriter.assertUniqueTemplateValues( ...
                template,runConfig,options.templateRoot);

            planWorkflow.templates.PlanTemplate.writeToFolder( ...
                template,templateFolder,runConfig.description,templateId);

            result = struct('templateId',templateId, ...
                'templateFolder',templateFolder, ...
                'template',template);
        end

        function result = saveMacro(runConfig,templateId,macroName,varargin)
            options = planWorkflow.gui.PlanPresetWriter.parseOptions( ...
                varargin{:});
            templateId = planWorkflow.gui.PlanPresetWriter.validateTemplateId( ...
                runConfig.description,templateId);
            runConfig = ...
                planWorkflow.gui.PlanPresetWriter.alignRunConfigWithTemplateId( ...
                runConfig,templateId,options.templateRoot);
            macroName = planWorkflow.gui.PlanPresetWriter.validateMacroName( ...
                macroName);
            macroFile = planWorkflow.gui.PlanPresetWriter.macroFile( ...
                runConfig,macroName,options.macroFolder);
            if isfile(macroFile)
                error('planWorkflow:gui:PlanPresetWriter:MacroExists', ...
                    'Workflow macro already exists: %s.',macroFile);
            end
            planWorkflow.gui.PlanPresetWriter.assertUniqueMacroValues( ...
                runConfig,templateId,options.macroFolder);

            macroFolder = fileparts(macroFile);
            if ~isfolder(macroFolder)
                mkdir(macroFolder);
            end
            planWorkflow.gui.PlanPresetWriter.writeMacroFile( ...
                macroFile,macroName,runConfig,templateId);

            result = struct('templateId',templateId, ...
                'macroName',macroName, ...
                'macroFile',macroFile);
        end

        function names = defaultPresetNames(runConfig)
            templateBase = ...
                planWorkflow.gui.PlanPresetWriter.uniqueTemplateId( ...
                runConfig.description,[char(runConfig.plan_template) '_copy']);
            macroBase = ['run' ...
                planWorkflow.gui.PlanPresetWriter.pascalCase( ...
                runConfig.description) ...
                planWorkflow.gui.PlanPresetWriter.pascalCase(templateBase) ...
                'Workflow'];
            macroFolder = fullfile(runConfig.rootPath,'macros');
            names = struct('templateId',templateBase, ...
                'macroName', ...
                planWorkflow.gui.PlanPresetWriter.uniqueMacroName( ...
                macroFolder,macroBase));
        end

        function status = exportNameStatus(template,runConfig,templateId, ...
                macroName,varargin)
            options = planWorkflow.gui.PlanPresetWriter.parseOptions( ...
                varargin{:});

            status = struct( ...
                'templateId',char(string(templateId)), ...
                'macroName',char(string(macroName)), ...
                'templateFolder','', ...
                'macroFile','', ...
                'templateExists',false, ...
                'macroExists',false, ...
                'templateSameNameSameValues',false, ...
                'macroSameNameSameValues',false, ...
                'templateSameValueIds',{{}}, ...
                'macroSameValueNames',{{}}, ...
                'templateMessage','', ...
                'macroMessage','', ...
                'templateSeverity','none', ...
                'macroSeverity','none', ...
                'canExportTemplate',false, ...
                'canExportMacro',false, ...
                'canExportBoth',false, ...
                'valid',false);

            templateValid = true;
            try
                status.templateId = ...
                    planWorkflow.gui.PlanPresetWriter.validateTemplateId( ...
                    runConfig.description,templateId);
            catch ME
                templateValid = false;
                status.templateMessage = ME.message;
            end

            macroValid = true;
            try
                status.macroName = ...
                    planWorkflow.gui.PlanPresetWriter.validateMacroName( ...
                    macroName);
            catch ME
                macroValid = false;
                status.macroMessage = ME.message;
            end

            if templateValid
                status.templateFolder = ...
                    planWorkflow.gui.PlanPresetWriter.templateFolder( ...
                    runConfig,status.templateId,options.templateRoot);
                status.templateExists = isfolder(status.templateFolder);
                status.templateSameValueIds = ...
                    planWorkflow.gui.PlanPresetWriter.findTemplateValueMatches( ...
                    template,runConfig,options.templateRoot);
                status.templateSameNameSameValues = any(strcmp( ...
                    status.templateSameValueIds,status.templateId));
                if status.templateExists
                    if status.templateSameNameSameValues
                        status.templateMessage = ...
                            ['A template with this name already exists ', ...
                            'with the same values.'];
                    else
                        status.templateMessage = ...
                            ['A template with this name already exists ', ...
                            'with different values. Choose another ', ...
                            'template name.'];
                    end
                    status.templateSeverity = 'error';
                elseif ~isempty(status.templateSameValueIds)
                    status.templateMessage = sprintf( ...
                        'Same template values already exist as: %s.', ...
                        planWorkflow.gui.PlanPresetWriter.formatNameList( ...
                        status.templateSameValueIds));
                    status.templateSeverity = 'error';
                end
            end

            if macroValid
                macroRunConfig = ...
                    planWorkflow.config.WorkflowContractValidator.alignRobustPlansWithTemplate( ...
                    runConfig,template);
                status.macroFile = ...
                    planWorkflow.gui.PlanPresetWriter.macroFile( ...
                    macroRunConfig,status.macroName,options.macroFolder);
                status.macroExists = isfile(status.macroFile);
                if templateValid
                    status.macroSameValueNames = ...
                        planWorkflow.gui.PlanPresetWriter.findMacroValueMatches( ...
                        macroRunConfig,status.templateId, ...
                        options.macroFolder);
                    status.macroSameNameSameValues = any(strcmp( ...
                        status.macroSameValueNames,status.macroName));
                end
                if status.macroExists
                    if status.macroSameNameSameValues
                        status.macroMessage = ...
                            ['A macro with this name already exists ', ...
                            'with the same values.'];
                    else
                        status.macroMessage = ...
                            ['A macro with this name already exists ', ...
                            'with different values. Choose another ', ...
                            'macro name.'];
                    end
                    status.macroSeverity = 'error';
                elseif ~isempty(status.macroSameValueNames)
                    status.macroMessage = sprintf( ...
                        'Same macro values already exist as: %s.', ...
                        planWorkflow.gui.PlanPresetWriter.formatNameList( ...
                        status.macroSameValueNames));
                    status.macroSeverity = 'error';
                elseif templateValid && ~status.templateExists
                    status.macroMessage = ...
                        ['Macro-only export requires an existing template ', ...
                        'name. Export both, or export the template first.'];
                    status.macroSeverity = 'warning';
                end
            end

            templateValuesAreUnique = isempty(status.templateSameValueIds);
            macroValuesAreUnique = isempty(status.macroSameValueNames);
            status.canExportTemplate = templateValid && ...
                ~status.templateExists && templateValuesAreUnique;
            status.canExportMacro = templateValid && macroValid && ...
                status.templateExists && ~status.macroExists && ...
                macroValuesAreUnique;
            status.canExportBoth = templateValid && macroValid && ...
                ~status.templateExists && ~status.macroExists && ...
                templateValuesAreUnique && macroValuesAreUnique;
            status.valid = status.canExportBoth;
        end

        function options = parseMacroOptions(defaults,varargin)
            options = ...
                planWorkflow.gui.PlanPresetWriter.normalizeMacroOptionStruct( ...
                defaults);
            provided = struct('caseID',false,'rootPath',false, ...
                'cacheRootPath',false);

            if isempty(varargin)
                return;
            end

            if numel(varargin) == 1 && isstruct(varargin{1})
                [options,provided] = ...
                    planWorkflow.gui.PlanPresetWriter.applyMacroOptionPatch( ...
                    options,provided,varargin{1});
            elseif planWorkflow.gui.PlanPresetWriter.usesPositionalMacroOptions( ...
                    varargin{:})
                [options,provided] = ...
                    planWorkflow.gui.PlanPresetWriter.applyPositionalMacroOptions( ...
                    options,provided,varargin{:});
            else
                [options,provided] = ...
                    planWorkflow.gui.PlanPresetWriter.applyNameValueMacroOptions( ...
                    options,provided,varargin{:});
            end

            if provided.rootPath && ~provided.cacheRootPath && ...
                    strcmp(char(defaults.cacheRootPath), ...
                    fullfile(char(defaults.rootPath),'output','cache'))
                options.cacheRootPath = ...
                    fullfile(options.rootPath,'output','cache');
            end
        end

        function text = macroText(macroName,runConfig,templateId)
            macroName = planWorkflow.gui.PlanPresetWriter.validateMacroName( ...
                macroName);
            templateId = char(templateId);
            lines = { ...
                ['function ' macroName '(varargin)']; ...
                ['% ' macroName ' Run a saved planWorkflow macro.']; ...
                ['% Usage: ' macroName ...
                '(''caseID'',''3482'',''rootPath'',userDataRoot,' ...
                '''cacheRootPath'',fullfile(userDataRoot,''output'',''cache''))']; ...
                '%'; ...
                ['% This macro was generated from the planWorkflow GUI on ' ...
                char(datetime('now','Format','yyyy-MM-dd HH:mm:ss')) '.']; ...
                ''; ...
                'macroFolder = fileparts(mfilename(''fullpath''));'; ...
                'macroRoot = fileparts(macroFolder);'; ...
                'if exist(fullfile(macroRoot,''helpers''),''dir'') ~= 7'; ...
                '    macroRoot = macroFolder;'; ...
                'end'; ...
                'helperFolder = fullfile(macroRoot,''helpers'');'; ...
                'if exist(helperFolder,''dir'') == 7'; ...
                '    addpath(helperFolder);'; ...
                'end'; ...
                sprintf('if exist(''ensurePlanWorkflowAvailable'',''file'') == 2'); ...
                sprintf('    ensurePlanWorkflowAvailable(''%s'');',macroName); ...
                'end'; ...
                'userDataRoot = fileparts(macroRoot);'; ...
                ''};
            lines = [lines; ...
                planWorkflow.gui.PlanPresetWriter.macroOptionsLines( ...
                runConfig); ...
                {''; ...
                'workflowConfig = struct();'; ...
                ''}];
            lines = [lines; ...
                planWorkflow.gui.PlanPresetWriter.sharedPathLines( ...
                runConfig)];

            stageDescriptors = ...
                planWorkflow.config.StageConfigSchema.descriptors();
            for stageIx = 1:numel(stageDescriptors)
                descriptor = stageDescriptors(stageIx);
                lines = [lines; ...
                    planWorkflow.gui.PlanPresetWriter.stageLines( ...
                    descriptor.macroTitle,descriptor.publicName, ...
                    planWorkflow.config.StageConfigSchema.macroFields( ...
                    descriptor.publicName,runConfig), ...
                    runConfig,templateId)]; %#ok<AGROW>
            end

            workflowLines = { ...
                'workflow = planWorkflow.Workflow(workflowConfig);'; ...
                'cleanupObj = onCleanup(@() workflow.releaseMemory());'; ...
                ''; ...
                'workflow.gui();'};
            for stageIx = 1:numel(stageDescriptors)
                workflowLines{end + 1,1} = sprintf( ...
                    'workflow.%s();', ...
                    stageDescriptors(stageIx).workflowMethod); %#ok<AGROW>
            end

            lines = [lines; workflowLines; { ...
                ''; ...
                'workflow.save();'; ...
                'workflow.releaseMemory();'; ...
                ''; ...
                'end'}];

            text = strjoin(lines,newline);
            text = [text newline];
        end

        function valueText = matlabValue(value)
            if ischar(value)
                valueText = planWorkflow.gui.PlanPresetWriter.quoteText(value);
            elseif isstring(value)
                valueText = planWorkflow.gui.PlanPresetWriter.quoteText( ...
                    char(value));
            elseif islogical(value)
                if isscalar(value)
                    valueText = planWorkflow.gui.PlanPresetWriter.logicalText( ...
                        value);
                else
                    valueText = mat2str(value);
                end
            elseif isnumeric(value)
                valueText = mat2str(value);
            elseif iscell(value)
                valueText = planWorkflow.gui.PlanPresetWriter.cellValue(value);
            elseif isstruct(value)
                valueText = planWorkflow.gui.PlanPresetWriter.structValue(value);
            else
                error('planWorkflow:gui:PlanPresetWriter:UnsupportedValue', ...
                    'Cannot write MATLAB literal for value of class "%s".', ...
                    class(value));
            end
        end
    end

    methods (Static, Access = private)
        function [template,templateId] = prepareTemplateForExport( ...
                template,runConfig,templateId)
            templateId = planWorkflow.gui.PlanPresetWriter.validateTemplateId( ...
                runConfig.description,templateId);
            template.schemaVersion = 1;
            template.id = templateId;
            template.description = char(runConfig.description);
            validationRunConfig = runConfig;
            validationRunConfig.plan_template = templateId;
            planWorkflow.templates.PlanTemplate.validateEffectiveTemplate( ...
                template,validationRunConfig);
        end

        function templateFolder = templateFolder(runConfig,templateId, ...
                templateRoot)
            templateRoot = ...
                planWorkflow.gui.PlanPresetWriter.resolveTemplateRoot( ...
                templateRoot);
            templateFolder = fullfile(templateRoot, ...
                char(runConfig.description),templateId);
        end

        function macroFile = macroFile(runConfig,macroName,macroFolder)
            macroFolder = ...
                planWorkflow.gui.PlanPresetWriter.resolveMacroFolder( ...
                runConfig,macroFolder);
            macroFile = fullfile(macroFolder,[macroName '.m']);
        end

        function runConfig = alignRunConfigWithTemplateId( ...
                runConfig,templateId,templateRoot)
            template = [];
            candidateFolder = ...
                planWorkflow.gui.PlanPresetWriter.templateFolder( ...
                runConfig,templateId,templateRoot);
            if isfolder(candidateFolder)
                try
                    template = ...
                        planWorkflow.templates.PlanTemplate.loadFromFolder( ...
                        candidateFolder,templateId);
                catch ME
                    error(['planWorkflow:gui:PlanPresetWriter:' ...
                        'TemplateLoadFailed'], ...
                        'Cannot load plan template "%s" from "%s": %s', ...
                        templateId,candidateFolder,ME.message);
                end
            end
            if isempty(template)
                try
                    template = ...
                        planWorkflow.templates.PlanTemplate.loadForDescription( ...
                        runConfig.description,templateId);
                catch ME
                    error(['planWorkflow:gui:PlanPresetWriter:' ...
                        'UnknownTemplate'], ...
                        ['Cannot save macro because plan template "%s" ' ...
                         'for description "%s" could not be loaded: %s'], ...
                        templateId,char(runConfig.description),ME.message);
                end
            end
            runConfig.plan_template = templateId;
            [~,runConfig] = ...
                planWorkflow.config.WorkflowContractValidator.validateAction( ...
                template,runConfig);
        end

        function ids = findTemplateValueMatches(template,runConfig, ...
                templateRoot)
            ids = {};
            try
                currentSignature = ...
                    planWorkflow.gui.PlanPresetWriter.templateValueSignature( ...
                    template,runConfig.description);
            catch
                return;
            end

            templateRoot = ...
                planWorkflow.gui.PlanPresetWriter.resolveTemplateRoot( ...
                templateRoot);
            candidateIds = ...
                planWorkflow.gui.PlanPresetWriter.availableTemplateIdsInRoot( ...
                templateRoot,runConfig.description);
            for i = 1:numel(candidateIds)
                candidateId = candidateIds{i};
                candidateFolder = fullfile(templateRoot, ...
                    char(runConfig.description),candidateId);
                try
                    candidate = ...
                        planWorkflow.templates.PlanTemplate.loadFromFolder( ...
                        candidateFolder,candidateId);
                    candidateSignature = ...
                        planWorkflow.gui.PlanPresetWriter.templateValueSignature( ...
                        candidate,runConfig.description);
                catch
                    continue;
                end
                if strcmp(currentSignature,candidateSignature)
                    ids{end + 1} = candidateId; %#ok<AGROW>
                end
            end
        end

        function assertUniqueTemplateValues(template,runConfig, ...
                templateRoot)
            ids = planWorkflow.gui.PlanPresetWriter.findTemplateValueMatches( ...
                template,runConfig,templateRoot);
            if ~isempty(ids)
                error('planWorkflow:gui:PlanPresetWriter:TemplateValuesExist', ...
                    'Same template values already exist as: %s.', ...
                    planWorkflow.gui.PlanPresetWriter.formatNameList(ids));
            end
        end

        function signature = templateValueSignature(template,description)
            template.schemaVersion = 1;
            template.description = char(description);
            if isfield(template,'id')
                template = rmfield(template,'id');
            end
            if isfield(template,'description')
                template = rmfield(template,'description');
            end
            signature = planWorkflow.templates.PlanTemplate.hash(template);
        end

        function ids = availableTemplateIdsInRoot(templateRoot,description)
            descriptionRoot = fullfile(templateRoot,char(description));
            if ~isfolder(descriptionRoot)
                ids = {};
                return;
            end
            entries = dir(descriptionRoot);
            isTemplateFolder = [entries.isdir] & ...
                ~ismember({entries.name},{'.','..'});
            ids = sort({entries(isTemplateFolder).name});
        end

        function names = findMacroValueMatches(runConfig,templateId, ...
                macroFolder)
            names = {};
            currentSignature = ...
                planWorkflow.gui.PlanPresetWriter.macroValueSignature( ...
                runConfig,templateId);
            macroFolder = ...
                planWorkflow.gui.PlanPresetWriter.resolveMacroFolder( ...
                runConfig,macroFolder);
            if ~isfolder(macroFolder)
                return;
            end
            entries = dir(fullfile(macroFolder,'*.m'));
            for i = 1:numel(entries)
                macroPath = fullfile(entries(i).folder,entries(i).name);
                try
                    candidateSignature = ...
                        planWorkflow.gui.PlanPresetWriter.macroValueSignatureFromText( ...
                        fileread(macroPath));
                catch
                    continue;
                end
                if strcmp(currentSignature,candidateSignature)
                    [~,name] = fileparts(entries(i).name);
                    names{end + 1} = name; %#ok<AGROW>
                end
            end
            names = sort(names);
        end

        function assertUniqueMacroValues(runConfig,templateId,macroFolder)
            names = planWorkflow.gui.PlanPresetWriter.findMacroValueMatches( ...
                runConfig,templateId,macroFolder);
            if ~isempty(names)
                error('planWorkflow:gui:PlanPresetWriter:MacroValuesExist', ...
                    'Same macro values already exist as: %s.', ...
                    planWorkflow.gui.PlanPresetWriter.formatNameList(names));
            end
        end

        function signature = macroValueSignature(runConfig,templateId)
            signature = ...
                planWorkflow.gui.PlanPresetWriter.macroValueSignatureFromText( ...
                planWorkflow.gui.PlanPresetWriter.macroText( ...
                'planWorkflowMacroFingerprint',runConfig,templateId));
        end

        function signature = macroValueSignatureFromText(text)
            lines = regexp(char(text),'\r\n|\n|\r','split');
            valueLines = {};
            for i = 1:numel(lines)
                line = strtrim(lines{i});
                if ~isempty(regexp(line, ...
                        '^(workflowConfig|macroDefaults)\.','once'))
                    valueLines{end + 1} = line; %#ok<AGROW>
                end
            end
            signature = strjoin(sort(valueLines),newline);
        end

        function text = formatNameList(names)
            text = strjoin(cellfun(@char,names,'UniformOutput',false),', ');
        end

        function templateRoot = resolveTemplateRoot(templateRoot)
            if isempty(templateRoot)
                templateClassFile = ...
                    which('planWorkflow.templates.PlanTemplate');
                templateRoot = fullfile(fileparts(templateClassFile), ...
                    'json');
            end
        end

        function macroFolder = resolveMacroFolder(runConfig,macroFolder)
            if isempty(macroFolder)
                macroFolder = fullfile(runConfig.rootPath,'macros');
            end
        end

        function options = parseOptions(varargin)
            options = struct('templateRoot','','macroFolder','');
            if mod(numel(varargin),2) ~= 0
                error('planWorkflow:gui:PlanPresetWriter:InvalidOptions', ...
                    'Options must be name-value pairs.');
            end
            for i = 1:2:numel(varargin)
                name = char(varargin{i});
                if ~isfield(options,name)
                    error('planWorkflow:gui:PlanPresetWriter:InvalidOptions', ...
                        'Unknown option "%s".',name);
                end
                options.(name) = varargin{i + 1};
            end
        end

        function options = normalizeMacroOptionStruct(defaults)
            allowedFields = ...
                planWorkflow.gui.PlanPresetWriter.macroOptionFields();
            if ~isstruct(defaults) || ~isscalar(defaults)
                error('planWorkflow:gui:PlanPresetWriter:InvalidMacroOptions', ...
                    'Macro option defaults must be a scalar struct.');
            end
            for i = 1:numel(allowedFields)
                fieldName = allowedFields{i};
                if ~isfield(defaults,fieldName)
                    error('planWorkflow:gui:PlanPresetWriter:InvalidMacroOptions', ...
                        'Missing macro option default "%s".',fieldName);
                end
                options.(fieldName) = ...
                    planWorkflow.gui.PlanPresetWriter.macroOptionCharValue( ...
                    defaults.(fieldName),fieldName);
            end
        end

        function tf = usesPositionalMacroOptions(varargin)
            tf = false;
            if isempty(varargin)
                return;
            end
            allowedFields = ...
                planWorkflow.gui.PlanPresetWriter.macroOptionFields();
            if numel(varargin) > numel(allowedFields)
                return;
            end

            firstArg = varargin{1};
            if ~(ischar(firstArg) || isstring(firstArg))
                return;
            end

            firstText = char(string(firstArg));
            tf = ~any(strcmp(firstText,allowedFields));
        end

        function [options,provided] = applyPositionalMacroOptions( ...
                options,provided,varargin)
            fields = planWorkflow.gui.PlanPresetWriter.macroOptionFields();
            if numel(varargin) > numel(fields)
                error('planWorkflow:gui:PlanPresetWriter:InvalidMacroOptions', ...
                    ['Use at most three positional macro options: ' ...
                     'caseID, rootPath, cacheRootPath.']);
            end
            for i = 1:numel(varargin)
                fieldName = fields{i};
                options.(fieldName) = ...
                    planWorkflow.gui.PlanPresetWriter.macroOptionCharValue( ...
                    varargin{i},fieldName);
                provided.(fieldName) = true;
            end
        end

        function [options,provided] = applyNameValueMacroOptions( ...
                options,provided,varargin)
            if mod(numel(varargin),2) ~= 0
                error('planWorkflow:gui:PlanPresetWriter:InvalidMacroOptions', ...
                    'Macro options must be name-value pairs.');
            end
            patch = struct();
            for i = 1:2:numel(varargin)
                name = char(string(varargin{i}));
                patch.(name) = varargin{i + 1};
            end
            [options,provided] = ...
                planWorkflow.gui.PlanPresetWriter.applyMacroOptionPatch( ...
                options,provided,patch);
        end

        function [options,provided] = applyMacroOptionPatch( ...
                options,provided,patch)
            allowedFields = ...
                planWorkflow.gui.PlanPresetWriter.macroOptionFields();
            patchFields = fieldnames(patch);
            for i = 1:numel(patchFields)
                fieldName = patchFields{i};
                if ~any(strcmp(fieldName,allowedFields))
                    error('planWorkflow:gui:PlanPresetWriter:InvalidMacroOptions', ...
                        'Unknown macro option "%s".',fieldName);
                end
                options.(fieldName) = ...
                    planWorkflow.gui.PlanPresetWriter.macroOptionCharValue( ...
                    patch.(fieldName),fieldName);
                provided.(fieldName) = true;
            end
        end

        function value = macroOptionCharValue(value,fieldName)
            if ~(ischar(value) || isstring(value))
                error('planWorkflow:gui:PlanPresetWriter:InvalidMacroOptions', ...
                    'Macro option "%s" must be text.',fieldName);
            end
            value = char(string(value));
        end

        function fields = macroOptionFields()
            fields = {'caseID','rootPath','cacheRootPath'};
        end

        function templateId = validateTemplateId(description,templateId)
            templateId = ...
                planWorkflow.templates.PlanTemplate.normalizeTemplateId( ...
                description,templateId);
            if isempty(regexp(templateId,'^[A-Za-z][A-Za-z0-9_-]*$', ...
                    'once'))
                error('planWorkflow:gui:PlanPresetWriter:InvalidTemplateId', ...
                    ['Template name must start with a letter and contain ' ...
                    'only letters, numbers, underscores, or hyphens.']);
            end
        end

        function macroName = validateMacroName(macroName)
            macroName = char(string(macroName));
            [~,name,extension] = fileparts(macroName);
            if strcmp(extension,'.m')
                macroName = name;
            end
            if ~isvarname(macroName)
                error('planWorkflow:gui:PlanPresetWriter:InvalidMacroName', ...
                    'Macro name must be a valid MATLAB function name.');
            end
        end

        function lines = stageLines(title,stageName,fields,runConfig, ...
                templateId)
            lines = {''; ['% ' title '.']};
            for i = 1:numel(fields)
                fieldName = fields{i};
                [configField,value] = ...
                    planWorkflow.gui.PlanPresetWriter.stageValue( ...
                    stageName,fieldName,runConfig,templateId);
                if isempty(configField)
                    continue;
                end
                if strcmp(stageName,'precompute') && ...
                        strcmp(configField,'robustPlans')
                    lines = [lines; ...
                        planWorkflow.gui.PlanPresetWriter.robustPlanLines( ...
                        stageName,value)]; %#ok<AGROW>
                elseif strcmp(stageName,'precompute') && ...
                        strcmp(configField,'reference')
                    lines = [lines; ...
                        planWorkflow.gui.PlanPresetWriter.structAssignmentLines( ...
                        sprintf('workflowConfig.%s.reference',stageName), ...
                        value)]; %#ok<AGROW>
                else
                    lines{end + 1,1} = sprintf( ...
                        'workflowConfig.%s.%s = %s;',stageName, ...
                        configField, ...
                        planWorkflow.gui.PlanPresetWriter.stageValueText( ...
                        stageName,configField,value)); %#ok<AGROW>
                end
            end
        end

        function valueText = stageValueText(stageName,configField,value)
            if strcmp(stageName,'prepare') && strcmp(configField,'caseID')
                valueText = 'macroOptions.caseID';
            else
                valueText = planWorkflow.gui.PlanPresetWriter.matlabValue( ...
                    value);
            end
        end

        function lines = robustPlanLines(stageName,robustPlans)
            lines = {};
            for planIx = 1:numel(robustPlans)
                plan = robustPlans(planIx);
                planId = char(plan.id);
                plan = rmfield(plan,'id');
                baseExpression = sprintf( ...
                    'workflowConfig.%s.robustPlans.%s', ...
                    stageName,planId);
                lines = [lines; ...
                    planWorkflow.gui.PlanPresetWriter.structAssignmentLines( ...
                    baseExpression,plan)]; %#ok<AGROW>
            end
        end

        function lines = structAssignmentLines(baseExpression,value)
            lines = {};
            fields = fieldnames(value);
            if isempty(fields)
                lines{end + 1,1} = sprintf('%s = struct();', ...
                    baseExpression);
                return;
            end

            for fieldIx = 1:numel(fields)
                fieldName = fields{fieldIx};
                fieldValue = value.(fieldName);
                if planWorkflow.gui.PlanPresetWriter.skipStructAssignmentField( ...
                        fieldName,fieldValue)
                    continue;
                end
                fieldExpression = sprintf('%s.%s',baseExpression,fieldName);
                if isstruct(fieldValue)
                    if isempty(fieldnames(fieldValue))
                        lines{end + 1,1} = sprintf('%s = struct();', ...
                            fieldExpression); %#ok<AGROW>
                    elseif isscalar(fieldValue)
                        lines = [lines; ...
                            planWorkflow.gui.PlanPresetWriter.structAssignmentLines( ...
                            fieldExpression,fieldValue)]; %#ok<AGROW>
                    else
                        for structIx = 1:numel(fieldValue)
                            lines = [lines; ...
                                planWorkflow.gui.PlanPresetWriter.structAssignmentLines( ...
                                sprintf('%s(%d)',fieldExpression, ...
                                structIx),fieldValue(structIx))]; %#ok<AGROW>
                        end
                    end
                else
                    valueText = ...
                        planWorkflow.gui.PlanPresetWriter.matlabValue( ...
                        fieldValue);
                    lines{end + 1,1} = sprintf('%s = %s;', ...
                        fieldExpression,valueText); %#ok<AGROW>
                end
            end
        end

        function [configField,value] = stageValue(stageName,fieldName, ...
                runConfig,templateId)
            [configField,value] = ...
                planWorkflow.config.StageConfigSchema.valueFromRunConfig( ...
                stageName,fieldName,runConfig);
            if strcmp(char(stageName),'prepare') && ...
                    strcmp(char(fieldName),'plan_template') && ...
                    ~isempty(configField)
                value = char(templateId);
            end
        end

        function tf = skipStructAssignmentField(fieldName,fieldValue)
            tf = false;
            if strcmp(char(fieldName),'strategyOptions') && ...
                    isstruct(fieldValue) && isscalar(fieldValue) && ...
                    isempty(fieldnames(fieldValue))
                tf = true;
                return;
            end
            if strcmp(char(fieldName),'optimization4D')
                tf = true;
            end
        end

        function lines = sharedPathLines(runConfig)
            lines = { ...
                '% Shared configuration.'; ...
                planWorkflow.gui.PlanPresetWriter.pathAssignment( ...
                'rootPath',runConfig.rootPath,'macroOptions.rootPath', ...
                runConfig.rootPath); ...
                planWorkflow.gui.PlanPresetWriter.pathAssignment( ...
                'outputRootPath',runConfig.outputRootPath, ...
                'fullfile(macroOptions.rootPath,''output'')', ...
                fullfile(runConfig.rootPath,'output')); ...
                planWorkflow.gui.PlanPresetWriter.pathAssignment( ...
                'patientDataPath',runConfig.patientDataPath, ...
                'fullfile(macroOptions.rootPath,''patients'')', ...
                fullfile(runConfig.rootPath,'patients')); ...
                planWorkflow.gui.PlanPresetWriter.pathAssignment( ...
                'cacheRootPath',runConfig.cacheRootPath, ...
                'macroOptions.cacheRootPath', ...
                fullfile(runConfig.rootPath,'output','cache')); ...
                ''};
        end

        function lines = macroOptionsLines(runConfig)
            lines = { ...
                'macroDefaults = struct();'; ...
                sprintf('macroDefaults.caseID = %s;', ...
                planWorkflow.gui.PlanPresetWriter.matlabValue( ...
                runConfig.caseID)); ...
                planWorkflow.gui.PlanPresetWriter.macroDefaultAssignment( ...
                'rootPath',runConfig.rootPath,'userDataRoot', ...
                runConfig.rootPath); ...
                planWorkflow.gui.PlanPresetWriter.macroDefaultAssignment( ...
                'cacheRootPath',runConfig.cacheRootPath, ...
                'fullfile(userDataRoot,''output'',''cache'')', ...
                fullfile(runConfig.rootPath,'output','cache')); ...
                ['macroOptions = planWorkflow.gui.PlanPresetWriter.' ...
                'parseMacroOptions(macroDefaults,varargin{:});']};
        end

        function line = macroDefaultAssignment(fieldName,value, ...
                defaultExpression,defaultValue)
            if strcmp(char(value),char(defaultValue))
                valueText = defaultExpression;
            else
                valueText = planWorkflow.gui.PlanPresetWriter.matlabValue( ...
                    value);
            end
            line = sprintf('macroDefaults.%s = %s;',fieldName,valueText);
        end

        function line = pathAssignment(fieldName,value,defaultExpression, ...
                defaultValue)
            if strcmp(char(value),char(defaultValue))
                valueText = defaultExpression;
            else
                valueText = planWorkflow.gui.PlanPresetWriter.matlabValue( ...
                    value);
            end
            line = sprintf('workflowConfig.%s = %s;',fieldName,valueText);
        end

        function text = quoteText(value)
            text = ['''' strrep(char(value),'''','''''') ''''];
        end

        function text = logicalText(value)
            if logical(value)
                text = 'true';
            else
                text = 'false';
            end
        end

        function text = cellValue(value)
            if isempty(value)
                text = '{}';
                return;
            end
            parts = cell(1,numel(value));
            for i = 1:numel(value)
                parts{i} = planWorkflow.gui.PlanPresetWriter.matlabValue( ...
                    value{i});
            end
            text = ['{' strjoin(parts,',') '}'];
        end

        function text = structValue(value)
            if isempty(fieldnames(value))
                text = 'struct()';
                return;
            end
            jsonText = jsonencode(value);
            text = ['jsondecode(' ...
                planWorkflow.gui.PlanPresetWriter.quoteText(jsonText) ')'];
        end

        function writeTextFile(fileName,text)
            fid = fopen(fileName,'w');
            if fid == -1
                error('planWorkflow:gui:PlanPresetWriter:WriteFailed', ...
                    'Could not open macro for writing: %s.',fileName);
            end
            cleanupObj = onCleanup(@() fclose(fid));
            fprintf(fid,'%s',text);
        end

        function writeMacroFile(fileName,macroName,runConfig,templateId)
            planWorkflow.gui.PlanPresetWriter.writeTextFile( ...
                fileName, ...
                planWorkflow.gui.PlanPresetWriter.macroText( ...
                macroName,runConfig,templateId));
        end

        function templateId = uniqueTemplateId(description,baseName)
            existing = ...
                planWorkflow.templates.PlanTemplate.availableTemplateIds( ...
                description);
            templateId = planWorkflow.gui.PlanPresetWriter.uniqueListName( ...
                existing,baseName);
        end

        function macroName = uniqueMacroName(macroFolder,baseName)
            existing = {};
            if isfolder(macroFolder)
                entries = dir(fullfile(macroFolder,'*.m'));
                existing = erase({entries.name},'.m');
            end
            macroName = planWorkflow.gui.PlanPresetWriter.uniqueListName( ...
                existing,baseName);
        end

        function name = uniqueListName(existing,baseName)
            name = char(baseName);
            suffix = 1;
            while any(strcmp(existing,name))
                suffix = suffix + 1;
                name = sprintf('%s_%d',baseName,suffix);
            end
        end

        function text = pascalCase(value)
            tokens = regexp(char(value),'[A-Za-z0-9]+','match');
            text = '';
            for i = 1:numel(tokens)
                token = lower(tokens{i});
                text = [text upper(token(1)) token(2:end)]; %#ok<AGROW>
            end
            if isempty(text)
                text = 'Plan';
            end
        end
    end
end
