classdef PlanEditorSession
    % PlanEditorSession Builds initial editor state from template and config.

    methods (Static)
        function state = initialize(template,runConfig)
            runConfig.plan_template = ...
                planWorkflow.templates.PlanTemplate.normalizeTemplateId( ...
                runConfig.description,runConfig.plan_template);

            state = struct();
            state.descriptionIds = ...
                planWorkflow.templates.PlanTemplate.availableDescriptions();
            [state.descriptionIds,state.selectedDescriptionIx] = ...
                planWorkflow.gui.PlanEditorSession.optionSetWithCurrent( ...
                state.descriptionIds,runConfig.description);
            state.templateIds = ...
                planWorkflow.templates.PlanTemplate.availableTemplateIds( ...
                runConfig.description);
            [state.templateIds,state.selectedTemplateIx] = ...
                planWorkflow.gui.PlanEditorSession.optionSetWithCurrent( ...
                state.templateIds,runConfig.plan_template);

            includeOtherRadiationModes = false;
            state.radiationModes = ...
                planWorkflow.templates.BeamSelection.radiationModeOptions( ...
                template,includeOtherRadiationModes);
            if ~any(strcmp(runConfig.radiationMode,state.radiationModes))
                runConfig.radiationMode = state.radiationModes{1};
            end
            runConfig = ...
                planWorkflow.templates.BeamSelection.applyTemplateDefaults( ...
                runConfig,template,false);
            [runConfig,template] = ...
                planWorkflow.gui.PlanEditorContract.alignPrecomputeWithTemplate( ...
                runConfig,template);

            [state.radiationModes,state.selectedRadiationModeIx] = ...
                planWorkflow.gui.PlanEditorSession.optionSetWithCurrent( ...
                state.radiationModes,runConfig.radiationMode);
            state.machineOptions = ...
                planWorkflow.matRadCapabilitiesReader.supportedMachines( ...
                runConfig.radiationMode);
            [state.machineOptions,state.selectedMachineIx] = ...
                planWorkflow.gui.PlanEditorSession.optionSetWithCurrent( ...
                state.machineOptions,runConfig.machine);
            state.bioModelOptions = ...
                planWorkflow.matRadCapabilitiesReader.supportedBioModels( ...
                runConfig.radiationMode);
            [state.bioModelOptions,state.selectedBioModelIx] = ...
                planWorkflow.gui.PlanEditorSession.optionSetWithCurrent( ...
                state.bioModelOptions,runConfig.bioModel);
            state.quantityOptions = ...
                planWorkflow.matRadCapabilitiesReader.supportedDoseQuantities( ...
                runConfig.radiationMode,runConfig.bioModel);
            [state.quantityOptions,state.selectedQuantityIx] = ...
                planWorkflow.gui.PlanEditorSession.optionSetWithCurrent( ...
                state.quantityOptions,runConfig.quantityOpt);

            state.acquisitionTypes = ...
                planWorkflow.matRadCapabilitiesReader.supportedAcquisitionTypes();
            [state.acquisitionTypes,state.selectedAcquisitionTypeIx] = ...
                planWorkflow.gui.PlanEditorSession.optionSetWithCurrent( ...
                state.acquisitionTypes,runConfig.AcquisitionType);
            state.hlutFileNames = ...
                planWorkflow.gui.WorkflowParameterOptions.availableHlutFileNames();
            [state.hlutFileNames,state.selectedHlutFileIx] = ...
                planWorkflow.gui.PlanEditorSession.optionSetWithCurrent( ...
                state.hlutFileNames,runConfig.hlutFileName);

            state.caseIds = ...
                planWorkflow.gui.WorkflowParameterOptions.availableCaseIds( ...
                runConfig.patientDataPath,runConfig.description, ...
                runConfig.AcquisitionType);
            [state.caseIds,state.selectedCaseIx] = ...
                planWorkflow.gui.WorkflowParameterOptions.caseIdOptionSet( ...
                state.caseIds,runConfig.caseID);

            state.planParameterOptions = struct();
            state.planParameterOptions.description = state.descriptionIds;
            state.planParameterOptions.AcquisitionType = ...
                state.acquisitionTypes;
            state.planParameterOptions.hlutFileName = state.hlutFileNames;
            state.planParameterOptions.plan_template = state.templateIds;
            state.planParameterOptions.caseID = state.caseIds;

            state.planParameterSelection = struct();
            state.planParameterSelection.description = ...
                state.selectedDescriptionIx;
            state.planParameterSelection.AcquisitionType = ...
                state.selectedAcquisitionTypeIx;
            state.planParameterSelection.hlutFileName = ...
                state.selectedHlutFileIx;
            state.planParameterSelection.plan_template = ...
                state.selectedTemplateIx;
            state.planParameterSelection.caseID = state.selectedCaseIx;

            state.beamIds = ...
                planWorkflow.templates.BeamSelection.beamSetIds(template);
            state.selectedBeamIx = find(strcmp( ...
                state.beamIds,runConfig.plan_beams),1);
            if isempty(state.selectedBeamIx)
                state.selectedBeamIx = 1;
            end
            state.objectiveSetNames = ...
                planWorkflow.templates.PlanTemplate.objectiveSetNames( ...
                template);
            state.selectedObjectiveRows = struct();
            for objectiveSetIx = 1:numel(state.objectiveSetNames)
                state.selectedObjectiveRows.( ...
                    state.objectiveSetNames{objectiveSetIx}) = [];
            end
            state.selectedStructureRow = [];
            state.template = template;
            state.runConfig = runConfig;
            state.includeOtherRadiationModes = includeOtherRadiationModes;
        end

        function [values,selectedIx] = optionSetWithCurrent(values,currentValue)
            currentText = char(currentValue);
            if isempty(values)
                values = {currentText};
            end
            selectedIx = find(strcmp(values,currentText),1);
            if isempty(selectedIx)
                values{end + 1} = currentText;
                selectedIx = numel(values);
            end
        end
    end
end
