classdef PlanEditorContract
    % PlanEditorContract GUI-facing adapters for canonical workflow contracts.

    methods (Static)
        function runConfig = alignRobustPlansWithTemplate( ...
                runConfig,template)
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.alignRobustPlansWithTemplate( ...
                runConfig,template);
        end

        function [runConfig,template] = alignPrecomputeWithTemplate( ...
                runConfig,template)
            runConfig = ...
                planWorkflow.gui.PlanEditorContract.retargetPrecomputeRobustnessFromObjectives( ...
                runConfig,template);
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.alignRobustPlansWithTemplate( ...
                runConfig,template);
            template = ...
                planWorkflow.config.WorkflowContractValidator.syncRobustObjectiveSetLabels( ...
                template,runConfig);
        end

        function [runConfig,template] = resetPrecomputeForTemplateSelection( ...
                runConfig,template)
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.ensureReferencePlanLabel( ...
                runConfig);
            runConfig.precompute.robustPlans = ...
                planWorkflow.config.RobustPlanConfig.normalizePlans([]);
            [runConfig,template] = ...
                planWorkflow.gui.PlanEditorContract.alignPrecomputeWithTemplate( ...
                runConfig,template);
        end

        function runConfig = retargetPrecomputeRobustnessFromObjectives( ...
                runConfig,template)
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.ensureReferencePlanLabel( ...
                runConfig);
            runConfig = ...
                planWorkflow.gui.PlanEditorContract.retargetReferenceFromObjectives( ...
                runConfig,template);
            runConfig = ...
                planWorkflow.gui.PlanEditorContract.retargetRobustPlansFromObjectives( ...
                runConfig,template);
        end

        function runConfig = ensureReferencePlanLabel(runConfig)
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.ensureReferencePlanLabel( ...
                runConfig);
        end

        function label = normalizeReferencePlanLabel(label)
            label = ...
                planWorkflow.config.WorkflowContractValidator.normalizeReferencePlanLabel( ...
                label);
        end

        function label = normalizeRobustPlanLabel(label)
            label = ...
                planWorkflow.config.WorkflowContractValidator.normalizeRobustPlanLabel( ...
                label);
        end

        function template = syncRobustObjectiveSetLabels( ...
                template,runConfig)
            template = ...
                planWorkflow.config.WorkflowContractValidator.syncRobustObjectiveSetLabels( ...
                template,runConfig);
        end

        function labels = objectiveSetLabelsForRunConfig(template,runConfig)
            objectiveSetNames = ...
                planWorkflow.templates.PlanTemplate.objectiveSetNames( ...
                template);
            labels = ...
                planWorkflow.templates.PlanTemplate.objectiveSetLabels( ...
                template);
            runConfig = ...
                planWorkflow.gui.PlanEditorContract.ensureReferencePlanLabel( ...
                runConfig);
            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            labels{1} = ...
                planWorkflow.gui.panels.PrecomputePanel.referencePlanTabTitle( ...
                reference.label);
            robustPlans = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            for setIx = 2:numel(objectiveSetNames)
                planIx = ...
                    planWorkflow.gui.PlanEditorContract.findRobustPlanByObjectiveSet( ...
                    robustPlans,objectiveSetNames{setIx});
                if planIx ~= 0
                    labels{setIx} = char(robustPlans(planIx).label);
                end
            end
        end

        function planIx = findRobustPlanByObjectiveSet( ...
                robustPlans,objectiveSetName)
            planIx = 0;
            objectiveSetName = char(objectiveSetName);
            for candidateIx = 1:numel(robustPlans)
                if isfield(robustPlans(candidateIx),'objectiveSetName') && ...
                        strcmp(char( ...
                        robustPlans(candidateIx).objectiveSetName), ...
                        objectiveSetName)
                    planIx = candidateIx;
                    return;
                end
                if isfield(robustPlans(candidateIx),'id') && ...
                        strcmp(char(robustPlans(candidateIx).id), ...
                        objectiveSetName)
                    planIx = candidateIx;
                    return;
                end
            end
        end

        function needsRebuild = objectiveSetTabsNeedRebuild( ...
                currentSetNames,templateSetNames)
            currentSetNames = cellstr(currentSetNames(:));
            templateSetNames = cellstr(templateSetNames(:));
            needsRebuild = numel(currentSetNames) ~= ...
                numel(templateSetNames) || ...
                ~isequal(sort(currentSetNames),sort(templateSetNames));
        end
    end

    methods (Static, Access = private)
        function runConfig = retargetReferenceFromObjectives( ...
                runConfig,template)
            contract = ...
                planWorkflow.templates.ObjectiveRobustnessContract.forTemplateObjectiveSet( ...
                template,'reference');
            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            reference = ...
                planWorkflow.gui.PlanEditorContract.retargetPlanConfig( ...
                reference,contract.robustnessMode);
            runConfig.precompute.reference = ...
                planWorkflow.config.RobustPlanConfig.normalizeReference( ...
                reference);
        end

        function runConfig = retargetRobustPlansFromObjectives( ...
                runConfig,template)
            robustPlans = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            robustObjectiveSets = ...
                planWorkflow.templates.PlanTemplate.robustObjectiveSets( ...
                template);
            for setIx = 1:numel(robustObjectiveSets)
                objectiveSet = robustObjectiveSets(setIx);
                planIx = ...
                    planWorkflow.gui.PlanEditorContract.findRobustPlanByObjectiveSet( ...
                    robustPlans,char(objectiveSet.id));
                if planIx == 0
                    continue;
                end
                contract = ...
                    planWorkflow.templates.ObjectiveRobustnessContract.forObjectiveSet( ...
                    objectiveSet);
                robustPlans(planIx) = ...
                    planWorkflow.gui.PlanEditorContract.retargetPlanConfig( ...
                    robustPlans(planIx),contract.robustnessMode);
            end
            if ~isfield(runConfig,'precompute') || ...
                    ~isstruct(runConfig.precompute)
                runConfig.precompute = ...
                    planWorkflow.config.RobustPlanConfig.defaults();
            end
            runConfig.precompute.robustPlans = robustPlans;
        end

        function planConfig = retargetPlanConfig(planConfig,robustnessMode)
            robustnessMode = char(robustnessMode);
            currentMode = 'none';
            if isfield(planConfig,'robustnessMode') && ...
                    ~isempty(planConfig.robustnessMode)
                currentMode = char(planConfig.robustnessMode);
            end
            if ~strcmp(currentMode,robustnessMode)
                planConfig.robustnessOptions = ...
                    planWorkflow.config.RobustPlanConfig.defaultRobustnessOptions( ...
                    robustnessMode);
                planConfig.variants = ...
                    planWorkflow.config.RobustPlanConfig.defaultVariants( ...
                    robustnessMode);
                if isfield(planConfig,'variantsWithPenalties')
                    planConfig.variantsWithPenalties = [];
                end
            end
            planConfig.robustnessMode = robustnessMode;
        end
    end
end
