classdef PlanEditorContract
    % PlanEditorContract GUI-facing adapters for canonical workflow contracts.

    methods (Static)
        function runConfig = alignRobustPlansWithTemplate( ...
                runConfig,template)
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.alignRobustPlansWithTemplate( ...
                runConfig,template);
        end

        function runConfig = ensureReferencePlanLabel(runConfig)
            runConfig = ...
                planWorkflow.config.WorkflowContractValidator.ensureReferencePlanLabel( ...
                runConfig);
        end

        function label = normalizeReferencePlanLabel(label)
            label = ...
                planWorkflow.config.WorkflowContractValidator.normalizeReferencePlanLabel( ...
                label);
        end

        function label = normalizeRobustPlanLabel(label)
            label = ...
                planWorkflow.config.WorkflowContractValidator.normalizeRobustPlanLabel( ...
                label);
        end

        function template = syncRobustObjectiveSetLabels( ...
                template,runConfig)
            template = ...
                planWorkflow.config.WorkflowContractValidator.syncRobustObjectiveSetLabels( ...
                template,runConfig);
        end

        function labels = objectiveSetLabelsForRunConfig(template,runConfig)
            objectiveSetNames = ...
                planWorkflow.templates.PlanTemplate.objectiveSetNames( ...
                template);
            labels = ...
                planWorkflow.templates.PlanTemplate.objectiveSetLabels( ...
                template);
            runConfig = ...
                planWorkflow.gui.PlanEditorContract.ensureReferencePlanLabel( ...
                runConfig);
            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            labels{1} = ...
                planWorkflow.gui.panels.PrecomputePanel.referencePlanTabTitle( ...
                reference.label);
            robustPlans = ...
                planWorkflow.config.RobustPlanConfig.plansFromRunConfig( ...
                runConfig);
            for setIx = 2:numel(objectiveSetNames)
                planIx = ...
                    planWorkflow.gui.PlanEditorContract.findRobustPlanByObjectiveSet( ...
                    robustPlans,objectiveSetNames{setIx});
                if planIx ~= 0
                    labels{setIx} = char(robustPlans(planIx).label);
                end
            end
        end

        function planIx = findRobustPlanByObjectiveSet( ...
                robustPlans,objectiveSetName)
            planIx = 0;
            objectiveSetName = char(objectiveSetName);
            for candidateIx = 1:numel(robustPlans)
                if isfield(robustPlans(candidateIx),'objectiveSetName') && ...
                        strcmp(char( ...
                        robustPlans(candidateIx).objectiveSetName), ...
                        objectiveSetName)
                    planIx = candidateIx;
                    return;
                end
                if isfield(robustPlans(candidateIx),'id') && ...
                        strcmp(char(robustPlans(candidateIx).id), ...
                        objectiveSetName)
                    planIx = candidateIx;
                    return;
                end
            end
        end

        function needsRebuild = objectiveSetTabsNeedRebuild( ...
                currentSetNames,templateSetNames)
            currentSetNames = cellstr(currentSetNames(:));
            templateSetNames = cellstr(templateSetNames(:));
            needsRebuild = numel(currentSetNames) ~= ...
                numel(templateSetNames) || ...
                ~isequal(sort(currentSetNames),sort(templateSetNames));
        end
    end
end
