classdef PlanEditorFrame
    % PlanEditorFrame Owns top-level editor frame, tabs and footer widgets.

    methods (Static)
        function frame = create(options,callbacks)
            fig = figure('Name','Plan workflow editor', ...
                'NumberTitle','off','MenuBar','none','ToolBar','none', ...
                'WindowStyle',planWorkflow.gui.EditorChrome.editorWindowStyle(), ...
                'Color',[0.94 0.94 0.94], ...
                'Position',[100 100 1120 760], ...
                'CloseRequestFcn',callbacks.cancel);

            actionBar = uipanel('Parent',fig,'Units','normalized', ...
                'Position',[0.02 0.94 0.96 0.04], ...
                'BorderType','none','BackgroundColor',[0.94 0.94 0.94]);
            actionLabels = planWorkflow.gui.EditorChrome.actionButtonLabels();
            frame.resumeActionButton = ...
                planWorkflow.gui.EditorChrome.createActionTextButton( ...
                actionBar,[0.800 0.10 0.090 0.80], ...
                actionLabels.resume,callbacks.resume);
            frame.settingsActionButton = ...
                planWorkflow.gui.EditorChrome.createActionTextButton( ...
                actionBar,[0.900 0.10 0.090 0.80], ...
                actionLabels.settings,callbacks.settings);

            tabGroup = uitabgroup('Parent',fig,'Units','normalized', ...
                'Position',[0.02 0.20 0.96 0.73]);
            frame.prepareTab = uitab(tabGroup,'Title','Prepare');
            frame.precomputeTab = uitab(tabGroup,'Title','Precompute');
            frame.pullingTab = uitab(tabGroup,'Title','Dose pulling');
            frame.optimizeTab = uitab(tabGroup,'Title','Optimize');
            frame.samplingTab = uitab(tabGroup,'Title','Sampling');
            frame.analysisTab = uitab(tabGroup,'Title','Analysis');

            footerLayout = planWorkflow.gui.EditorChrome.footerLayout();
            calculateButtonColor = [21 128 61] / 255;
            stopButtonColor = [185 28 28] / 255;
            statusText = uicontrol('Parent',fig,'Style','text', ...
                'String','0%  Ready to calculate.', ...
                'HorizontalAlignment','left','Units','normalized', ...
                'Position',footerLayout.statusText);
            progressBar = uipanel('Parent',fig,'Units','normalized', ...
                'Position',footerLayout.progressBar, ...
                'BorderType','line','BackgroundColor',[1 1 1]);
            progressFill = uipanel('Parent',progressBar, ...
                'Units','normalized','Position',[0 0 0 1], ...
                'BorderType','none','BackgroundColor',[0.18 0.45 0.75]);
            progressDetails = uicontrol('Parent',fig,'Style','listbox', ...
                'String',{},'Units','normalized', ...
                'Position',footerLayout.progressDetails, ...
                'BackgroundColor',[1 1 1]);

            frame.exportPresetButton = uicontrol('Parent',fig, ...
                'Style','pushbutton', ...
                'String',planWorkflow.gui.EditorChrome.exportButtonLabel(), ...
                'TooltipString','Export template and macro', ...
                'Units','normalized','Position',footerLayout.exportButton, ...
                'Callback',callbacks.export);
            calculateButtonLabel = 'Calculate';
            if options.readOnly
                calculateButtonLabel = 'Continue';
            end
            frame.calculateButton = uicontrol('Parent',fig, ...
                'Style','pushbutton','String',calculateButtonLabel, ...
                'Units','normalized','Position',footerLayout.calculateButton, ...
                'BackgroundColor',calculateButtonColor, ...
                'ForegroundColor',[1 1 1], ...
                'Callback',callbacks.calculate);
            frame.stopButton = uicontrol('Parent',fig,'Style','pushbutton', ...
                'String','Stop','Units','normalized', ...
                'Position',footerLayout.stopButton, ...
                'BackgroundColor',stopButtonColor, ...
                'ForegroundColor',[1 1 1], ...
                'Enable','off','Callback',callbacks.stop);
            frame.cancelButton = uicontrol('Parent',fig,'Style','pushbutton', ...
                'String','Cancel','Units','normalized', ...
                'Position',footerLayout.cancelButton, ...
                'Callback',callbacks.cancel);
            frame.progressReporter = planWorkflow.gui.PlanProgressReporter( ...
                fig,progressFill,statusText,progressDetails, ...
                frame.stopButton,tabGroup);
            frame.progressReporter.ready();

            frame.fig = fig;
            frame.tabGroup = tabGroup;
        end
    end
end
