classdef PostprocessingEditorFrame
    % PostprocessingEditorFrame Owns the postprocessing editor widgets.

    methods (Static)
        function frame = create(options,callbacks)
            if nargin < 1
                options = struct();
            end
            if nargin < 2
                callbacks = struct();
            end
            fig = figure('Name','Plan workflow postprocessing', ...
                'NumberTitle','off','MenuBar','none','ToolBar','none', ...
                'WindowStyle',planWorkflow.gui.EditorChrome.editorWindowStyle(), ...
                'Color',[0.94 0.94 0.94], ...
                'Position',[120 90 1120 760], ...
                'CloseRequestFcn', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'close'));

            tabGroup = uitabgroup('Parent',fig,'Units','normalized', ...
                'Position',[0.02 0.20 0.96 0.76]);
            frame.dataTab = uitab(tabGroup,'Title','Data');
            frame.parametersTab = uitab(tabGroup,'Title','Parameters');
            frame.plotsTab = frame.parametersTab;
            frame.filtersTab = uitab(tabGroup,'Title','Filters');
            frame.outputTab = uitab(tabGroup,'Title','Output');
            frame.resultsTab = [];
            frame.resultGroup = [];

            frame = planWorkflow.gui.PostprocessingEditorFrame.addDataTab( ...
                frame,callbacks);
            frame = planWorkflow.gui.PostprocessingEditorFrame.addParametersTab( ...
                frame,callbacks);
            frame = planWorkflow.gui.PostprocessingEditorFrame.addFiltersTab( ...
                frame,callbacks);
            frame = planWorkflow.gui.PostprocessingEditorFrame.addOutputTab( ...
                frame,callbacks);
            frame = planWorkflow.gui.PostprocessingEditorFrame.addFooter( ...
                frame,fig,tabGroup,callbacks);

            frame.fig = fig;
            frame.tabGroup = tabGroup;

            if isfield(options,'outputDir') && ~isempty(options.outputDir)
                set(frame.outputDirEdit,'String',char(options.outputDir));
            end
            if isfield(options,'pythonPath') && ~isempty(options.pythonPath)
                set(frame.pythonPathEdit,'String',char(options.pythonPath));
            end
        end

        function frame = showResultsTab(frame,outputDir,entries,callbacks)
            frame = planWorkflow.gui.PostprocessingEditorFrame.deleteResultsTab( ...
                frame);
            frame.resultsTab = uitab(frame.tabGroup,'Title','Results');
            frame.resultGroup = uitabgroup('Parent',frame.resultsTab, ...
                'Units','normalized','Position',[0.02 0.10 0.96 0.87]);
            frame = planWorkflow.gui.PostprocessingEditorFrame.addFiguresPanelTab( ...
                frame,frame.resultGroup,char(outputDir),entries,callbacks);
            try
                set(frame.tabGroup,'SelectedTab',frame.resultsTab);
            catch
            end
        end

        function frame = deleteResultsTab(frame)
            if isfield(frame,'resultsTab') && ~isempty(frame.resultsTab) && ...
                    ishandle(frame.resultsTab)
                delete(frame.resultsTab);
            end
            frame.resultsTab = [];
            frame.resultGroup = [];
        end
    end

    methods (Static, Access = private)
        function frame = addDataTab(frame,callbacks)
            tab = frame.dataTab;
            uicontrol('Parent',tab,'Style','text', ...
                'String','Result folders', ...
                'Units','normalized','Position',[0.03 0.90 0.30 0.05], ...
                'FontWeight','bold','HorizontalAlignment','left');
            frame.addFolderButton = uicontrol('Parent',tab, ...
                'Style','pushbutton','String','Add folder', ...
                'Units','normalized','Position',[0.03 0.84 0.12 0.05], ...
                'Callback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'addFolder'));
            frame.removeSourceButton = uicontrol('Parent',tab, ...
                'Style','pushbutton','String','Remove selected', ...
                'Units','normalized','Position',[0.16 0.84 0.15 0.05], ...
                'Callback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'removeSources'));
            frame.clearSourcesButton = uicontrol('Parent',tab, ...
                'Style','pushbutton','String','Clear', ...
                'Units','normalized','Position',[0.32 0.84 0.10 0.05], ...
                'Callback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'clearSources'));
            frame.sourceTable = uitable('Parent',tab,'Units','normalized', ...
                'Position',[0.03 0.07 0.94 0.74], ...
                'ColumnName',{'#','Folder','File'}, ...
                'ColumnEditable',[false false false], ...
                'ColumnWidth',{45 680 220}, ...
                'Data',{}, ...
                'CellSelectionCallback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'sourceSelected'));
        end

        function frame = addParametersTab(frame,callbacks)
            tab = frame.parametersTab;
            selectionCallback = ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'selectionChanged');
            panel = planWorkflow.gui.PostprocessingEditorFrame.createParameterPanel( ...
                tab,'planWorkflowPostprocessingParametersPanel');
            y = planWorkflow.gui.PostprocessingEditorFrame.firstParameterRowY();
            rowControls = gobjects(0);

            [controls,rowHeight] = ...
                planWorkflow.gui.PostprocessingEditorFrame.addSectionRow( ...
                panel,y,'Endpoint scatter');
            rowControls = [rowControls controls(:)'];
            y = y - planWorkflow.gui.PostprocessingEditorFrame.parameterRowStride( ...
                rowHeight,true);
            [frame.endpointCheckbox,rowHeight,controls] = ...
                planWorkflow.gui.PostprocessingEditorFrame.addCheckboxRow( ...
                panel,y,'Generate endpoint scatter',true,selectionCallback);
            rowControls = [rowControls controls(:)'];
            y = y - planWorkflow.gui.PostprocessingEditorFrame.parameterRowStride( ...
                rowHeight,false);
            [frame.endpointStatPopup,rowHeight,controls] = ...
                planWorkflow.gui.PostprocessingEditorFrame.addPopupRow( ...
                panel,y,'Stat',{'por','mean','max','all'},1,selectionCallback);
            rowControls = [rowControls controls(:)'];
            y = y - planWorkflow.gui.PostprocessingEditorFrame.parameterRowStride( ...
                rowHeight,false);
            [frame.endpointFilterPopup,rowHeight,controls] = ...
                planWorkflow.gui.PostprocessingEditorFrame.addPopupRow( ...
                panel,y,'Plans',{'all','dominant','both'},1,selectionCallback);
            rowControls = [rowControls controls(:)'];
            y = y - planWorkflow.gui.PostprocessingEditorFrame.parameterRowStride( ...
                rowHeight,false);

            [controls,rowHeight] = ...
                planWorkflow.gui.PostprocessingEditorFrame.addSectionRow( ...
                panel,y,'Timing');
            rowControls = [rowControls controls(:)'];
            y = y - planWorkflow.gui.PostprocessingEditorFrame.parameterRowStride( ...
                rowHeight,true);
            [frame.precomputeTimeCheckbox,rowHeight,controls] = ...
                planWorkflow.gui.PostprocessingEditorFrame.addCheckboxRow( ...
                panel,y,'Precompute dij time',true,selectionCallback);
            rowControls = [rowControls controls(:)'];
            y = y - planWorkflow.gui.PostprocessingEditorFrame.parameterRowStride( ...
                rowHeight,false);
            [frame.optimizationRtpiCheckbox,rowHeight,controls] = ...
                planWorkflow.gui.PostprocessingEditorFrame.addCheckboxRow( ...
                panel,y,'Optimization rTPI',true,selectionCallback);
            rowControls = [rowControls controls(:)'];
            y = y - planWorkflow.gui.PostprocessingEditorFrame.parameterRowStride( ...
                rowHeight,false);
            [frame.timeValuePopup,rowHeight,controls] = ...
                planWorkflow.gui.PostprocessingEditorFrame.addPopupRow( ...
                panel,y,'Time value',{'absolute','relative','both'},2, ...
                selectionCallback);
            rowControls = [rowControls controls(:)'];
            y = y - planWorkflow.gui.PostprocessingEditorFrame.parameterRowStride( ...
                rowHeight,false);

            [controls,rowHeight] = ...
                planWorkflow.gui.PostprocessingEditorFrame.addSectionRow( ...
                panel,y,'Dij size');
            rowControls = [rowControls controls(:)'];
            y = y - planWorkflow.gui.PostprocessingEditorFrame.parameterRowStride( ...
                rowHeight,true);
            [frame.precomputeSizeCheckbox,rowHeight,controls] = ...
                planWorkflow.gui.PostprocessingEditorFrame.addCheckboxRow( ...
                panel,y,'Precompute dij size',true,selectionCallback);
            rowControls = [rowControls controls(:)'];
            y = y - planWorkflow.gui.PostprocessingEditorFrame.parameterRowStride( ...
                rowHeight,false);
            [frame.sizeValuePopup,~,controls] = ...
                planWorkflow.gui.PostprocessingEditorFrame.addPopupRow( ...
                panel,y,'Size value',{'absolute','relative','both'},2, ...
                selectionCallback);
            rowControls = [rowControls controls(:)'];

            scrollSlider = planWorkflow.gui.PanelScroller.panelSlider(panel);
            if ~isempty(scrollSlider)
                planWorkflow.gui.PanelScroller.configure( ...
                    scrollSlider,rowControls,y);
            end
        end

        function frame = addFiltersTab(frame,callbacks)
            tab = frame.filtersTab;
            uicontrol('Parent',tab,'Style','text', ...
                'String','Filters', ...
                'Units','normalized','Position',[0.03 0.90 0.30 0.05], ...
                'FontWeight','bold','HorizontalAlignment','left');
            frame.addFilterButton = uicontrol('Parent',tab, ...
                'Style','pushbutton','String','Add filter', ...
                'Units','normalized','Position',[0.03 0.84 0.12 0.05], ...
                'Callback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'addFilter'));
            frame.removeFilterButton = uicontrol('Parent',tab, ...
                'Style','pushbutton','String','Remove selected', ...
                'Units','normalized','Position',[0.16 0.84 0.15 0.05], ...
                'Callback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'removeFilter'));
            frame.filterTable = uitable('Parent',tab,'Units','normalized', ...
                'Position',[0.03 0.07 0.94 0.74], ...
                'ColumnName',{'Mode','Field','Values'}, ...
                'ColumnFormat',{{'include','exclude'},'char','char'}, ...
                'ColumnEditable',[true true true], ...
                'ColumnWidth',{120 220 520}, ...
                'Data',{}, ...
                'CellSelectionCallback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'filterSelected'), ...
                'CellEditCallback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'selectionChanged'));
        end

        function frame = addOutputTab(frame,callbacks)
            tab = frame.outputTab;
            updateCallback = ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'selectionChanged');
            uicontrol('Parent',tab,'Style','text','String','Python executable', ...
                'Units','normalized','Position',[0.03 0.87 0.18 0.05], ...
                'HorizontalAlignment','left');
            frame.pythonEdit = uicontrol('Parent',tab,'Style','edit', ...
                'String','python3','Units','normalized', ...
                'Position',[0.22 0.87 0.55 0.05], ...
                'HorizontalAlignment','left','BackgroundColor',[1 1 1], ...
                'Callback',updateCallback);
            frame.browsePythonButton = uicontrol('Parent',tab, ...
                'Style','pushbutton','String','Browse', ...
                'Units','normalized','Position',[0.79 0.87 0.12 0.05], ...
                'Callback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback( ...
                callbacks,'browsePythonExecutable'));
            uicontrol('Parent',tab,'Style','text','String','Python path', ...
                'Units','normalized','Position',[0.03 0.78 0.18 0.05], ...
                'HorizontalAlignment','left');
            frame.pythonPathEdit = uicontrol('Parent',tab,'Style','edit', ...
                'String','','Units','normalized', ...
                'Position',[0.22 0.78 0.55 0.05], ...
                'HorizontalAlignment','left','BackgroundColor',[1 1 1], ...
                'Callback',updateCallback);
            frame.browsePythonPathButton = uicontrol('Parent',tab, ...
                'Style','pushbutton','String','Browse', ...
                'Units','normalized','Position',[0.79 0.78 0.12 0.05], ...
                'Callback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback( ...
                callbacks,'browsePythonPath'));
            uicontrol('Parent',tab,'Style','text','String','Output directory', ...
                'Units','normalized','Position',[0.03 0.69 0.18 0.05], ...
                'HorizontalAlignment','left');
            frame.outputDirEdit = uicontrol('Parent',tab,'Style','edit', ...
                'String','','Units','normalized', ...
                'Position',[0.22 0.69 0.55 0.05], ...
                'HorizontalAlignment','left','BackgroundColor',[1 1 1], ...
                'Callback',updateCallback);
            frame.browseOutputButton = uicontrol('Parent',tab, ...
                'Style','pushbutton','String','Browse', ...
                'Units','normalized','Position',[0.79 0.69 0.12 0.05], ...
                'Callback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'browseOutput'));
            uicontrol('Parent',tab,'Style','text','String','Command preview', ...
                'Units','normalized','Position',[0.03 0.59 0.30 0.05], ...
                'FontWeight','bold','HorizontalAlignment','left');
            frame.commandPreview = uicontrol('Parent',tab,'Style','listbox', ...
                'String',{},'Units','normalized', ...
                'Position',[0.03 0.07 0.94 0.51], ...
                'BackgroundColor',[1 1 1]);
        end

        function frame = addFiguresPanelTab(frame,resultGroup,outputDir, ...
                entries,callbacks)
            tab = uitab(resultGroup,'Title','Figures');
            panel = planWorkflow.gui.PostprocessingEditorFrame.createReadOnlyPanel( ...
                tab,'planWorkflowPostprocessingFiguresPanel');

            rowControls = gobjects(0);
            y = 0.93;
            [controls,rowHeight] = ...
                planWorkflow.gui.PostprocessingEditorFrame.addPanelRow( ...
                panel,1,y,'Folder',outputDir,'Open', ...
                @(src,event) planWorkflow.gui.PostprocessingEditorFrame.openOutputFolder( ...
                callbacks,src,event,outputDir),'');
            rowControls = [rowControls controls(:)'];
            y = y - planWorkflow.gui.PostprocessingEditorFrame.panelRowStride( ...
                rowHeight);

            for i = 1:numel(entries)
                [~,name,ext] = fileparts(entries(i).filePath);
                [controls,rowHeight] = ...
                    planWorkflow.gui.PostprocessingEditorFrame.addPanelRow( ...
                    panel,i + 1,y,entries(i).label,[name ext],'Open', ...
                    @(src,event) planWorkflow.gui.PostprocessingEditorFrame.openResultFile( ...
                    callbacks,src,event,entries(i).filePath),'');
                rowControls = [rowControls controls(:)']; %#ok<AGROW>
                y = y - ...
                    planWorkflow.gui.PostprocessingEditorFrame.panelRowStride( ...
                    rowHeight);
            end

            scrollSlider = planWorkflow.gui.PanelScroller.panelSlider(panel);
            if ~isempty(scrollSlider)
                planWorkflow.gui.PanelScroller.configure( ...
                    scrollSlider,rowControls,y);
            end
        end

        function frame = addFooter(frame,fig,tabGroup,callbacks)
            footerLayout = planWorkflow.gui.EditorChrome.footerLayout();
            statusText = uicontrol('Parent',fig,'Style','text', ...
                'String','0%  Ready to postprocess.', ...
                'HorizontalAlignment','left','Units','normalized', ...
                'Position',footerLayout.statusText);
            progressBar = uipanel('Parent',fig,'Units','normalized', ...
                'Position',footerLayout.progressBar, ...
                'BorderType','line','BackgroundColor',[1 1 1]);
            progressFill = uipanel('Parent',progressBar, ...
                'Units','normalized','Position',[0 0 0 1], ...
                'BorderType','none','BackgroundColor',[0.18 0.45 0.75]);
            progressDetails = uicontrol('Parent',fig,'Style','listbox', ...
                'String',{},'Units','normalized', ...
                'Position',footerLayout.progressDetails, ...
                'BackgroundColor',[1 1 1]);
            frame.footerOpenOutputButton = uicontrol('Parent',fig, ...
                'Style','pushbutton','String','Open output', ...
                'Units','normalized','Position',footerLayout.exportButton, ...
                'Callback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'openOutputFolder'));
            frame.runButton = uicontrol('Parent',fig, ...
                'Style','pushbutton','String','Run', ...
                'Units','normalized','Position',footerLayout.calculateButton, ...
                'BackgroundColor',[21 128 61] / 255, ...
                'ForegroundColor',[1 1 1], ...
                'Callback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'run'));
            frame.stopButton = uicontrol('Parent',fig,'Style','pushbutton', ...
                'String','Stop','Units','normalized', ...
                'Position',footerLayout.stopButton, ...
                'BackgroundColor',[185 28 28] / 255, ...
                'ForegroundColor',[1 1 1], ...
                'Enable','off');
            frame.closeButton = uicontrol('Parent',fig,'Style','pushbutton', ...
                'String','Close','Units','normalized', ...
                'Position',footerLayout.cancelButton, ...
                'Callback', ...
                planWorkflow.gui.PostprocessingEditorFrame.callback(callbacks,'close'));
            frame.progressReporter = planWorkflow.gui.PlanProgressReporter( ...
                fig,progressFill,statusText,progressDetails, ...
                frame.stopButton,tabGroup);
            frame.progressReporter.ready();
        end

        function callback = callback(callbacks,name)
            if isstruct(callbacks) && isfield(callbacks,name) && ...
                    isa(callbacks.(name),'function_handle')
                callback = callbacks.(name);
            else
                callback = @(~,~) [];
            end
        end

        function openResultFile(callbacks,src,event,filePath)
            if isstruct(callbacks) && isfield(callbacks,'openResultFile') && ...
                    isa(callbacks.openResultFile,'function_handle')
                callbacks.openResultFile(src,event,filePath);
            end
        end

        function openOutputFolder(callbacks,src,event,folderPath)
            if isstruct(callbacks) && ...
                    isfield(callbacks,'openOutputFolderPath') && ...
                    isa(callbacks.openOutputFolderPath,'function_handle')
                callbacks.openOutputFolderPath(src,event,folderPath);
            end
        end

        function panel = createParameterPanel(parent,tag)
            panel = uipanel('Parent',parent,'Units','normalized', ...
                'Position',[0.03 0.05 0.94 0.90], ...
                'BorderType','line','BackgroundColor',[1 1 1], ...
                'Tag',tag);
            planWorkflow.gui.PanelScroller.createSlider(panel);
        end

        function y = firstParameterRowY()
            y = 0.93;
        end

        function [controls,rowHeight] = addSectionRow(panel,y,label)
            rowHeight = planWorkflow.gui.ParameterPanelLayout.sectionHeight();
            controls = uicontrol('Parent',panel,'Style','text', ...
                'String',char(label),'Units','normalized', ...
                'Position',[0.02 y 0.94 rowHeight], ...
                'HorizontalAlignment','left','FontWeight','bold', ...
                'BackgroundColor',[0.94 0.94 0.94], ...
                'TooltipString','');
        end

        function [control,rowHeight,controls] = addCheckboxRow(panel,y, ...
                label,value,callback)
            rowHeight = planWorkflow.gui.ParameterPanelLayout.controlHeight();
            labelControl = ...
                planWorkflow.gui.PostprocessingEditorFrame.addParameterLabel( ...
                panel,y,label,rowHeight);
            control = uicontrol('Parent',panel,'Style','checkbox', ...
                'String','','Units','normalized', ...
                'Position',[0.32 y 0.08 rowHeight], ...
                'BackgroundColor',[1 1 1], ...
                'Value',logical(value),'Callback',callback);
            controls = [labelControl control];
        end

        function [control,rowHeight,controls] = addPopupRow(panel,y, ...
                label,options,value,callback)
            rowHeight = planWorkflow.gui.ParameterPanelLayout.controlHeight();
            labelControl = ...
                planWorkflow.gui.PostprocessingEditorFrame.addParameterLabel( ...
                panel,y,label,rowHeight);
            control = uicontrol('Parent',panel,'Style','popupmenu', ...
                'String',options,'Units','normalized', ...
                'Position',[0.32 y 0.30 rowHeight], ...
                'BackgroundColor',[1 1 1], ...
                'Value',value,'Callback',callback);
            controls = [labelControl control];
        end

        function labelControl = addParameterLabel(panel,y,label,rowHeight)
            labelControl = uicontrol('Parent',panel,'Style','text', ...
                'String',char(label),'Units','normalized', ...
                'Position',[0.02 y 0.27 rowHeight], ...
                'HorizontalAlignment','left','FontWeight','bold', ...
                'BackgroundColor',[1 1 1], ...
                'TooltipString','');
        end

        function stride = parameterRowStride(rowHeight,isSection)
            if isSection
                stride = planWorkflow.gui.ParameterPanelLayout.sectionRowStride();
            else
                stride = max( ...
                    planWorkflow.gui.ParameterPanelLayout.baseRowStride(), ...
                    rowHeight + 0.013);
            end
        end

        function panel = createReadOnlyPanel(parent,tag)
            panel = uipanel('Parent',parent,'Units','normalized', ...
                'Position',[0.03 0.05 0.94 0.90], ...
                'BorderType','line','BackgroundColor',[1 1 1], ...
                'Tag',tag);
            planWorkflow.gui.PanelScroller.createSlider(panel);
        end

        function [controls,rowHeight] = addPanelRow(panel,rowIndex,y, ...
                label,value,buttonText,callback,tagPrefix)
            controlHeight = 0.050;
            rowHeight = controlHeight;
            if nargin < 8
                tagPrefix = '';
            end

            labelTag = '';
            valueTag = '';
            if ~isempty(tagPrefix)
                labelTag = sprintf('%sLabel%d',tagPrefix,rowIndex);
                valueTag = sprintf('%sValue%d',tagPrefix,rowIndex);
            end

            labelControl = uicontrol('Parent',panel,'Style','text', ...
                'String',char(label),'Units','normalized', ...
                'Position',[0.02 y 0.27 controlHeight], ...
                'HorizontalAlignment','left','FontWeight','bold', ...
                'BackgroundColor',[1 1 1], ...
                'TooltipString','', ...
                'Tag',labelTag);
            valueWidth = 0.64;
            if ~isempty(buttonText)
                valueWidth = 0.52;
            end
            valueControl = uicontrol('Parent',panel,'Style','edit', ...
                'String',char(string(value)),'Units','normalized', ...
                'Position',[0.32 y valueWidth controlHeight], ...
                'HorizontalAlignment','left','Enable','inactive', ...
                'BackgroundColor',[1 1 1], ...
                'TooltipString',char(string(value)), ...
                'Tag',valueTag);
            controls = [labelControl valueControl];
            if ~isempty(buttonText)
                buttonControl = uicontrol('Parent',panel,'Style','pushbutton', ...
                    'String',buttonText,'Units','normalized', ...
                    'Position',[0.86 y 0.10 controlHeight], ...
                    'Callback',callback);
                controls = [controls buttonControl];
            end
        end

        function stride = panelRowStride(rowHeight)
            stride = max(0.075,rowHeight + 0.020);
        end
    end
end
