classdef StageParameterPanels
    % StageParameterPanels Owns simple workflow-stage parameter panels.

    methods (Static)
        function callbacks = callbacks(handlers,defaults)
            if nargin < 2
                defaults = struct();
            end
            callbacks = struct();
            callbacks.sampling = struct( ...
                'sampling_linkToOptimization',handlers.samplingLinkChanged, ...
                'sampling_AcquisitionType', ...
                handlers.samplingAcquisitionTypeChanged, ...
                'sampling_scen_mode',handlers.samplingScenarioModeChanged, ...
                'sampling_ctActive',handlers.samplingScenarioModeChanged, ...
                'sampling_setupActive',handlers.samplingScenarioModeChanged, ...
                'sampling_rangeActive',handlers.samplingScenarioModeChanged, ...
                'sampling_gantryActive',handlers.samplingScenarioModeChanged, ...
                'sampling_couchActive',handlers.samplingScenarioModeChanged);
            callbacks.analysis = struct( ...
                'robustnessTargetMode',handlers.analysisTargetModeChanged);
            callbacks.dosePulling = struct( ...
                'dose_pulling1',handlers.dosePullingToggleChanged, ...
                'dose_pulling2',handlers.dosePullingToggleChanged, ...
                'dose_pulling_strategy', ...
                handlers.dosePullingToggleChanged, ...
                'dose_pulling_search_schedule', ...
                handlers.dosePullingToggleChanged, ...
                'dose_pulling_selection_policy', ...
                handlers.dosePullingToggleChanged);
            callbacks.optimize = struct();

            callbacks.dosePulling = ...
                planWorkflow.gui.StageParameterPanels.addDefault( ...
                callbacks.dosePulling,defaults,'dosePulling');
            callbacks.optimize = ...
                planWorkflow.gui.StageParameterPanels.addDefault( ...
                callbacks.optimize,defaults,'optimize');
            callbacks.sampling = ...
                planWorkflow.gui.StageParameterPanels.addDefault( ...
                callbacks.sampling,defaults,'sampling');
            callbacks.analysis = ...
                planWorkflow.gui.StageParameterPanels.addDefault( ...
                callbacks.analysis,defaults,'analysis');
        end

        function panels = create(parents,runConfig,template,callbacks)
            panels = struct();
            panels.parents = parents;
            panels.dosePulling = ...
                planWorkflow.gui.panels.DosePullingPanel.create( ...
                parents.dosePulling,[0.03 0.05 0.94 0.90], ...
                callbacks.dosePulling);
            panels.optimize = ...
                planWorkflow.gui.panels.OptimizePanel.create( ...
                parents.optimize,[0.03 0.05 0.94 0.90], ...
                runConfig,callbacks.optimize);
            panels.sampling = ...
                planWorkflow.gui.panels.SamplingPanel.create( ...
                parents.sampling,[0.03 0.05 0.94 0.90], ...
                runConfig,callbacks.sampling);
            panels.analysis = ...
                planWorkflow.gui.panels.AnalysisPanel.create( ...
                parents.analysis,[0.03 0.05 0.94 0.90], ...
                runConfig.analysis,template,runConfig,callbacks.analysis);
        end

        function loadAll(panels,runConfig,template)
            planWorkflow.gui.StageParameterPanels.loadDosePulling( ...
                panels,runConfig);
            planWorkflow.gui.StageParameterPanels.loadOptimize( ...
                panels,runConfig);
            planWorkflow.gui.StageParameterPanels.loadSampling( ...
                panels,runConfig);
            planWorkflow.gui.StageParameterPanels.loadAnalysis( ...
                panels,runConfig.analysis,template,runConfig);
        end

        function loadDosePulling(panels,runConfig)
            planWorkflow.gui.panels.DosePullingPanel.load( ...
                panels.dosePulling,runConfig);
        end

        function runConfig = syncDosePulling(panels,runConfig)
            runConfig = planWorkflow.gui.panels.DosePullingPanel.sync( ...
                panels.dosePulling,runConfig);
        end

        function refreshDosePulling(panels)
            planWorkflow.gui.panels.DosePullingPanel.refresh( ...
                panels.dosePulling);
        end

        function loadOptimize(panels,runConfig)
            planWorkflow.gui.panels.OptimizePanel.load( ...
                panels.optimize,runConfig);
        end

        function runConfig = syncOptimize(panels,runConfig)
            runConfig = planWorkflow.gui.panels.OptimizePanel.sync( ...
                panels.optimize,runConfig);
        end

        function loadSampling(panels,runConfig)
            planWorkflow.gui.panels.SamplingPanel.load( ...
                panels.sampling,runConfig);
        end

        function runConfig = syncSampling(panels,runConfig)
            runConfig = planWorkflow.gui.panels.SamplingPanel.sync( ...
                panels.sampling,runConfig);
        end

        function runConfig = refreshSampling(panels,runConfig)
            runConfig = planWorkflow.gui.panels.SamplingPanel.refresh( ...
                panels.sampling,runConfig);
        end

        function runConfig = refreshSamplingCaseIds(panels,runConfig)
            runConfig = ...
                planWorkflow.gui.panels.SamplingPanel.refreshCaseIds( ...
                panels.sampling,runConfig);
        end

        function loadAnalysis(panels,analysis,template,runConfig)
            if nargin < 4
                runConfig = struct();
            end
            planWorkflow.gui.panels.AnalysisPanel.load( ...
                panels.analysis,analysis,template,runConfig);
        end

        function analysis = syncAnalysis(panels,analysis)
            analysis = planWorkflow.gui.panels.AnalysisPanel.sync( ...
                panels.analysis,analysis);
        end

        function refreshAnalysis(panels)
            planWorkflow.gui.panels.AnalysisPanel.refresh( ...
                panels.analysis);
        end

        function tableHandle = activeParameterPanel(panels,selectedTopTab)
            tableHandle = [];
            if isequal(selectedTopTab,panels.parents.dosePulling)
                tableHandle = panels.dosePulling;
            elseif isequal(selectedTopTab,panels.parents.optimize)
                tableHandle = panels.optimize;
            elseif isequal(selectedTopTab,panels.parents.sampling)
                tableHandle = panels.sampling;
            elseif isequal(selectedTopTab,panels.parents.analysis)
                tableHandle = panels.analysis;
            end
        end

        function controls = controls(panels)
            controls = planWorkflow.gui.ParameterPanelRenderer.controls( ...
                [panels.dosePulling; panels.optimize; panels.sampling; ...
                panels.analysis]);
        end

        function controls = analysisControls(panels)
            controls = planWorkflow.gui.ParameterPanelRenderer.controls( ...
                panels.analysis);
        end

        function callbacks = addDefault(callbacks,defaults,fieldName)
            if isfield(defaults,fieldName) && ~isempty(defaults.(fieldName))
                callbacks.defaultCallback = defaults.(fieldName);
            end
        end
    end
end
