classdef TemplateStructureTableAdapter
    % TemplateStructureTableAdapter maps template structures to GUI rows.

    methods (Static)
        function data = toTable(template)
            data = cell(0,7);
            if isfield(template,'structures')
                for i = 1:numel(template.structures)
                    spec = template.structures(i);
                    data(end + 1,:) = { ...
                        'Structure', ...
                        planWorkflow.gui.TemplateStructureTableAdapter.fieldText( ...
                        spec,'name'), ...
                        planWorkflow.gui.TemplateStructureTableAdapter.fieldText( ...
                        spec,'role'), ...
                        planWorkflow.gui.TemplateStructureTableAdapter.colorTextFromSpec( ...
                        spec), ...
                        planWorkflow.gui.TemplateStructureTableAdapter.fieldText( ...
                        spec,'priority'), ...
                        planWorkflow.gui.TemplateStructureTableAdapter.fieldText( ...
                        spec,'operation'), ...
                        ''}; %#ok<AGROW>
                end
            end

            if isfield(template,'rings')
                for i = 1:numel(template.rings)
                    spec = template.rings(i);
                    data(end + 1,:) = { ...
                        'Ring', ...
                        planWorkflow.gui.TemplateStructureTableAdapter.fieldText( ...
                        spec,'name'), ...
                        planWorkflow.gui.TemplateStructureTableAdapter.fieldText( ...
                        spec,'role'), ...
                        planWorkflow.gui.TemplateStructureTableAdapter.colorTextFromSpec( ...
                        spec), ...
                        planWorkflow.gui.TemplateStructureTableAdapter.fieldText( ...
                        spec,'priority'), ...
                        '', ...
                        planWorkflow.gui.TemplateStructureTableAdapter.marginText( ...
                        spec)}; %#ok<AGROW>
                end
            end
        end

        function template = applyTable(template,data)
            if isempty(data)
                data = cell(0,7);
            end

            oldStructures = planWorkflow.gui.TemplateStructureTableAdapter.templateField( ...
                template,'structures');
            oldRings = planWorkflow.gui.TemplateStructureTableAdapter.templateField( ...
                template,'rings');
            kindValues = lower(strtrim(string(data(:,1))));
            structures = repmat( ...
                planWorkflow.gui.TemplateStructureTableAdapter.defaultStructureSpec(), ...
                1,sum(kindValues == "structure"));
            rings = repmat( ...
                planWorkflow.gui.TemplateStructureTableAdapter.defaultRingSpec(), ...
                1,sum(kindValues == "ring"));
            structureRowIx = 0;
            ringRowIx = 0;

            for rowIx = 1:size(data,1)
                kind = lower(strtrim(char(string(data{rowIx,1}))));
                switch kind
                    case 'structure'
                        structureRowIx = structureRowIx + 1;
                        structures(structureRowIx) = ...
                            planWorkflow.gui.TemplateStructureTableAdapter.structureFromRow( ...
                            data(rowIx,:));
                    case 'ring'
                        ringRowIx = ringRowIx + 1;
                        rings(ringRowIx) = ...
                            planWorkflow.gui.TemplateStructureTableAdapter.ringFromRow( ...
                            data(rowIx,:));
                    otherwise
                        error(['planWorkflow:gui:TemplateStructureTableAdapter:' ...
                            'InvalidStructureKind'], ...
                            'Structure table row %d has unsupported kind "%s".', ...
                            rowIx,char(data{rowIx,1}));
                end
            end

            template.structures = structures;
            template.rings = rings;
            template = ...
                planWorkflow.gui.TemplateStructureTableAdapter.syncObjectiveSets( ...
                template,oldStructures,oldRings);
            template.targets = ...
                planWorkflow.gui.TemplateStructureTableAdapter.targetCandidates( ...
                template.structures,template.primaryTarget);
        end

        function row = defaultRow(data)
            if nargin < 1
                data = cell(0,7);
            end
            existingNames = {};
            if ~isempty(data)
                existingNames = cellfun(@(value) char(string(value)), ...
                    data(:,2),'UniformOutput',false);
            end
            name = ...
                planWorkflow.gui.TemplateStructureTableAdapter.uniqueName( ...
                existingNames,'NEW_STRUCTURE');
            row = {'Structure',name,'OAR', ...
                planWorkflow.gui.TemplateStructureTableAdapter.colorText( ...
                [0 1 0]),5,'',''};
        end

        function text = colorText(color)
            color = ...
                planWorkflow.gui.TemplateStructureTableAdapter.validateColorVector( ...
                color);
            text = sprintf('[%.3g %.3g %.3g]', ...
                color(1),color(2),color(3));
        end

        function color = parseColorText(value)
            if isnumeric(value)
                color = value;
            else
                text = strtrim(char(string(value)));
                if isempty(text)
                    color = [0 1 0];
                    return;
                end
                text = regexprep(text,'[\[\],;]',' ');
                color = sscanf(text,'%f')';
            end
            color = ...
                planWorkflow.gui.TemplateStructureTableAdapter.validateColorVector( ...
                color);
        end
    end

    methods (Static, Access = private)
        function specs = templateField(template,fieldName)
            if isfield(template,fieldName)
                specs = template.(fieldName);
            else
                specs = [];
            end
        end

        function spec = defaultStructureSpec()
            spec = struct('name','','role','OAR','priority',5, ...
                'visibleColor',[0 1 0], ...
                'operation','');
        end

        function spec = defaultRingSpec()
            spec = struct('name','','role','OAR', ...
                'visibleColor',[0 1 0.501960784313726], ...
                'innerMarginMm',0,'outerMarginMm',20, ...
                'priority',4);
        end

        function spec = structureFromRow(row)
            spec = ...
                planWorkflow.gui.TemplateStructureTableAdapter.defaultStructureSpec();
            spec.name = ...
                planWorkflow.gui.TemplateStructureTableAdapter.requiredText( ...
                row{2},'structure name');
            spec.role = ...
                planWorkflow.gui.TemplateStructureTableAdapter.requiredText( ...
                row{3},'structure role');
            spec.priority = ...
                planWorkflow.config.WorkflowParameterSchema.parseValue( ...
                row{5},'numericScalar','structure.priority');
            spec.visibleColor = ...
                planWorkflow.gui.TemplateStructureTableAdapter.parseColorText( ...
                row{4});
            operation = strtrim(char(string(row{6})));
            if ~isempty(operation)
                spec.operation = operation;
            end
        end

        function spec = ringFromRow(row)
            spec = planWorkflow.gui.TemplateStructureTableAdapter.defaultRingSpec();
            spec.name = ...
                planWorkflow.gui.TemplateStructureTableAdapter.requiredText( ...
                row{2},'ring name');
            spec.role = ...
                planWorkflow.gui.TemplateStructureTableAdapter.requiredText( ...
                row{3},'ring role');
            spec.priority = ...
                planWorkflow.config.WorkflowParameterSchema.parseValue( ...
                row{5},'numericScalar','ring.priority');
            spec.visibleColor = ...
                planWorkflow.gui.TemplateStructureTableAdapter.parseColorText( ...
                row{4});
            [spec.innerMarginMm,spec.outerMarginMm] = ...
                planWorkflow.gui.TemplateStructureTableAdapter.parseMargins( ...
                row{7});
        end

        function template = syncObjectiveSets(template,oldStructures,oldRings)
            setNames = planWorkflow.templates.PlanTemplate.objectiveSetNames( ...
                template);
            for setIx = 1:numel(setNames)
                setName = setNames{setIx};
                objectiveSet = planWorkflow.templates.PlanTemplate.objectiveSet( ...
                    template,setName);
                objectiveSet.structureObjectives = ...
                    planWorkflow.gui.TemplateStructureTableAdapter.syncGroups( ...
                    template.structures,oldStructures, ...
                    objectiveSet.structureObjectives);
                objectiveSet.ringObjectives = ...
                    planWorkflow.gui.TemplateStructureTableAdapter.syncGroups( ...
                    template.rings,oldRings,objectiveSet.ringObjectives);
                template = planWorkflow.templates.PlanTemplate.setObjectiveSet( ...
                    template,setName,objectiveSet);
            end
        end

        function groups = syncGroups(baseSpecs,oldSpecs,oldGroups)
            groups = planWorkflow.gui.ObjectiveTableAdapter.emptyGroups( ...
                baseSpecs);
            for i = 1:numel(baseSpecs)
                groupIx = find(strcmp({oldGroups.name}, ...
                    char(baseSpecs(i).name)),1);
                if isempty(groupIx) && i <= numel(oldSpecs)
                    groupIx = find(strcmp({oldGroups.name}, ...
                        char(oldSpecs(i).name)),1);
                end
                if ~isempty(groupIx)
                    groups(i).objectives = oldGroups(groupIx).objectives;
                end
            end
        end

        function text = requiredText(value,fieldName)
            text = strtrim(char(string(value)));
            if isempty(text)
                error(['planWorkflow:gui:TemplateStructureTableAdapter:' ...
                    'MissingTableValue'], ...
                    'The %s field must not be empty.',fieldName);
            end
        end

        function [innerMargin,outerMargin] = parseMargins(value)
            text = strtrim(char(string(value)));
            text = strrep(text,'–','-');
            tokens = regexp(text, ...
                '^\s*([+-]?\d*\.?\d+)\s*-\s*([+-]?\d*\.?\d+)\s*$', ...
                'tokens','once');
            if isempty(tokens)
                error(['planWorkflow:gui:TemplateStructureTableAdapter:' ...
                    'InvalidRingMargins'], ...
                    ['Ring margins must use "inner-outer" millimeters, ' ...
                    'for example "0-20".']);
            end
            innerMargin = str2double(tokens{1});
            outerMargin = str2double(tokens{2});
            if ~isfinite(innerMargin) || ~isfinite(outerMargin) || ...
                    innerMargin < 0 || outerMargin <= innerMargin
                error(['planWorkflow:gui:TemplateStructureTableAdapter:' ...
                    'InvalidRingMargins'], ...
                    ['Ring margins must be finite and satisfy ' ...
                    '0 <= inner < outer.']);
            end
        end

        function targets = targetCandidates(structures,primaryTarget)
            targets = {char(primaryTarget)};
            for i = 1:numel(structures)
                if strcmp(char(structures(i).role),'TARGET')
                    targets{end + 1} = char(structures(i).name); %#ok<AGROW>
                end
            end
            [~,ia] = unique(targets,'stable');
            targets = targets(sort(ia));
        end

        function name = uniqueName(existingNames,baseName)
            name = baseName;
            suffix = 1;
            while any(strcmp(existingNames,name))
                suffix = suffix + 1;
                name = sprintf('%s_%d',baseName,suffix);
            end
        end

        function text = colorTextFromSpec(spec)
            if isfield(spec,'visibleColor') && ~isempty(spec.visibleColor)
                text = planWorkflow.gui.TemplateStructureTableAdapter.colorText( ...
                    spec.visibleColor);
            else
                text = planWorkflow.gui.TemplateStructureTableAdapter.colorText( ...
                    [0 1 0]);
            end
        end

        function color = validateColorVector(color)
            color = double(color(:)');
            if numel(color) ~= 3 || any(~isfinite(color)) || ...
                    any(color < 0) || any(color > 1)
                error('planWorkflow:gui:TemplateStructureTableAdapter:InvalidColor', ...
                    'Color must contain three finite RGB values between 0 and 1.');
            end
        end

        function text = fieldText(spec,fieldName)
            if ~isfield(spec,fieldName) || isempty(spec.(fieldName))
                text = '';
                return;
            end
            text = ...
                planWorkflow.gui.TemplateStructureTableAdapter.valueToText( ...
                spec.(fieldName));
        end

        function text = marginText(spec)
            if isfield(spec,'innerMarginMm') && ...
                    isfield(spec,'outerMarginMm')
                text = sprintf('%g-%g', ...
                    spec.innerMarginMm,spec.outerMarginMm);
            else
                text = '';
            end
        end

        function text = valueToText(value)
            if ischar(value)
                text = value;
            elseif isstring(value)
                text = char(value);
            elseif isnumeric(value) || islogical(value)
                text = mat2str(value);
            elseif iscell(value)
                text = strjoin(cellfun(@char,value, ...
                    'UniformOutput',false),', ');
            else
                text = char(string(value));
            end
        end
    end
end
