classdef WorkflowParameterOptions
    % WorkflowParameterOptions Builds GUI option values for workflow fields.

    methods (Static)
        function optionSets = prepareBeamOptionSets(beamIds,radiationModes, ...
                machineOptions,bioModelOptions,quantityOptions)
            if nargin < 2 || isempty(radiationModes)
                radiationModes = ...
                    planWorkflow.matRadCapabilitiesReader.supportedRadiationModes();
            end
            if nargin < 3 || isempty(machineOptions)
                machineOptions = ...
                    planWorkflow.matRadCapabilitiesReader.supportedMachines( ...
                    radiationModes{1});
            end
            if nargin < 4 || isempty(bioModelOptions)
                bioModelOptions = ...
                    planWorkflow.matRadCapabilitiesReader.supportedBioModels( ...
                    radiationModes{1});
            end
            if nargin < 5 || isempty(quantityOptions)
                quantityOptions = ...
                    planWorkflow.matRadCapabilitiesReader.supportedDoseQuantities( ...
                    radiationModes{1},bioModelOptions{1});
            end
            optionSets = struct('plan_beams',{beamIds}, ...
                'radiationMode',{radiationModes}, ...
                'machine',{machineOptions}, ...
                'bioModel',{bioModelOptions}, ...
                'quantityOpt',{quantityOptions});
        end

        function hlutFileNames = availableHlutFileNames()
            try
                matRadCfg = MatRad_Config.instance();
                hlutDirs = {fullfile(matRadCfg.matRadSrcRoot,'hluts')};
                userHlutDirs = cellfun(@(userFolder) ...
                    fullfile(userFolder,'hluts'), ...
                    matRadCfg.userfolders,'UniformOutput',false);
                hlutDirs = [hlutDirs,userHlutDirs(:)'];
            catch
                hlutFileNames = {'matRad_default.hlut'};
                return;
            end

            hlutFileNames = {};
            for i = 1:numel(hlutDirs)
                files = dir(fullfile(hlutDirs{i},'*.hlut'));
                for j = 1:numel(files)
                    hlutFileNames{end + 1} = files(j).name; %#ok<AGROW>
                end
            end
            hlutFileNames = unique(hlutFileNames,'stable');
            if isempty(hlutFileNames)
                hlutFileNames = {'matRad_default.hlut'};
            else
                hlutFileNames = sort(hlutFileNames);
            end
        end

        function optionSets = precomputeOptionSets(runConfig,planConfig)
            reference = ...
                planWorkflow.config.RobustPlanConfig.referenceFromRunConfig( ...
                runConfig);
            if nargin < 2 || isempty(planConfig)
                planConfig = ...
                    planWorkflow.config.RobustPlanConfig.defaultPlan();
            end

            optionSets = struct();
            optionSets.robustness = ...
                planWorkflow.gui.WorkflowParameterOptions.optionValuesWithCurrent( ...
                planWorkflow.matRadCapabilitiesReader.supportedWorkflowRobustnessModes(), ...
                planConfig.strategy);
            optionSets.reference_robustness = ...
                planWorkflow.gui.WorkflowParameterOptions.optionValuesWithCurrent( ...
                planWorkflow.matRadCapabilitiesReader.supportedWorkflowRobustnessModes(), ...
                reference.strategy);
            optionSets.reference_scen_mode = ...
                planWorkflow.gui.WorkflowParameterOptions.optionValuesWithCurrent( ...
                planWorkflow.matRadCapabilitiesReader.supportedScenarioModes(), ...
                reference.scenario.mode);
            optionSets.robust_scen_mode = ...
                planWorkflow.gui.WorkflowParameterOptions.optionValuesWithCurrent( ...
                planWorkflow.matRadCapabilitiesReader.supportedScenarioModes(), ...
                planConfig.scenario.mode);
            optionSets.scen_mode = ...
                planWorkflow.gui.WorkflowParameterOptions.optionValuesWithCurrent( ...
                planWorkflow.matRadCapabilitiesReader.supportedScenarioModes(), ...
                planConfig.scenario.mode);
            optionSets.useCache = ...
                planWorkflow.gui.WorkflowParameterOptions.optionValuesWithCurrent( ...
                planWorkflow.gui.WorkflowParameterOptions.logicalOptionValues(), ...
                runConfig.useCache);
            optionSets.writeCache = ...
                planWorkflow.gui.WorkflowParameterOptions.optionValuesWithCurrent( ...
                planWorkflow.gui.WorkflowParameterOptions.logicalOptionValues(), ...
                runConfig.writeCache);
            optionSets = ...
                planWorkflow.gui.WorkflowParameterOptions.addStrategyOptionSets( ...
                optionSets,'',planConfig);
            optionSets = ...
                planWorkflow.gui.WorkflowParameterOptions.addStrategyOptionSets( ...
                optionSets,'reference',reference);
        end

        function optionSets = optimizeOptionSets(runConfig)
            optionSets = struct();
            optionSets.optimizer = ...
                planWorkflow.gui.WorkflowParameterOptions.optionValuesWithCurrent( ...
                planWorkflow.matRadCapabilitiesReader.supportedOptimizers(), ...
                runConfig.optimizer);
        end

        function optionSets = samplingOptionSets(runConfig)
            acquisitionType = runConfig.sampling_AcquisitionType;
            if strcmp(char(acquisitionType),'none')
                acquisitionType = runConfig.AcquisitionType;
            end

            caseId = runConfig.sampling_caseID;
            if strcmp(char(caseId),'none')
                caseId = runConfig.caseID;
            end

            caseIds = ...
                planWorkflow.gui.WorkflowParameterOptions.availableCaseIds( ...
                runConfig.patientDataPath,runConfig.description, ...
                acquisitionType);
            [caseIds,~] = ...
                planWorkflow.gui.WorkflowParameterOptions.caseIdOptionSet( ...
                caseIds,caseId);

            optionSets = struct();
            optionSets.sampling_caseID = caseIds;
            optionSets.sampling_AcquisitionType = ...
                planWorkflow.gui.WorkflowParameterOptions.optionValuesWithCurrent( ...
                planWorkflow.matRadCapabilitiesReader.supportedAcquisitionTypes(), ...
                acquisitionType);
            optionSets.sampling_scen_mode = ...
                planWorkflow.gui.WorkflowParameterOptions.optionValuesWithCurrent( ...
                planWorkflow.matRadCapabilitiesReader.supportedScenarioModes(), ...
                runConfig.sampling_scen_mode);
        end

        function optionSets = analysisOptionSets(analysis,template,runConfig)
            if nargin < 2
                template = struct();
            end
            if nargin < 3
                runConfig = struct();
            end
            optionSets = struct();
            optionSets.evaluationMode = ...
                planWorkflow.gui.WorkflowParameterOptions.optionValuesWithCurrent( ...
                {'perFraction','total'},analysis.evaluationMode);
            optionSets.robustnessTargetMode = ...
                planWorkflow.gui.WorkflowParameterOptions.optionValuesWithCurrent( ...
                {'all','include','exclude'}, ...
                analysis.robustnessTargetMode);
            optionSets.robustnessTargets = ...
                planWorkflow.gui.WorkflowParameterOptions.analysisRobustnessTargetOptions( ...
                template,analysis.robustnessTargets);
            optionSets.endpointsFile = ...
                planWorkflow.gui.WorkflowParameterOptions.endpointFileOptions( ...
                analysis,runConfig);
        end

        function [options,status] = endpointFileOptions(analysis,runConfig)
            doseQuantity = ...
                planWorkflow.plan.DoseQuantityResolver.visualFromRunConfig( ...
                runConfig);
            validOptions = ...
                planWorkflow.analysis.ClinicalEndpointCatalog.fileNamesForDoseQuantity( ...
                doseQuantity);
            status = ...
                planWorkflow.gui.WorkflowParameterOptions.endpointFileSelectionStatus( ...
                analysis,runConfig,validOptions,doseQuantity);
            options = ...
                planWorkflow.gui.WorkflowParameterOptions.optionSet( ...
                validOptions,validOptions);
            options.validValues = validOptions;
            options.invalidCurrentValue = '';
            if ~status.isCompatible && ~strcmp(status.currentValue,'none')
                options.labels = [{sprintf('%s (not valid for %s)', ...
                    status.currentValue,char(doseQuantity))}, ...
                    options.labels];
                options.values = [{status.currentValue},options.values];
                options.invalidCurrentValue = status.currentValue;
            end
        end

        function status = endpointFileSelectionStatus(analysis,runConfig, ...
                options,doseQuantity)
            if nargin < 3 || isempty(options)
                if nargin < 4
                    doseQuantity = ...
                        planWorkflow.plan.DoseQuantityResolver.visualFromRunConfig( ...
                        runConfig);
                end
                options = ...
                    planWorkflow.analysis.ClinicalEndpointCatalog.fileNamesForDoseQuantity( ...
                    doseQuantity);
            elseif nargin < 4
                doseQuantity = ...
                    planWorkflow.plan.DoseQuantityResolver.visualFromRunConfig( ...
                    runConfig);
            end
            currentValue = '';
            if isstruct(analysis) && isfield(analysis,'endpointsFile')
                currentValue = ...
                    planWorkflow.analysis.ClinicalEndpointCatalog.normalizeFileSelection( ...
                    analysis.endpointsFile);
            end
            if isempty(currentValue)
                currentValue = 'none';
            end

            status = struct('currentValue',currentValue, ...
                'isCompatible',true,'message','');
            if strcmp(currentValue,'none') || any(strcmp(options,currentValue))
                return;
            end

            status.isCompatible = false;
            try
                fileDoseQuantities = ...
                    planWorkflow.analysis.ClinicalEndpointCatalog.fileDoseQuantities( ...
                    currentValue);
            catch ME
                status.message = sprintf( ...
                    'Selected endpoint file "%s" is invalid: %s', ...
                    currentValue,ME.message);
                return;
            end
            if isempty(fileDoseQuantities)
                status.message = sprintf( ...
                    'Selected endpoint file "%s" is not available.', ...
                    currentValue);
                return;
            end
            status.message = sprintf( ...
                ['Selected endpoint file "%s" defines doseQuantity %s, ' ...
                 'but the current plan analyzes "%s"; it will be ' ...
                 'ignored unless the dose quantity or endpoint file changes.'], ...
                currentValue,strjoin(fileDoseQuantities,', '), ...
                char(doseQuantity));
        end

        function caseIds = availableCaseIds(patientDataPath,description, ...
                acquisitionType)
            if isempty(patientDataPath)
                matRadCfg = MatRad_Config.instance();
                patientDataPath = fullfile(matRadCfg.primaryUserFolder, ...
                    'patients');
            end

            patientRoot = fullfile(char(patientDataPath),char(description));
            if ~isfolder(patientRoot)
                caseIds = {};
                return;
            end

            switch char(acquisitionType)
                case 'dicom'
                    caseIds = ...
                        planWorkflow.gui.WorkflowParameterOptions.dicomCaseIds( ...
                        patientRoot);
                case 'mat'
                    caseIds = ...
                        planWorkflow.gui.WorkflowParameterOptions.matCaseIds( ...
                        patientRoot);
                otherwise
                    caseIds = unique([ ...
                        planWorkflow.gui.WorkflowParameterOptions.dicomCaseIds( ...
                        patientRoot), ...
                        planWorkflow.gui.WorkflowParameterOptions.matCaseIds( ...
                        patientRoot)]);
            end

            caseIds = sort(caseIds);
        end

        function caseIds = dicomCaseIds(patientRoot)
            entries = dir(patientRoot);
            caseIds = {};
            for i = 1:numel(entries)
                if ~entries(i).isdir || startsWith(entries(i).name,'.')
                    continue;
                end
                if isfolder(fullfile(patientRoot,entries(i).name,'dicom'))
                    caseIds{end + 1} = entries(i).name; %#ok<AGROW>
                end
            end
        end

        function caseIds = matCaseIds(patientRoot)
            files = dir(fullfile(patientRoot,'*.mat'));
            caseIds = cell(1,numel(files));
            for i = 1:numel(files)
                [~,caseIds{i}] = fileparts(files(i).name);
            end
        end

        function [values,selectedIx] = caseIdOptionSet(values,currentValue)
            currentValue = char(currentValue);
            if isempty(values)
                values = {currentValue};
                selectedIx = 1;
                return;
            end

            selectedIx = find(strcmp(values,currentValue),1);
            if isempty(selectedIx)
                selectedIx = 1;
            end
        end

        function values = analysisRobustnessTargetOptions( ...
                template,currentTargets)
            if nargin < 2
                currentTargets = [];
            end

            values = ...
                planWorkflow.gui.WorkflowParameterOptions.targetVolumeNames( ...
                template);
            values = unique(values,'stable');
            currentTargets = ...
                planWorkflow.gui.OptionValues.normalizeCellOptionValues( ...
                currentTargets);
            currentTargets = currentTargets(ismember(currentTargets,values));
            values = unique([values,currentTargets],'stable');
        end

        function values = targetVolumeNames(template)
            values = {};
            volumeFields = {'structures','rings'};
            for fieldIx = 1:numel(volumeFields)
                fieldName = volumeFields{fieldIx};
                if ~isfield(template,fieldName)
                    continue;
                end

                specs = template.(fieldName);
                for i = 1:numel(specs)
                    role = planWorkflow.gui.OptionValues.fieldText( ...
                        specs(i),'role');
                    name = planWorkflow.gui.OptionValues.fieldText( ...
                        specs(i),'name');
                    if strcmpi(role,'TARGET') && ~isempty(name)
                        values{end + 1} = name; %#ok<AGROW>
                    end
                end
            end
        end
    end

    methods (Static, Access = private)
        function optionSets = addStrategyOptionSets( ...
                optionSets,prefix,planConfig)
            optionSpecs = ...
                planWorkflow.config.RobustStrategySpec.allParameterSpecs();
            for specIx = 1:numel(optionSpecs)
                values = optionSpecs(specIx).optionValues;
                if isempty(values)
                    continue;
                end
                fieldName = optionSpecs(specIx).name;
                if isempty(prefix)
                    optionField = fieldName;
                else
                    optionField = [char(prefix) '_' fieldName];
                end
                currentValue = optionSpecs(specIx).default;
                if isfield(planConfig,'strategyOptions') && ...
                        isstruct(planConfig.strategyOptions) && ...
                        isfield(planConfig.strategyOptions,fieldName)
                    currentValue = planConfig.strategyOptions.(fieldName);
                end
                optionSets.(optionField) = ...
                    planWorkflow.gui.WorkflowParameterOptions.optionValuesWithCurrent( ...
                    values,currentValue);
            end
        end

        function values = logicalOptionValues()
            values = {'true','false'};
        end

        function values = optionValuesWithCurrent(values,currentValue)
            values = planWorkflow.gui.OptionValues.optionValuesWithCurrent( ...
                values,currentValue);
        end

        function options = optionSet(labels,values)
            labels = planWorkflow.gui.OptionValues.normalizeCellOptionValues( ...
                labels);
            values = planWorkflow.gui.OptionValues.normalizeCellOptionValues( ...
                values);
            if numel(labels) ~= numel(values)
                error(['planWorkflow:gui:WorkflowParameterOptions:' ...
                    'InvalidOptionSet'], ...
                    'Option set labels and values must have equal length.');
            end
            options = struct('labels',{labels},'values',{values});
        end
    end
end
