classdef WorkflowDataArtifact
    % WorkflowDataArtifact Compacts and restores persisted workflow data.

    properties (Constant)
        SchemaVersion = 2
        SchemaName = 'planWorkflow.workflowData.v2'
        RefKind = 'planWorkflowDoseInfluenceRef'
    end

    methods (Static)
        function [data,metadata] = compactForSave(data,runConfig,cachePath)
            metadata = struct( ...
                'schema',planWorkflow.persistence.WorkflowDataArtifact.SchemaName, ...
                'schemaVersion', ...
                planWorkflow.persistence.WorkflowDataArtifact.SchemaVersion);
            data = ...
                planWorkflow.persistence.WorkflowDataArtifact.removeTransientFields( ...
                data);
            data = ...
                planWorkflow.persistence.WorkflowDataArtifact.compactNode( ...
                data,runConfig,cachePath,data);
        end

        function data = rehydrateAfterLoad(data,dataMetadata,runConfig, ...
                cachePath)
            if ~planWorkflow.persistence.WorkflowDataArtifact.hasCurrentSchema( ...
                    dataMetadata)
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'UnsupportedWorkflowDataSchema'], ...
                    ['workflow_data.mat uses an unsupported internal ' ...
                    'schema. This refactor does not provide legacy ' ...
                    'fallbacks for artifacts that depended on ' ...
                    'robustData.dij.']);
            end
            data = ...
                planWorkflow.persistence.WorkflowDataArtifact.rehydrateNode( ...
                data,runConfig,cachePath,data);
        end
    end

    methods (Static, Access = private)
        function tf = hasCurrentSchema(dataMetadata)
            tf = isstruct(dataMetadata) && ...
                isfield(dataMetadata,'workflowData') && ...
                isstruct(dataMetadata.workflowData) && ...
                isfield(dataMetadata.workflowData,'schemaVersion') && ...
                dataMetadata.workflowData.schemaVersion == ...
                planWorkflow.persistence.WorkflowDataArtifact.SchemaVersion && ...
                isfield(dataMetadata.workflowData,'schema') && ...
                strcmp(char(dataMetadata.workflowData.schema), ...
                planWorkflow.persistence.WorkflowDataArtifact.SchemaName);
        end

        function data = removeTransientFields(data)
            if isstruct(data) && isfield(data,'performance')
                data = rmfield(data,'performance');
            end
        end

        function node = compactNode(node,runConfig,cachePath,rootData)
            if iscell(node)
                for ix = 1:numel(node)
                    node{ix} = ...
                        planWorkflow.persistence.WorkflowDataArtifact.compactNode( ...
                        node{ix},runConfig,cachePath,rootData);
                end
                return;
            end
            if ~isstruct(node)
                return;
            end
            if isempty(node)
                return;
            end
            if numel(node) > 1
                for ix = 1:numel(node)
                    node(ix) = ...
                        planWorkflow.persistence.WorkflowDataArtifact.compactNode( ...
                        node(ix),runConfig,cachePath,rootData);
                end
                return;
            end
            planWorkflow.persistence.WorkflowDataArtifact.rejectLegacyDijFields( ...
                node);
            node = ...
                planWorkflow.persistence.WorkflowDataArtifact.compactOwnerDijFields( ...
                node,runConfig,cachePath,rootData);

            names = fieldnames(node);
            for nameIx = 1:numel(names)
                fieldName = names{nameIx};
                fieldValue = node.(fieldName);
                if planWorkflow.persistence.WorkflowDataArtifact.isDijRef( ...
                        fieldValue)
                    continue;
                end
                node.(fieldName) = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactNode( ...
                    fieldValue,runConfig,cachePath,rootData);
            end
        end

        function node = compactOwnerDijFields(node,runConfig,cachePath, ...
                rootData)
            if isfield(node,'optimizationInput') && ...
                    isstruct(node.optimizationInput) && ...
                    isfield(node.optimizationInput,'dij')
                node.optimizationInput = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactOptimizationInput( ...
                    node.optimizationInput,node,runConfig,cachePath, ...
                    rootData);
            end
            if planWorkflow.persistence.WorkflowDataArtifact.isPlanData(node)
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactPlanArtifact( ...
                    node,'dijRobust',runConfig,cachePath,rootData);
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactPlanArtifact( ...
                    node,'dijNominal',runConfig,cachePath,rootData);
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactPlanArtifact( ...
                    node,'dijIntervalContext',runConfig,cachePath, ...
                    rootData);
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactPlanArtifact( ...
                    node,'dijProb2Context',runConfig,cachePath,rootData);
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactPlanArtifact( ...
                    node,'dij_interval',runConfig,cachePath,rootData);
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactPlanArtifact( ...
                    node,'dij_prob2',runConfig,cachePath,rootData);
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.removeOptimizationAliasArtifacts( ...
                    node);
            end
        end

        function input = compactOptimizationInput(input,owner,runConfig, ...
                cachePath,rootData)
            if isfield(input,'dijRef')
                return;
            end
            ref = planWorkflow.persistence.WorkflowDataArtifact.refForOptimizationInput( ...
                input,owner,runConfig,cachePath,rootData);
            input.dijRef = ref;
            input = rmfield(input,'dij');
        end

        function node = compactPlanArtifact(node,fieldName,runConfig, ...
                cachePath,rootData)
            if ~isfield(node,fieldName)
                return;
            end
            fieldValue = node.(fieldName);
            if isempty(fieldValue) || ...
                    planWorkflow.persistence.WorkflowDataArtifact.isDijRef( ...
                    fieldValue)
                return;
            end
            node.(fieldName) = ...
                planWorkflow.persistence.WorkflowDataArtifact.refForPlanArtifact( ...
                node,fieldName,runConfig,cachePath,rootData);
        end

        function ref = refForOptimizationInput(input,owner,runConfig, ...
                cachePath,rootData)
            if strcmp(char(input.source),'reference')
                ref = ...
                    planWorkflow.persistence.WorkflowDataArtifact.standardRef( ...
                    'reference','dij',input.pln,input.cst,input.stf, ...
                    runConfig,cachePath,input.dij,input.dijKind, ...
                    'optimizationInput');
                return;
            end
            if ~isfield(owner,'planConfig')
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'MissingPlanConfig'], ...
                    ['Cannot persist optimizationInput.dij for source ' ...
                    '"%s" without owner.planConfig.'],char(input.source));
            end
            fieldName = ...
                planWorkflow.persistence.WorkflowDataArtifact.fieldForDijKind( ...
                input.dijKind);
            ref = ...
                planWorkflow.persistence.WorkflowDataArtifact.refForPlanArtifact( ...
                owner,fieldName,runConfig,cachePath,rootData);
            ref.role = 'optimizationInput';
            ref.dijKind = char(input.dijKind);
        end

        function ref = refForPlanArtifact(owner,fieldName,runConfig, ...
                cachePath,rootData)
            switch char(fieldName)
                case 'dijRobust'
                    tag = ['robust_' char(owner.planConfig.id)];
                    ref = ...
                        planWorkflow.persistence.WorkflowDataArtifact.standardRef( ...
                        tag,'dij',owner.pln,owner.cst,owner.stf, ...
                        runConfig,cachePath,owner.(fieldName), ...
                        'scenario',fieldName);
                case 'dijNominal'
                    if planWorkflow.persistence.WorkflowDataArtifact.requiresIntervalDij( ...
                            owner)
                        ref = ...
                            planWorkflow.persistence.WorkflowDataArtifact.compactRef( ...
                            owner,'dijIntervalContext','interval', ...
                            runConfig,cachePath,rootData);
                        ref.role = fieldName;
                        ref.dijKind = 'nominal';
                    elseif planWorkflow.persistence.WorkflowDataArtifact.requiresProb2Dij( ...
                            owner)
                        ref = ...
                            planWorkflow.persistence.WorkflowDataArtifact.compactRef( ...
                            owner,'dijProb2Context','prob2', ...
                            runConfig,cachePath,rootData);
                        ref.role = fieldName;
                        ref.dijKind = 'nominal';
                    else
                        tag = ['robustNominal_' char(owner.planConfig.id)];
                        ref = ...
                            planWorkflow.persistence.WorkflowDataArtifact.standardRef( ...
                            tag,'dij',owner.plnNominal,owner.cst, ...
                            owner.stfNominal,runConfig,cachePath, ...
                            owner.(fieldName),'nominal',fieldName);
                    end
                case {'dijIntervalContext','dij_interval'}
                    ref = ...
                        planWorkflow.persistence.WorkflowDataArtifact.compactRef( ...
                        owner,fieldName,'interval',runConfig,cachePath, ...
                        rootData);
                case {'dijProb2Context','dij_prob2'}
                    ref = ...
                        planWorkflow.persistence.WorkflowDataArtifact.compactRef( ...
                        owner,fieldName,'prob2',runConfig,cachePath, ...
                        rootData);
                otherwise
                    error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                        'UnsupportedDijArtifact'], ...
                        'Unsupported dose influence artifact "%s".', ...
                        char(fieldName));
            end
        end

        function node = removeOptimizationAliasArtifacts(node)
            if ~isfield(node,'optimizationInput') || ...
                    ~isstruct(node.optimizationInput) || ...
                    ~isfield(node.optimizationInput,'dijRef') || ...
                    ~isfield(node.optimizationInput,'dijKind')
                return;
            end
            switch char(node.optimizationInput.dijKind)
                case 'scenario'
                    fieldName = 'dijRobust';
                case 'nominal'
                    fieldName = 'dijNominal';
                otherwise
                    return;
            end
            if isfield(node,fieldName) && ...
                    planWorkflow.persistence.WorkflowDataArtifact.isSameDijRef( ...
                    node.(fieldName),node.optimizationInput.dijRef)
                node = rmfield(node,fieldName);
            end
        end

        function tf = isSameDijRef(left,right)
            tf = ...
                planWorkflow.persistence.WorkflowDataArtifact.isDijRef(left) && ...
                planWorkflow.persistence.WorkflowDataArtifact.isDijRef(right) && ...
                strcmp(char(left.cacheKind),char(right.cacheKind)) && ...
                strcmp(char(left.tag),char(right.tag)) && ...
                strcmp(char(left.variableName),char(right.variableName)) && ...
                strcmp(char(left.cacheRelativeFile), ...
                char(right.cacheRelativeFile)) && ...
                strcmp(char(left.cacheIdentityHash), ...
                char(right.cacheIdentityHash)) && ...
                strcmp(char(left.dijKind),char(right.dijKind)) && ...
                isequal(left.totalNumOfBixels,right.totalNumOfBixels);
        end

        function ref = standardRef(tag,variableName,pln,cst,stf, ...
                runConfig,cachePath,dij,dijKind,role)
            cacheContext = planWorkflow.cache.DoseInfluenceCache.context( ...
                cst,stf);
            cacheFile = planWorkflow.cache.DoseInfluenceCache.cacheFile( ...
                cachePath,runConfig,tag,pln,cacheContext);
            cached = ...
                planWorkflow.persistence.WorkflowDataArtifact.loadCacheFile( ...
                cacheFile,variableName,role);
            if ~planWorkflow.cache.DoseInfluenceCache.isCompatible( ...
                    runConfig,cached,pln,tag,cacheContext)
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'IncompatibleDijCache'], ...
                    ['Cannot persist %s as a cache reference because ' ...
                    'cache identity does not match tag "%s".'], ...
                    char(role),char(tag));
            end
            ref = ...
                planWorkflow.persistence.WorkflowDataArtifact.createRef( ...
                'standard',tag,variableName,cacheFile,cachePath, ...
                cached.cacheMetadata,dij,dijKind,role);
        end

        function ref = compactRef(owner,fieldName,cacheKind,runConfig, ...
                cachePath,rootData)
            cache = planWorkflow.cache.DoseInfluenceCacheService( ...
                runConfig,cachePath,@(message) []);
            context = struct();
            context.stageName = 'workflowDataArtifact';
            context.runConfig = runConfig;
            context.data = rootData;
            context.log = @(message) [];
            context.runMeasuredPlanTask = @(varargin) [];
            context.cache = cache;
            switch char(cacheKind)
                case 'interval'
                    tag = ...
                        planWorkflow.precompute.IntervalDoseInfluence.cacheTag( ...
                        owner);
                    cacheContext = ...
                        planWorkflow.precompute.IntervalDoseInfluence.cacheContext( ...
                        context,owner);
                    cacheFile = cache.file(tag,owner.pln,cacheContext);
                    cached = load(cacheFile,'dij_interval', ...
                        'dijIntervalContext','cacheMetadata');
                    if ~planWorkflow.precompute.IntervalDoseInfluence.isCacheCompatible( ...
                            context,cached,owner)
                        error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                            'IncompatibleIntervalCache'], ...
                            ['Cannot persist %s because interval cache ' ...
                            'identity is incompatible.'],char(fieldName));
                    end
                    variableName = char(fieldName);
                    dijKind = 'interval';
                case 'prob2'
                    tag = ...
                        planWorkflow.precompute.Prob2DoseInfluence.cacheTag( ...
                        owner);
                    cacheContext = ...
                        planWorkflow.precompute.Prob2DoseInfluence.cacheContext( ...
                        context,owner);
                    cacheFile = cache.file(tag,owner.pln,cacheContext);
                    cached = load(cacheFile,'dij_prob2','dijProb2Context', ...
                        'cacheMetadata');
                    if ~planWorkflow.precompute.Prob2DoseInfluence.isCacheCompatible( ...
                            context,cached,owner)
                        error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                            'IncompatibleProb2Cache'], ...
                            ['Cannot persist %s because PROB2 cache ' ...
                            'identity is incompatible.'],char(fieldName));
                    end
                    variableName = char(fieldName);
                    dijKind = 'prob2';
            end
            ref = ...
                planWorkflow.persistence.WorkflowDataArtifact.createRef( ...
                char(cacheKind),tag,variableName,cacheFile,cachePath, ...
                cached.cacheMetadata,owner.(fieldName),dijKind,fieldName);
        end

        function ref = createRef(cacheKind,tag,variableName,cacheFile, ...
                cachePath,cacheMetadata,dij,dijKind,role)
            ref = struct();
            ref.artifactKind = ...
                planWorkflow.persistence.WorkflowDataArtifact.RefKind;
            ref.schemaVersion = 1;
            ref.cacheKind = char(cacheKind);
            ref.tag = char(tag);
            ref.variableName = char(variableName);
            ref.role = char(role);
            ref.dijKind = char(dijKind);
            ref.cacheRelativeFile = ...
                planWorkflow.persistence.WorkflowDataArtifact.relativeFile( ...
                cacheFile,cachePath);
            ref.cacheIdentityHash = cacheMetadata.cacheIdentityHash;
            ref.totalNumOfBixels = ...
                planWorkflow.precompute.OptimizationInput.totalNumOfBixels( ...
                dij);
        end

        function node = rehydrateNode(node,runConfig,cachePath,rootData)
            if iscell(node)
                for ix = 1:numel(node)
                    node{ix} = ...
                        planWorkflow.persistence.WorkflowDataArtifact.rehydrateNode( ...
                        node{ix},runConfig,cachePath,rootData);
                end
                return;
            end
            if ~isstruct(node) || ...
                    planWorkflow.persistence.WorkflowDataArtifact.isDijRef(node)
                return;
            end
            if isempty(node)
                return;
            end
            if numel(node) > 1
                for ix = 1:numel(node)
                    node(ix) = ...
                        planWorkflow.persistence.WorkflowDataArtifact.rehydrateNode( ...
                        node(ix),runConfig,cachePath,rootData);
                end
                return;
            end

            node = ...
                planWorkflow.persistence.WorkflowDataArtifact.rehydrateOwnerDijFields( ...
                node,runConfig,cachePath,rootData);
            names = fieldnames(node);
            for nameIx = 1:numel(names)
                fieldName = names{nameIx};
                fieldValue = node.(fieldName);
                if planWorkflow.persistence.WorkflowDataArtifact.isDijRef( ...
                        fieldValue)
                    continue;
                end
                node.(fieldName) = ...
                    planWorkflow.persistence.WorkflowDataArtifact.rehydrateNode( ...
                    fieldValue,runConfig,cachePath,rootData);
            end
        end

        function node = rehydrateOwnerDijFields(node,runConfig,cachePath, ...
                rootData)
            fields = {'dijRobust','dijNominal','dijIntervalContext', ...
                'dijProb2Context','dij_interval','dij_prob2'};
            for fieldIx = 1:numel(fields)
                fieldName = fields{fieldIx};
                if isfield(node,fieldName)
                    fieldValue = node.(fieldName);
                else
                    continue;
                end
                if planWorkflow.persistence.WorkflowDataArtifact.isDijRef( ...
                        fieldValue)
                    node.(fieldName) = ...
                        planWorkflow.persistence.WorkflowDataArtifact.loadDijRef( ...
                        fieldValue,node,runConfig,cachePath, ...
                        rootData);
                end
            end
            if isfield(node,'optimizationInput') && ...
                    isfield(node.optimizationInput,'dijRef')
                input = node.optimizationInput;
                input.dij = ...
                    planWorkflow.persistence.WorkflowDataArtifact.loadDijRef( ...
                    input.dijRef,node,runConfig,cachePath,rootData);
                input = rmfield(input,'dijRef');
                planWorkflow.precompute.OptimizationInput.validate( ...
                    input,'workflow_data.mat rehydration');
                node.optimizationInput = input;
            end
        end

        function dij = loadDijRef(ref,owner,runConfig,cachePath,rootData)
            cacheFile = fullfile(cachePath,ref.cacheRelativeFile);
            switch char(ref.cacheKind)
                case 'standard'
                    cacheContext = ...
                        planWorkflow.persistence.WorkflowDataArtifact.standardContextForRef( ...
                        ref,owner);
                    pln = ...
                        planWorkflow.persistence.WorkflowDataArtifact.planForRef( ...
                        ref,owner);
                    cached = ...
                        planWorkflow.persistence.WorkflowDataArtifact.loadCacheFile( ...
                        cacheFile,ref.variableName,ref.role);
                    if ~planWorkflow.cache.DoseInfluenceCache.isCompatible( ...
                            runConfig,cached,pln,ref.tag,cacheContext)
                        error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                            'IncompatibleDijCacheOnResume'], ...
                            ['Cannot rehydrate %s from cache "%s": ' ...
                            'cache identity does not match.'], ...
                            char(ref.role),cacheFile);
                    end
                    dij = cached.(ref.variableName);
                case 'interval'
                    dij = ...
                        planWorkflow.persistence.WorkflowDataArtifact.loadCompactRef( ...
                        ref,owner,runConfig,cachePath,rootData,'interval', ...
                        {'dij_interval','dijIntervalContext','cacheMetadata'});
                case 'prob2'
                    dij = ...
                        planWorkflow.persistence.WorkflowDataArtifact.loadCompactRef( ...
                        ref,owner,runConfig,cachePath,rootData,'prob2', ...
                        {'dij_prob2','dijProb2Context','cacheMetadata'});
                otherwise
                    error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                        'UnknownDijRefKind'], ...
                        'Unknown dose influence cache kind "%s".', ...
                        char(ref.cacheKind));
            end
            planWorkflow.persistence.WorkflowDataArtifact.assertRefBixels( ...
                ref,dij);
        end

        function dij = loadCompactRef(ref,owner,runConfig,cachePath, ...
                rootData,cacheKind,variables)
            cache = planWorkflow.cache.DoseInfluenceCacheService( ...
                runConfig,cachePath,@(message) []);
            context = struct();
            context.stageName = 'workflowDataArtifact';
            context.runConfig = runConfig;
            context.data = rootData;
            context.log = @(message) [];
            context.runMeasuredPlanTask = @(varargin) [];
            context.cache = cache;
            switch char(cacheKind)
                case 'interval'
                    cacheContext = ...
                        planWorkflow.precompute.IntervalDoseInfluence.cacheContext( ...
                        context,owner);
                    tag = ...
                        planWorkflow.precompute.IntervalDoseInfluence.cacheTag( ...
                        owner);
                case 'prob2'
                    cacheContext = ...
                        planWorkflow.precompute.Prob2DoseInfluence.cacheContext( ...
                        context,owner);
                    tag = ...
                        planWorkflow.precompute.Prob2DoseInfluence.cacheTag( ...
                        owner);
            end
            cacheFile = cache.file(tag,owner.pln,cacheContext);
            if ~strcmp(cacheFile,fullfile(cachePath,ref.cacheRelativeFile))
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'CacheIdentityPathMismatch'], ...
                    ['Cannot rehydrate %s: resolved cache file does not ' ...
                    'match persisted cache reference.'],char(ref.role));
            end
            cached = load(cacheFile,variables{:});
            switch char(cacheKind)
                case 'interval'
                    compatible = ...
                        planWorkflow.precompute.IntervalDoseInfluence.isCacheCompatible( ...
                        context,cached,owner);
                case 'prob2'
                    compatible = ...
                        planWorkflow.precompute.Prob2DoseInfluence.isCacheCompatible( ...
                        context,cached,owner);
            end
            if ~compatible
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'IncompatibleCompactCacheOnResume'], ...
                    'Cannot rehydrate %s: compact cache is incompatible.', ...
                    char(ref.role));
            end
            if ~isfield(cached,ref.variableName)
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'MissingCachedVariable'], ...
                    'Cache "%s" does not contain variable "%s".', ...
                    cacheFile,char(ref.variableName));
            end
            dij = cached.(ref.variableName);
        end

        function cached = loadCacheFile(cacheFile,variableName,role)
            if ~isfile(cacheFile)
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'MissingDijCache'], ...
                    'Cannot persist or resume %s: cache file is missing: %s.', ...
                    char(role),cacheFile);
            end
            cached = load(cacheFile,variableName,'cacheMetadata');
            if ~isfield(cached,variableName) || ...
                    ~isfield(cached,'cacheMetadata')
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'IncompleteDijCache'], ...
                    'Cache "%s" does not contain %s and cacheMetadata.', ...
                    cacheFile,char(variableName));
            end
        end

        function cacheContext = standardContextForRef(ref,owner)
            switch char(ref.role)
                case {'dijNominal'}
                    cacheContext = ...
                        planWorkflow.cache.DoseInfluenceCache.context( ...
                        owner.cst,owner.stfNominal);
                otherwise
                    if isfield(owner,'optimizationInput') && ...
                            strcmp(char(ref.role),'optimizationInput')
                        cacheContext = ...
                            planWorkflow.cache.DoseInfluenceCache.context( ...
                            owner.optimizationInput.cst, ...
                            owner.optimizationInput.stf);
                    else
                        cacheContext = ...
                            planWorkflow.cache.DoseInfluenceCache.context( ...
                            owner.cst,owner.stf);
                    end
            end
        end

        function pln = planForRef(ref,owner)
            switch char(ref.role)
                case {'dijNominal'}
                    pln = owner.plnNominal;
                otherwise
                    if isfield(owner,'optimizationInput') && ...
                            strcmp(char(ref.role),'optimizationInput')
                        pln = owner.optimizationInput.pln;
                    else
                        pln = owner.pln;
                    end
            end
        end

        function assertRefBixels(ref,dij)
            expected = ref.totalNumOfBixels;
            if isempty(expected)
                return;
            end
            actual = ...
                planWorkflow.precompute.OptimizationInput.totalNumOfBixels( ...
                dij);
            if ~isempty(actual) && actual ~= expected
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'DijRefBixelMismatch'], ...
                    ['Rehydrated %s has %d bixels, but persisted ' ...
                    'reference expects %d.'],char(ref.role),actual, ...
                    expected);
            end
        end

        function fieldName = fieldForDijKind(dijKind)
            switch char(dijKind)
                case 'nominal'
                    fieldName = 'dijNominal';
                case 'scenario'
                    fieldName = 'dijRobust';
                case 'interval'
                    fieldName = 'dijIntervalContext';
                case 'prob2'
                    fieldName = 'dijProb2Context';
                otherwise
                    error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                        'InvalidDijKind'], ...
                        'Unsupported optimizationInput.dijKind "%s".', ...
                        char(dijKind));
            end
        end

        function rejectLegacyDijFields(node)
            if isfield(node,'dij_intervalContext') || ...
                    isfield(node,'dij_prob2Context')
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'LegacyCompactDijField'], ...
                    ['workflow data contains legacy compact dij fields. ' ...
                    'Use dijIntervalContext/dijProb2Context only.']);
            end
            if isfield(node,'dij') && ...
                    ~planWorkflow.persistence.WorkflowDataArtifact.isOptimizationInput( ...
                    node)
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'LegacyDataDij'], ...
                    ['workflow data contains legacy field "dij" outside ' ...
                    'optimizationInput. No legacy fallback is allowed.']);
            end
        end

        function tf = isOptimizationInput(node)
            tf = isstruct(node) && isfield(node,'ct') && ...
                isfield(node,'cst') && isfield(node,'pln') && ...
                isfield(node,'stf') && isfield(node,'dij') && ...
                isfield(node,'dijKind');
        end

        function tf = isPlanData(node)
            tf = isstruct(node) && isfield(node,'planConfig') && ...
                isfield(node,'pln') && isfield(node,'cst') && ...
                isfield(node,'stf');
        end

        function tf = requiresIntervalDij(node)
            tf = isstruct(node) && isfield(node,'planConfig') && ...
                isstruct(node.planConfig) && ...
                isfield(node.planConfig,'requiresIntervalDij') && ...
                logical(node.planConfig.requiresIntervalDij);
        end

        function tf = requiresProb2Dij(node)
            tf = isstruct(node) && isfield(node,'planConfig') && ...
                isstruct(node.planConfig) && ...
                isfield(node.planConfig,'requiresProb2Dij') && ...
                logical(node.planConfig.requiresProb2Dij);
        end

        function tf = isDijRef(value)
            tf = isstruct(value) && isfield(value,'artifactKind') && ...
                strcmp(char(value.artifactKind), ...
                planWorkflow.persistence.WorkflowDataArtifact.RefKind);
        end

        function rel = relativeFile(filePath,rootPath)
            prefix = [char(rootPath) filesep];
            filePath = char(filePath);
            if startsWith(filePath,prefix)
                rel = filePath(numel(prefix) + 1:end);
            else
                rel = filePath;
            end
        end
    end
end
