classdef WorkflowDataArtifact
    % WorkflowDataArtifact Compacts and restores persisted workflow data.

    properties (Constant)
        SchemaVersion = 4
        SchemaName = 'planWorkflow.workflowData.v4'
        RefKind = 'planWorkflowDoseInfluenceRef'
        InlineKind = 'planWorkflowDoseInfluenceInline'
    end

    methods (Static)
        function [data,metadata] = compactForSave(data,runConfig,cachePath)
            metadata = struct( ...
                'schema',planWorkflow.persistence.WorkflowDataArtifact.SchemaName, ...
                'schemaVersion', ...
                planWorkflow.persistence.WorkflowDataArtifact.SchemaVersion);
            data = ...
                planWorkflow.persistence.WorkflowDataArtifact.removeTransientFields( ...
                data);
            data = ...
                planWorkflow.persistence.WorkflowDataArtifact.compactSamplingPayloads( ...
                data,runConfig,cachePath);
            data = ...
                planWorkflow.persistence.WorkflowDataArtifact.compactNode( ...
                data,runConfig,cachePath,data);
        end

        function [data,metadata] = compactForStageBoundary(data, ...
                runConfig,cachePath)
            [data,metadata] = ...
                planWorkflow.persistence.WorkflowDataArtifact.compactForSave( ...
                data,runConfig,cachePath);
        end

        function data = rehydrateAfterLoad(data,dataMetadata,runConfig, ...
                cachePath)
            if ~planWorkflow.persistence.WorkflowDataArtifact.hasCurrentSchema( ...
                    dataMetadata)
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'UnsupportedWorkflowDataSchema'], ...
                    ['workflow_data.mat uses an unsupported internal ' ...
                    'schema. This refactor does not provide legacy ' ...
                    'fallbacks for artifacts that depended on ' ...
                    'robustData.dij.']);
            end
            data = ...
                planWorkflow.persistence.WorkflowDataArtifact.rehydrateNode( ...
                data,runConfig,cachePath,data);
        end

        function [input,loaded] = loadOptimizationInputDij(owner, ...
                runConfig,cachePath,rootData,context)
            if nargin < 5 || isempty(context)
                context = 'optimizationInput';
            end
            if nargin < 4 || isempty(rootData)
                rootData = owner;
            end
            if nargin < 3 || isempty(cachePath)
                cachePath = ...
                    planWorkflow.persistence.WorkflowDataArtifact.cachePath( ...
                    runConfig);
            end
            if ~isstruct(owner) || ~isfield(owner,'optimizationInput') || ...
                    isempty(owner.optimizationInput)
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'MissingOptimizationInput'], ...
                    '%s requires optimizationInput.',char(context));
            end
            input = owner.optimizationInput;
            loaded = false;
            if isfield(input,'dij') && ~isempty(input.dij)
                planWorkflow.precompute.OptimizationInput.validate( ...
                    input,char(context));
                return;
            end
            if ~planWorkflow.persistence.WorkflowDataArtifact.hasOptimizationDijArtifact( ...
                    input)
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'MissingOptimizationDijArtifact'], ...
                    ['%s requires optimizationInput.dij, but no dijRef ' ...
                     'or dijInline artifact is available.'],char(context));
            end
            artifact = ...
                planWorkflow.persistence.WorkflowDataArtifact.optimizationDijArtifact( ...
                input);
            input.dij = ...
                planWorkflow.persistence.WorkflowDataArtifact.loadDijArtifact( ...
                artifact,owner,runConfig,cachePath,rootData);
            input = ...
                planWorkflow.persistence.WorkflowDataArtifact.removeOptimizationDijArtifact( ...
                input);
            loaded = true;
            planWorkflow.precompute.OptimizationInput.validate( ...
                input,char(context));
        end

        function [owner,loadedFields] = loadOwnerDijArtifacts(owner, ...
                runConfig,cachePath,rootData,fieldNames)
            loadedFields = {};
            if nargin < 5 || isempty(fieldNames)
                fieldNames = {'dijRobust','dijNominal', ...
                    'dijIntervalContext','dijProb2Context', ...
                    'dij_interval','dij_prob2'};
            end
            if nargin < 4 || isempty(rootData)
                rootData = owner;
            end
            if nargin < 3 || isempty(cachePath)
                cachePath = ...
                    planWorkflow.persistence.WorkflowDataArtifact.cachePath( ...
                    runConfig);
            end
            for fieldIx = 1:numel(fieldNames)
                fieldName = fieldNames{fieldIx};
                if ~isstruct(owner) || ~isfield(owner,fieldName)
                    continue;
                end
                fieldValue = owner.(fieldName);
                if ~planWorkflow.persistence.WorkflowDataArtifact.isDijArtifact( ...
                        fieldValue)
                    continue;
                end
                owner.(fieldName) = ...
                    planWorkflow.persistence.WorkflowDataArtifact.loadDijArtifact( ...
                    fieldValue,owner,runConfig,cachePath,rootData);
                loadedFields{end + 1} = fieldName; %#ok<AGROW>
            end
        end

        function [owner,loadedFields] = materializeOwnerDijArtifacts( ...
                owner,runConfig,cachePath,rootData,fieldNames,contextLabel)
            if nargin < 6 || isempty(contextLabel)
                contextLabel = 'dose-influence materialization';
            end
            if nargin < 5 || isempty(fieldNames)
                fieldNames = {'dijRobust','dijNominal', ...
                    'dijIntervalContext','dijProb2Context', ...
                    'dij_interval','dij_prob2'};
            end
            if nargin < 4 || isempty(rootData)
                rootData = owner;
            end
            if nargin < 3 || isempty(cachePath)
                cachePath = ...
                    planWorkflow.persistence.WorkflowDataArtifact.cachePath( ...
                    runConfig);
            end
            fieldNames = ...
                planWorkflow.persistence.WorkflowDataArtifact.normalizeFieldNames( ...
                fieldNames);

            [owner,loadedFields] = ...
                planWorkflow.persistence.WorkflowDataArtifact.loadOwnerDijArtifacts( ...
                owner,runConfig,cachePath,rootData,fieldNames);

            for fieldIx = 1:numel(fieldNames)
                fieldName = fieldNames{fieldIx};
                if planWorkflow.persistence.WorkflowDataArtifact.hasMaterializedOwnerDijField( ...
                        owner,fieldName)
                    continue;
                end
                [owner,loaded] = ...
                    planWorkflow.persistence.WorkflowDataArtifact.materializeFieldFromOptimizationInput( ...
                    owner,runConfig,cachePath,rootData,fieldName, ...
                    contextLabel);
                if loaded
                    loadedFields{end + 1} = fieldName; %#ok<AGROW>
                end
                if ~planWorkflow.persistence.WorkflowDataArtifact.hasMaterializedOwnerDijField( ...
                        owner,fieldName)
                    error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                        'MissingMaterializedDijArtifact'], ...
                        ['%s requires materialized %s, but it is missing, ' ...
                         'empty, or still a lazy artifact.'], ...
                        char(contextLabel),fieldName);
                end
            end
        end

        function artifact = cachedDijArtifact(owner,fieldName, ...
                runConfig,cachePath,rootData)
            if nargin < 5
                rootData = owner;
            end
            if nargin < 4 || isempty(cachePath)
                cachePath = ...
                    planWorkflow.persistence.WorkflowDataArtifact.cachePath( ...
                    runConfig);
            end
            artifact = ...
                planWorkflow.persistence.WorkflowDataArtifact.dijArtifactForPlanArtifactValue( ...
                owner,fieldName,[],runConfig,cachePath,rootData);
        end
    end

    methods (Static, Access = private)
        function fieldNames = normalizeFieldNames(fieldNames)
            if ischar(fieldNames) || ...
                    (isstring(fieldNames) && isscalar(fieldNames))
                fieldNames = {char(fieldNames)};
            elseif isstring(fieldNames)
                fieldNames = cellstr(fieldNames);
            end
            fieldNames = fieldNames(:)';
        end

        function tf = hasMaterializedOwnerDijField(owner,fieldName)
            tf = isstruct(owner) && isfield(owner,fieldName) && ...
                ~isempty(owner.(fieldName)) && ...
                ~planWorkflow.persistence.WorkflowDataArtifact.isDijArtifact( ...
                owner.(fieldName)) && ...
                ~planWorkflow.cache.DoseInfluenceCacheRef.isRef( ...
                owner.(fieldName));
        end

        function [owner,loaded] = materializeFieldFromOptimizationInput( ...
                owner,runConfig,cachePath,rootData,fieldName,contextLabel)
            loaded = false;
            if ~isstruct(owner) || ~isfield(owner,'optimizationInput') || ...
                    isempty(owner.optimizationInput)
                return;
            end
            input = owner.optimizationInput;
            if ~planWorkflow.persistence.WorkflowDataArtifact.optimizationInputMatchesField( ...
                    input,fieldName)
                return;
            end
            if ~planWorkflow.precompute.OptimizationInput.hasFullDij(input)
                input = ...
                    planWorkflow.persistence.WorkflowDataArtifact.loadOptimizationInputDij( ...
                    owner,runConfig,cachePath,rootData,contextLabel);
            end
            if ~planWorkflow.precompute.OptimizationInput.hasFullDij(input)
                return;
            end
            owner.optimizationInput = input;
            owner.(fieldName) = input.dij;
            loaded = true;
        end

        function tf = optimizationInputMatchesField(input,fieldName)
            tf = false;
            if ~isstruct(input) || ~isfield(input,'dijKind') || ...
                    isempty(input.dijKind)
                return;
            end
            switch char(fieldName)
                case 'dijRobust'
                    expectedKind = 'scenario';
                case 'dijNominal'
                    expectedKind = 'nominal';
                case 'dijIntervalContext'
                    expectedKind = 'interval';
                case 'dijProb2Context'
                    expectedKind = 'prob2';
                otherwise
                    return;
            end
            tf = strcmp(char(input.dijKind),expectedKind);
        end

        function tf = hasCurrentSchema(dataMetadata)
            tf = isstruct(dataMetadata) && ...
                isfield(dataMetadata,'workflowData') && ...
                isstruct(dataMetadata.workflowData) && ...
                isfield(dataMetadata.workflowData,'schemaVersion') && ...
                dataMetadata.workflowData.schemaVersion == ...
                planWorkflow.persistence.WorkflowDataArtifact.SchemaVersion && ...
                isfield(dataMetadata.workflowData,'schema') && ...
                strcmp(char(dataMetadata.workflowData.schema), ...
                planWorkflow.persistence.WorkflowDataArtifact.SchemaName);
        end

        function cachePath = cachePath(runConfig)
            cachePath = [];
            if isstruct(runConfig) && isfield(runConfig,'cacheRootPath')
                cachePath = runConfig.cacheRootPath;
            end
        end

        function data = removeTransientFields(data)
            if isstruct(data) && isfield(data,'performance')
                data = rmfield(data,'performance');
            end
        end

        function data = compactSamplingPayloads(data,runConfig,cachePath)
            if ~isstruct(data) || isempty(data)
                return;
            end
            if isfield(data,'sampling')
                data.sampling = ...
                    planWorkflow.persistence.SamplingPayloadArtifact.compactSamplingData( ...
                    data.sampling,runConfig,cachePath);
            end
            if isfield(data,'results') && isstruct(data.results) && ...
                    isfield(data.results,'sampling')
                data.results.sampling = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactSamplingResults( ...
                    data.results.sampling);
            end
        end

        function samplingResults = compactSamplingResults(samplingResults)
            if ~isstruct(samplingResults) || isempty(samplingResults)
                return;
            end
            if isfield(samplingResults,'reference')
                samplingResults.reference = ...
                    planWorkflow.results.SamplingDataCompactor.compactPlanSamplingResults( ...
                    samplingResults.reference);
            end
            if isfield(samplingResults,'robust') && iscell(samplingResults.robust)
                for resultIx = 1:numel(samplingResults.robust)
                    samplingResults.robust{resultIx} = ...
                        planWorkflow.results.SamplingDataCompactor.compactPlanSamplingResults( ...
                        samplingResults.robust{resultIx});
                end
            end
        end

        function node = compactNode(node,runConfig,cachePath,rootData)
            if iscell(node)
                for ix = 1:numel(node)
                    node{ix} = ...
                        planWorkflow.persistence.WorkflowDataArtifact.compactNode( ...
                        node{ix},runConfig,cachePath,rootData);
                end
                return;
            end
            if ~isstruct(node)
                return;
            end
            if isempty(node)
                return;
            end
            if numel(node) > 1
                for ix = 1:numel(node)
                    node(ix) = ...
                        planWorkflow.persistence.WorkflowDataArtifact.compactNode( ...
                        node(ix),runConfig,cachePath,rootData);
                end
                return;
            end
            if planWorkflow.persistence.WorkflowDataArtifact.isDijArtifact( ...
                    node) || ...
                    planWorkflow.cache.DoseInfluenceCacheRef.isRef(node) || ...
                    planWorkflow.persistence.WorkflowDataArtifact.isDijCacheRefRegistry( ...
                    node)
                return;
            end
            planWorkflow.persistence.WorkflowDataArtifact.rejectLegacyDijFields( ...
                node);
            node = ...
                planWorkflow.persistence.WorkflowDataArtifact.compactOwnerDijFields( ...
                node,runConfig,cachePath,rootData);

            names = fieldnames(node);
            for nameIx = 1:numel(names)
                fieldName = names{nameIx};
                fieldValue = node.(fieldName);
                if planWorkflow.persistence.WorkflowDataArtifact.isDijArtifact( ...
                        fieldValue)
                    continue;
                end
                node.(fieldName) = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactNode( ...
                    fieldValue,runConfig,cachePath,rootData);
            end
        end

        function node = compactOwnerDijFields(node,runConfig,cachePath, ...
                rootData)
            if isfield(node,'optimizationInput') && ...
                    isstruct(node.optimizationInput) && ...
                    isfield(node.optimizationInput,'dij')
                node.optimizationInput = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactOptimizationInput( ...
                    node.optimizationInput,node,runConfig,cachePath, ...
                    rootData);
            end
            if planWorkflow.persistence.WorkflowDataArtifact.isPlanData(node)
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactPlanArtifact( ...
                    node,'dijRobust',runConfig,cachePath,rootData);
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactPlanArtifact( ...
                    node,'dijNominal',runConfig,cachePath,rootData);
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactPlanArtifact( ...
                    node,'dijIntervalContext',runConfig,cachePath, ...
                    rootData);
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactPlanArtifact( ...
                    node,'dijProb2Context',runConfig,cachePath,rootData);
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactPlanArtifact( ...
                    node,'dij_interval',runConfig,cachePath,rootData);
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.compactPlanArtifact( ...
                    node,'dij_prob2',runConfig,cachePath,rootData);
                node = ...
                    planWorkflow.persistence.WorkflowDataArtifact.removeOptimizationAliasArtifacts( ...
                    node);
            end
        end

        function input = compactOptimizationInput(input,owner,runConfig, ...
                cachePath,rootData)
            if isfield(input,'dijRef') || isfield(input,'dijInline')
                return;
            end
            artifact = ...
                planWorkflow.persistence.WorkflowDataArtifact.dijArtifactForOptimizationInput( ...
                input,owner,runConfig,cachePath,rootData);
            input = ...
                planWorkflow.persistence.WorkflowDataArtifact.attachOptimizationDijArtifact( ...
                input,artifact);
            input = rmfield(input,'dij');
        end

        function node = compactPlanArtifact(node,fieldName,runConfig, ...
                cachePath,rootData)
            if ~isfield(node,fieldName)
                return;
            end
            fieldValue = node.(fieldName);
            if isempty(fieldValue) || ...
                    planWorkflow.persistence.WorkflowDataArtifact.isDijArtifact( ...
                    fieldValue)
                return;
            end
            node.(fieldName) = ...
                planWorkflow.persistence.WorkflowDataArtifact.dijArtifactForPlanArtifact( ...
                node,fieldName,runConfig,cachePath,rootData);
        end

        function artifact = dijArtifactForOptimizationInput(input,owner, ...
                runConfig,cachePath,rootData)
            if strcmp(char(input.source),'reference') && ...
                    strcmp(char(input.dijKind),'nominal')
                artifact = ...
                    planWorkflow.persistence.WorkflowDataArtifact.dijArtifactFromCacheRefOrInline( ...
                    owner,'dij','standard','dij',input.dij, ...
                    input.dijKind,'optimizationInput',cachePath);
                return;
            end
            if ~isfield(owner,'planConfig')
                artifact = ...
                    planWorkflow.persistence.WorkflowDataArtifact.dijArtifactForPlanlessOptimizationInput( ...
                    input,owner,cachePath);
                artifact.role = 'optimizationInput';
                return;
            end
            fieldName = ...
                planWorkflow.persistence.WorkflowDataArtifact.fieldForDijKind( ...
                input.dijKind);
            artifact = ...
                planWorkflow.persistence.WorkflowDataArtifact.dijArtifactForPlanArtifactValue( ...
                owner,fieldName,input.dij,runConfig,cachePath,rootData);
            artifact.role = 'optimizationInput';
            artifact.dijKind = char(input.dijKind);
        end

        function artifact = dijArtifactForPlanArtifact(owner,fieldName,~, ...
                cachePath,~)
            artifact = ...
                planWorkflow.persistence.WorkflowDataArtifact.dijArtifactForPlanArtifactValue( ...
                owner,fieldName,owner.(fieldName),[],cachePath,[]);
        end

        function artifact = dijArtifactForPlanArtifactValue(owner,fieldName, ...
                dij,~,cachePath,~)
            switch char(fieldName)
                case 'dijRobust'
                    artifact = ...
                        planWorkflow.persistence.WorkflowDataArtifact.dijArtifactFromCacheRefOrInline( ...
                        owner,'dijRobust','standard','dij', ...
                        dij,'scenario',fieldName,cachePath);
                case 'dijNominal'
                    if planWorkflow.persistence.WorkflowDataArtifact.requiresIntervalDij( ...
                            owner)
                        artifact = ...
                            planWorkflow.persistence.WorkflowDataArtifact.dijArtifactFromCacheRefOrInline( ...
                            owner,'interval','interval', ...
                            'dijIntervalContext',dij, ...
                            'nominal',fieldName,cachePath);
                        artifact.role = fieldName;
                        artifact.dijKind = 'nominal';
                    elseif planWorkflow.persistence.WorkflowDataArtifact.requiresProb2Dij( ...
                            owner)
                        artifact = ...
                            planWorkflow.persistence.WorkflowDataArtifact.dijArtifactFromCacheRefOrInline( ...
                            owner,'prob2','prob2', ...
                            'dijProb2Context',dij, ...
                            'nominal',fieldName,cachePath);
                        artifact.role = fieldName;
                        artifact.dijKind = 'nominal';
                    else
                        artifact = ...
                            planWorkflow.persistence.WorkflowDataArtifact.dijArtifactFromCacheRefOrInline( ...
                            owner,'dijNominal','standard','dij', ...
                            dij,'nominal',fieldName, ...
                            cachePath);
                    end
                case {'dijIntervalContext','dij_interval'}
                    artifact = ...
                        planWorkflow.persistence.WorkflowDataArtifact.dijArtifactFromCacheRefOrInline( ...
                        owner,'interval','interval',fieldName, ...
                        dij,'interval',fieldName,cachePath);
                case {'dijProb2Context','dij_prob2'}
                    artifact = ...
                        planWorkflow.persistence.WorkflowDataArtifact.dijArtifactFromCacheRefOrInline( ...
                        owner,'prob2','prob2',fieldName, ...
                        dij,'prob2',fieldName,cachePath);
                otherwise
                    error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                        'UnsupportedDijArtifact'], ...
                        'Unsupported dose influence artifact "%s".', ...
                        char(fieldName));
            end
        end

        function node = removeOptimizationAliasArtifacts(node)
            if ~isfield(node,'optimizationInput') || ...
                    ~isstruct(node.optimizationInput) || ...
                    ~planWorkflow.persistence.WorkflowDataArtifact.hasOptimizationDijArtifact( ...
                    node.optimizationInput) || ...
                    ~isfield(node.optimizationInput,'dijKind')
                return;
            end
            switch char(node.optimizationInput.dijKind)
                case 'scenario'
                    fieldName = 'dijRobust';
                case 'nominal'
                    fieldName = 'dijNominal';
                otherwise
                    return;
            end
            artifact = ...
                planWorkflow.persistence.WorkflowDataArtifact.optimizationDijArtifact( ...
                node.optimizationInput);
            if isfield(node,fieldName) && ...
                    planWorkflow.persistence.WorkflowDataArtifact.isSameDijArtifact( ...
                    node.(fieldName),artifact)
                node = rmfield(node,fieldName);
            end
        end

        function input = attachOptimizationDijArtifact(input,artifact)
            if planWorkflow.persistence.WorkflowDataArtifact.isDijRef( ...
                    artifact)
                input.dijRef = artifact;
                return;
            end
            if planWorkflow.persistence.WorkflowDataArtifact.isDijInline( ...
                    artifact)
                input.dijInline = artifact;
                return;
            end
            error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                'InvalidDijArtifact'], ...
                'Cannot attach unsupported dose influence artifact.');
        end

        function tf = hasOptimizationDijArtifact(input)
            tf = isstruct(input) && ...
                (isfield(input,'dijRef') || isfield(input,'dijInline'));
        end

        function artifact = optimizationDijArtifact(input)
            if isfield(input,'dijRef')
                artifact = input.dijRef;
                return;
            end
            if isfield(input,'dijInline')
                artifact = input.dijInline;
                return;
            end
            artifact = [];
        end

        function input = removeOptimizationDijArtifact(input)
            if isfield(input,'dijRef')
                input = rmfield(input,'dijRef');
            end
            if isfield(input,'dijInline')
                input = rmfield(input,'dijInline');
            end
        end

        function tf = isSameDijArtifact(left,right)
            if planWorkflow.persistence.WorkflowDataArtifact.isDijRef( ...
                    left) || ...
                    planWorkflow.persistence.WorkflowDataArtifact.isDijRef( ...
                    right)
                tf = ...
                    planWorkflow.persistence.WorkflowDataArtifact.isSameDijRef( ...
                    left,right);
                return;
            end
            tf = ...
                planWorkflow.persistence.WorkflowDataArtifact.isDijInline( ...
                left) && ...
                planWorkflow.persistence.WorkflowDataArtifact.isDijInline( ...
                right) && ...
                strcmp(char(left.dijKind),char(right.dijKind)) && ...
                isequal(left.totalNumOfBixels,right.totalNumOfBixels) && ...
                isequaln(left.dij,right.dij);
        end

        function tf = isSameDijRef(left,right)
            tf = ...
                planWorkflow.persistence.WorkflowDataArtifact.isDijRef(left) && ...
                planWorkflow.persistence.WorkflowDataArtifact.isDijRef(right) && ...
                strcmp(char(left.cacheKind),char(right.cacheKind)) && ...
                strcmp(char(left.tag),char(right.tag)) && ...
                strcmp(char(left.variableName),char(right.variableName)) && ...
                strcmp(char(left.cacheRelativeFile), ...
                char(right.cacheRelativeFile)) && ...
                strcmp(char(left.cacheIdentityHash), ...
                char(right.cacheIdentityHash)) && ...
                strcmp(char(left.dijKind),char(right.dijKind)) && ...
                isequal(left.totalNumOfBixels,right.totalNumOfBixels);
        end

        function artifact = dijArtifactForPlanlessOptimizationInput( ...
                input,owner, ...
                cachePath)
            switch char(input.dijKind)
                case 'interval'
                    artifact = ...
                        planWorkflow.persistence.WorkflowDataArtifact.dijArtifactFromCacheRefOrInline( ...
                        owner,'interval','interval', ...
                        'dijIntervalContext',input.dij,input.dijKind, ...
                        'optimizationInput',cachePath);
                case 'prob2'
                    artifact = ...
                        planWorkflow.persistence.WorkflowDataArtifact.dijArtifactFromCacheRefOrInline( ...
                        owner,'prob2','prob2', ...
                        'dijProb2Context',input.dij,input.dijKind, ...
                        'optimizationInput',cachePath);
                otherwise
                    error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                        'MissingPlanConfig'], ...
                        ['Cannot persist optimizationInput.dij for source ' ...
                        '"%s" without owner.planConfig.'], ...
                        char(input.source));
            end
        end

        function artifact = dijArtifactFromCacheRefOrInline(owner,refKey, ...
                expectedCacheKind,variableName,dij,dijKind,role, ...
                cachePath)
            if planWorkflow.persistence.WorkflowDataArtifact.hasDijCacheRef( ...
                    owner,refKey)
                artifact = ...
                    planWorkflow.persistence.WorkflowDataArtifact.refFromDijCacheRef( ...
                    owner.dijCacheRefs.(refKey),expectedCacheKind, ...
                    variableName,dij,dijKind,role,cachePath);
                return;
            end
            artifact = ...
                planWorkflow.persistence.WorkflowDataArtifact.createInline( ...
                dij,dijKind,role);
        end

        function tf = hasDijCacheRef(owner,refKey)
            tf = isstruct(owner) && isfield(owner,'dijCacheRefs') && ...
                isstruct(owner.dijCacheRefs) && ...
                isfield(owner.dijCacheRefs,refKey) && ...
                ~isempty(owner.dijCacheRefs.(refKey));
        end

        function ref = refFromDijCacheRef(cacheRef,expectedCacheKind, ...
                variableName,dij,dijKind,role,cachePath)
            planWorkflow.persistence.WorkflowDataArtifact.assertDijCacheRef( ...
                cacheRef,expectedCacheKind,variableName,role);
            cacheFile = fullfile(cachePath,cacheRef.cacheRelativeFile);
            cached = ...
                planWorkflow.persistence.WorkflowDataArtifact.loadCacheMetadata( ...
                cacheFile,variableName,role);
            planWorkflow.persistence.WorkflowDataArtifact.assertCacheRefMetadata( ...
                cacheRef,cached.cacheMetadata,cacheFile,role);
            ref = ...
                planWorkflow.persistence.WorkflowDataArtifact.createRef( ...
                cacheRef,variableName,dij,dijKind,role);
        end

        function inline = createInline(dij,dijKind,role)
            inline = struct();
            inline.artifactKind = ...
                planWorkflow.persistence.WorkflowDataArtifact.InlineKind;
            inline.schemaVersion = 1;
            inline.role = char(role);
            inline.dijKind = char(dijKind);
            inline.totalNumOfBixels = ...
                planWorkflow.precompute.OptimizationInput.totalNumOfBixels( ...
                dij);
            inline.dij = dij;
        end

        function assertDijCacheRef(cacheRef,expectedCacheKind, ...
                variableName,role)
            if ~planWorkflow.cache.DoseInfluenceCacheRef.isRef(cacheRef)
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'InvalidDijCacheRef'], ...
                    'Cannot persist %s because its cache ref is invalid.', ...
                    char(role));
            end
            if ~strcmp(char(cacheRef.cacheKind),char(expectedCacheKind))
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'DijCacheRefKindMismatch'], ...
                    'Cannot persist %s with %s cache ref; expected %s.', ...
                    char(role),char(cacheRef.cacheKind), ...
                    char(expectedCacheKind));
            end
            if ~isfield(cacheRef,'variables') || ...
                    ~any(strcmp(char(variableName),cacheRef.variables))
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'DijCacheRefVariableMismatch'], ...
                    ['Cannot persist %s because cache ref does not ' ...
                    'declare variable "%s".'],char(role), ...
                    char(variableName));
            end
        end

        function assertCacheRefMetadata(cacheRef,cacheMetadata,cacheFile, ...
                role)
            if ~isfield(cacheMetadata,'cacheIdentityHash') || ...
                    ~strcmp(char(cacheMetadata.cacheIdentityHash), ...
                    char(cacheRef.cacheIdentityHash))
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'DijCacheRefIdentityMismatch'], ...
                    ['Cannot persist or resume %s from cache "%s": ' ...
                    'identity hash does not match the declared ref.'], ...
                    char(role),cacheFile);
            end
            if ~isfield(cacheMetadata,'tag') || ...
                    ~strcmp(char(cacheMetadata.tag),char(cacheRef.tag))
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'DijCacheRefTagMismatch'], ...
                    ['Cannot persist or resume %s from cache "%s": ' ...
                    'cache tag does not match the declared ref.'], ...
                    char(role),cacheFile);
            end
        end

        function ref = createRef(cacheRef,variableName,dij,dijKind,role)
            ref = struct();
            ref.artifactKind = ...
                planWorkflow.persistence.WorkflowDataArtifact.RefKind;
            ref.schemaVersion = 1;
            ref.cacheKind = char(cacheRef.cacheKind);
            ref.tag = char(cacheRef.tag);
            ref.variableName = char(variableName);
            ref.role = char(role);
            ref.dijKind = char(dijKind);
            ref.cacheRelativeFile = char(cacheRef.cacheRelativeFile);
            ref.cacheIdentityHash = cacheRef.cacheIdentityHash;
            ref.totalNumOfBixels = ...
                planWorkflow.precompute.OptimizationInput.totalNumOfBixels( ...
                dij);
            if isempty(ref.totalNumOfBixels) && ...
                    isfield(cacheRef,'totalNumOfBixels')
                ref.totalNumOfBixels = cacheRef.totalNumOfBixels;
            end
        end

        function node = rehydrateNode(node,runConfig,cachePath,rootData)
            if iscell(node)
                for ix = 1:numel(node)
                    node{ix} = ...
                        planWorkflow.persistence.WorkflowDataArtifact.rehydrateNode( ...
                        node{ix},runConfig,cachePath,rootData);
                end
                return;
            end
            if ~isstruct(node) || ...
                    planWorkflow.persistence.WorkflowDataArtifact.isDijArtifact( ...
                    node) || ...
                    planWorkflow.cache.DoseInfluenceCacheRef.isRef(node) || ...
                    planWorkflow.persistence.WorkflowDataArtifact.isDijCacheRefRegistry( ...
                    node)
                return;
            end
            if isempty(node)
                return;
            end
            if numel(node) > 1
                for ix = 1:numel(node)
                    node(ix) = ...
                        planWorkflow.persistence.WorkflowDataArtifact.rehydrateNode( ...
                        node(ix),runConfig,cachePath,rootData);
                end
                return;
            end

            node = ...
                planWorkflow.persistence.WorkflowDataArtifact.rehydrateOwnerDijFields( ...
                node,runConfig,cachePath,rootData);
            names = fieldnames(node);
            for nameIx = 1:numel(names)
                fieldName = names{nameIx};
                fieldValue = node.(fieldName);
                if planWorkflow.persistence.WorkflowDataArtifact.isDijArtifact( ...
                        fieldValue)
                    continue;
                end
                node.(fieldName) = ...
                    planWorkflow.persistence.WorkflowDataArtifact.rehydrateNode( ...
                    fieldValue,runConfig,cachePath,rootData);
            end
        end

        function node = rehydrateOwnerDijFields(node,~,~,~)
            if isfield(node,'optimizationInput') && ...
                    planWorkflow.persistence.WorkflowDataArtifact.hasOptimizationDijArtifact( ...
                    node.optimizationInput)
                input = node.optimizationInput;
                planWorkflow.precompute.OptimizationInput.validateLight( ...
                    input,'workflow_data.mat rehydration');
            end
        end

        function dij = loadDijArtifact(artifact,owner,runConfig,cachePath, ...
                rootData)
            if planWorkflow.persistence.WorkflowDataArtifact.isDijRef( ...
                    artifact)
                dij = ...
                    planWorkflow.persistence.WorkflowDataArtifact.loadDijRef( ...
                    artifact,owner,runConfig,cachePath,rootData);
                return;
            end
            if planWorkflow.persistence.WorkflowDataArtifact.isDijInline( ...
                    artifact)
                dij = ...
                    planWorkflow.persistence.WorkflowDataArtifact.loadDijInline( ...
                    artifact,owner,runConfig,cachePath,rootData);
                return;
            end
            error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                'InvalidDijArtifact'], ...
                'Cannot load unsupported dose influence artifact.');
        end

        function dij = loadDijRef(ref,owner,runConfig,cachePath,rootData)
            cache = planWorkflow.cache.DoseInfluenceCacheService( ...
                runConfig,cachePath,@(~) []);
            dij = cache.loadCompatibleRef(ref,owner,rootData);
        end

        function dij = loadDijInline(inline,~,~,~,~)
            dij = inline.dij;
            planWorkflow.persistence.WorkflowDataArtifact.assertRefBixels( ...
                inline,dij);
        end

        function cached = loadCacheMetadata(cacheFile,variableName,role)
            if ~isfile(cacheFile)
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'MissingDijCache'], ...
                    'Cannot persist or resume %s: cache file is missing: %s.', ...
                    char(role),cacheFile);
            end
            variables = who('-file',cacheFile);
            hasVariable = any(strcmp(char(variableName),variables));
            hasMetadata = any(strcmp('cacheMetadata',variables));
            if ~hasVariable || ~hasMetadata
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'IncompleteDijCache'], ...
                'Cache "%s" does not contain %s and cacheMetadata.', ...
                cacheFile,char(variableName));
            end
            cached = load(cacheFile,'cacheMetadata');
        end

        function assertRefBixels(ref,dij)
            expected = ref.totalNumOfBixels;
            if isempty(expected)
                return;
            end
            actual = ...
                planWorkflow.precompute.OptimizationInput.totalNumOfBixels( ...
                dij);
            if ~isempty(actual) && actual ~= expected
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'DijRefBixelMismatch'], ...
                    ['Rehydrated %s has %d bixels, but persisted ' ...
                    'reference expects %d.'],char(ref.role),actual, ...
                    expected);
            end
        end

        function fieldName = fieldForDijKind(dijKind)
            switch char(dijKind)
                case 'nominal'
                    fieldName = 'dijNominal';
                case 'scenario'
                    fieldName = 'dijRobust';
                case 'interval'
                    fieldName = 'dijIntervalContext';
                case 'prob2'
                    fieldName = 'dijProb2Context';
                otherwise
                    error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                        'InvalidDijKind'], ...
                        'Unsupported optimizationInput.dijKind "%s".', ...
                        char(dijKind));
            end
        end

        function rejectLegacyDijFields(node)
            if isfield(node,'dij_intervalContext') || ...
                    isfield(node,'dij_prob2Context')
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'LegacyCompactDijField'], ...
                    ['workflow data contains legacy compact dij fields. ' ...
                    'Use dijIntervalContext/dijProb2Context only.']);
            end
            if isfield(node,'dij') && ...
                    ~planWorkflow.persistence.WorkflowDataArtifact.isOptimizationInput( ...
                    node)
                error(['planWorkflow:persistence:WorkflowDataArtifact:' ...
                    'LegacyDataDij'], ...
                    ['workflow data contains legacy field "dij" outside ' ...
                    'optimizationInput. No legacy fallback is allowed.']);
            end
        end

        function tf = isOptimizationInput(node)
            tf = isstruct(node) && isfield(node,'ct') && ...
                isfield(node,'cst') && isfield(node,'pln') && ...
                isfield(node,'stf') && isfield(node,'dij') && ...
                isfield(node,'dijKind');
        end

        function tf = isPlanData(node)
            tf = isstruct(node) && isfield(node,'planConfig') && ...
                isfield(node,'pln') && isfield(node,'cst') && ...
                isfield(node,'stf');
        end

        function tf = requiresIntervalDij(node)
            tf = isstruct(node) && isfield(node,'planConfig') && ...
                isstruct(node.planConfig) && ...
                isfield(node.planConfig,'requiresIntervalDij') && ...
                logical(node.planConfig.requiresIntervalDij);
        end

        function tf = requiresProb2Dij(node)
            tf = isstruct(node) && isfield(node,'planConfig') && ...
                isstruct(node.planConfig) && ...
                isfield(node.planConfig,'requiresProb2Dij') && ...
                logical(node.planConfig.requiresProb2Dij);
        end

        function tf = isDijRef(value)
            tf = isstruct(value) && isfield(value,'artifactKind') && ...
                strcmp(char(value.artifactKind), ...
                planWorkflow.persistence.WorkflowDataArtifact.RefKind);
        end

        function tf = isDijInline(value)
            tf = isstruct(value) && isfield(value,'artifactKind') && ...
                strcmp(char(value.artifactKind), ...
                planWorkflow.persistence.WorkflowDataArtifact.InlineKind);
        end

        function tf = isDijArtifact(value)
            tf = ...
                planWorkflow.persistence.WorkflowDataArtifact.isDijRef(value) || ...
                planWorkflow.persistence.WorkflowDataArtifact.isDijInline( ...
                value);
        end

        function tf = isDijCacheRefRegistry(value)
            tf = false;
            if ~isstruct(value) || isempty(value) || numel(value) ~= 1
                return;
            end
            names = fieldnames(value);
            allowed = {'dij','dijRobust','dijNominal','interval','prob2'};
            if isempty(names) || ~all(ismember(names,allowed))
                return;
            end
            for nameIx = 1:numel(names)
                ref = value.(names{nameIx});
                if isempty(ref)
                    continue;
                end
                if ~planWorkflow.cache.DoseInfluenceCacheRef.isRef(ref)
                    return;
                end
            end
            tf = true;
        end

        function rel = relativeFile(filePath,rootPath)
            prefix = [char(rootPath) filesep];
            filePath = char(filePath);
            if startsWith(filePath,prefix)
                rel = filePath(numel(prefix) + 1:end);
            else
                rel = filePath;
            end
        end
    end
end
